#!/usr/local/bin/perl -si

require "ctime.pl";
require "/local1/www/apache-isu/cgi-bin/netforum2/lib/sys_config";
require "/local1/www/apache-isu/cgi-bin/netforum2/lib/forum_config";
if($allow_forum_config){
require "/local1/www/apache-isu/cgi-bin/netforum2/Learn-English-Now%21/forum_config";
}
require "/local1/www/apache-isu/cgi-bin/netforum2/lib/main";
require "/local1/www/apache-isu/cgi-bin/netforum2/lib/variables";
require "/local1/www/apache-isu/cgi-bin/netforum2/lib/utilities";


$which_forum = "Learn-English-Now%21";
$script_name = 'a';
$netforum_url = "$base_url/Learn-English-Now%2521/$script_name";

$forum_name = "Learn English Now!";
$forum_owner = "ClassNet Instructor";
$forum_owner_code_name = "cnet";
$forum_monitor = "Cynthia Arancibia";
$forum_monitor_email = "novabs\@ptd.net";



if ($ENV{'REQUEST_METHOD'} eq 'GET') {
	&get_url_vars;
	&get_command;
}

if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	&ReadParse();
	&get_url_vars;
	&post_command;
}

