===from:Rebekah Walker
===date:Wed Jan  9 13:55:10 2002
===subject:Overpopulation
===message:Although there are a number of important ICZM problems in the world, I feel that overpopulation is the most serious and threatening.  As the world population grows, more demands are placed on the environment.  These demands may only stress some areas, but lead to degradation of the entire ecosystem.  Technologies to house, feed, protect and provide for the growing population, have produced toxins and pollutants in mass.  Some of the effects of these pollutants are short-lived, however others have caused deleterious effects that may prove to be irreversible.  Sewage outfall increases as population increases, and many times this sewage is untreated in the most populated areas.  Food demand increases forcing the use of pesticides to grow more crops.  There is also a higher demand on fisheries taking from already declining ocean populations.  The bycatch from these fisheries increases as effort by the fishermen increases to make up for low catches, endangering non-economic species as well.  Transportation of more people and goods results in invasive species introduced by ballast water, heavy metals introduced to the water from non-corrosive paints on boats, toxic run-off from airports and highways and of course global warming due to CO2 increase.  Most populations also rely on energy for everyday activities.  The production of this energy releases more CO2 into the atmosphere or relies on nuclear power with its inherent risks.  Since so much of the world population resides on the coast, the building of houses displaces species from their wetland and dune habitats.  Coastal runoff, harbor construction, beach renourishment and shipping influences near-coast marine communities, such as seagrass beds and coral reefs.   For these reasons I feel that overpopulation is the origin of most major problems facing the marine environment.  If we hope to control the destruction of the coastal environment, we must first keep more damage from being done.  If populations can be held in check, it is possible that some problems can be remedied.  If, however, the world population continue to rise at its present rate, it will be impossible to stop “incidental” damage done to the environment.



=========yorg=========
===from:Kristi Foster
===email:scubadoobydoo_FL@hotmail.com
===date:Thu Jan 10 13:26:16 2002
===subject:Our Belief in an Inexhaustible Resource
===message:I believe the most important ICZM problem in the world is humankind’s belief that the ocean is an inexhaustible resource from which we can take whatever we want and to which we can do whatever we choose without consequence.  In earlier “less civilized” cultures around the globe, entire populations lived in harmony with the sea, taking only that which was needed for survival, when it was needed.   Then came “modern” man.  Examples can be found around the world where people have built homes and businesses near shore without regard for their interference with estuaries and flood plains.  People have re-constructed shorelines and diverted rivers without regard for impacts to the natural surroundings.   Overharvesting has been the result of economic greed rather than a need to feed the people.  Pollution from point and non-point sources has gone unregulated until the last 50 years (or less) with the rationalization that the entirety of the ocean will dilute the problem.  But this problem is not unique.  We see the similar destruction of our air, land, forests, and wildlife.  Until a paradigm shift occurs so that people start thinking about the future, rather than the here and now, the ICZM problem will not go away no matter how many laws are instituted or preservation programs implemented.  Unfortunately, as long as there are people in need of food and a means to support their families, we cannot expect such a shift from developing nations.  Nor are the so-called world leaders likely to give up the ways of life and the luxuries to which we’ve become accustomed.  It will take a world-wide catastrophic event before people take immediate, meaning action to resolve our environmental problems.
=========yorg=========
===from:Greg Foster
===date:Thu Jan 10 16:29:21 2002
===subject:Policy Outpaced by Technology
===message:The greatest challenge facing the International Integrated Coastal Management community is keeping pace with technological innovation and implementation.  The reasoning behind this assertion is two-fold; 
1.  Technology is the progeny of Science, which by nature grows geometrically.  An old axiom informs us that for every question answered by Science, two new questions will arise (and likely be answered).
2.  Technology has, and will continue to be, the primary factor governing the extent, distribution, and impact of human populations.

Every problem facing the ocean today is to some degree a result of technological advancement.  The doubling of the global population since 1950 is largely due to the discovery of antibiotics and the subsequent decline in infant mortality.  The eutrophication of coastal waters stems from the advent of chemical fertilizers.  The development of mechanical refrigeration, high-grade steel, and radar allowed for the production of the behemoth factory-trawlers that have since decimated once abundant fish stocks.  The list goes on, and on, and on.  Policymakers must find a way to enact swift, effective, and cooperative responses to existing and emergent ecological pressures.  This will likely require a major overhaul of the current regime, as the pace and complexity of issues have made obsolescent the traditional wait-and-see and constituency-based decision making processes.

=========yorg=========
===from:Ian Gibson
===date:Thu Jan 10 17:50:14 2002
===subject:Ignorance and Indifference
===message:I believe that answering this question goes beyond the typical vein of cause and effect.  The most pressing problem facing integrated CZM on a global scale isn't the depletion of fisheries, sea-level rise, pollution, or over-development.  These issues, while all extremely important in future health of the coastal zone, are merely symptoms of a much larger epidemic. Though an strong environmental ethic has taken root (to a certain extent) in the United States and other more developed countries, there still exists a predominence of ecological ignorance and environmental indifference in the vast majority of the nations on this planet.  The concepts of a "non renewable resource" and "conservation management", while understood by a substantial minority, is emphasised by a much smaller group.  The coastal zone is limited and this idea...no, this tenet, is lost on the masses.  I do acknowledge that in many third world countries it is highly impractical to think in these terms - simply surviving from one day and one regime to the next is worry enough. However, our own country, the most advanced and wealthy in the world, is having issues grasping this fairly simple concept.  It is hard line to follow - this is a capitalist society (one i wholeheartedly support) where the almighty dollar reigns.  But a line must soon be drawn in the sand  - the coastal zone must be managed with an emphasis on conservation, compromise, and most importantly, education.  A high priority must continue to be placed on the education of the public and of those in goverment as to the fragile nature of the coastal zone.  Hopefully, with increased knowledge and focus on our coastlines will we as a race perhaps be able to come to compromises that will dimish and perhaps reverse the prodigous damage being done to the CZ around the world.

=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution_site:http://mako.ocean.nova.edu
===institution:Nova Southeastern University
===date:Thu Jan 10 19:39:25 2002
===subject:A Coastal Population Bomb
===message:     I believe that over-population, coupled with the percentage of the world's population living along or near the coast creates the biggest problem for coastal zone management.  It is well documented that the majority of the world's population lives along or near the coast because coastal areas are productive, accessible etc... Coastal areas include productive estuaries and sheltered harbors, along with fertile soils along and just inland of the coast.  Coastal areas are, and have been throughout time, an obvious place for people to live.  The sheer numbers of people along with limited coastlines make management decisions and policies difficult.  Another problem for coastal management is the overall lack of knowledge regarding coastal and estuarine ecosystems and their inter-related processes. Yet another problem is that only recently have people realized that the coastal areas need to be managed and preserved to some degree.  Too much damage may have already been done.  This again is a result of overpopulation.  There isn't much that can be done to slow population growth throughout the world. Current and future management policies must include the coastal populations in the decision making processes.  There simply isn't a way around them. A suggestion (in jest) would have everyone move inland.  There should be plenty of land left in Wyoming or Montana. 

Matt Mitchell
=========yorg=========
===from:john osullivan
===email:johnosul@aol.com
===date:Fri Jan 11 15:25:09 2002
===subject:Worlds Oceans as an everyday economic resource
===message:Lets try this again, it seems I am half way through when I get logged off.

The most important problem today is relating the importance of the worlds oceans in everyday life.  The economic inplications are more important than the organic resources vrs inorganic ones.  This was certainly evident in South Florida this past year where drought conditions brought salt water further inland and in some areas swamping whole towns displacing its own fresh water, forever.  Population density has only increased the problem for freshwater and sewage along the rich gold coast of Ft Lauderdale.  Over 10,000 luxry condos are expected to open in the next two years without being attached to the cities fresh water supply. It will be a considerable expense when you have to pay $4.00 per gallon just for house hold needs.  Mankind has proven over and over how "selfish" he is in relation to natural resources and has been previously stated we cannot legislate local and national pollution controlls without specific  monetary penalties attached or else we wouldn't be seeing commercial properties still throwing paint and oil byproducts into the freshwater tables, which drain into the canals, to the sea.  It is all very well and good to stop developement because of a specific mating site but scientists have been seen as antagonistic to developers since the "seal huggers" of the 1960's.  It is important for scientists and government planners to relate the importance of the worlds coasts via its monetary impact it will have on us on a monthly basis as the need for fresh water rises.  This is a majopr shift in scientic thinking but is the responsibility of scientists to point out not only the ethical implications of the oceans destruction but also its economic.  Once again modern man will only wake up when it will cost him. What makes us think that our higher morality as a steward of our planets resources, is more defined, when our current President refused to sign the global climate controls this year.  It all comes down to economics of the here and the forseeable four years.
=========yorg=========
===from:Kelly Adams
===date:Sat Jan 12 14:23:58 2002
===subject:Ignorance
===message:Lack of knowledge is the greatest cause of destruction to coastal zones and the open ocean.  Generations upon generations have been given the knowledge that the ocean is a limitless food resource; yet, today the oceans are almost void of species that once existed in copious amounts.  The North Atlantic cod’s near extinction can be attributed to fishermen’s lack of knowledge and greed.  Disregarding the warning signs that the fish were becoming smaller and less abundant, the Canadians and Europeans built even bigger boats and caught even more fish. Ultimately, their ignorance and greed lead to the crash of cod and ground fish populations.  Human impact on the ocean does not stop at the fishing industry.  Humans are also, destroying the once pristine coastal habitats that are very important nursery grounds to hundreds of marine species.  The oceans have become waste dumping grounds.  High levels of nutrients like nitrates and phosphates are poured into the ocean and giant algae blooms occur.  The oxygen is quickly used up and the ocean then becomes a dead zone.  The Danube River in Romania primarily caused the Black Sea’s demise.  Before, this river empties into the sea, it picks up run off and waste materials hundreds of miles away. Romanians dumped everything into the river and now, because of this, the Black Sea is a giant dead zone.  The only explanation for the dead zone that is now occurring in the Gulf of Mexico is ignorance.  Americans use the great Mississippi River as a waste dump and there are visible signs that we are turning the Gulf into a ‘Black Sea.’  The destruction of the oceans is in the hands of humans. Unless we stop ignoring the obvious and start using our knowledge to clean up the damages we have done, the ocean will be a lifeless desert.
=========yorg=========
===from:Amanda Burgos
===date:Sat Jan 12 20:16:22 2002
===subject:Short term thinking and Immediate gain
===message:I believe the most serious problem International Integrated Coastal Zone Management faces is that people act without taking into consideration the consequences of their actions. We seem incapable of thinking beyond the now, the  immediate gratifaction we recieve, rather than what will happen in the long run. We lack foresight. Take for instance, the man who want a beach front home...he purchases a piece of land and clear cuts ALL the mangrove on it. Ten years down the road he wonders why the ocean is eroding his land. Thinking only of the present is fundamentally flawed. If a little thought is placed on "what will happen if we do this?" a lot of headache can be saved. In the book, for instance, Woodard mention the Danube river, which is now toxic with pollution. The fault is not the result of only one contributor; rather, it is the fault of all parties invovled-- the factory outfall, the sewage release, and the other contributors. It is reasonable to say that the factories only sought the cheapest, simplest, and in their view the best solution NOW to waste disposal. The government did not think in long term either....they merely thought of sewage disposal. No thought was placed on the river flowing into the Black sea, nor the potential for the disaster they are now in. Everything is interlinked; by only thinking of the immediate we endangerous everything and everyone involved. We seem undable to foresee the result of everyone thinking only in the short term. It is because of this I think focusing on the short term and the present gains of an activity is detrimental to all. All other problems are based on this flawed thinking. For instance, overfishing and wetland destruction are prime example of people only thinking in short term. No long term thought is in place while the activity at hand is immediately gratifying.
=========yorg=========
===from:MATT BROSIOUS
===date:Sun Jan 13 19:20:30 2002
===subject:Third World
===message:The most important problem, I believe is convincing the worlds population not to over-exploit our finite resources. Its not easy to get every nation to abide and adhere to treaties and protocols. Especially when you have to convince a citizen, that is starving that he or she shouldnt cut down the rain forest just so they can feed their family. Not gonna happen. I think that the modern nations of the world need to step up and help out the citizens of these third world nations and not just their governments. If we as a planet cannot abide by a single goal, such as saving our precious resources, then we are doomed.
=========yorg=========
===from:Achim Kretschmer
===date:Wed Jan 16 15:22:34 2002
===subject:Tourism
===message:I believe that tourism as an industry is one of the most important and serious International Integrated Coastal Zone Management problems. Here we have an industry that combines many issues mentioned in earlier discussions: greed, shortsightedness, ignorance and indifference. The tourism industry has government backing in every coastal country in the world. Environmental laws are often amended or dismissed and pristine coastal areas are being developed because tourism brings jobs and cash flow. Beach development draws not only tourists flocking to resorts and hotels, but native populations tend to migrate from inland agricultural jobs to where the tourist dollars are, thereby increasing population density at the coast. This is especially true for poorer countries, but even in front of our doorstep. Step out on the NOVA campus and look north, the beach is lined with high rises and hotels, producing communities that boast a population higher than many mid-sized cities elsewhere in the country. 
=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===institution_site:http://www.nova.edu
===institution:Nova Southeastern University
===date:Fri Jan 10 14:58:17 2003
===subject:Discussion # 1 -What is the Most Important ICZM Problem in the World?
===message:  From a global perspective, the most important ICZM problem is global laws and regulations. While each nation has sovereign waters with special needs and uses, global laws and regulations need to be put in place, regarding issues that effect every country. The recent Prestige Oil Tanker Spill off the coast of Spain is an example of this need. This was the third spill of the Galician coast, a fragile ecosystem.  The tanker was one-hulled, flew a Bahamas flag, was owned by the Dutch, had a Greek captain, and was last inspected in the United States.  When the tanker was not allowed in Spanish or Portuguese ports it set sail for a country with more lax regulations.  After the spill, blame and responsibility for the clean up was not easily placed.  One of many global laws may have prevented this occurrence; such as the owner of the vessel must fly that country's flag or a global ban on one-hulled tankers.  Other considerations for oceanic global policies include; ballast water treatment, fishery catch limits, endangered species, and shipping procedures- these are just to name a few.
=========yorg=========
===from:Arlo Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSUOC
===date:Sun Jan 12 22:31:57 2003
===subject:The Most Important ICZM Problem in the World
===message:When important issues affecting our planet's coasts come to mind, a number of topics quickly come to the forefront.  Issues such as intensive development and coastal "hardening", invasive species concerns, over-exploitation of fisheries, pollution problems, and climate change particularly stand out.  However, one key driving factor behind all of these issues is the exponetial rate of human population growth in coastal areas and the increasing pattern, especially in developed nations, of excessive over-consumption.  Coasts in particular are extremely susceptible to this problem as they are receiving the double impact of "normal" population expansion through human reproduction and increased life expectancy, and the migration of human population centers toward coastal areas.  As another student pointed out, laws and policies governing coastal resources should be made a priority and will serve to improve our current situation.  However, in many parts of the world where population increase is the most rampant, law enforcement is almost nonexistent and policies on paper are seldom known about or understood by the general populace, much less practiced on the scale needed to protect dissappearing coastal resources.  Sociocultural changes will become necessary in the near future on how society relates to and uses coastal areas, especially in terms of how large population centers interact with estuarine and marine environments.  Advances in aquaculture, the conservation of essential nursery habitats, zoning ordinances, and the observation of fishing regulations will increase the coastal zone's carrying capacity of our species, but these advances will only bring us so far.  There will be a point in which there are too many human lives demanding too high a standard of living for a particular region's resources to support.  In a moral and ethical way, we must find a means to curb population growth in coastal areas and furthermore, educate these populations on the grave impacts of their consumption patterns.
=========yorg=========
===from:Christian Legner
===date:Tue Jan 14 15:45:59 2003
===subject:Most important ICZM problem
===message:I think that the most important ICZm problem in the world today is a lack of education mixed with a lack of understanding.  For example, people that harvest sea turtles and eggs often do not have a concept of the decline in global populations.  As long as turtles are still nesting on their beaches, there are eggs for harvest. Viewed another way, contractors may know that sedimentation is a problem in their favorite fishing location, but don't understand how the little bit of dirt that is getting in to the creek on their site really matters.  
 
There are many people in the world that just don't know what problems threaten our coasts because they haven't been educated.  But there are also many who see the problems on the news, but do not understand the various "small" effects all around them add up to cause a big problem.  It is sometimes very hard for people to think globally when they live their lives locally.
=========yorg=========
===from:Heather Sariego
===date:Tue Jan 14 21:16:38 2003
===subject:Most Important CZM Issue
===message:I think the most important CZM problem is lack of education and enforcement. OK, that is two problems but I think they are both the root of all of our problems. First of all, a majority of the world is not well informed about environmental issues.  It is difficult because in many cases,it is a struggle just to survive and education is a luxury.  I also think that enforcement is a huge problem.  We can have the environmental regulations and protection we want but without enforcement they don't mean much.  I have experienced this time after time. Enforcement in the ocean is even tougher than on land.  The manpower needed to catch all the offenders of coastal policies is enormous.  The laws we have in place are not being followed and the penelty when caught is not strict enough.  We need to get more funding for education and enforcement of our already existing regulations.  People need to start respected the environmental laws as they are put in place to ensure the survival of our species as well. 
=========yorg=========
===from:Laura Kukich
===date:Wed Jan 15 12:36:08 2003
===subject:What is the Most Important ICZM Problem in the World?
===message:The most important ICZM problem in the world is the inability for governments to effectively regulate their coastlines. Regulations are passed in the United States as well as other countries that are in place for protection against invasive species, endangered species, ballast water laws, industrial waste issues etc. Passing laws and regulations are the first steps in protection and preserving our coastlines. Finding an effective way of upholding these is the bigger issue. Individual enterprise and financial success is what the majority of people breaking these laws are concerned with. There needs to be an increase in communication concerning these regulations put in place by the goverment, an understanding of why these regulations are in place and an effective way of making sure the laws are upheld. 
=========yorg=========
===from:Amy Diamond
===date:Wed Jan 15 19:52:08 2003
===subject:ICZM 2003
===message:While it seems rather obvious that one of the world's biggest problems when it comes to coastal zone management is overpopulation and the resulting overconsumption, this is something that has been recognized now for several years. What I believe to be even more of a concern is why nothing with substantial effectiveness is being done to stop, or at least prevent, this problem any further. I believe that the root of this problem is simply human nature. Our ignorance, carelessness, impatience, and lack of understanding of our surroundings, not to mention humans' extreme superiority complex continually feed the destruction and demise of the world around us. It is a vicious cycle. Humans believe that their "small" individual actions could not possibly cause a great enough impact as to damage something as vast and powerful as the ocean. When we finally realize that our actions have indeed done this, we look for quick fixes to our problems, throwing in another species to make up for the one we lost, or creating policy after policy in fruitless attempts to control issues we do not even fully understand or have not taken the time to properly examine all the factors involved. Until more people, worldwide, can start recognizing this and taking a step back to see that what we are doing now is not working, there is really no point in creating even more laws and policies when in fact the majority of the population is not even aware of the current ones, nor do the current ones  ever seem to be implemented or controlled properly. I believe it will require a great deal of education, cooperation, patience, and consideration of individual socioeconomic and cultural aspects of each coastal community involved in order to start making a differnece in coastal zone management. 
=========yorg=========
===from:Jillian McCarty
===date:Thu Jan 16 13:43:56 2003
===subject:Most important problem
===message:The overlying theme of everyone's messages is that humans (and our huge population size) are the most important problem facing our oceans and coastal zones today. The problems in CZM are all a direct result of unsustainable use of our natural resources and overdevelopment by people. Education may help to some degree, but it will not solve the problems we face. Humans are driven by personal gain and unfortunately education does not seem to change that. We have to have enforcable policies and laws, it is our only hope. In order for this to happen we need an effective way to govern IICZM policies on an international level. I personally don't see that happening in the near future since the focus of the world is on combatting terror and disarming countries with "weapons of mass destruction". I would never make light of any of these issues, however it amazes me that people can ignore the mass destruction we are causing to world and in turn ourselves everyday. It would be great to bring an end to terror and possibly achieve some form of world peace. However, it would also be nice to have a sustainable planet to live on if that happens.
=========yorg=========
===from:Michelle Cho
===date:Tue Jan 21 18:07:36 2003
===subject:It's all about the Benjamins...
===message:The interdependence on all facets of IICZM decides whether or not policy is efficient and effective. Effective means of policy depends greatly on funding. Implementation and enforcement are not possible without funding. This makes the model on which IICZM is based rather ineffective. The world ocean connects 3 different types of countries: developed, underdeveloped, and developing. There is a huge disparity in available funds from each of these different groups. Unless all 3 groups are able (and committed) to put forth funds towards policy implementation and enforcement, current existing policies, as well as future policies, are useless. An example lies in shark finning. Canada and the U.S. have banned shark finning. Neither of the countries, however, have been successful at enforcing the ban. The U.S. coast guard confiscated a U.S. flag vessel carrying over 12 tons of shark fins in U.S. waters just months after the shark finning ban was passed. The problem lies in the extremely lucrative international trade of fins. If these superpowers, with their available economic resources are unable to enforce their policies, it is unrealistic to expect developing and underdeveloped countries, with just a fraction of the economic resources, to be able to find the finances to enforce their policies. The biggest challenge in enforcement lies with the lack of available funds. The roots of this problem seem to suggest a possible solution in separate governance of our oceans, in which each major body of water can use the profits of its resources to fund its own policy enforcement and implementation. 
=========yorg=========
