===from:Achim Kretschmer
===date:Wed Jan 23 14:26:59 2002
===subject:The man who made a difference
===message:In 1994 I sailed from Woods Hole to the Lesser Antilles on board the Westward, a 125 foot schooner, as part of my sea semester. After visiting several islands, we anchored at a small island called Bequia, sitting just south of St. Vincent. Anyone who has ever been in the Lesser Antilles knows that the environment has taken a beating from environmental pollution. Imagine our surprise when we set foot on Bequia, where the streets were clean of litter and the beaches free of garbage. 
We met with an old man at the island's middle and high school, and he introduced himself as the principal who had led the school since over five decades. He claimed that he educated 80% of the islands population of 4000 souls, and his agenda was to drill his students about environmental awareness. "If you see litter in the street, pick it up" he even told us. 
When we spoke to some of the students, they recited their teachers' message, telling us that trash thrown into the storm drains will be swept to sea after a rainstorm where it chokes the turtles and reefs.
The old man made a difference, shaping the mindset of an island, and it definitely showed.
=========yorg=========
===from:Kelly Adams
===date:Wed Jan 23 17:25:48 2002
===subject:A disgusting site
===message:One of the most disgusting sites that I have seen along a coastal boundary was in Hawaii. Many of the beaches in Hawaii are pristine and beautiful.  However, it was quite a shock for me to see garbage littered along the shore for many yards at a remote site on the 'Big Island' of Hawaii. It was even more of a surprise to learn that this was the result of off shore dumping by cruise boats and that the garbage had been continually washing ashore for many years. It is definitely an eye opener to see first hand the destruction we ourselves are causing to beautiful, almost paradise-like (in my opinion), places. 
=========yorg=========
===from:Ian Gibson
===date:Wed Jan 23 23:43:07 2002
===subject:Big Issues, Little Island
===message:I could write volumes on this subject, but i will try to keep this somewhat direct and to the point.  Some of the specific numbers here might be maginally off, but i will try to stay in the ballpark, since this is from the cuff and i am not doing any research.  I have spent a good deal of time on the Puerto Rican satellite island of Vieques, which has within the past eighteen months or so become a test question in most high school current events classes.  For those of you unfamiliar with the situation, here is the severely annnotated version - the US military occupies (ed) the eastern and western thirds of the island.  In fact, the East End was until recently (?) used for target practice by warships and carrier-based aircraft.  The Viequesenos (locals) have long resented this use of their island, and in recent years the protests have become heated.  The breaking point came last year when a stray munition hit and destoyed an observation tower where a civilian guard was, well, observing.  Unfortunately, the man was killed, and, to throw more gas on the fire, he was also a local.  Nation-wide attention was placed on the little rock off the southeast coast of PR, and a public outcry for the removal of the military erupted.  Now, i have fallen a bit out of the loop in the past year in terms of my own current events awareness, but i believe hearing that the military in indeed leaving.  The Navy has withdrawn from the west end already, and i think the east end will be returned to the the island this year. 
<br>
NOW my point.  When the lands are eventually turned over to the local government, there is going to a very interesting situation.  What is going to be done with all of that prime Caribbean real estate?  There are many developers on the Big Island that would love to get their hands on it (as in the financiers behind the multi-billion Conquistador Hotel in San Juan).  That, however, would land the locals in another heated battle - after being confined to living in a third of their OWN ISLAND for over fifty years (?), are they going to want to just hand it back over to Big Island developers who don't really give a damn about the local population except for menial labor?  To boot, they aren't really crazy about main islanders anyways; Vieques has become a weekend spot for boaters from Fajardo and other eastern Big Island cities.  They tend to be loud and dirty....you know, like any good tourist.  
<br>
The problem doesn't end there.  The coastal ecosystem of the island could be in serious danger.  While overfishing has done serious damage to the area's fish populations, the mangroves, seagrass beds, and reefs of the coastal zone have avoided extensive damage.....though years of bombing did take a pretty good toll.  In any event, development would absolutely ravage what is left, or at least prevent/hamper the healing process.  Development of any sort would ruin the most spectacular aspect of the island ecology - Mosquito Bay.  This embayment is really a lagoon in the mangroves connected to the ocean by a long narrow inlet, and it is also one of the most brilliant bioluminescent bodies in the world (one of only a handful left of this quality in the world).  Development would create ambient light, which would ruin the ability to see the halo-like glow that surround your body as you jump into the lagoon on a moonless night.  
<br>
I don't have an answer....even trying to think of a basic compromise on one of the issues above can give you a migrane.  Of course, we didn't get into this field to be confronted with simplistic, color-by-numbers type problem. We are going to HAVE to come up with some type of solution, or a series of compromises that are logical and not based on some specialized agenda.  Yeah, i know what you are all thinking.
<br>
Good Luck.
=========yorg=========
===from:Kristi and Greg Foster
===email:scubadoobydoo@hotmail.com
===date:Mon Jan 28 19:07:22 2002
===subject:Haiti - 3 Different Situations
===message:We just returned from Haiti today and will co-write this story. There are so many issues in Haiti that we will simply report what we saw and leave most of the reasons why and the improbable solutions for the reader to discern.
<p>
We had a great opportunity to tour three areas around the country; Port-au-Prince, Kaliko resort along the Cote des Arcadins, and Cap Hatien.  In these diverse areas we observed and were made privy to several different ICZM issues.  Common to all three:
<br>
* No national ICZM program, or any other environmental programs, due to the extreme poverty and political chaos of the country;
<br>
* Most of Haiti has been irrevocably denuded by the local population, particularly around Port-au-Prince.  Most trees were cut to make charcoal for cooking.  Subsistence farmers cleared the rest.   
<br>
* Plumbing is available only to the small middle and upper classes.  Grey water runs down the streets and straight into waterways without treatment.
<p>
Port-au-Prince:  In the past 15 years, this city has grown from 200,000 people to 2,000,000 and from 50,000 cars to 200,000 cars.  The Port still receives a lot of large ships and barges, though the cruise ships no longer use it. In this same amount of time, our guide told us that the coral reef that was once in the port has died.  In fact, there is a grounded boat to mark the spot where it once was.
<p>
Cap Haitien - This is also a port city, though much smaller.  Here we saw garbage lining parts of the coast.  Our local guide said this was used as fill to create more land for development.  While this may be true, there was no apparent control or other methodology to the landfill. 
<p>
We also saw the classic beach destruction due to the building of a seawall.  In what was once a more expensive neighborhood, a seawall was built to protect the property.  Our guide could remember playing on the shore when he was a boy.  Now the sand was completely gone and the water level was several feet up the wall itself.
<p>
Kaliko - Except for a few densely-packed cities, Haiti has very little development along its coasts.  This particular resort (~1.5 hours north of Port-au-Prince)has a rocky beach, partly due to the lack of trees which can no longer prevent the rocks from rolling down hill and ending up on the shore.  The decline in tourism has vastly reduced the local diving, from 4 boats operating daily to only 1 boat operating on the weekends.  For the past 20+ years, all of the diving in the area has been managed by Mr. Jose Roy.  We talked at length with him and learned that overfishing has steadily impacted the size and number of fish on the reef and indeed, everything there seemed to be in miniature form compared to elsewhere in the Caribbean.  However, there is very little boat traffic in the area - the local fisherman are using mostly sailboats or kayak/dugouts.  This, along with Jose's respect for the reef over the years, have left this area amazingly pristine and with incredible diversity.  The coral, sponges, and plants were in very good health.  A great example of one person making a difference!
<p>
We also got the opportunity to see Jose bringing in a ship to sink as an artificial reef.  There were no governmental requirements for him to do this.  The ship was a trawler, ~250 feet, that was no longer in operation at Port-au-Prince.  The government was about to fine the owner unless the ship was removed from port.  The owner had no more use for it, so he gave it to Jose provided that he move it from the port.  Jose stripped the ship and had a tugboat move it to the bay at the resort.  To remove the residual oils and fuels, the boat was lit on fire.  Of course, Jose realizes that this causes some pollutants to be released into the air, but he believes this is better than into the water.  (In the US and other countries, solvents and hand-wipes to remove the oils and residuals create wastes that are land-filled.)  The ship will be sunk this week, with no further requirements as to placement, markings, or anything else.
<br>

=========yorg=========
===from:johnosullivan
===date:Tue Jan 29  8:30:29 2002
===subject:assignment 2 czmt personal story
===message:The reason I decided to go for a degree was a personal experience involving the canals on which I live.  These were built as a  residential canal zone in 1968.  It has access to a tidal flow through the New ZRiver in Ft Lauderdale.  After reading the "intro to CZMT"  I see some of the over lying frustration based on seperate jurisdicitions.  Let me give you an idea of a simple problem with no resolution as of yet.  In 2000 the city of Oakland park decided to widen a bridge over the choke point between the lakes and the river.  The city submitted a plan to the county, which disapproved it based on community input namely my group.  They had not done a below stream impact statement and the impact to local biological life wasn't even addressed.Apprantly the county latched onto a " mussel" which it claimed was an anchient mussel bed  (anchient 1968?) >  The local community tried to get the US ARMY corps of Engineers involved, Who supervised the initial construction but they lost jurisdiction in the late 1970's to the US Coast Guard, they have an interest because it can be used for recreational boating.  In 1987 the responsibility was passed to US Environment dept based in Atlanta.  They claimed they could not commence a study without state request and the state will not begin a review of the subjest until the county cites the city if the construction goes forward.  We are still working the problem but may have found a working group within the Southern Eastern water management group, I'll keep you posted.   This has been an excellent project and this involved only US interests imagine the difficulties involving more then one countries sets of common laws etc..
=========yorg=========
===from:Greg and Kristi Foster
===email:fjohn@nova.edu
===date:Wed Jan 30  9:55:19 2002
===subject:Yap Preserved the Yapese Way
===message:As recognized by the UN General Assembly in documents such as Agenda 21, small islands are particularly susceptible to severe degradation of natural resources.  While there is no doubt that many island nations have succumbed to the pressures of modern development, others have not.  It would seem that valuable strategies could be gleaned by examining the means by which small island nations have retained intact ecosystems.  Our experiences during a recent visit to the very small Micronesian island of Yap may yield some insight into these processes.
<p>
Unlike most cultures that have embraced the tourist trade, the Yapese culture has remained largely unaffected by contact with the modern world.  It would seem they have achieved the rare feat of selecting a few modern elements to use with the tourists(cash economy, cars, grocery store scanners), without contaminating their traditional culture with these elements.  We believe this ability is at least partially responsible for the remarkable preservation of this island’s coastal resources.  That Yap’s initial tourist development was initiated by retiring Peace Corp volunteers undoubtedly contributed to this rare balance of belief systems.  For instance, the owner and founder of Yap Divers came to Yap as a Peace Corp volunteer, is married to a high-ranking Yapese woman, and bears traditional Yapese tattoos.
<p>
Despite such modern developments as shipping ports, airports, and eco-resorts, the mangroves surrounding the island were entirely intact.  We kayaked through a large stretch of these mangroves, guided by an English-speaking local resident.  The experience of gliding though pristine mangroves was so enthralling that we pushed our guide to extend our tour well beyond the planned time.  As the daylight began to fade, she became emphatic that we exit the mangroves.  When we inquired about her urgency, she replied that we must not dwell there because of the spirits that awaken after sunset.  She then went on to tell horrific tales of what happens to people who dare to venture into mangroves after dark.  Further questioning revealed that destruction of mangroves would certainly release angry spirits that would exact great suffering on the inhabitants of the island.
<p>
The utility of such traditional beliefs should not be underestimated.  And likewise, we representatives of the modern world should be careful not to disrupt them.  In the absence of scientific and governmental programs, such indigenous beliefs have preserved Yap’s mangroves far better than any modern society can claim.
<br>

=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution:nsuoc
===date:Tue Feb  5 13:42:55 2002
===subject:From the Beginning
===message:     My most interesting story dealing with CZM is the Florida Keys National Marine Sanctuary and and other marine issues in the Keys.  I spent most of my time growing up in the Keys, so i have been able to see all of the marine management policies discussed, passed and implemented.  As an avid fisherman and sport diver, i agree with the policies within the management of the sanctuary.  The different designations of zones within the sanctuary are especially helpful to the related marine system.  The no-take zones throughout the sanctuary have been a success (at least in my opinion).I have noticed an increase in the numbers of recreational species such as Yellowtail snapper and spiny lobster.
     One suggestion i would have towards the management of the species within the sanctuary would be "rolling closings."  Instead of permanenetly closing certain areas, which is opposed by some commercial and recreational fisherman, certain areas should be designated as no-take zones for set periods of time.  For instance, close one reef for a year, re-open it, and close an adjacent (or different) reef for the next year.
     More recently, the Sanctuary was expanded to include the areas surrounding the Dry Tortugas.  The will be beneficial in preotecting the fertile, deep reefs of the area.  These deep reefs, such as Sherwood Forest, are rare due their depth and composition (Black Corals).  One goal i have is to dive at least this site in the coming months.
=========yorg=========
===from:Michelle Cho
===date:Tue Jan 21 19:20:31 2003
===subject:Ras Mohamed Nat'l Marine Park
===message:In 2000, I went to the Sinai peninsula in Egypt to dive in the well reputed Red Sea. There's a national marine park right at the tip of the peninsula, and our divemaster warned us about the importance of not touching anything. He threatened to unbuckle our weight belts if he saw us touch anything. I was surprised by his vehemence, but not put off by it. I kind of liked the strict way in which he tried to enforce the park's policies. The day we entered the park, however, I was definitely put off. That morning, a bunch of hung over, wealthy, European tourists decided they wanted to dive in the park that day, as well. Their number exceeded the daily limits this park would allow. It was no problem for them, though, as I watched the dive organization pay off the rangers (baksheesh) as we entered the park. Then, during our dives, I watched these divers hang onto the reef, break pieces off, and disturb almost all life they encountered (including my buddy and I). Only advanced divers were supposed to be allowed to dive in this park, or divers w/ 30+ dives. I observed many of these tourists having buoyancy problems and later learned that it was only their 5th dive, and that some of them had been certified online!!! (hey, you can do anything online these days! ;)) Despite the divemasters' strict guidelines, they did nothing to discourage this damaging behavior. This was an eye-opening experience for me, as previously I had only dove (dived? diven?;)) in areas in SE Asia, where budget travelers were rampant. I had found most of them to be a lot more respectful of the reef. This experience made me realize how difficult it is to enforce laws and regulations in underdeveloped and developing countries. As long as someone has enough money, they can get around any existing conservation policies. 
=========yorg=========
===from:steffen Schmidt
===date:Sat Jan 25 13:36:55 2003
===subject:Ghosts and Spirits - Arlo's Message to the Foster's
===message:<p> Arlo: since you posted to an earlier posting from 2002 when the Foster's took the class I've taken the liberty of inserting your comments here since they are so interesting (and deal with deep cultural issues related to coastal zone management)! In many ways we all have cultural and behavioral traditions and myths that shape our views about and treatment of the shore, beaches, coasts, and oceans. Sometimes they are more "exotic" like the duendes (we have those in Colombia where I gre up too!)... but other times they are myths about the "condo's" and "the good life" and "success =a really nice 1.6 m ocean-facing 3 br apartment in Aventura!<p>
"Hey Greg and Kristi, Your story about the belief of evil spirits in the mangroves of Yap is extremely interesting in that I found very similar beliefs in coastal Ecuador. The people of the northwestern coast, along with most of the coast of Colombia, believe in a mangrove spirit called the Tunda. This is an evil spirit that often takes the form of a beautiful woman and draws men into the mangroves with her singing. If you become enchanted by the singing, she draws you down into the mangrove mud and you dissappear forever. Further south in Ecuador, the Tunda is replaced by a Duende, or evil dwarf, that will kill you if you harm the mangroves. Arlo 
=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===date:Mon Jan 27  7:54:48 2003
===subject:That's my sand!
===message:My example is a fresh water example. In my undergraduate studies (in Chicago), I took a Coastal Engineering course.  Illinois is one of the only states that does not participate in the Coastal Zone Management Act and therefore much of the coast is privately owned. A particularly wealthy section, north of Chicago, is called the Gold Coast.  As part of the course, we would go to these homes on the coast and assess their beaches.  Many of these homes had individual break walls, jetties, or other structures, worth lots of $$$, to hold the sand on 'their' beach.  On such a small scale these structures stopped flow of sand from one house to the next, therefore residents were thought to be 'stealing' sand from their neighbors. My thought was that if they all worked together and catered to the area as whole, they might find more efficient means...Another ironic note is that many of the their homes were in danger of being eroded off of the cliffs they were on, due to Chicago's fierce winters and winds. So, every few years they have to rebuild their cliffs and reinforce them. I feel their battling with nature and their millions might be better spent.   
=========yorg=========
===from:Heather
===date:Mon Jan 27 20:52:10 2003
===subject:Sariego
===message:Shark Soup! Coming to Costa Rica has been a lifetime experience for me. I came to teach about the environment in an area that is visited for its natural environment. At first glance, Costa Rica looks like a country that is prides itself on protection of its natural resources. Hence the term commonly used "Pura Vida" or pure life.  But what they really mean is protection of terrestrial environments.  I have noticed in my few months here a real need for coastal and marine protection.  As I was visiting the Caribbean coast, I saw lots of shark and billfish on the menu.  I also had a boat captain proceed to tell me that it was ok to eat hawksbill turtle eggs because they are not endangered. What an eye opener! I understand now more than ever the need for environmental education and coastal zone management in areas of the world like Costa Rica.  Sometimes it is overwhelming how far we have to go! 
=========yorg=========
===from:Heather
===date:Mon Jan 27 20:54:42 2003
===subject:Sariego
===message:Shark Soup! Coming to Costa Rica has been a lifetime experience for me. I came to teach about the environment in an area that is visited for its natural environment. At first glance, Costa Rica looks like a country that is prides itself on protection of its natural resources. Hence the term commonly used "Pura Vida" or pure life.  But what they really mean is protection of terrestrial environments.  I have noticed in my few months here a real need for coastal and marine protection.  As I was visiting the Caribbean coast, I saw lots of shark and billfish on the menu.  I also had a boat captain proceed to tell me that it was ok to eat hawksbill turtle eggs because they are not endangered. What an eye opener! I have also been researching the trade of shark fins here in Costa Rica.  International ships come into the port of Puntarenas and ship fins overseas to the markets in Japan and Asia. Although the fins are being exported by Costa Rican airports, it is not considered an export of Costa Rica since it is coming from international ships! I understand now more than ever the need for environmental education and coastal zone management in areas of the world like Costa Rica.  Sometimes it is overwhelming how far we have to go! 
=========yorg=========
===from:Amy Diamond
===date:Tue Jan 28 10:21:54 2003
===subject:lobsters!
===message:A few months ago I went down to Biscayne National Park to help out in "regulating" lobster mini-season. I stood on the dock with about four others, who were both employees of BNP and student interns. Our job was to interview the fishermen as they came into the dock and keep track of the number, size, sex of the lobsters they caught, and the sites and methods by which they captured them. It was interesting just to see how the fishermen would react to us waving them down (most of them know that this stop at the dock is not mandatory) - some would act completely oblivious, just pretend they didn't see us and keep going, some would shout some really "choice" phrases at us (!!), and some, on the other hand, were quite willing and proud to show us their catch for the day. What was even more interesting to me was the process of recording the statistics and getting a little glimpse at the extent to which this activity is, or can be, accurately monitored and managed. Quite a few boats pulled in females carrying  eggs. As far as I understood, they are supposed to check this before they catch them, and throw them back in if they find pregnant females. WHen we would point out to the boat that they had done this, we tried to do it in a constructive way, just showing them how we look for eggs or measure the size, if efforts to not offend or insult them. Most of them would seem very shocked and tell us that they did check. Some of them didn't seem very interested! The same thing occurred when we found several lobsters that did not meet the size requirements. Regardless of whether they knew what the requirements were or what they had caught, the questions it brought up in my mind was why is there not more enforcement being carried out BEFORE they reach us at the dock? Because at this point, most of the lobsters we found were already dead and it would be pretty pointless to throw them back in the water? Not to mention all the boats that drove by us that we did not interview. It was an eye-opening experience to see first-hand the conflicts that exist between user groups for the oceans and also the apparent incohesiveness of some coastal management aspects. Even if the policies are established, does not mean they are always being sufficiently enforced or implemented. 
=========yorg=========
===from:Jillian McCarty
===date:Tue Jan 28 12:27:59 2003
===subject:my personal story
===message:Growing up in Philadelphia, I spent most of my summers at the Jersey shore. When I was about 10 years old I had a life changing experience in Ocean City, NJ. My friend and I were floating about in the ocean, when we started to hear screaming and commotion about a shark. Lifegaurds got everyone out of the water and quickly determined there was no shark, rather a dead bottlenose dolphin. It seemed very sad to me as I watched them drag the carcass onto the beach and take it away in a truck. The beach closed as did many in the area shortly afterward. Later we came to learn that more animals were washing ashore dead, as was enormous amounts of medical waste. When I realized that this waste had purposely been dumped in the ocean I became very frustrated. Even though I was young, I really wanted to help prevent something like this from happening again. 
This was my first experience with problems in our coastal zones. However it had the most direct impact on me because it led me to pursue a career in this field. 
=========yorg=========
===from:Arlo Hanlin Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSU Oceanographic Center
===date:Tue Jan 28 19:54:30 2003
===subject:Shrimp versus Mangroves?
===message:Prior to coming to Nova, I worked as the Director of the Coastal Conservation Program for the Jatun Sacha Foundation, an Ecuadorian NGO.  When starting with the program, we traveled up and down the coast of Ecuador in an effort to pinpoint what were the most pressing issues affecting the coastal zone.  Many issues came to light including shark-finning, point pollution, overfishing, lack of sewage treatment, lack of management of protected areas, lack of protection of threatened species such as sea turtles and American crocodiles, and trawling.  However, one issue stood out far beyond the rest for the shear magnitude of its impacts.  This issue is the conversion of mangrove wetland and salt flats into shrimp farms.  Shrimp farms first became established in coastal Ecuador in the late 1960s.  The industry expanded rapidly in Ecuador, becoming the third largest export commodity after oil and bananas.  Ecuador's shrimp farms became the largest aquaculture industry in the Americas and the biggest supplier of shrimp to the United States.  However, the expansion of this industry did not come without a price.  Due to a multitude of factors, including lack of a legal framework protecting coastal ecosystems, an ignorance of aquaculture best practices on the part of small-scale farmers, cheap land prices, and basic trial and error of a fledgeling industry, literally thousands upon thousand of hectares of mangrove wetland and other coastal ecosystems were converted into an endless horizon of square earthen ponds.  Additionally, many coastal communities were displaced, local artisenal fisheries were destroyed, and the major estuaries were eutrophied and otherwise polluted.  The industry eventually suffered a near collapse from the uncontrolled spread of disease within the high density monoculture environment of the region.  This collapse allowed my organization to enter the scene on the basis of introducing best practices.  The methodology we adopted was to partner with a local shrimp farm, establish a mangrove reserve and research station, and convert the shrimp farm into a model of internationally accepted best practices. Modern thought in shrimp farming naturally avoids mangrove areas, preferring the biosecurity of inland farming with the use of well water and laboratory-reared larvae.  Additionally, excess nutrients are now removed through biofilters, a minimalist approach is taken with antibiotics and other chemicals, and when present, the presence of mangroves is encouraged due to their role in preventing the erosion of shorelines, filtering nutrified waters, and providing a nursery habitat for juvenile shrimp as well as commercially important fishes.  Ecuador still has a long way to go before their industry meets these standards, but economic disaster has opened the doors to restore the damages of environmental disaster.
=========yorg=========
===from:Laura Kukich
===date:Wed Jan 29 12:02:29 2003
===subject:The things we'll do for money.
===message:In my hometown in southeastern Virginia, we basically live in the marsh and the majority of the families orginially made thier living from the Chesapeake Bay. It's a relativly small fishermans town, one stop light, one flashing light and everbody knows just about everyone. One man has owned quite a bit of land in the area and has developed some of it but, left it to his son when he died. The land was very close to my home, an area that had been developed by his father, and as a kid my freinds and I would play out in the woods and in the marsh. Dirt trails and tire swings were throughout the area from the kids and locals who used it. The son, about 2 years after the death of his father decided to develop all of it into huge $500,000 homes. He brought this to the city to get approved and it was initially denied. The city is small and the area to be developed was near marshland and water, in order to compensate for the amount of construction done to the area, the city would have to complete new roads, increase school capacities and tackle several other large development issues. The community was trying to prevent as much construction as possible because of the damage that is done to the area but, people are willing to pay as much money as it takes to be near these water-view areas. The next week as we passed what used to be a beautiful area of vegetation, we passed by broken trees and destroyed habitat. He had destroyed the area anyway, and eventually got the permits to build. Now the area has about 40 of these monstrous houses near the water. 

What we do for money.
=========yorg=========
===from:Christian Legner
===date:Wed Jan 29 13:08:15 2003
===subject:ORV Management
===message:<p>My personal coastal zone management experience is about Cape Hatteras, NC and the National Park Service.  Currently, vehicles are allowed to access certain areas of Park Service land along the Outer Banks, and on Cape Hatteras National Seashore without a permit or payment.  Some environmental groups oppose the operation of off road vehicles(ORV) in the National Park, citing habitat destruction and disturbance of nesting piping plovers, among other things.</p>
<p>The park's current management of ORV access includes a ramp system that controls entrance points to the beach, enforcement of responsible beach driving, and large protection areas marked around bird and turtle nesting sites.  This "management" is not controlled by an official ORV Management Plan as required for all National Parks.</p>
<p>Some suggested plans include instituting a fee/permit system to limit vehicles and increase revenue for conservation goals.  Some conservation groups want to prohibit vehicular beach access citing the Cape Hatteras National Seashore Enabling Legislation, which makes reference to preserving area "as a primitive wilderness" and that plans for the "convenience of visitors...would be incompatible with the preservation of the unique flora and fauna."</p>
<p>But here is my feeling about this area that I visit, fish, and, yes, drive at least twice a year.  While the introduction of ORV's to an easily erodable area is probably not the best management plan, the next best thing is to limit the amount of access by providing a controlled location where people can enjoy the privelege.  While I have witnessed the incredible erosion of the Outer Banks over the last 23 years, I do believe that the current plan is not so bad considering:<br>
1. Loss of vehicle access to the great fishing at the "point" will shorten the tourist season, which would be a major blow to the local economy which has already taken a hit on the commercial fishing front.<br>
2.  Much of the seashore to both the north and south is heavily protected, but could become damaged as people who have lost legal ORV access look for secluded places to gain access.<br>
3.  Many of the current users of the ORV access area of Cape Hatteras are conscientious and respectful. While strict enforcement has helped this along, a love of the area inspires many people.<br></p>
Having said this, I also believe that the Park Service needs a valid, defendable ORV Management Plan.
=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===institution:NSU
===date:Thu Jan 30  7:39:07 2003
===subject:On a positive note...
===message:After reading all of the replies and our mostly negative experiences, I began to think of a positive example, something that's working.  TIDE (Toledo Institute for Development and Environment) is a NGO is southern Belize.  TIDE co-manages the Port Honduras Marine Reserve with the local community members (little government input). Together three communities decided to ban gill nets, agree to seasonal catch regulations and size regulations, and to focus on sustainability versus today.  The reserve is five years old and TIDE has successfully trained many former fisherman as tour guides and others as researchers and rangers.  Though depending on tourists may not be the perfect solution, relieving pressure off the resources and giving the locals the sense of ownership they need has proven to be successful so far. 
=========yorg=========
