===from:Amanda Burgos
===date:Sun Feb  3 17:48:51 2002
===subject:The truth about ICM initiation
===message:I believe the statement is true, that <b>developed</b> nations state economic development for ICM initiation versus <b>developing</b> nations accredit ICM initiation to environmental issues. In my opinion the matter all boils down to greed and a general believe you have no other means of action. It is a simple matter of the "have's and have not's". 

<p>It is common knowledge that those <b>developed</b> nations which "have" achieved economic gain are striving for more. Essentially greed plays a key role in the matter...they do not care about the environment until the situation is dire. They removed mangroves,destroy beaches, and search out for remote areas to destroy, all in the name of economic gain. It is in the attainment of this economic gain/development they experience the cumulative effect of their actions. It is in this discovery that they realize the need for an integrated coastal zone management plan.

<p>In the world scenario the <b>developing</b> nations are the "have not's". In their strive for economic gain (achieving a "developed nation status") they destroy what they do "have", behaving carelessly, damaging coastal ecosystems. In addition to reckless environmental behavior, their countries face an additional problem poverty. Poverty is a large issue in these areas, causing a series of problems such as, the cutting of mangroves for fire wood or the encrouchment of the population on coastal areas. Increased pollution and insufficient funds for the proper disposal of sewage and trash, all add up to a situation of environmental dispair. The result being a need for some sort of intergrated coastal zone management.

<p>The implications of two sources for ICM initiation does not diminish the need for there establishment nor the basic prinicples they are funded on. It does, however, makes the situation all the more difficult. In the case of <b>developed</b> nations, greed and money are a difficult force to battle against. <b>Developing</b> nations do not differ greatly in that the lust for money is also a powerful negative influence on ICM initiation. The plight in <b>developing</b> countries is greater as you are addressing a public, which feels it has no other course of action. In both circumstances, however, the battle to change minds and lifestyles is a difficult one.
=========yorg=========
===from:Kristi Foster
===email:scubadoobydoo_FL@hotmail.com
===date:Tue Feb  5 14:27:57 2002
===subject:Economic and Environmental Reasons
===message:I think the statement is true, though somewhat misleading in that both economic AND environmental reasons for initiating ICZM were given by countries regardless of their status (developed vs developing).  Both are very important - the difference had more to do with ranking priorities rather than chosing one to the exclusion of the other.
<p>
For developed nations, economic  benefits were ranked higher as reasons for starting ICZM programs.  Let's start with considering which nations fall into this category:  the US and UK, Canada, France, the Netherlands, Japan, Australia, etc.  These countries are some of the forerunners in technology and are indeed very interested in global marketplace competitiveness.  Presumably with stable governments, active social programs and environmental controls (though the effectiveness of these may be arguable), these countries can focus more of their attention on the value of the coasts and the oceans.  This includes land development, fisheries management, oil & gas production, deep sea mining, biopharmacueticals, etc.  Similar to other business strategies, when a new market is developed, the policies and procedures grow up around it.  Upon maturation, the business finds itself entangled in a web of inefficiencies, redundancies and jurisdictional splits.  All of these cost money and impact the bottom line; therefore streamlining efforts are begun.  This analogy can be drawn to the developed nations' ICZM programs.  Coastal and Ocean-related policies have developed piece-meal over the past 25 years, with no oversight agency looking at the big picture.  It has gotten to the point where agencies are tripping over each other and it's taking more time and $$ to get less done.  This is effecting each country's global competitiveness.  The time is ripe for re-engineering...thus ICZM.
<p>
In contrast, the developing nations are still working on stabilizing their governments, implementing social and environmental programs, as well as trying to get a foothold in the international marketplace.  In addition, they are under extreme pressure from the developed nations not to destroy the last of the world's valuable ecosystems.  They don't want to make the same mistakes that the developed nations did through over-exploitation.  Therefore, given the chance to do it right the first time, these countries consider the environment an important building block upon which to base their policies and procedures.  If they can bring in the newer technology without suffering the resource depletion or the pollution that the developed nations self-inflicted, this is definitely the smarter and more responsible way to go.  Let's also not be fooled, by pushing the environmental protection agenda, the developing nations are more likely to get monetary support from the developed nations than if they simply pushed for access to technology for economic gains.

=========yorg=========
===from:Matt B.
===date:Tue Feb  5 15:40:14 2002
===subject:ICZM implementation
===message:Countries should precisely work out and implement national ICZM policies, including legislative measures and economic plans, in order to ensure sustainable development of resources and not only should the resources be sustainably developed, but they must also be conserved for future generations. A good example of such implementation is the Black Sea Programme (BSEP)and more specifically the Georgia ICZM program. Georgia's ICZM plan is paralleled by on-going investments in coastal regions of the country under the Municipal Infrastructure Rehabilitation Project (MIRP), which is funded by the World Bank. MIRP plans to upgrade exhausted sewage and water supply systems in the coastal cities of Batumi and Poti, rehabilitate solid waste treatment operations and develop river engineering solution for the landfill site in Batumi. This ICZM "seeding" into the coastal investment project provides a useful mechanism for integrating interests of various key authorities (Ministry of Environemt, municipalities, coastal research institutions, project implementing agency, multinational donor and others) in developing most appropriate allocation of resources for environmental improvements. I hope this has served as an example of how a country should bring together its legislative bodies and stakeholders, as well as the implementation of the ICZM plan along with other investment projects.
=========yorg=========
===from:Kelly Adams
===date:Tue Feb  5 20:39:23 2002
===subject:The need for ICZM
===message:One of the articles suggested that a reason developing counties would cite environmental issues as the reason for initiating ICM is perhaps the realization of the environmental costs of inappropriate economic development. I believe this to be true. 
   I think a prime example of this is the United States and their efforts to safe the city of New Orleans. A lot of money was invested in order to protect the developing city from flooding of the Mississippi River.  In turn this caused massive amounts of wetlands to be destroyed and ultimately created a bigger problem for the city.  There has been a lot of environmental damage to the coastal areas of Louisiana in addition to the Gulf of Mexico because of the efforts to save the city.  As the article suggested, perhaps developing countries have realized the enviromental costs of inapproiate economic development. 
   On the other hand, developing nations have more poverty and therefore, more individuals (understandably) willing to sacrifice a mangrove swamp in order to build a shrimp farm that will supply money to feed their family. Of course the destuction of such habitats cause negative environmental effects, thus developing countries are more aware of these types of environmental issues.  The important fact is that it is apparent that ICZM is needed for whatever the reason in both developed and developing countries. 
=========yorg=========
===from:Rebekah Walker
===date:Tue Feb  5 21:57:52 2002
===subject:Marketing the Environment
===message:	Although it seems that developing countries are more worried about economics than the environment, one must look first at the placement of these countries on the globe.  Most developing countries have begun to rely on a great deal of money from tourism (granted this is not true for all, but people are starting to look for undeveloped areas and they are generally found in undeveloped countries).  The important thing is that the majority of the public in these areas realizes that their money is becoming more and more linked to tourists, who want to see “pristine” environments.  Since a large percentage of the population knows this, environmental education needs only to connect the dots between conservation and a better economic outlook.  ICZM offers a way to account for the social, economic and environmental aspects of the area before determining a plan of action, however when asked why the project needs to be started, respondents think back to what their customers are looking for: environments lacking all the issues of their home country.<p>

	On the other hand, in developed countries, economics are the top priority.  If people see that ICZM will help the economy, they will accept it without needing to understand the environmental implications.  Economic development on the coast has needed to win a growing number of battles with environmental groups trying to save the coasts.  ICZM offers them a way to develop, while accounting for the environment, so they can make money and the activist groups stay off their backs (well, sometimes).  Therefore, in this situation, although the environment will benefit, if asked why ICZM should be put into action, the people think to the economic development that can be accomplished by making some compromises.<p>

	The implications for ICZM are simply to cater to what the public is searching for.  ICZM should be presented to a country and its public as a way to solve their major issues, while solving other issues along the way.  Developing countries are prime places to start ICZM because it can help solve the environmental issues, which in turn will help their tourism.  By illustrating this to the public, developing countries will support ICZM proposals, and work with environmental groups to meet the goals.  In developed countries, people need to see how ICZM will allow economic development and in turn keep that development sustainable through a healthier environment.  In many ways, it is a matter of marketing, and knowing how and who to market to.  This does <b>not</b> involve lying about ICZM, it involves showing the aspects that will benefit that group of people.  For some reason, people want to see what will help them and then tune out the rest, so show them what will help them before they start to tune you out.  Then if they are interested they will listen for more details.  In developed countries there are also people who have the luxury of not only worrying about how to eat the next day, but also about how to save the environment, so this is also an important group to consider.  We have seen it in the past, but need to listen to our own words.  ICZM needs to be catered for each place specifically; this involves catering the program to the needs of the public and marketing the program to the interested parties.   

=========yorg=========
===psite:http://fjohn@nova.edu
===from:Greg Foster
===date:Tue Feb  5 23:12:37 2002
===subject:Environmental&Economical are One and the Same
===message:While I agree that developing countries have clear environmentally-based motivations for implementing ICZM policies, I believe economic motivations underly many of them.  Examples include the following:   
<p>
1. The economies of many developing nations are based on exportation of renewable natural resources to developed countries.  ICZM policies can aid in sustaining these revenue sources, while at the same time preserving to some degree the utilized sector.
<p>
2.  Many developing nations, though certainly not all, derive a sizable portion of GDP from tourism.  Many tourist draws, such as beach resorts, sport-fishing, birdwatching, snorkeling, diving, and eco-tourism, necessitate healthy and aesthetically-appealing ecosystems.  Managing conflicting resources, and thus the ecosystem as a whole, requires ICZM.
<p>
3. Many developing nations are under pressure from developed nations to preserve their rich ecosystems in the name of global preservation, e.g. greenbelts for CO2 sinks, preservation of biodiversity for conservationist principles and genetic-resource exploitation.  As a result, international funds often have an environmental string attached.
<p>
4.  The need for nutritional self-sufficiency.  Many developing nations can't afford not to be self-sufficient, and thus are more dependent than developed countries on locally produced or harvested foodstuffs.  ICZM offers long-term solutions to these concerns, versus the short-term and destructive practices of slash and burn agriculture, poorly managed aquaculture, and overexploitation of fisheries. 
<br>
5. Industrializaton efforts in developing countries are often made with little or no regulation/enforcement of hazardous emissions.  Such unregulated industry can create staggering environmental problems, which can slowly, or quickly, become economic ones. 
<p>
But the ultimate motivation for implementing ICZM policies is not the paramount issue.  Instead, it is the potential ecological benefits that can result from an earnest attempt at ICZM.  By definition, if developing nations achieve sustainable consumption and production, the ecosystems supporting this effort will be preserved to a much higher degree than without ICZM.  In the end, that is what matters most.

=========yorg=========
===from:john osullivan 
===email:johnosul@aol.com
===date:Fri Feb  8 13:32:35 2002
===subject:Survey disappointment
===message:I was a little disappointed with the survey results.  As a member of a developed country I would have expected survey respondents to be more eco aware and by now understand that the economy cannot stand alone from ecological stewardship.  Two prime exampoles of this is the Exon Valdez oil spil and the Eco-terrorism of Mr. Hussian alighting the Kuwait oil fields.  I would have expected developed countries with nightly CNN news to be more intellectualy mature with respect to cause and effect of short term environmental concerns, rather then underdeveloped countries.  I agree with Greg that undeveloped countries are just trying to survive and more interested in hard cash and a ready source of protein in a low technology environment.  I wonder if there might be another reason.
Last year I visted Bolivia and was surprised to see so many cell phones with the general public, espically college and high school kids ( American Arrogance?).  This despite the fact that most of the country still do not have land lines.  The learning curve, though sharp has none the less been fast.  I wonder similarly if developed countries have benefitted from the so call developed worlds mistakes or if it is just a resource dependent mentality ( Remember the 2000 computer scare, not a problem if you only had computers post 1995).
With any survey I like to dissect the statstics, including the population surveyed, the mood, including the motivation to respond and as Greg implies if semantics have played a role.  I rather approve of Rehebikas modern usage of marketing CZM as the future of economic developement. The developed nations use of quick fixes have been well documented,  the undeveloped countries might now benefit, from incorporating environmental resources on a National level, as Beliz, or incorporating NGO's and international parterships to utilze their experience and cost sharing.  Perhaps the reason the underdeveloped countries listed the environment contrary to economics is that "they" have a different view on what is a successful program.  Are the end goals different from a capitalist paridigm.  Is   a countries goal to be monatary rewrding before a project is sanctioned or do some societies place a long term multi-generational view to success, "sacrifice today for tomorrows child" ( China model),.
  It may well be that underdeveloped countries, with limited manpower expertise and minimal infrastructure need an intra-governmental approach. In an intragrated CZM model it is ideal in terms of time and rewards i.e. In 1998 nine countries of the winward islands formed the RSS, originally designed as a Regional Support Service for Security, drug running and natural disaster relief, it has now included  domestic social reforms, tourism, protection  of tradional fishing and cultural similiarities. ( headquarted in Barbados)  These islands learded they importance of interdependency when St. Lucias volcano erupted and threatened  coastal populations.  Individually they didnot have enough sealift to evacuate.  Together they did.  As good a model, not to mention incentive, to build a positive intergrated CZM policy, espicialy inview of the Marshall Island scereno.      
=========yorg=========
===from:john osullivan 
===email:johnosul@aol.com
===date:Fri Feb  8 13:34:25 2002
===subject:Survey disappointment
===message:I was a little disappointed with the survey results.  As a member of a developed country I would have expected survey respondents to be more eco aware and by now understand that the economy cannot stand alone from ecological stewardship.  Two prime exampoles of this is the Exon Valdez oil spil and the Eco-terrorism of Mr. Hussian alighting the Kuwait oil fields.  I would have expected developed countries with nightly CNN news to be more intellectualy mature with respect to cause and effect of short term environmental concerns, rather then underdeveloped countries.  I agree with Greg that undeveloped countries are just trying to survive and more interested in hard cash and a ready source of protein in a low technology environment.  I wonder if there might be another reason.
Last year I visted Bolivia and was surprised to see so many cell phones with the general public, espically college and high school kids ( American Arrogance?).  This despite the fact that most of the country still do not have land lines.  The learning curve, though sharp has none the less been fast.  I wonder similarly if developed countries have benefitted from the so call developed worlds mistakes or if it is just a resource dependent mentality ( Remember the 2000 computer scare, not a problem if you only had computers post 1995).
With any survey I like to dissect the statstics, including the population surveyed, the mood, including the motivation to respond and as Greg implies if semantics have played a role.  I rather approve of Rehebikas modern usage of marketing CZM as the future of economic developement. The developed nations use of quick fixes have been well documented,  the undeveloped countries might now benefit, from incorporating environmental resources on a National level, as Beliz, or incorporating NGO's and international parterships to utilze their experience and cost sharing.  Perhaps the reason the underdeveloped countries listed the environment contrary to economics is that "they" have a different view on what is a successful program.  Are the end goals different from a capitalist paridigm.  Is   a countries goal to be monatary rewrding before a project is sanctioned or do some societies place a long term multi-generational view to success, "sacrifice today for tomorrows child" ( China model),.
  It may well be that underdeveloped countries, with limited manpower expertise and minimal infrastructure need an intra-governmental approach. In an intragrated CZM model it is ideal in terms of time and rewards i.e. In 1998 nine countries of the winward islands formed the RSS, originally designed as a Regional Support Service for Security, drug running and natural disaster relief, it has now included  domestic social reforms, tourism, protection  of tradional fishing and cultural similiarities. ( headquarted in Barbados)  These islands learded they importance of interdependency when St. Lucias volcano erupted and threatened  coastal populations.  Individually they didnot have enough sealift to evacuate.  Together they did.  As good a model, not to mention incentive, to build a positive intergrated CZM policy, espicialy inview of the Marshall Island scereno.      
=========yorg=========
===from:Achim Kretschmer
===date:Sun Feb 10 16:21:59 2002
===subject:ICM Forever
===message:At first, the thought of developing nations naming environmental issues as their main reason to initiate ICM seemed counter-intuitive indeed.  Why would respondents to the Cicin-Sain and Knecht survey from developing nations be more concerned about environmental issues than economic ones? And why do developed nations find it important to initiate ICM for economic reasons rather than environmental ones? There are several plausible answers.

One very likely reason is that developing nations have learned from the mistakes of industrialized countries. As the cost of preserving and replenishing wetlands and coastal areas in developed nations is skyrocketing, developing nations start realizing what a sensibly managed coastal area is worth. An eradicated mangrove swamp can make way for high-priced development of sea-side mansions (one time benefit), or a pristine mangrove swamp can provide continuos supply of fish for low impact, but high income, recreational fishing from tourists. 

Another reason may be the existing laws governing the coastal areas. Some developed nations now have very stringent environmental laws, so ICM needs to be initiated to sensibly develop coastal real estate. In comparison, environmental laws lack in some developing nations, therefore ICM needs to be initiated to reign in well-connected industrialists and help strike a balance between development and preservation. 

The implications for ICZM are immense.  The mere fact that both developing and developed nations need ICM is very encouraging. This means that ICM is gaining in importance as a tool to govern coastal policy both ways, preserving and developing. It is a tool that can be used by every nation with a coastal area, be it pristine or industrialized. 

=========yorg=========
===from:Ian Gibson
===date:Mon Feb 11 23:05:06 2002
===subject:Ingrained Ethics
===message:The results of the survey would at first look to an anomoly, but with a little thought the underlying reason can easily be found. The primary difference b/t a developing country and a developed country is the length of time that the nation has been at or near the leading edge of global technology.  The US has been a modernized country for the better part of two centuries, while the populations of certain Pacific islands are still relatively primative.  This leads to two distinct environmental ethics, which in tern have a strong bearing on the path of a given nation's ICZM.  There is the " i live in a technologically advanced developed country where i am accustomed to a modern life style.  While i may care for the CZ, it has always been an econonic entity and has to managed as such, or it will be misused." This generally indicates the idea that the CZ in developed countries will always be managed with economics in mind.
 Then there is the" i am a Pacific tribesman who for the who has lived in a culture that has just entered the modern age.  I have been raised with a environmental consiousness because of my aboriginal culture."  This last ethic does not automatically indicate that countries just now developing will be eco-tourism hotspots.  With the spread of modern medicine, birth rates and populations are rapidly rising.  This has lead economically struggling countries to move away from an environmental ethic and towards maximum exploitation.  After all, there has to be bread on the table.  However, if feasible alternatives are presented, then a shift towards a environmentally geared ICZM policy could happen, since that is a more familiar ethic than the (mostly) Western capture, conquer, and colonize.
=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution:NSUOC
===date:Tue Feb 12 16:58:09 2002
===subject:What we had hoped for
===message:   Maybe we have gotten through. The results of the survey actually make sense, once the initial shock is overcome.  Throughout the past 20 or 30 years, people (mostly scientists and environmentalists) have been preaching about the importance of the environment, the ocean, the rainforests etc...  It only makes sense that awareness has spread throughout the world.  Developing countries realize that the only way to preserve the marine environment is to protect it from the beginning.  These countries have essentially seen the errors of our (1st world/developed countries) ways. This is obvious in the "Scope and focus of ICM Programs" reading from a week or two ago.  the first objective is to "Identify existing and projected uses of coastal areas with a focus upon their interactions and interdependencies."  Developed countries have figured this out a little too late and are now back-pedaling in order to manage what we do have left. The more advanced countries over developed the coastal areas without first considering the repercussions.  Now, such countries see economic reasons for initiating Integrated Coastal Management.  There are so few environmental reasons left. Today, most coastal development in coastal areas is for the wealthy.  It is an economics driven society and the environment, no matter how hard we try, will always play second fiddle.  It is encouraging to see developing countries taking an initiative at early stages to manage the coastal areas.  This should prove beneficial to them in the future, when sustained economic gain will result form careful planning.
    ICZM will become more important throughout the coming years.  New practices and policies can be implemented all over the world in order to preserve coastal marine systems. Sound decision making for ICZM through trial and error from here on out wins out over errors from bad decisions in the past.  This should alleviate the problems for developing countries that developed countries now face.
=========yorg=========
===from:Michelle Cho
===date:Mon Feb  3 15:10:50 2003
===subject:Indirect reasons
===message:At first glance, it seems illogical for a higher percentage of developed countries to cite “economic development” as their reason for initiating ICM than middle developed, or developing countries.  It seems even more surprising that these two latter groups had the highest percentages of citing some environmental issue instead, as their incentive for initiating ICM.  The irony comes from the relatively recent (within the last two decades) realization that coastal and marine resources are experiencing noticeably rapid environmental degradation.  While the initial reasons for utilizing these resources were most likely to induce economic development, the speed and impropriety with which the natural resources were utilized has left them in a high state of degradation.  Therefore, the primary reasons for establishing management of these resources would be for the environmental issues involved.  I think it is understood that economic development would naturally follow from the protection and conservation of coastal and marine resources that ICM would inevitably establish, and so, remains a long-term goal, and indirectly provides the motivation to initiate ICM in middle-developed, and developing countries.  Developed countries, on the other hand, have already realized that they need to initiate ICM for economic development, and that they need to heed environmental factors in order to establish successful ICM.  The implications for ICZM are that these environmental issues require immediate attention, especially in developing and middle-developed countries (not to mention underdeveloped countries), since this indicates to me that the state of degradation of coastal and marine resources is so high that it is visibly noticeable and can no longer be ignored.    
=========yorg=========
===from:Christian Legner
===date:Thu Feb  6  6:59:15 2003
===subject:The American Way ?
===message:<p>I was disappointed to see the results of this survey, but , frankly, not too surprised.  I think that developed countries pretty much always have the economy at heart, if not from greed, from the task of supporting large populations at an expected lifestyle level.  While I think many citizens of developed countries do see the need for coastal management plans, I also think that improved land equals improved monetary uses, which is not an unusual way to think, I guess.  Sometimes, too, for developers CZM can be a means to an end.  Following the laws quickly may appease opponents to said development and allow the project to get under way.  </p>
<p> As for still developing countries, I think of examples from our book.  In some areas, huge environmental problems have emerged in recent years.  While turning around these mistakes may have a beneficial economic impact, it seems that fixing the problem is foremost in the minds of the public.  I don't really know how to explain this - maybe because many of the inhabitants still work the land as farmers, shepards, etc. there is a tie to the earth?  Whatever the reason, perhaps these countries feel that bettering thier land is most important, and resulting economic gains are just a happy side effect. </p>
<p>  Implications for ICZM:  I think that this indicates that plans must be somewhat tailored for particular regions of the world. Sometimes providing the right explanation or incentive could make all the difference in how successfully plans are implemented.  I also think that ICZM could maybe take advantage of developed countries citing that economic reasons are important by making sure developers shoulder most or all costs required to manage land that they want to build on or use. ( as noted in the Rio Declaration).</p>
=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===institution:NSU
===date:Thu Feb  6 12:13:32 2003
===subject:Capitalism
===message:Looking at the two reasons for ICM, I see capitalism as a major player.  In developed countries where the majority of society revolves around economics, it seems only natural (sadly so) for government and the greater part of society to see the coasts in a financial manner. Our government is set up to aide the majority and environmental protection means, job "loss", non-utilized resources, and untapped opportunities in the 'Land of Opportunity'.
Opposite, in underdeveloped countries, capitalism has possibly not taken hold completely.  Person’s lives aren’t paved for societal gain, but possibly in a simpler way. Subsistence farming and living would mean that protection of a resource would be prioritized.  Healthy coasts and waters means survival, food and prosperity for people in underdeveloped countries.  In developed countries, the majority of the population has these needs met with or without healthy coasts. International trade, education, and a stable economy make healthy coasts less of a 'necessity'.  

=========yorg=========
===from:Heather Sariego
===date:Thu Feb  6 19:34:23 2003
===subject:How much does it really matter-the reason?
===message:How much does it really matter-the reason?  All I mean is if countries are involved in ICZM does it really matter why. For coastal zone managers and students who are trying to understand the different reasons behind actions it does.  As an end result, does it really matter the reason behind the action.  In Monteverde, Costa Rica, ticos are fighting to protect their environment because they know they can charge people to come onto their land and explore the beauty that it holds.  They recycle because it costs too much money to pay for their trash to be picked up.  Although their reasons may not be as noble as we would like, they are getting the job done.  I actually think we should create more economic benefit for protecting the environment as this is one of the only ways to "really" get the job done. We can work our whole lives to try and change the way people "care" about the environment..and I think we should..but we need to realize some people will not change.Money does affect people's behavior and we should use that as a tool to accomplish environmental protection that may not otherwise happen.  
=========yorg=========
===from:Laura Kukich
===date:Thu Feb  6 20:34:55 2003
===subject:It all comes back around eventually
===message:I was a little startled at the responses from both developed and developing countries but, after some thought it makes a lot of sense. The initiation of CZM in developing countries is probably a new addition to countless others. There will be many questions asked pertaining to each new development in the country, as to what affects it has on the people and the environment because they see the affects first hand and they have learned from the mistakes of others. Therefore the concern of the people is not the economic standpoint because, they are moving towards better economic standing. Rather their concerns lie in what practices will be put in place for the environment they have now and what the consequences of their actions may be. Initiating CZM is the best way to protect their resources and develop into an economically well-developed country.


In developed countries, economic advantage doesn’t generally mean that the environment is also benefiting from an economic increase. In order to protect it’s coastline while at the same time increasing the advantages for it’s country, the implementation of CZM is the best way to decide what types of compromises need to be addressed environmentally. If CZM is not implemented during this time of economic gain, then in the future the repercussions of what they have already destroyed environmentally will take their toll economically. In order to keep up with the level of production, as well as the supply and demand, the addition of CZM at that time will seriously affect the wallets of those who used to produce inexpensively and sell for a profit at the expense of the environment.          

=========yorg=========
===from:Amy Diamond
===date:Fri Feb  7 20:35:24 2003
===subject:the more we have, the more we want
===message:I was not very surprised by the results of this survey; in fact, when given some thought, it seems pretty logical to me that developing countries would emphasize environmental issues over economic as the reason for ICM initiation.  I think, generally speaking, that most developing countries still hold very strong and direct ties to their land, whether it be for cultural or religious reasons, or simply for survival. In a lot of developing countries, the environment represents their main industry, such as agriculture or fishing, and hence, their source of survival as individuals and as a country. This could of course be viewed as an economically-driven reason, but I see it as more of an indirect result rather than it being a first priority. I think many of these countries are starting to recognize the extent of environmental degradation that has been occuring over the past two decades, and that this could be a serious problem for their survival as individuals and as a country/nation.  The initiation of ICM here would be at first, to ensure that "ends be met"; that families were provided for; that there was "enough" to go around. I am sure these countries are also concerned with the indirect economic benefits ICM could reap for their countries, yet I do not think their main concern is to attempt to capitalize on those benefits. 
On the other hand, the goals for ICM in developed countries are more economically-driven; the motivation to make a profit, to capitalize on what has already been established, and to accomodate for the high standards of living that have already been set. I think, here, such countries have recognized the fact that in order to accomplish such economic goals and to keep achieving "more" and "better", they must implement some sound management practices so that they can continue to do what they want with the land and seas. 
I think the implications for ICZM here are that the motivations for ICM will obviously vary between countries, user groups, and individuals. Those encouraging and implementing the initiation of ICM will need to find a way to treat issues on a case-by-case basis (to consider all of the people, places, economics, etc, involved), while also creating some level of cohesiveness for ICM guidelines among all user groups, countries, levels of government, etc. This is a tough goal to accomplish!
=========yorg=========
===from:Arlo Hanlin Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSUCO
===date:Tue Feb 18 12:30:26 2003
===subject:Survey says...
===message:I have to say that I am not really surprised by this survey, but that I am highly skeptical of what it REALLY means.  I imagine that the answers given by the people who took this survey are highly influenced by both the surveyors and the recent socioeconomic/political environment in which they live.  When it comes to coastal issues here in the US, people are used to thinking in terms of beach condos versus hurricanes, etc.  In developing countries, locals are now used to westerners harping on them about the environment.  It seems natural that your average American, otherwise unversed on coastal issues, would assume a coastal management program would be about economic issues - let's save the resorts from hurricanes.  This does not mean that the same American would be unconcerned if you explained the environmental implications of coastal development to them, it was just not what was on the forefront of his or her mind.  On the other hand, the person in the developing nation may have never thought of the poorly developed coast as a potential source of economic riches.  Logically, this intellectual "city-slicker" (be he/she western or not), is obviously looking for an environmental answer from me and maybe, if I give out the song and dance that the Peace Corps volunteer taught me, he/she will give me a new machete for my time in answering these questions that I really don't understand in the first place.  Granted, this is a little extreme and there are many in the developed world who DO understand the issues, but just because environmental issues came to the forefront in the survey, this does not mean that the local people would prefer environmental protection over economic gain if offered the choice between the two.  In fact, it would probably be quite the opposite.   Surprise, surprise, the mean, cold-hearted capitalist Americans boast the best damn national park system in the world.  As another student recently pointed out for Belize, many developing nations do not even put more than one or two park employees for what on paper represent enormous national nature reserves.  Basically, this survey means very little to me.  Put your money where you mouth is/Actions speak louder than words.  I want to see results, not rhetoric.
=========yorg=========
===from:Jillian McCarty
===date:Tue Feb 25 10:22:47 2003
===subject:discussion 3
===message:People in developed nations, for the most part feel that they already have everything they need (ie, food, shelter...). So, residents of developed countries focus on how to make their lives better. As a result the driving force for these nations has become economic development. In developing nations, people do not necessarily have all of there basic needs met on a regular basis. Therefore they see the world differently. This means their driving force is more focused on essential survival issues. This, of course , involves the environment. In the eyes of those residing in developing areas, the environment affects their basic survival in many ways and it must be protected.
People in our develpoed countries, need to realize that there is more to the world than money. For ICM to be effective we also need to realize how important the environment is to our survival as a species.
=========yorg=========
