===from:Kristi Foster
===date:Fri Mar  1  8:14:24 2002
===subject:Not All That Hard to Survive
===message:After reading the Nuku Hiva case study, I felt the urge to laugh a bit at the absurdity of all the stage preparations required to restore Daniel's Bay to an "uninhabited state".  I've never seen an episode of the show, yet it's been nearly impossible to escape the contant commercial previews and the talk around the water cooler after each episode.  I'm glad to have something to contribute this season as I share the true "behind the scenes" story of spraying insecticide along the beach and the primitive living conditions in the Pearl Lodge Hotel and aboard the Spirit of Oceanus cruise ship.
<p>
The two reports of the show's preparations shared much of the same basic information.  The Sail magazine story focused on the alteration of the natural setting, while the Cruising World report introduced the opinions of the locals to the event.  It seems that the visitors/cruisers to Daniel's Bay are more upset than the locals.  Initially, after reading the Sail magazine story, I shared the sadness of the cruisers.  However, after continuing on to the next article, I felt that maybe I was diplaying a bit of arrogance.  It is very easy to speak out against the alteration of the Daniel Bay ecosystem and subculture when I have all of the luxuries of the modern world.  But upon reading that the locals were enthusiastic about the computer donations and other economic benefits, it is not fair to expect their community to stay behind the times.  The statement that Daniel and Antoinette prefer their new home supports the local government's "sell out" of the bay for the TV show.  I think that local inhabitants have to be able to determine the extent to which their culture and their surroundings are going to be developed.  Hopefully this is done with some sense of environmental responsibility.
<p>
Of course, the world has so few pristine areas left, it seems a tragedy to lose any more.  I was happy to read that CBS will return the area to its original condition.  While Daniel may no longer be there, it is still possible that the ecosystem will not suffer long-term as a result of this temporary modification.  If CBS actually goes through with its promise, this may end up as a win-win for the people of Nuku Hiva.
=========yorg=========
===from:Rebekah Walker
===date:Fri Mar  1 18:57:09 2002
===subject:Locals should rule their land
===message:While both articles summarized the development of the set similarly, I was amazed by how differently the reaction of the locals was conveyed.  My first reaction was outrage at CBS having leveled the area without permission.  Afterwards though I began thinking of the good of having income, computers, and more homes for the islanders.  The problem is, when reading articles you must assume those reporting and those they interviewed are telling the whole truth, which seldom is the case.  While the Sail article said David and his wife did not agree to the leveling of their house, the Cruising World article said they did.  And while the Sail article cited locals as being overwhelmed and unwelcoming of the process, the Cruising World article said the locals were “totally behind the show”.  Which is the full truth?  Neither.  Which is partially true?  Both.<p>
I feel that while both points of view are valid, the local’s view is more important to consider.  While it is true that cruisers loved the pristine environment and the undeveloped feel of the island they were welcomed to, the locals have a right to live in new houses, use the internet, and make a living.  If CBS actually follows through on their agreement the island will greatly benefit by the “restored” island and more technology.  I think it is important to consider what the locals want and whether their plans are going to do more harm in the long run, or if they will be sustainable.  I actually think it would be a perfect time to introduce a coastal zone plan to the country because the start of an economy is a very vulnerable time for the environment.<p>
It is true that while some things will be changed back to their original conditions, others never will.  But, this is not entirely a bad thing.  It must be remembered that a healthy environment is only one part of the goal of ICZM.  Health economies and a good standard of living for the people is also a top priority.  While the beginning of this story is shocking and did not look to be good for the people or the environment, the outcome may be positive.  Unfortunately we will just have to wait and see. 

=========yorg=========
===from:Kelly Adams
===date:Sat Mar  2  7:21:07 2002
===subject:Are economic advances always a positive thing?
===message:      My initial response to these articles was one of shock.  You see and hear people talking about these type of TV shows, but you never think of what really goes into making them and certainly don't think about them causing  people's homes to be destroyed.  It gives me one more reason not to like these new 'reality TV' shows. 
     The first article published in Sail magazine gave the reader the impression that there was nothing good to come from the TV show being filmed on the island; however, in the second article published in Cruising World, the reader learns that at least the people of Nuku Hiva will benefit economically from the result of the TV show being filmed there. The homes that the crew for the TV show built for themselves while on the island will be donated to low-income familes when they leave and computers  will also be donated to island schools. These are a few advantages to having the TV show filmed on the island, but these might not be considered advantages in the eyes of everyone.
    The inhabitants of Nuku Hiva have lived a simple lifestyle for many years and most were probably very content with that.  People generally consider  technological and economic advances as positive things, but believe it or not, this isn't always the case. Take the Hawaiians for example, they were very content with their lifestyle, but then Americans came in and started changing things and the Hawaiians lost their land, culture, and freedoms. 
   Who is to say what is right? Obviously, lives were disrupted by the TV show.  As we learned from the writers, there are always two sides to a story. In this case, those that jusitfy their destructive actions by only speaking of the positive things that will come from it and those that only see the negative side of the situation. In the end, the fact remains that some individuals will benefit and some won't.
=========yorg=========
===from:Amanda Burgos
===date:Sat Mar  2 22:55:48 2002
===subject:Somewhere in the middle
===message:It's funny how some sayings just seem to pop up in your head. In this case it was "there are always two sides to a story" and the truth is somewhere in the middle. I kinda felt like that after reading both the "Sail" and "Cruising World" articles. 
Both articles decribe what happened to Daniel's Bay prior and during the filming of the "Survivor" show. The Sail article was a bit more personal..told as a story, a narrative of his visit and shock at what he saw. The writer had been to the island and specifically Daniel's Bay numerous times over the years. He had developed fond memories of the site and rightfully so. As a result, it was expected that he would be upset at the changes made since he loved it "as it was", pre-cbs.
The author from "Cruising World", on the other hand, attempted to be objective. She gave no indication of being to the island before and thus had no history with the island or islanders. Because of this she went to a "reliable" source of information..the tourism director, Al Keahi. (Now from his point of view..what better promotion for his island than weeks of free advertising via the show and articles such as these...they could never afford an advertising campaign with such worldwide exposure, and the possible economic gains are staggering..and no one is opposed to making money nor making their living conditions a little better).
The Cruising writer makes sure to mention all of the good that came from the project..computers, homes for low income families, etc. BUT somehow I felt her report was lacking maybe because she never spoke to Daniel or any of the other locals. Yes, Daniel "willingly moved"/ "gave permission to remove the strutures" but, he never owned the land to begin with..thus could government have been the one applying the "strong pressure" mentioned in the "Sail" article. 
So which of the two was closer to the truth? Well, I would say the truth lies somewhere in the middle. The life of the locals probably were disrupted as mentioned in the "Sail" article BUT they did reap and thus approve of the benefits gained from the project. I think the reality was that it was upsetting to find out that no one and nowhere can escape the reach of the U.S.  And isn't that what it is all about. How disturbing it is that Americans for sake of entertainment can come in and take over for a few months..completely change the lives of everyone around and then just pack up and leave. Good or bad, the show changed their lives forever.

=========yorg=========
===from:Greg Foster
===email:fjohn@nova.edu
===date:Sun Mar  3 10:41:03 2002
===subject:Story vs History
===message:As this case study suggests, the pervasive influence of human bias and editorializing can create an infinite number of accounts.  History approaches truth only when the historian goes to great lengths to examine all aspects leading to a final outcome.  But such thorough reporting is generally unsuitable for special-interest magazines such as Sail and Cruising World.  Working within the confines of short attention spans and marketing pressures, the magazine writer is often limited to a cursory overview and compelled to represent events in a manner appealing to the readers.
<p>
After considering the content of both articles and reading between the lines, it appeared to me that much was open to interpretation.  For example, it seems that Daniel and Antoinette were ambivalent about the relocation, and that their feelings evolved during the process.  The other locals viewed the production activities from a number of different perspectives, based on their individual benefit/loss ratios and personal feelings regarding the matter.  These are ripe reporting grounds indeed. 
<p>
The article appearing in Sail magazine laments the undoing of Daniel and Antoinette's charming presence in the bay.  Feeling justified by such an insensitive action, the author takes a cynical stance towards the entire process, consistently disparaging the practices of the production crew.  Accordingly, the author focuses only on Daniel and Antoinette's negative feelings towards the events.  Likewise, the injustices to other locals are highlighted, while the possibility of benefits is not mentioned.  The article is obviously a human-interest spin, as no other explanation exists for the mention of Daniel's single tooth. 
<p>
The article appearing in Cruising World magazine is considerably more objective in comparison.  As opposed to the Sail article, this author generally refrains from making judgments.  Instead, she presents a select few pro/con considerations and allows the reader to pass final judgment. 
<p>
If forced to rank the veracity of the two reports, I believe the Cruising World article is clearly the better of the two.  In general, emotional and one-sided reports such as the Sail article are rarely representative accounts.  However, neither comes close to providing enough information to make an informed decision regarding the effects of the Survivor shooting.  If this were to go to the courts the trial would probably last for a week, during which time numerous parties would testify on their behalf and opposing lawyers would present reams of information.  To make a judgment based on a magazine article is nothing short of folly.

=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution:NSUOC
===date:Mon Mar  4 15:21:02 2002
===subject:Reality Bites
===message:   It is strangely ironic that it takes the production of a  "Reality-based" television show to portray opposing perspectives.  In this case, the two opposing "realities" are completely different from one another.  On one side, there are the rich world hoppers with enough money and time to cruise around the world, visiting locales not yet affected by western culture.  These "cruisers" see these locations as idyllic paradises, places that time forgot.  Even as such, they are also an escape form the westernization of the world.  On the other side are the native peoples of these far off places.  These people have lived here for ages.  It was/is only a matter of time before technology and western culture would reach these places.  It is quite possible, almost undoubtedley so, that such people crave the things of western culture.  Computers, cell phones and in some places television.  In Nuku Hiva, the influence of western culture happened to be brought by a television show.
   The first article portrays how Survivor ruined an island paradise.  The article shows Nuku Hiva as some idyllic island paradise where natives and visitors happily stay in undeveloped bliss.  The show turned a familiy's livlihood into a television set.  The show erased decades of Daniel's life within days.  The entire island, it's laid-back lifestyle and friendly culture was invaded by American culture.  The laid-back lifestyle and culture, however, are viewed as such only by the author, or who ever is lucky enough to "sail" to places such as Nuku Hiva.  It probably isn't viewed the same by the islanders.
   The second article takes a view more along that of the locals.  To them, the show has brought money and tourism, as well as items difficult to obtain beforehand.  The natives want to earn money, want the internet, and essentially, want to become more developed.  The Survivor show has brought this all to them only at the expense of some old guy's beach.  It seems well worth it to them.
   Although i love the outdoors, and would enjoy cruising to these undisturbed island paradises, I would have to side with the view of the locals.  If i lived by little means on some pacific island, i wouldn't mind the opportunity to make some money, surf the web, and maybe see my island develop.  If that occurred at the expense a deserted beach and some rich tourist with his mega yacht, then so be it.  This may not seem like the proper point of view for ICZM issues, but then again, most of us can't even fathom the situation to begin with.
=========yorg=========
===from:Ian Gibson
===date:Mon Mar  4 19:18:40 2002
===subject:Ya Can't Have Your Cake and Eat It Too!
===message:This whole case study simply left me shaking my head and reassuring myself that this was simply part of the game.  I feel that both of the articles suffered from an obvious bias, though the Sail magazine piece definetly had more of a whiney feel to it.  I can almost see the author now....miffed that he can't kick back with a pina colada and watch the little people run around in grass skirts.  Well, that might be a little heavy handed, but i think you catch my drift.  Sailors love to find those places that remind them why the sail in the first place - the idyllic bay, friendly natives, a laid back yet servicable atmosphere.  Unfortunately, what these boatsmen seem to forget is that simply there presence is enough to force a change.  The islanders aren't totally ignorant - they know what they are looking at.  Thirty years ago natives may have not deemed the modern world worthy of there attention or desires, but i think the word on such advances as modern medicine and such got out.  It is utterly selfish of world sailors to think that the island should remain static simply for their own piece of mind.  
I AM NOT condoning or supporting the Survivor invasion.  Hollywood has long been unconcerned with the impact it makes on location.  "Reverting the beach back to nature"??
It sound as if daniel had practically made himself part of the ecosystem.  The second article sounded like a Nuku Hiva chamber of commerce release (and it actually is, as the source of most of the quotes is the director of the Tourism Board).  It is obviously biased in support of the Survivors show, and on the larger scale the influx of modern ideas and money.  That, however, is irrelevant.   Daniel is one man, and the sailors are a special interest group.  Given the typical reactions of small islands when introduced en masse to Western influence, i am apt to believe that the locals welcomed the show.  There maybe a minority of folks that see the show as a attack that will kill the original state of the island.  However, perhaps this minority was simply responsible for retarding the evolution of the island's culture and this "attack" was inevitable.  Don't get me wrong, i wish that all island cultures could slowly move into contact with the modern world and only assimilate those qualities that are benign.  That, obviously will never happen.
=========yorg=========
===from:john osullivan
===email:johnosul@ aol.com
===date:Tue Mar  5 10:14:12 2002
===subject:Sail vrs Motor
===message:After reviewing my fellow classmates responses I agree with the more personal viewpoint from Sail magazine to be the better rounded article.  I found it interesting that the articles were even approved by their respective editors.  While both magazines are in the leisure catagory I found it interesting that the editors would take such a different approach obviously based on their readership biasis sail vrs motor, slow vrs fast.  
The Sail magazine has a more laid back, personal and cynical "feel".  The author had been to the area before and had a personal expeience from which to make comparisons and he noted perhaps subconsciously that the bay will not be the same after the destruction of a -generation- of white No-nos, the building of a cement pier and its subsequent ripping out as well as over 100 round trip motorized tender boats burning 4 tons of fuel a day.  I sense that the amatuer environmentalist recognizes the potential for coastal destruction goes far beyond the here and now.  
The Cruising article author seems to take pains to note the fast and immediate financia1 and commercial rewards to the island residents as a whole.  The new pre-fab housing the new computers, "the investment in their childrens future".  All admirable and the immediate impact easily measured in dollars to the local community and in modernization.
She noted the pristine bay before the Hollywood invasion but ended on a "positive" note that while there were immediate results, "a collective groan across the Pacific Net"  acknowledged that not all the benefits are good and that despite CBS intentions not everything will be the same.  
Both articles ended in a cynical, "in reality, nothing will" be the same, tone: not for the islanders, not for Dainiel, not for the No-nos or the bay itself.  Interesting that despite both magazines based on utilizing the worlds oceans neither editor wondered about the destruction and long term concerns below the waves.  Maybe we should ask the editors of SCUBA or Skindiving Magazines for a follow-up    
=========yorg=========
===from:Matt B
===date:Tue Mar  5 20:17:31 2002
===subject:Crappy TV show
===message:Personally survivor is a waste of broadcasting time and no one on the show has to survive anything but each other. On the other hand the show does very well with American viewers and has very high ratings, which is one reason the show can go where it wants to, even Daniels Bay. The case study provides insight into a old native man's world and how it was taken from him. Although now he is in a better house, with better furnishings, so I doubt if he sold himself too short on the deal. Speaking honestly I cant get a sense of what the area may have looked like before CBS came in and what it looks like now. I can imagine a tropical scene with a run down house on a bay and a pier. I do feel sorry for Daniel but it wasn't his island to begin with and I am sure he has done his fair share of harm to the island along the way. I get a sense that the Sailors world article wanted to paint a sad picture of what happened to this poor guy and his Bay, but to me it doesnt seem like he is going to be suffering that much at all. "Survivor" probably made that guy much more than he ever would have been if the show never would have come there. I mean here are two articles written about him and I am sure there are more out there waiting to be read. I never would have heard about him without this class. The article that makes the most sense to me is the Cruisers World one. It gives positive light on a touchy subject. Yes his house was destroyed but now he is living in style and the island is going to be getting computers and revenue that it never would have seen without CBS. So although it is tragic that his little house on the bay was destroyed I want to hear what he has to say about his new situation now and whether or not he is really sad or misses his old house.
=========yorg=========
===from:Achim Kretschmer
===date:Thu Mar  7 13:29:44 2002
===subject:What is pristine?
===message:<P>The moment David build his house and outhouse on the beach 30 years ago, it ended being pristine. His little farm most likely meant that lots of trees had to be cut down, hardly low impact in a fragile environment. Welcoming sailors after a long voyage also means accepting their trash that accumulates onboard. The Sail article paints an emotional picture of a corporate invasion destroying a way of life, but it seems that it was the sailor’s romanticized image that was destroyed. No wonder the Sail article stood in contrast to the “natives’” version of events. According to them, they make money for the first time, get housing and computers and recognition in turn for a few disruptive weeks. No harm done, right? </P>
<P>One would like to think that life on Marquesas returned to normal after the crews left, but history has proven otherwise. There are most likely several “investors” working on drawing up plans to develop parts of Marquesas, now that an entire nation is seeing untouched dream beaches, no crowds, and no high rise hotels (yet). How long will it take before tourists request that big cruise liners make Marquesas a featured port of call? </P> 
<P>But to answer the question and not get entirely off the subject, I would agree with the Cruising World article since it describes the way the locals feel. But I find it interesting how the Cruising article says the bay was “restored to its uninhabited state” while more people lived there for the show than ever before. Going forward, one can only hope that the government of French Polynesia enacts a sound ICZM policy to manage the sure to come onslaught of tourists, adventurers, and the worst of them all: deep pocketed developers. </P>

=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===institution:NSU
===date:Tue Mar  4  7:18:08 2003
===subject:We come in peace
===message:Just when you thought the taking over of land and resources by white men was part of history books, it starts happening again.  As always the promise of wealth and luxuries, persuaded a local population and government to relinquish their lifestyle.  The first article from Sail, typifies the immediete feeling a traveler feels when revisiting a favorite natural spot.  Eco-travelers never want these places to change, so they have a place to visit, escaping their busy lives.  But change is usually much slower, Daniel and his family never knew what was coming.  The irony of how Sept. 11 effected everyone is also pointed out.  The ulitimate defiance of capitalism, brought capitalism right to this island.  
Cruising World, focused on the backing of the project by most of the local population.  The money brought in from the invasion, likely fed and clothed many, but the article lacked insight as to what happens when the invaders pack up and go.  The article ignorantly states that the island was, "restored to an uninhabited state", but the bay practically was before they came.  
I feel both articles misrepresent the truth because they are both written from their own agenda. The Sail article, points out mainly Daniel's side, leaving out the thoughts of many locals who have come to depend upon tourism.  The Cruising article makes it sound as if everthing turned out fine in the end, so it was worthwhile to wipe out the natural character of the bay.
=========yorg=========
===from:Michelle
===date:Tue Mar  4 18:11:28 2003
===subject:Lots to say.....
===message:<p>I found that the Nuku Hiva case study brings up an important issue that we have previously not addressed.  I was in Thailand when they were getting ready to film “The Beach” (Leonardo DiCaprio movie), and a public outcry ensued. Koh Phi Phi is on the west coast of Thailand, and is part of a protected nature preserve. I remember thinking how ridiculous some of the preparations for the film sounded, for example, they were digging up indigenous species of flora, and replacing them with coconut trees, to make it look more like a “Hollywood paradise”. This was in a protected nature preserve.  There were also many rumors that they were bulldozing dunes.  I heard that the Thai government was getting lots of money from the Hollywood filmmakers to comply with their wishes. All of the information I heard was from the international community.  They were largely leading the protests against the changes to the area the film was causing.</p>
                                                           <p>A few years later, my sister was working for an adventure magazine, and they went to a remote place in Mexico to do a photo shoot for a surfwear issue. There were a few Americans there, and some Aussies as well, all of who pleaded with the magazine crew to keep the location a secret. To them, it was an unknown surf spot, one where they didn’t have to fight with other surfers for waves, or watch for people stealing their keys/money while they slept on the beach.  The locals, however, were so excited for the exposure. They were constantly asking the editors to print the name of the location, how to get there, and to encourage people to go there. They wanted tourism, and everything they believed it brought—clothes, money, gear. In the end, the editor published the name of the town, with directions on how to get there, despite promising the foreign surfers, who had agreed to pose for the shoot in exchange for keeping their spot a secret. She reasoned that it was good for the locals, who needed the business.</p> 
                                                         <p>The two Nuku Hiva stories provide two different perspectives on the same story.  The first provides the perspective of the “cruisers”, those that visit the islands by boat, and expect to find tranquility, and the welcoming charm to which they are accustomed.  The second provides the perspective of the locals, those who see these boats, and the sailors with their computers, and other technological gadgets.  The “cruisers” want this place to stay as it is, set in an earlier time, when things were slower, and priorities were different.  The locals are anxious to join their neighbors in their progress, both technologically and developmentally.  I agree with the “cruisers” in the Nuku Hiva story and the surfers in the Mexico story, over the locals.  The reason is because I feel like the “cruisers” and surfers have more experience and knowledge of the likely outcome. There are so many irreversible changes that can happen, including loss of tradition, and culture, most of which the locals are not, and cannot be aware. The added stress to the environment can easily destroy the physical beauty of a place, which is one of the first things that draws tourism in the first place.  One local states, "Coming to the Marquesas is a once-in-a-lifetime thing for many sailors, but they want the islands to stay the same, which is selfish.” I agree with this statement, however, this case in particular is more complicated.  The locals found that they made money in the restaurant and hotel businesses. To them, these Hollywood affiliates are their idea of tourists.  Restaurants and hotels call for more stress on natural resources, and in their minds, this is what brings the extra money, to “invest in their children’s future”. The reality is that there still exists a compromise. Many tourists are like the cruisers, and are supporters of low impact eco-tourism.  This can also create work and added wealth for the locals that are involved, while ensuring that their children will have a future where they grew up—it can be considered an added investment in their children’s children’s futures.</p>                              
<p> The reason I agree so strongly with the “cruisers” and even with the international community in Thailand, even though I admit that all of my information is one-sided, is because Hollywood’s “Survivor” and “The Beach” are purely about entertainment value. Even though executives and producers so often point out all of the positive effects their production had on a place, like cleaning garbage, or “mitigating” to make-up for all of the damage they caused, in reality, these places need long-term monitoring to endure the suddenness with which such large-scale changes are made on the environment, as well as on the local mentality. </p>

=========yorg=========
===from:Christian Legner
===date:Thu Mar  6 12:07:07 2003
===subject:Survivor
===message:<p>I felt like these two articles both held half-truths.  The obvious differences were the descriptions of destruction of a place and culture vs. an economic boom for a poor country.  Before I discuss the two articles, though, I have to say that I was amazed at the irony of the destruction/use of a previously inhabited beach as a set for a "wilderness" survival show.  </p>
<p>The <u>Sail</u> magazine article did its best to describe the sad loss of a culturally important location.  I also think that it was accurate in describing an unwillingness by Daniel and his wife to leave their home of 30+ years.  However, the things that the article describes as being destroyed were not natural to begin with - they were the products of human habitiation.  These included the fresh water pipeline, the planted fruit trees, the house and jetty, and the docking and landfall of many cruisers and their sailors.  </p>
<p>The <u>Cruising World</u> article, I think, also told truths about the feelings of the island people when this opportunity offered an economic stimulus.  Perhaps if the beach in question had been pristine to begin with, the islanders would have protested the onslaught of people, but the beach had already been in use by locals nad tourists for many years.  While Daniel and his wife would have been understandably upset about leaving their family home, that doesn't mean that the rest of the island should have opposed the idea. </p>
<p>So, my point is this - both articles were about half-way valid, one describing the loss of a cultural icon, one describing the ability of the islanders to deal with this when presented with an opportunity to prepare for the future.  Unfortunately, I feel that this influx of money and people will be setting Nuku Hiva up for the coastal zone problems that many quickly developing island nations face.  Without proper planning, development here may quickly exceed the ecosystem's ability to deal with man-made changes.  The beauty of the area brought the television viewers, but Nuku Hiva must remember that conservation and preservation of the island is what will truly provide for future generations.</p>
=========yorg=========
===from:Amy Diamond
===date:Fri Mar  7 12:18:04 2003
===subject:where to begin!?!!? 
===message:     I knew I had legitimate reasons for protesting Survivor ever since its first season! While I must admit it is easy these days to get sucked into the mindless and “entertaining” dribble of reality television, for many reasons, the idea behind Survivor has always rubbed me the wrong way.  The story behind Nuku Hiva is simply case in point of my opinion.  The season of Survivor that took place in Australia ran soon after I returned from studying abroad there, traveling around to various remote islands and lush rainforests, visiting with indigenous people and learning about their culture and connections to the land.  Similarly, as Michelle had mentioned in her message, I  had also just been in Thailand a few months prior to the filming of The Beach. I heard the same thing about bulldozing the dunes, etc. It is extremely upsetting to return from such beautiful and serene locations to hear that they are being taken over by bulldozers and video cameras.  Not that these places were all completely pristine and untouched before this...although some of them definitely looked that way; the point is that they had certainly never before been invaded to such an extent as they were about to be.  
<br>
     I think both articles are similar in their descriptions of how Daniel’s Bay was taken over by camera and construction crews during the production of Survivor.  It is interesting though, to note the slight differences between the articles’ points of view.  Both evoke a certain sympathy for Daniel and Antoinette because they were displaced from their home, but the Sail article depicts more that Daniel and his wife were not at all in favor of leaving their land; that they basically did not know what hit them when the “quick and rich” Americans swooped in and pressured them into taking the bay for the show.  Interestingly enough, this perspective is coming from the “rich” cruisers, who visit the island expecting to see the peaceful setting of Daniel’s Bay unchanged.  The Cruising World article says that Daniel was asked to leave, that with their permission, the owner of the land removed what they had spent years building, and that even though the government offered to rebuild their house on the beach, they preferred their new home.   This however, was all reported by the CBS publicist, who I have a hard time believing would give an unbiased, fully knowledgeable report of this whole situation! This article also gives more of the perspective of the locals, saying that the people of Nuku Hiva supported the production because of the forthcoming economic gain, an “investment in their children’s future.”
<br>
     I think often the international community (i.e., the cruisers) are more upset by things like this happening than the locals.  While at first this thought seemed a little backwards to me, after some thought, it makes sense.  We, the outsiders, view these remote, peaceful islands as novelties; places to go on vacation when we need to escape the chaos of the “real world.” While there are some of us that are upset that this is happening because we have a general concern for the  environmental and cultural aspects of the situation, I think the majority of people that are upset over this is more for selfish reasons, that their favorite vacation spots are being taken away.  I think the Sail article was a little overdramatic by saying that the cruising boats were “struggling to survive the sudden and total loss of tranquility!”  I don’t think it is the cruisers that are the ones “struggling to survive”, and most of them have probably not stopped to consider, from an economic standpoint, the attraction of this production for the locals.  However, in the same respect, the locals may not be able to see that one event, such as the production of Survivor, could lead to a continual spiral of commercial development and environmental/cultural degradation. They have not yet seen the aftermath, as we have, of this happening on a daily basis, and may not be aware that there may be other ways to achieve economic gain while still making a minimal impact on the land and people, an “ecotourism” approach, which unfortunately is not what is happening when Hollywood rolls the cameras and bulldozers in.
<br>
    I don’t know whether it is necessarily a question of which article is more truthful.  I would tend to agree more with the perspective of the cruisers who are upset that this once serene land was taken over by Hollywood, because I can appreciate and empathize with their distraught after seeing similar things happen to places I had grown to love and respect.  Yet this is a totally one-sided statement because I have never been in the situation where I might see my only chance for economic flourishment is to let something like this happen. I think both articles bring up valid points and represent the ongoing controversy between economic gain and development, and environmental preservation/conservation. 
<br>
     One last note...both articles similarly describe the way Daniel’s Bay  was taken over by people and commotion.  The Cruising World article reported that “[P]roduction crews flattened his house, removed the small jetty, and wiped out all traces of habitation along the shores of Hakatea Bay...three days later, no sign remained of the life [Daniel] took three decades to build”. I find it completely ironic and ridiculous that Hollywood does all this work to find little remote islands they can use for television, and then THAT’s not even good enough, so they have to then go through all of this destruction and reconstruction, in order to transform these places into “uninhabitable” islands for the Survivor contestants.  It just seems to me, that if this is the case, it would make as much sense to just find an “uninhabitable” junkyard somewhere in the States, or just some empty space, get rid of everything there, dump some white sand down, plant some coconut and grapefruit trees there, and have THAT be the next site of Survivor!
=========yorg=========
===from:Laura Kukich
===date:Fri Mar  7 15:14:34 2003
===subject:Reality TV 
===message:<p>Personally, putting 16 people in a deserted area to compete for money makes me laugh. Here come the crazy Americans. Willing to do anything for ratings and even more money. </p>

<p>After I read both articles I could see that there may be truth in both of them. Having your lifestyle changed, food monopolized, and home overrun due to TV crews and bulldozers would be something that not many of us would put up with. But, for money I'm sure everyone wouldn't mind it for a month or two. Daniel and his wife lived in what we would call, relative poverty in this amazing place. So to compensate them they are given a house, and thier home is demolished along with the area by TV crews, boats, and increased pollution. What are we promoting? Go to pristine areas that are few and far between and exploit them as well as pollute them? There is no way that the area will be restored to it's original state, and that may be for the best considering the community but, I think the environment is what is truly robbed.<p/>

<p> In all honesty, the influx of money to the area was probably appreciated by the community as well as tolerated. Having "survivor" there brought more opportunities for the area and in some ways helped them. But, this also created environmental concerns which are probably being dealt with now. The fact that the bay was put under construction for a television show and that the people were willing to allow it to happen shows, that societies, even remote ones, will allow for exploitation of thier environement for a price. <p/>
  
=========yorg=========
===from:jillian mccarty
===institution:nova
===date:Sun Mar  9 10:59:14 2003
===subject:daniel vs survivor
===message:This case study was a very good example of the positive and negative impacts that money can have for small, developing areas. CBS transformed Daniel's Bay into the perfect set for the hit show "Survivor" in a very short time. The article in Sail really focused on the negative impact this had on Nuku Hiva. Whereas the Cruising World article put a positive spin on it, in terms of the local economy. As far as the "truth" is concerned, it probably lies somewhere in the middle. For that reason I don't want to say that one article is more valid than the other. Personally, I would probably agree more with the perspective presented in the Sail article. But, I don't live on Nuku Hiva. Development is a complicated issue and sometimes it is hard to say what is right or wrong for an island like this. That is one of the reasons why ICZM is so difficult to implement. However, I also think ICZM is necessary for us to work through these complicated issues. 
=========yorg=========
===from:Arlo Hanliin Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSUOC
===date:Wed Mar 12  6:17:01 2003
===subject:Nuku Hiva
===message:Overall, I found both versions of this story to be depressing, if only for the loss of the tradition inspired by the life of Daniel.  This really comes across as an ugly and horrific scenario.  The first of the two articles was by far the more negative of the two, and really pointed out the injustices played out by the Survivor team.  The second of the two, while not entirely in support of Survivor, did point out some valid benefits that the Survivor crew's presence would have on this island.  Finally, the question was raised whether these benefits would make truly beneficial changes to the island.  The romantic and the idealist in me wants to say no - things should not change from the "idyllic" setting that we are imagining.  However, the realist in me understands the points made in the second article - why shouldn't the local people be able to obtain computers and sailing ships if they want them?  Why are Americans and Australians the only ones that should have these "priveledges"??  I also know from previous readings that idyllic settings are not always so idyllic.  The Marquesas Islands are truly one of the most visually majestic settings in the South Pacific.  However, the local populations have a long history of quarreling, malnutrition, and epidemics of elephantiasis and other horrible diseases.   Due to their remoteness and their economy, they have not traditionally had access to medical benefits, which could have relieved some of these ailments.  Additionally, the modern polynesians living on these shores took these islands from a previous group.  Archelogical remains on the islands show that these peaceful Polynesians displayed ruthless genocide in order to obtain this new homeland.  On another note, Thor Heyerdahl, the famed voyager of the Kon Tiki, set out to live the "idyllic" life on nearby Fatu Hiva.  His goal was to prove to the world that life without modern conveniences was better and that we could survive in harmony with nature if only we could fully separate ourselves from the evils of modern society.  Thor, along, with his wife, did not make it even a year before they gave up.  So in the end, was Survivor's presence on Nuka Hiva responsible?  No, their actions were for the most part invasive, imperialistic, and insensitive.  On the other hand, are the gifts they left behind a negative thing (prefab houses, computers, dollars spent in local hotels and bars)?  No, I don't think so.  From what I can see, the people on the islands already crave these things and through the process of craving and not obtaining, are made poor.  Although the impacts on the environment (and this is another topic altogether) may be detrimental, they have just as much right to pursue the "American" (or materialistic) dream as anyone else.

Arlo
=========yorg=========
