===from:Rebekah Walker
===date:Fri Mar  8 21:49:24 2002
===subject:Compromise if you want something!
===message:This, like many other coastal issues is of major local importance, however requires worldwide support and assistance to be successful.  While this case is different from the others we have examined in this class in that it concerns a developed country, it is similar in regards to the controversy it has caused and the numerous compromises, which will be necessary to accomplish goals on either side.  This problem is similar to the Marshall Islands issue since sea rise due to global warming will impact the outcome, however it is different because much of the problem Venice is facing was caused by human error.<p>  

A major topic ICZM will have to face is how to handle problems caused solely by the building of structures too near the coast.  Venice is a prime example of this.  It was built on mud flats, an environment never meant for human habitation.  Buildings residing on barrier islands, places never meant to stay stationary, or the problems faced by erosion eating away land in front of wealthy resorts build on sand dunes, since the beaches cannot be replenished by the sand stored in the dunes, are prime examples of this issue.  This is not as much of a lesson for ICZM as a heads up to what is in store. <p> 

Other human error that put Venice in the place it is today is emptying aquifers below certain levels and affecting water flow in the lagoon by deepening channels, putting up walls and filling in parts.  These all show how shortsighted answers to major problems can intensify the dilemma.  The Everglades and the Kissimmee River are other examples of this.  All the effort and money being put into the Everglades is trying to reverse the effects of the canal system built almost a half century ago to fix water problems.  The Kissimmee River was straightened to alleviate flooding, however now a major restoration effort is putting the river back to its original condition after water quality and wildlife dropped dramatically.  These are examples of what can happen if the entire scene is not considered. <p>

That scene in Venice includes both the “Greens” and the supporters of the gates.  I do not question that the gates will help stop the flooding and that they may be the only way to “save” Venice, however will this be another effort that will simply be reversed in upcoming years?  I think a major lesson to take from this is what happens when two sides to an issue do not attempt to compromise.  The first plan suggesting the use of the gates was developed 20 years ago.  In that time, nothing much has been accomplished either for the city or for the lagoon.  Perimeters of islands were raised, however flooding still occurs and, as a result, quite a bit of money is being spent to restore Venice instead of being used to save it.  The gates have not yet affected the lagoon, but that is not likely to be the case for long.  Were other plans researched and considered, or has all the effort been spent on simply fighting the present proposal?  I find this to be a major issue with environmentalism.  We have too many people fighting, and not enough people fixing.  It is necessary to fight, but we need to have solutions to give when the powers that be finally listen to us.  If not the plan we know will not work is going to be implemented for lack of something better.  The theory behind ICZM calls for compromise, but will it be delivered?  I feel it is the only way something useful can truly be accomplished.           

=========yorg=========
===from:Kelly Adams
===date:Sat Mar  9  9:22:57 2002
===subject:Temporary solutions
===message:When I first read this article, it immediately reminded me of New Orleans.  The situation seems to be similar except New Orleans is not flooded with water yet.When New Orleans was first founded, a 3 foot tall, mile long dike was constructed to protect the city. Since then, levees have continually been built higher and higher to protect the growing city from periodic flooding. The Army corps of Engineers designed several plans to control the river, but thus far all of their plans have weaknesses and they find that they can't control the river.  Today, New Orleans is still in trouble of one day being flooded by a powerful storm surge and the city could be under 20 feet of water. In the end all the efforts that have been made to protect the city have actually made the situation worse.
     The article on Venice sounded very similar to the New Orleans situation. The city initially began sinking because of industries pumping water from aquifers under Venice.  They didn't know what their actions would cause. This was the same for the people of New Orleans who didn't know that building up levees and sealing off spillways or flood plain areas would only make the situation worse. Now in attemps to solve the problem in Venice they have raised the perimeter walls 40 inches. This seems to remain a temporary solution to the problem. The flood gates will probably also help the situation for awhile and nobody really knows if the gates will cause the lagoon to become stagnant. 
    As Newton best described it, "for every action there is an equal and opposite reaction."  The people of New Orleans are still dealing with the problem of the Mississippi River. All their attempts to fix the problem have just resulted in additional problems.  The same could be true for Venice. The problems might be fixed temporarily, but man can not control mother nature.  The real soultion to the problem is to not build cities too close to the coast and not below sea level.  
=========yorg=========
===from:Achim Kretschmer
===date:Sun Mar 10 15:38:49 2002
===subject:Out of options
===message:<P>When I first visited Venice 15 years ago, one had to plan around the tides. At low tide the smell was so nauseating that it was difficult to enjoy this fantastic city. Over the past decade I visited many more times, and each visit was more pleasant due to the effort by the government of cleaning up the canals and bay. This is a big event for Italy, because usually nothing gets done when the environment is concerned. Italy is the prime example of a big bureaucracy. As the article points out, plans for a barrier exist since 20 years, but nothing is being done about them, except endless stages of planning.<P><P>There is more at stake in Venice than just saving a city from flooding. Venice is one of the most culturally and historically important cities in Europe, and any attempt of tackling long term solutions need to be handled by the European Union and not just by Italy itself. The bay is currently cleaner than it has been in decades, and I think that building a barrier protecting the city is the best solution given the choices. It is working in the Netherlands, and it can work in Venice. While it will have an adverse impact on the water quality on days the bay can't be flushed due to the raised barrier, it is the only workable long term option left for Venice.<P><P>Unfortunately, the Marshall Islands do not have this option, since their islands are spread too far apart and thus make a barrier impossible to build. The human tragedy is intensified in the Marshall Islands, because their population is growing while Venice is losing inhabitants. Both locations are victims of local and global mismanagement. Pumping the aquifers caused Venice to sink, while ecological destruction has caused irreversible damage to the Marshall Islands. This was the catalyst to speed the effects both areas are feeling now with raised sea levels. If a worst case scenario should come true in the next century and sea levels rise by a foot, Italians would lose a city, but the Marshall Islanders are losing their country and heritage.<P><P>While all efforts to save the Marshall Islands depend on the rising sea level, Venice is in a position to implement a solution that can save the city. While building the barrier might cause some setbacks in water quality, a strict ICZM policy could offset these and actually improve water quality on most days. If Italy could only enforce the environmental laws already in place, and as a concession to the Greens tighten these laws some more, many polluters upstream and around Venice could be forced to clean up their act.<P/> 
=========yorg=========
===from:Greg Foster
===date:Sun Mar 10 21:42:26 2002
===subject:Arrivederci Venice
===message:Consensus Building and Conflict Resolution  --  The backlash against the floating-gates proposal is to some degree a result of the Italian governments failure to achieve consensus on the scope of the project before spending money to advance it through the planning phases.  While I'm sure that all involved parties could agree that saving Venice was a good thing, its obvious that not all agree on what will be sacrificed in the process.  And it's a bit late for compromise now, as the government has already spent $150 million U.S. on the planning phase of the gates project.
<p>
An Ounce of Prevention  --  Venice is sinking at an accelerated rate because of the excessive amount of groundwater pumped from the Veneto region in the 1930-1970's to supply a growing industrial complex.  Any twentieth-century civil planner should know that pumping water out faster than it is replaced causes things to sink.  Given the $2.6 billion price tag for saving Venice, Italy would have been better off supplying their industry with Perrier.  
<p>
Spotty Track Record  --  Even with a $2.6 billion price tag, I'd guess that there would be a groundswell of support for the project IF the Italian people believed the project would be successful.  But with the dubious improvements to the Leaning Tower and the unfinished Sicily Bridge still fresh in the public mind, I imagine the public opinion polls would fall short of optimistic.
<p>
Everyone Has a Right to their own Opinion, BUT  --  The regional environmental group Veneto Ambiente has been a vocal opponent to the gates, claiming that they would seriously damage the lagoon environment by backing-up the sewage flowing into it, resulting in anoxic zones.  The MIT team that conducted the modeling work for the environmental impact assessment feels strongly otherwise.  I already know who I would believe, but if it's any help, Veneto Ambiente's other big crusade is against the dangers of electromagnetic radiation from high-tension power lines.  After years of hounding by skeptical researchers in the field, the scientist who started the controversy finally admitted to fudging his data to show a causal relationship between exposure and cancer rates.  That happened four years ago, and it was big news in the science world.  Yet Veneto Ambiente rattles on.  

=========yorg=========
===from:Ian Gibson
===date:Mon Mar 11 14:53:27 2002
===subject:A big bad wolf named the Adriatic
===message:We have all read that children's story - it has a "happy ending" as the house of brick/stone vanquishes the lung power of the wolf (incidentally, i always rooted for the wolf - who knows if it was winter and the poor canine had pups to feed).  While fanciful, this story is also a metaphor for one of the greatest falicies in the thinking of modern man - that nature, through ingenuity, will eventually be conquered.  This is BS, and Venice is a perfect example.  It is one of the oldest and most interesting cities in the history of the world, and all throughout it's history it has resisted the efforts of it's neighbor - the Adriatic Sea - to sweep it away.  Resisted, until now.  Mother nature took her time, but she has finally caught up to Venice.  Ironically, she has been aided by the errors of the same species that has sought to contain her - man.  By chronically polluting the environment, we as a race have managed to initiate global sea-level rises.  The current efforts - gates and bulwarking the islands - might work, but only with assistance in a more regional sense.  The city has to be focused on in terms of environmental cleanliness.  Cleaing the canals and restructuring appropriate portions of the city to accomodate changes in the environment are an utmost nessecity.  Otherwise, the life blood of the city - the Adriatic -  will ultimately  spell the end for what we consider modern Venice.
Similar situations can be seen in other regions of the world.  Here in American, the city of New Orleans has been living on borrowed time thanks to an ecolgically immoral dike system that has totally disrupted the natural floodplain region of the area.  The Marshall islands is another sad story, and this one will almost certainly have an even more sad ending unless global warming becomes THE international issue, and unfortunately i don't see that happening anytime soon.  The bottom line is, we have had a lesson sitting in front of our faces for the past millenium as to the dangers of freely manipulating the ocean and we as a race we utterly blind to it.  Hopefully we can us the technology that we once used to ravage the earth to heal it.
=========yorg=========
===from:Kristi Foster
===email:scubadoobydoo_FL@hotmail.com
===date:Tue Mar 12 11:22:22 2002
===subject:Move It or Lose It
===message:I think the biggest ICZM issue here is the lack of integration between science and environmental management, one of the five basics definitions of "integration" listed in our online reading assignments.  Back in 1984 the Consorzio Venezia Nuova, composed of 50 of the largest engineering and construction firms in Italy, were tasked with finding a solution.  The best available technology led to raising the Venetian islands and building the gates.  Anything less than this will result in less protection.  Yet the environmental groups did not believe or trust that science had come up with the best solution.  (Unfortunately the article only told of the Greens' oppostion to the plan, rather than providing some of their alternative solutions.)
<p>
As often is the case in industry, Italy did not believe it's own engineers so it hired outside consultants.  The independent commission supported the original design.  So with this corraboration, how is it that non-technical people can still question that this is the best available solution?  Perhaps a public forum should be held to discuss the proposed solution and why other alternatives were not chosen.  Perhaps representatives of special interest groups should be invited to a roundtable discussion to make sure their interests are heard and to convince them that these concerns have been addressed whenever possible during the formulation of the solution.
<p>
The bottom line is that something must be done.  If resistance continues to stall progress, Venice will be underwater permanently and the world will lose so much history and culture.  Unfortunately, the scientists and the environmentalists are not working together, even though they have the same goal of saving Venice.
<p>
This case study reminded me of the Abu Simbal temples in Egypt.  When the Aswan Dam was built, it flooded the river valley and put the temple under several feet of water.  Once the international community became aware of the historical loss underway, it rallied together to move the temple back several feet.  Perhaps Venice could build a "New Venice" and relocate to higher ground?  If this seems ridiculous, then the only viable solution that remains is to protect the present location with the best avilable technology.
=========yorg=========
===from:john O'Sullivan
===date:Thu Mar 14 11:40:50 2002
===subject:Venice history
===message:Unfortunatly this is a resend I lost the original message when I sent it since it is no longer here.  It happened when I hit reset where does it go??

My response stated that the parallels to New Orleans are obvious, in the environmental and political sense.  Both local citizens have a distrust of their national governments trying to achieve anything quickly, respionsibly and within an honest budget.   Part of the proble is a lack of accountability in the political arena, espicially in an elected government.  If you take a stand what will your opponent say?  This is a reason to seek outside experts, but it gives the illusion of shifting liability but gives no actual authority.
The European environmentalists have certainly learned the political and economical power of delaying any action by utilizing the courts.  Governmants and industrial companies just love a 200-300%  increase in project costs.  In the Mid 1980's the US Congress streamlined and timeline the use of the courts to stop projects by environmental groups opposing Nuclear power.  Something the EU will have to do.  Issues such as Venice cnnot wait a generation from policical action to immplementation.  
The Italian government attempted a ICZM initiave ( in ignorance) by initially forming a group to study the problem with 50 industryleaders. Then Report back.  The problem is that they undermined the group by then opening to MIT and European Nations to help.  What is needed in an ICZM project is a clear mandate with the legal and fiscal responsibility to make recommendations that will be followed irrespective of national governments.  This implies a verticle loaning of responsibility and power but if is stipulated -in a charter- it is a legal authority and should be respected as such. 
Can cities die, be born or perhaps reborn? Definatly, take for example Alexandria- short version_ the Nile moved so a major port had no water.  No port, no  new tariffs , no taxes so the political powers moved and the city died.  More recently; When the communistists won in China they move the political capital from Taipai to Beijing, including the move of over three million administrators to populate the new capital.  So if there is  political will a city can be born.  I'm afraid however that our grandchrildren will be viewing Venice through their snorkles.
=========yorg=========
===from:Amanda Burgos
===date:Thu Mar 14 14:55:23 2002
===subject:The lost city of  Venice
===message:Okay so here's a concept..the government in Rome uses all the money currently being used to keep the city from sinking to relocate it. After spending millions it seems inevitable, the city will sink. It seems that no matter what they do the water keeps rising...they put up perimeter walls and propose gates but the prognostic doesn't look any better. The whole situation has a striking resemblence to New Orleans. In an attempt to save the city, the government is spending millions on levees. The result being that over time the walls(in Venice)and levees (in New Orleans) have to go higher; and yet, upon the arrival of a major flood, the end result will be the same..a total disaster. Adding to the dilemna is global warming and the rising of sea level, like the people of the Marshall Islands, Venetians will be forced out of their homes unless something is done. In addition let us not forget that this is salt water we are dealing with, it corrodes everything... eventually everything will crumble.
My solution sounds harsh and maybe I can even suggest it because I do not live in Venice. It is easy to understand the cultural and historical value of Venice. But the fact of the matter is it not my home, which is probably the heart of the issue. No one wants to give up their home and therefore despite ill fated suggestions they will try all in a futile attempt to save it. I merely feel it is a losing battle, nothing suggested seems to work. Plus not everyone is in accordance with ideas proposed, for one opposition does not want the gates--feeling it would "stagnate the lagoon". In the end government stalling will only quicken the city's demise. 
=========yorg=========
===from:matt b
===date:Mon Mar 18 19:41:00 2002
===subject:Water world
===message:I have never been to Venice and as far as I can say I may never go there, so I have no idea what the city looks like apart from what I see in magazines or books. I have been to New Orleans though several times and the city is facing similar problems. We as humans thought that we could tame mother nature by building large dykes to hold back water as well as giant flood control gates. The higher we build them the more damage that will occur once they break. If the city of Venice chooses to build walls around it and flood control structures to keep the water out then almost certainly one day the city will have a great disaster. Maybe it is meant to be that mans engineering successes are inevitably wiped out by mother nature and then we must build again. So Venice is most likely to be the next victim that mother nature claims in her triumph over mans pitiful attempts at controllig her. 

Just like when we tried to drain the Everglades for more land and control over water. Now we have less water, animals are being wiped out along with their habitat, pollutants are changing the fauna of the system and only after years of litigation are we finally trying to do something about it. Its all about control. Control over natural processes we want it and will do anything to get it because we think when we have it we will have bettered our society. When in the end all we are doing is setting ourselves up for disaster. Such as fires in California which occur naturally but we have to suppress them only adding fuel to the fire, that when it burns, it burns and people end up losing their possessions and worse their lives. I say let it burn and let it fall into the sea. We can always rebuild a building but we cant rebuild a damaged Earth.
=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution:NSUOC
===date:Thu Mar 21 12:14:52 2002
===subject:Venice or Atlantis?
===message: Maybe turning the mud flats of the bRenta River into a city wasn't a great idea. But as most things already done to coatal areas and marine ecosystems, the harm has already been done.  Unfortunately, due to mostly natural causes, Venice is slowly being lost.  Not only is a tourist destination being lost, but an entire community thousands of years old is being lost.  The problem is obviously trying to either raise the city or lower the tidal waters that threaten it continuously. Neither solution seems plausible, but something needs to be done.  Due to the building of Venice, the flood plain has disappeared and altered the original workings of the system.  The project to raise the islands and build gates around the lagoon's openings appears good in theory, but is widely opposed.  Whatever decision is made, a lot more research needs to be done in order to prevent a hasty decision.  First, the workings of the entire system need to be fully understood.  Then the impacts of the proposed projects need to be evaluated.  It may however, be impossible to fully predict what might happen.  Ideally, the final decision should be the one the best suits all possible aspects....social, environmental, political and economical.  "but in the end, Venice will probably get it's gates.  Whether or not they work remains to be seen."  That pretty much says it all.  Not everyone can be pleased.  Besides, enough evidence shows that rising sea levels should finish the problem regardless of what is done. Talk about being stuck between a rock and a wet place...
=========yorg=========
===from:Nicolle Cushion
===email:cushion@nova.edu
===date:Wed Mar 12  8:59:40 2003
===subject:Screen doors on a submarine
===message:The Venice case study lacks a major component of ICZM- THE INTEGRATION.  Reading through recent attempts, I realized stakeholders had not been brought together and no dialogue seems to have transpired.  A problem as incredible as this is what the concept ICZM is built around.  What do the people want, how much will it cost, what do El Nino observations predict for the area, can Venice be saved???
These are just a few questions, which need input from scientists, engineers, governmental bodies, local people, and many more.  
That being considered, a more important issue is the MANAGEMENT part of ICZM.  Can this situation be managed?  The saying, 'useful as screen doors on a submarine', comes to mind with Venice.  People need to look at what can be reconciled and what cannot. As shown throughout history, nature ultimately wins, and no man-made structure is foolproof.  A gate, more retaining walls, etc., are not solutions, but temporary band-aids for a situation that seems UNMANAGABLE.  Not to sound heartless, but many great civilizations have gone into the ocean. Maybe the problems Venice has faced should be considered ‘lesson learned’ and knowledge gained should be applied to future developments.

=========yorg=========
===from:Michelle Cho
===date:Fri Mar 14 14:39:11 2003
===subject:Venice
===message:<p> One of the problems here reminds me of the chapter in Woodard’s "Ocean’s End" about the island nations and climate change. There are major differences, though. Venice is a city of 70,000. The young have already started to leave because of the exorbitant rent prices, and the lack of jobs. The MOSE project revolves around gating the city from water, a $4 billion method that has not even been proven to work, and even if it does, it may just gate the city’s waste in and become a cesspool. The island nations were pushing for management plans linked to climate change, and atmospheric pollution. Venice is more centered around its own problem, with good reason. The city may well be underwater by 2050. This is definitely a pressing issue.</p>
<p> After reading parts of Dean’s "Against the Tide", one is left overwhelmed by nature’s forces. Dean seems to focus on the fact that nature usually prevails. Venice seems to have always been at battle with nature, first when they rerouted the rivers around the lagoon, so the sediment would be dumped into the Adriatic, instead of cutting off the city’s access to its port, and ironically, now by adding gates to keep the water out of the city. One gets the feeling they are fighting a losing battle. I think trying to postpone the inevitable is a waste of time and money. $4 billion is a lot of money to bury underwater. It is better to focus on preserving the city's history and cultural relics, and making sure the city is well documented, so that even when the city is gone, all is not lost. No matter what happens, I think I am going to try to get to Venice as soon as possible.</p> 

=========yorg=========
===from:Laura Kukich
===date:Fri Mar 14 15:36:07 2003
===subject:Waterworld
===message:The situation in Venice deals with many questions that don't always have an answer we want to hear. Venice has a crisis in that, it will eventually become unable to allow populations to live there, unless they are fish. The city wants to be able to allow people to still live and work in the area. In providing a solution to it's problem, it tends to get the run around through the environment or politics, and there is never a clear solution. 
With the esatblishment of the gate system, there is a possibilty to allow life to proceed as normal. There is also the possibilty that nothing will change and a lot of money will have been used for no reason. Also there could be an adverse affect on the environment, which upsets the Greens and will upset others in the envieonmental community if this gate system doesn't work.
So the bigger question is, "Is it worth it?" Will we be able to prevent Venice from flooding or is this just a way of prolonging the inevitable? At what lengths will we protect our homes at the cost of an environment that will overtake it anyway?
=========yorg=========
===from:Arlo Hanlin Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSUOC
===date:Sun Mar 16 20:15:08 2003
===subject:Venetian Blinds
===message:This situation in Venice is frustrating from the standpoint of the shear historical value of the city, its art, and its architecture.  Were it not for this incredible heritage value to humankind as a whole (not just to Venetians), I might say that it is simply not worth it to try to fight nature in this manner.  It seems that many of the young feel this way regardless and are slowly migrating to other areas.  The idea to raise the islands sounds the most interesting, but is it really an economically viable possiblity?  Also, it seems to me that whatever is done, be it gates or the removal of landfills, it is still a losing battle.  Maybe, were it only rising sea levels that needed to be addressed, dikes could be built and the Venetians could begin a centuries long fight against the sea, much as the Dutch have.  However, the land is also subsiding.  It is sinking into the sea.  Man has the ability to block and divert water, but we do not have the power to alter the movement of tectonic plates!  Although this might sound sacreligous to admirers of the uniqueness of Venice, I propose moving the most important aspects of the city.  The rich have been moving buildings for centuries (English castles and Egyptian pyramids to North America, etc).   Maybe what needs to be done is to choose a well-grounded site in which artificial and well-managed canals could be built.  From there, move the churchs, museums, the art to this New Venice.  It is a horibble thought, but unless you prefer to think of these artifacts as a dive site, there might not be many other options.  Since this will probably not be done, I support blocking the canals with the gates and reworking the entire city's sewage system in order to address the problem of stagnation.  ICZM will show its pretty head and Venetians will have to learn that they can no longer dump resteraunt waste or whatever else in the canals without having to pay heavy fines.  In comparison to the Marshall Islands, there are similarities, but I think that global interest in Venice sets it apart.  Many who are callous would just assume that the Marshall Islanders can move to other, higher, islands and nothing of historical/cultural value would be lost.  This of course is arrogant and untrue, but how it will be played out nonetheless.  Also, the Marshall Islands are not sinking, at least not at the rate Venice is.  The management issue should be considered very differently due to this fact alone.
=========yorg=========
===from:Jillian McCarty
===institution:Nova
===date:Sun Mar 16 20:16:46 2003
===subject:Venice
===message:Venice certainly is an interesting case study for czm and this course specifically. It has many similarities to the other topics we have discussed. The parallels to New Orleans and the Marshall Islands are obvious. However, it also reminded me of Newfoundland. The population is fleeting in both locations, though for very different reasons. I can honestly say I wouldn't want to live in either place. 
Also, I find it apalling that the Italian government has allowed this problem to escalate to its current state. Proactive steps should have been taken by them decades ago. Now, it seems like something may finally happen with the MOSE project. Unfortunately this project may  cause new environmental concerns for the people of venice. Either way the gates seem to be the only viable hope for Venice at this point. Hopefully, its not too late because Italy doesn't have 20 more years to come up with a new plan.   
=========yorg=========
===from:Amy Diamond
===date:Mon Mar 17 22:57:12 2003
===subject:conflicts abound
===message:The future of Venice looks extremely bleak. Whether the MOSE project goes through, or dikes are built, or some other form of a "solution" is constructed, these are all most likely, just temporary solutions to avoid what unfortunately seems to be the inevitable for this city.  It amazes me that this problem has been going on for decades and yet a project originally proposed in 1972 is still being debated as whether it is a viable alternative to the current situation...4 million dollars later, nonetheless! THis alone should be a bright red flashing light that maybe these problems are not being approached appropriately, or maybe, sadly enough, they simply cannot be managed and other alternatives to preserving the cultural and historical artifacts of Venice should start to be explored. We have learned through many of the examples of involving ICZM that one of the major obstacles in this process is conflict resolution, or at least conflict management. This idea alone seems to be completely obselete from the mindsets of those involved with the Venice situation. It is inevitable that conflicts between stakeholders and user groups will arise with any management issue; however it is important to try and minimize or manage those conflicts in order to get SOMETHING, ANYTHING accomplished or decided! It seems in Venice, since no one can agree on anything and everybody is afraid of upsetting someone else, that nothing is being done, nothing is being tried. That is not to say anyone's needs should be neglected either, but there is definitely a call for integrated and participatory management here. Unfortunately, this was needed many decades ago in Venice, and perhaps not even then would it have been able to solve this city's problems of going under. Venice is built upon an unfortunate array of challenges. Unless a miraculous solution can be agreed upon and implemented soon, Venice may soon become a new undersea attraction for dive enthusiasts. 
=========yorg=========
===from:Christian Legner
===date:Sun Mar 23  9:20:08 2003
===subject:Save Venice
===message:<p> I find that the problems facing Venice are similar to those of the Marshall Islands.  Both places rich in their particular cultures, they face ecomonic and environmental destruction.  The threat of constant flooding that will eventually be irreversible has many sent members of younger generations packing.  The danger in both of these locations is from natural threat that has only been worsened by man-made structures and actions. </p>
<p>  After reading the Save Venice information, I think that one of the most important ICZM lessons that can be learned is PLANNING.  While Venice has been "planning" since 1984, it appears that a lot of that time was spent re-establishing new commissions to study the problem and arguing over the outcome.  Early on, decisions should have been voted on by the public and government to make sure that there wasn't strong opposition to these plans.  Perhaps if this had occurred, the later years could have been spent completing the reconstruction, instead of dragging it out.</p>
<p> I think another important lesson could be the use of foresight.  This probably wouldn't have worked in Venice, since it was built so long ago, but it can work today.  Using locations like Venice or the Marshall Islands as examples, coastal developers should "troubleshoot."  Our world has so many examples of how nature can reclaim the land that developers should consider various possibilities and plan around them (in a researched, intelligent way). </p> 
=========yorg=========
