===from:Amanda Burgos
===date:Sat Mar 16 17:59:41 2002
===subject:Informing the public
===message:After viewing all the websites and links, it seem that non government agencies and the United Nations are responsible for their creation and running. Their main purpose being to inform the public. Their goal as one website stated is "to serve as a clearing house for environmental information and conferences". They seem like one-stop shops for the latest environmental information, providing the latest articles, summaries of conferences, and promoting summits (and participation). The next question asked is whether on not there is an agenda. It appeared there was no one issue emphasized. The main objective or agenda was again easy access to information. They all seem general, looking at the info. related to the environment & sustainable development, focusing on the issues at the heart of the conferences. So is politics involved..well, yes and no. No, politics were not directly involved in the creation of the websites; but, they do play a crucial role in the environment and the turn out of the conferences. I get the feeling the ultimate goal of the websites is to have a public who is knowledgable and aware of the event affecting the environment. If the public is educated then they can get their ideas and opinions expressed at conferences via government representatives and ngo's that partake in the conferences.

=========yorg=========
===from:Kristi Foster
===email:scubadoobydoo_FL@hotmail.com
===date:Tue Mar 19 11:15:07 2002
===subject:Underlying Agendas
===message:An interesting variety of groups are maintaining websites regarding Rio +10 and Sustainable Development, all with their own political agendas.  My take on these sites are summarized below.
<p>
Of course there is the official United Nation's website regarding the Johannesburg Summit.  The site provides updates and official press releases.  All of the information appears to have either a nuetral or positive spin to it.  Nothing negative is published.  I'm sure the content writers are exceedingly aware that Agenda 21 is a non-binding agreement, therefore criticisms against some countries' slow progress or non-participation may be considered too harsh.  Gentle coersion is more in order for this consensus-building entity.  Lead by example and market successes.
<p>
Stakeholder Forum posts www.earthsummit2002.org.  They are the facilitators working with the United Nations during the preparations for the Rio+10 conference.  So, keeping in mind who their bosses are, this website's information compliments the official UN site.  My impression of the site is somewhat of a progress report (i.e.  Look what we're doing for you).  Afterall, if the conference prep is running smoothly on its own, who needs a facilitator? If nothing is running well, then this facilitator isn't doing its job.  So, look at the 50-100 people we're bringing together to agree on the top 5 key (workable) issues and develop action plans just in time to demonstrate progress.
<p>
NGO organizations such as WorldWatch and the International Institute for Environment and Development act as the government watchdogs.  Their purpose is to view progress, highlighting the positive changes and the ongoing obstacles.  They provide "Green" interpretations of the official Rio+10 information. 
<p>
The International Institute of Sustainable Development is a group of lawyers, PhDs and PhD candidates that specialize in international environmental and development relations.  They publish the Earth Negotiations Bulletin which summarizes proceedings such as Rio+10.  These legal briefs can then be used by others to stay informed regarding upcoming legislation and compliance.  Or they can be used to sue governements that are not in compliance with their own environmental laws.
<p>
The University of Delaware's Center for the Study of Marine Policy posts its website as a tool for ICZM research and policy studies.  Similar to this class, it has an educational agenda and will be more likely to be a forum for discussing the pros & cons, who's doing what and why, etc.
<p>
Let's not forget the Business Sustainable Development Global.com site.  This is a group of companies (most likely consultants in the making) that are monitoring the sustainable development process and promoting it as a way to gain competitive edge, increase market share and boost shareholder values.  This is a familiar pitch after working in the petrochemical industry for 12 years.  This same justification was used to institute Total Quality Management, ISO 9000, ISO 14000, Affirmative Action, Inclusion and Diversity, OSHA Star, and other "soft" programs to upper and executive management levels.  Of course, the people in the field recognize that some things, such as sustainable development, should be done simply because they are the "right" thing to do.  But managment needs to see a bottom line impact in order to support time and money investments.  I expect to see a business practice paradigm shift marketed by BSDG regarding sustainable development - show your customers that you comply with the international sustainable development agreements and help them achieve their SD goals, secure better contracts with suppliers who have already implemented SD, be a good corporate citizen, etc. etc.
=========yorg=========
===from:Greg Foster
===email:fjohn@nova.edu
===date:Tue Mar 19 13:08:58 2002
===subject:What's My Motivation?
===message:Any international initiative with such a wide-sweeping scope as the Johannesburg Summit is bound to attract the attention of a number of entities with wide-ranging motivations.  There are many subtleties and nuances, but most boil down to two basic elements; money being the most prevalent and personal conviction a distant second.   
<p>
1.  National Agendas
<p>
·  To influence the summit proceedings towards a favorable outcome, e.g. the debate of access to biotechnology between developed nations (who have the resources to exploit genetic resources) and developing nations (who have the natural resources in the form of rainforests and coral reefs)
<p>
·  To direct subsequent financial expenditures towards their nation
<p>
2.  Governmental Organization Agendas
<p>
·  From a personnel perspective, the Johannesburg Summit has importance beyond its intended objectives, namely job security.  For as long as these discussions remain in the international spotlight, its participants are reasonably assured of continued employment.
<p>
·  From an interdepartmental perspective, individual government organizations are competing against each other for funding. 
<p>
3.  NGO Agendas
<p>
·  The motivation of NGO participants tends to be more personal, and typically more idealistic.  Their involvement stems from a need to positively steer proceedings towards what they consider an environmentally-friendly direction.  
<p>
4.  Academic Agendas
<p>
·  Professors must acquire funding, and advertising can certainly assist that effort.
<p>
·  The amount of attention that these conferences receive also makes them excellent subjects for a doctoral thesis.
<p>
5.  Private Sector Agendas
<p>
·  These conferences have created a new industry for ICZM consultants, who are busily positioning themselves for the expected windfall. 

=========yorg=========
===from:Rebekah Walker
===date:Tue Mar 19 17:10:43 2002
===subject:So many issues, so many websites
===message:Due to the numerous interests and numerous issues that will be covered at the Johannesburg Conference, it is understandable that there are a huge number of web-sites related to the topic.  Although each seems to just offer information about the history of the event, and the topics that will be covered, once you start reading the information they offer, it is clear there are agendas being met by each.  And, since a different group with a different agenda sets up nearly every site, it is obvious that these web-sites are being used to sell each agenda to the public before the event.  <p>

The “official” site is maintained by the Johannesburg World Summit Company, which is supported by the government of South Africa.  This site is the only one that offers information on how to get there, what to do when you are there and the logistical information necessary if you are actually travelling to the conference.  While this is important for someone going to Johannesburg, for the general public, this is really just a way to sell South Africa.  I found less information actually relating to the subject of the conference on this site than any other.  Now, if this site is being given to the public as the place to find out information on the conference, that is a problem, but if the site is mainly for those attending the conference it is logical.  Those attending know the issues and really just want to know how to get there. <p>

I felt the most well rounded sites were those maintained by the UN and the International Institute on Sustainable Development (IISD).  This again makes sense.  Both these groups want the public to know more about the actual content of the event than the logistics of it.  These groups are not as interested in making the conference experience successful as in making the end product successful, and the end product is determined by the level of knowledge going into the event.  It is also determined by how well that end product is received, which is dependent on the information the public received beforehand to prep the decisions made at the event.  Links to and overviews of each issue and each stakeholder are provided on the UN site, and the IISD offers newsletters, books, preparation reports, and other ways to find out information on all the issues.  IISD and UNESCO also have sites devoted entirely to the preparatory meeting held last year to highlight the major issues already being discussed. <p>

The sites maintained by Worldwatch and END team were geared towards environmentalist issues.  Their major links were to discussions of environmental problems and how they will be addressed at the conference.  The END team is made up of PhDs and lawyers with experience in international environment and development issues, so trade was mentioned, however most material centered around the environment.  By doing this, these sites are getting people ready for the conference to deliver ways to save the environment.  If the conference instead focuses on social or economic issues (as I think it will) those interested in the environment, who preped by reading these sites will want more conservation issues highlighted at upcoming conferences. <p>

The site maintained by the Stakeholders Forum focused on the needs faced by the people, and the site maintained by BSD Global focused on trade and development priorities.  These sites highlight the social and economic sides of sustainable development so people will be expecting less environmental focus and more people focus.  The Stakeholders Forum site offered a great deal of information from numerous briefings covering a range of issues, but most centered around social problems, like hunger, water shortage and such.  BSD Global was clearly geared towards economic issues as noted by reading the wording of their conference expectations.  Development and trade were the first focus areas, with the environment being mentioned briefly afterwards.  These sites offered more information on the development side of sustainable development that will be covered at the conference. <p>

Now, I am not saying that any of these sites were done poorly or that their agendas are wrong.  Actually, it is good that there are so many sites with such a diverse amount of information available.  The problem is few people take the time to search around and find all the issues.  They expect all issues to be covered on one site and then from their reading unwillingly bias their expectations of the conference.  There are definite agendas that will be breached at this conference, however hopefully “politics” will not be an issue.  If all attendees remember that their own agenda is not more important than the goal of sustainable development then I feel the conference will be a success.  However, if they let their ideas completely control their thinking and are not open to other’s opinions, “politics” in its worse sense will stop the progress of this conference.  Since sustainable development is dependent on the environment, economics and social issues of the world, all sides of the issue should be covered.  I guess we will see…


=========yorg=========
===from:Kelly Adams
===date:Wed Mar 20 18:14:13 2002
===subject:websites galore
===message:  After looking over some of the web sites on the upcoming Johannesburg  world summit, I have concluded that there is a lot of information out there about it.  The different web sites are formed by a number of different organizations like the Worldwatch institute, the United Nations, the Heinrich Böell Foundation, the International Institute for Sustainable Development, and many more. From the information that I read it seems like one of the main agendas aside from sustainable development is the eradication of poverty. A lot of the information I read seemed like the main concern would be to assess progess made in the implementation of Agenda 21 from the World Summit of 1992. The concern is not with implementing new polices, but looking at what has worked and what things need work. And of course there are politics involved- politics are involved in almost every matter of business.   
=========yorg=========
===from:Matt Mitchell
===email:mitchelm@nova.edu
===institution:NSUOC
===date:Thu Mar 21 12:50:33 2002
===subject:Environmental 
===message:    Essentially, each of the web sites showcase the same basic information, with their own twist...so to speak.  The official conference site displays the published information. This should be expected. It focuses more on the political side of the conference.  The other sites use the conference as a forum to showcase their products, ideas etc...For instance, the Business and Sustainable Development site focuses on it's views of the economics of the conference and programs that have/will result for the conference.
   The Worldwatch site is more about the environmental aspects of the conference.  But, the "twist" is that worldwatch is also selling its collection of papers to you...the concerned environmentalist.  So yeah, it's good information, if you want to pay for it.
   The Oceans and Coasts site seems typical of an NGO.  the site explains how/what and why the organization is involved.  It even offers up accomidations for those of us interested or able to attend the conference. yippee.
   The Earth Summit web site at least has links and information related to the conference agenda.
   All in all, each of the sites has something to offer.  Each has it's own agenda and/or view on the topic. It shouldn't be too surprising to find so many sites about a similar topic.  Just look at all the napster clones and internet porn sites out there.  Everyone has something to offer.
=========yorg=========
===from:johno sullivan
===date:Fri Mar 22 10:00:40 2002
===subject:The Web Road to Rio+10
===message:Overall I was pleased with the Official Joburg website.  Like most governmental sites it was sanitized and generally made for public information without fanning much emotion on the underlying issses.  Having noted that and expressing a bit of cynicism ( a part of the discussion), I decided to find the originators of some of the web pages.  It is no surprise as a businessman I enjoyed the business pontential and surrounding new technologies and latest seminares found on the bsd.global.com page. It was  cear , user friendly and highly informative, up to dat (six days old) and listed future conferences and their web registration sites all economically efficient.  It also had a thorough listing of conference sponsers and even web page sponsers.  From the business world if a NGO or business partner will help sponsor your event, they will do so again! Good news for future employment?  Not all that companies monies is going towards developement/advertising. The worldwatch.org and the iied.org were very interesting and loaded with information.  So much information you wished for a screen that dealt only with marine issues.  The fact some of our acedemic kin are selling their "research" is no surprise and as a capitalist highly encouraging.  I just remember my MBA instructors saying to review your source documentation and its aurthor.   I was surprised that I could not access the IIed home page, but again plenty of ready information in a legal and potential business opportunities (if your up on the latest laws you can tailor existing technologies and markets) were here.  One negative note found through the links was  the Bonn.www-2001 page.  I accessed the home page but the actual conference papers did not download without saving them in the hard drive and then when I accessed it (after 11 min) it did not transfer into a word-98 document, a little techno reality check.  ( needless to say I will not be doing quest 1 or 2. Finally I wonder if the University of Delaware has a more than academic/environmental interest in Johannesburg 2002.  There are plenty of references to the school, even outside its website.  Could that Du-Pont money be trickling down from plastics research/factories?.  I wonder where all the other US and international education institutions are?
=========yorg=========
===from:Ian 
===date:Sat Mar 23 16:53:12 2002
===subject:Questioning Motivation
===message:I would just like to preface this discussion by saying that i am a environmentalist first, a politocrat second (or maybe a distant third)  That said, i strongly feel that several of the websites we out there not for general educational purposes, but rather to satisfy various agendas (and i am not talking about #21).  I have read several pieces of literature that have hinted at the strong anti-american sentiment at the Rio 1992 convention....one specific incident describes an exchange between a liberal Democratic senator from the Midwest and a representative from a central African country.  the African was berating the American for not channeling enough money towards the third world (cause we don't give them ANY money, right?) to which the senator replied we would, if the third world would make the slightest effort at cleaning up their corrupt governments. 
Nice.  I saw similar sentiments in some of the websites.  Here are a couple of observations. I am going to withhold any strong opinions...i don't they will be nessecary.  The IIED page pushes the poor-rich interface....and all of their staff is British, with the chair writing an article called "poverty and plenty" (another staff member, from Quebec,  worked on the I.C. of Social Welfare....) 
The BSD page was obviously a $$$$$$ site perhaps masked with sustainable development...see some of there goals? 1) Access to markets, 2) Access to finance & foreign investments (access for who?....rich corporations using sustainable development as a lever?)  
The last site that i took a little umbridge with was the UN page.....In an address from one of the ministers, he states that the events of 9/11 suggest that " we are in one world  and no part of the world can afford to ignore any other"  Maybe the UN hierarchy should practice what they preach....as i recall, they we one of the last groups to release statements of condemnation and one of the last to visit the ground zero.....AND THEY ARE BASED IN THE SAME GODDAMN CITY!!!  Makes no sense to me.
Not all the pages were suspicious.  The Worldwatch page was solid, as was the sustainable development page and the Oceans and Coasts Confrence.  Regardless, i was left a bit bitter.....i still think that the US is wearing a bullseye not only with militant muslims, but with many leaders of world governmen..... perhaps understandably so - that doesn't mean i have to like it.
=========yorg=========
===from:Achim Kretschmer
===date:Tue Mar 26 15:33:33 2002
===subject:Glut of Information
===message:<p>As can be expected, a conference of this magnitude attracts a variety of agendas that their respective proponents want to have included. The glut of web pages advertises not only these agendas but everything involved with making this conference happen. Hotels and travel agencies post specials, South African web pages discuss logistical issues, and the city of Johannesburg advertises its makeover in anticipation of the first arrivals. <p/>

<p>In regard to the summit itself, the official summit page and UN sites give a clearer picture about the many topics to be discussed. Anything outside the official agenda is being heavily lobbied by world agencies dedicated to that cause. Greenpeace is lobbying for the elimination of toxic chemicals, the United Nations Population Fund warns not to forget population issues, and African sites are praising the selection of the African continent as a host to the summit but warn that African concerns need to be among the most pressing during discussions. Other pages call for papers or posters, while many educational sites invite to workshops and submittal of ideas. On the local level, several high schools and universities discuss the significance of the summit.<p/>
<p>The only politically motivated pages found were concerned with the reluctance of the United States government to endorse many resolutions from the Rio summit. These sites express the hope that the US government would be more supportive this time around, though they acknowledge that the current President’s industrial background is not helping. <p/>

=========yorg=========
===from:Jillian McCarty
===institution:Nova
===date:Tue Mar 18 13:25:59 2003
===subject:Rio +10 websites
===message:Wow - there is so much information about the Joburg conference on the internet that I got a headache trying to sort through it all. The information related to Rio +10 is presented by the UN, IISD, IIED, BSD global, University of Delaware, Stakeholder Forum, Heirich Boell Foundation...the list goes on. For the most part these websites did a good job of detailing the conference and its issues. The UN site was, of course, the most straight forward and unbiased. The other sites outline the same information at varying magnitudes of detail, but most do have underlying agendas. Lets face it there is always an agenda and whether they are environmental, politcal, economic or even personal depends on who or what the sites are dealing with. The different sort of agendas involved in this particular topic demonstrate that politics are very important in all of this. Unfortunately, because there is so much politics involved I wonder what this conference and others like are truly accomplishing. And will all of this lead to any effective IICZM measures or do we need a new approach? 
=========yorg=========
===from:Michelle Cho
===date:Thu Mar 20 12:17:59 2003
===subject:websites
===message:There are those websites that are informational, making documents like Agenda 21 accessible to the public, in addition to agendas from the other world summits.  There are also some websites that seem merely a show that certain groups are taking some form of action, if only by identifying problems, and suggesting action.  Then there are those websites that are used as a poor excuse for action.  What I mean by that is that certain groups or countries can list their website as proof to themselves and to the rest of the world that they have been taking action.  It is exactly what the Jo’burg Conference tried to address—the disappointing outcome of the last 10 years—and unfortunately, all of these websites seem almost as though they have become an online debate, which is exactly what the General Assembly of the U.N. tried to discourage. They state, “What the world wanted was not a new philosophical or political debate but rather, a summit of actions and results.” It seems to me that this “new philosophical or political debate” was simply moved to a new forum—the cyber-forum, which allows those political leaders involved to do what they do best—discuss the world’s problems from their safe, comfortable havens.  On a more positive note, there are some websites that are great at creating awareness, and some that relay that real action has been taken, in the form of real policies and plans. However, like Jillian, I, too, wonder “will all of this lead to any effective IICZM measures or do we need a new approach?”
=========yorg=========
===from:Christian Legner
===date:Sun Mar 23 10:05:13 2003
===subject:Political Agendas +10
===message:<p> So many websites!  The IISD, different UN departments, a university, and even the city of Johannesburg itself.  The UN sites delivered a comprehensive collection of the accomplishments and shortcomings of the 1992 Eath Summit.  I thought the University of Delaware site was also a very informative, easy to navigate, unbiased source of information.  I did feel, though, that some of the sites I visited needed a forum emphasize certain areas of the summit.  One of the most interesting was the city of Johannesburg, which gave a lot of info on their particular contribution to the summit.</p>
<p>  Hmmm...politics?  If this thing weren't politically charged would we have an outcome like this?<br>
"As an implementation-focused Summit, Johannesburg did not produce a particularly dramatic outcome— there were no agreements that will lead to new treaties and many of the agreed targets were derived from a panoply of assorted lower profile meetings." (UN JohannesburgSummit.org)<br>
<p> I do think that a lot of the countries involved are interested in improving the environment and implementing plans for sustainable development.  But, not to be cynical, I think that a lot of those same countries will form treaties or agreements only when their political or economic climate is right.  Summits like Rio+10 are great for airing environmental concerns, and even promising to do something about them, but with so many different countries with different beliefs and agendas, someone has to start making the hard decisions.</p>
=========yorg=========
===from:Laura Kukich
===date:Tue Mar 25 19:58:11 2003
===subject:Rio +10
===message:There are a ton of websites on Rio +10. And searching through all of them takes a lot of time a patience to get through the "WOW!" and "look at this" parts and actually understand what each website was about. They all had a theme running through them with their own twist on how thier organization or area or department etc was a great asset and what they believe so it was difficult to navigate through all the jargon on some sites. Most sites had links to other sites and even more sites. It was difficult to figure out where I started from at some points. 
I do believe there to be some political issues underlying all of them, which is unforatunate but, true for anything these days. So whoever can swing the legislative leaders in thier direction gets what they need. But all were very informative and interesting to me, just to see how each type of area is affected and what they are looking to accomplish.
=========yorg=========
===from:Amy  Diamond
===date:Wed Mar 26 14:52:42 2003
===subject:too much information!
===message:Wow. The "information age" is starting to give me a huge headache! I think the intentions that most of these organizations and websites have are good - they are trying to share information and make it accessible to the public in order to raise awareness and education about ICZM and the WSSD. Increasing public awareness and communication about ICZM have been two of the main priorities concerning ICZM initiatives since Agenda 21, and so many, many committees, conferences, and organizations have created websites in order to do this. However, I am starting to think that too MUCH information may just be, TOO much, yet at the same time, not enough! How do we really know if we are getting the full story? The quantity of information out there does not necessarily reflect the quality of what is being said. It is a little overwhelming to find so many sites concerning just one topic, the Johannesburg Summit, and then even more overwhelming to try and figure out which ones are legitimate and accurate, and which ones are merely mediums for opinions and judgements to get passed. Of course some sites are going to be more informative and more impartial than other, and I am sure there are plenty of websites where only a select amount of information is actually being transmitted, so that we are not really getting the full story, but one group's version of it.  Sometimes it is even hard to figure out what group or organization is putting out the information.  I am sure that there are politics involved in this - with controversial issues concerning environment as well as social and economic aspects, I don't really see how there couldn't be politics involved.  I think the UN sites that offer full documentation of meetings like Agenda 21 or the implementation of the WSSD are very helpful and useful to researchers and policymakers trying to obtain accurate information. Yet it is a confusing process to try and figure out why some websites are out there and what their objectives are. Why affiliation does the University of Delaware have with the WSSD, for example? What aspect of the WSSD is it pushing, and what other issues has it possibly left out or painted a more negative picture of? It is definitely a difficult and frustrating process for people in our field who are trying to obtain the most accurate and non-objective information on ICZM. It definitely makes me wonder how effective this method of information exchange will be for ICZM as more and more websites are created, each with their own agendas, or if this might end up creating more conflicts than resolving them.
=========yorg=========
===from:Amy Diamond
===date:Thu Mar 27 12:14:46 2003
===subject:interesting article to check out
===message:Hi everyone,
This doesn't concern the Jo' summit but I read a really interesting article in the Sun Sentinel the other week that I think everyone should check out online at sun-sentinel.com. It is entitled "Caribbean girds for slump in revenues" and it is from Wed, March 12. I'd be interested to hear any comments on it!
=========yorg=========
===from:Arlo Hanlin Hemphill
===email:ahemphil@nova.edu
===institution_site:http://www.nova.edu/ocean
===institution:NSUOC
===date:Thu Mar 27 18:40:34 2003
===subject:Rio +10,000 websites
===message:As everyone else in the class has already stated, there are a trillion websites out there that covered this event and are continuing to cover the implementation process and/or results of the conference.  The websites are posted by a broad range of interest groups and as Amy Diamond pointed out, it is sometimes even difficult to pinpoint who exactly is posting the site.  I have to agree with the consensus that there might be too much information out there and too many agendas represented at the meeting.  With so many different agendas, politics are inevitable and I see no need to expand on that point.  This is an excellent forum for some of those agendas (e.g. the business agenda vs. the environmental agenda) to meet and hash out issues.  However, it seems to me that too many key issues were allowed to surface.  When bringing in such immensely important, yet hot, topics such as HIV/AIDS, food security, and tourism, how can even the basic components (development vs. deforestation, indigenous land rights, loss of wetlands) of the first Rio conference be addressed in any meaningful manner?  I am not saying that these new hot issues do not directly relate to sustainable development.  They do, especially in places like Africa where the AIDS crisis is literally changing environmental landscapes.  However, how can we address all these things, meet so many different agendas, and realistically expect to develop "sustainably" over the next ten years as a result of a conference of such limited temporal scale?  On another note, as someone who somewhat followed the event as it was taking place, I feel that Rio +10 was vastly biased in favor of southern/developing nations.  It was my feeling that the excessive consumption of the U.S., Europe, and Japan, in addition to the impacts of large corporations based in these countries was blamed for all of the world's current environmental crisises and the reason that the original Rio Conference did meet expectations.  These are surely serious problems that need to be addressed, but are only part of the problem.  In the developing world, exploding populations, unstable political systems, corruption, irresponsible resource management, lack of enforcement for existing policies, and faulty education systems are waging a terrible war on biodiversity, clean water, soil, etc. etc.  How can you approach an international conference like this one while looking at only one side of the picture?  The U.S. is to blame for the greatest percentage of greenhouse emissions, but there is nothing in the west that is fueling the needs for rhino horn and shark fin!
	On a final note, I found it difficult to find a great deal of information on coastal issues.  Two particular sites, Towards Earth Summit 2002 and the University of Delaware, offered informative pdf files on coastal issues.  Beyond these, I found the information to be very generalized, which unfortunately will probably lead to a lack of implementation when it comes to the most important issues.  If you are interested in the pdf files, they are: http://www.udel.edu/CMS/csmp/globaloceans/pdf/WSSDGuide.pdf and http://www.earthsummit2002.org/es/issues/oceans/oceans.PDF .

=========yorg=========
