===from:Debbie Whiteman
===date:Mon Aug 26 13:59:12 2002
===subject:Killing Fields
===message:After World War I, people thought that there would be no more wars.  WWI was known as "The Great War," and "The War to End All Wars."  It was a long horrible war with many casualties.  Such things as nerve gas and other chemical warfare was introduced.  When the "Doughboys" came marching home, of course people were joyous and just new in there hearts that they would not have to send their loved ones off again, but that was not happened.  That was everyones perspective.  If they lost loved ones in the war of course they had a very hard time getting back to normal.....if they ever got back to normal that is.  Women began the era of the suffrage movement in order for them to have the right to vote so they could have a say so in the government.  There was a time of prosperity and just having a good time without ever thinking that this horrible thing could happen again.  And, of course, about 20 years later, it did!  Because the country was prospering, etc., we felt invincible and that no country could touch us.
=========yorg=========
===from:Debbie Whiteman
===date:Mon Aug 26 13:59:21 2002
===subject:Killing Fields
===message:After World War I, people thought that there would be no more wars.  WWI was known as "The Great War," and "The War to End All Wars."  It was a long horrible war with many casualties.  Such things as nerve gas and other chemical warfare was introduced.  When the "Doughboys" came marching home, of course people were joyous and just new in there hearts that they would not have to send their loved ones off again, but that was not happened.  That was everyones perspective.  If they lost loved ones in the war of course they had a very hard time getting back to normal.....if they ever got back to normal that is.  Women began the era of the suffrage movement in order for them to have the right to vote so they could have a say so in the government.  There was a time of prosperity and just having a good time without ever thinking that this horrible thing could happen again.  And, of course, about 20 years later, it did!  Because the country was prospering, etc., we felt invincible and that no country could touch us.
=========yorg=========
===from:Debbie Whiteman
===date:Mon Aug 26 13:59:22 2002
===subject:Killing Fields
===message:After World War I, people thought that there would be no more wars.  WWI was known as "The Great War," and "The War to End All Wars."  It was a long horrible war with many casualties.  Such things as nerve gas and other chemical warfare was introduced.  When the "Doughboys" came marching home, of course people were joyous and just new in there hearts that they would not have to send their loved ones off again, but that was not happened.  That was everyones perspective.  If they lost loved ones in the war of course they had a very hard time getting back to normal.....if they ever got back to normal that is.  Women began the era of the suffrage movement in order for them to have the right to vote so they could have a say so in the government.  There was a time of prosperity and just having a good time without ever thinking that this horrible thing could happen again.  And, of course, about 20 years later, it did!  Because the country was prospering, etc., we felt invincible and that no country could touch us.
=========yorg=========
===from:Debbie Whiteman
===date:Mon Aug 26 13:59:36 2002
===subject:Killing Fields
===message:After World War I, people thought that there would be no more wars.  WWI was known as "The Great War," and "The War to End All Wars."  It was a long horrible war with many casualties.  Such things as nerve gas and other chemical warfare was introduced.  When the "Doughboys" came marching home, of course people were joyous and just new in there hearts that they would not have to send their loved ones off again, but that was not happened.  That was everyones perspective.  If they lost loved ones in the war of course they had a very hard time getting back to normal.....if they ever got back to normal that is.  Women began the era of the suffrage movement in order for them to have the right to vote so they could have a say so in the government.  There was a time of prosperity and just having a good time without ever thinking that this horrible thing could happen again.  And, of course, about 20 years later, it did!  Because the country was prospering, etc., we felt invincible and that no country could touch us.
=========yorg=========
===from:Debbie
===date:Mon Aug 26 14:01:49 2002
===subject:got carried away
===message:I don't know what I did, but I certainly did not mean to post my message four times
=========yorg=========
===from:Robert Jones
===date:Fri Aug 30  6:34:46 2002
===subject:Killing Fields
===message:People certainly viewed war in a different manner after the WWI. The promises of the governments of the world to their respective citizens was that all would be better off after a few years of hardship and conflict. The tone changed when, in a few months, it was realized that it was impossible to fight with outdated tactics while under the fire of modern weapons. Hundreds of thousands of lives were being lost in advancements that proved to bare no fruit. However, an advancing German army made the war unavoidable. The citizens of Europe found this new age war to be more imposing than they anticipated. Political leaders found themselves having to change tactics in the middle of the conflict. While changing tactics BETWEEN wars would be reasonable if not expected, changing and implementing new battle strategies while under fire caused casualties to reach several million. After the war, moral in Europe was low. However, the only solace the people could find was that their children would be safe from the same aggression.......or so they thought. They were unaware that the division of Germany by the following treaty would lay the groundwork for a war twenty years later. Most countries had no desire to have any conflict following that which took the lives of so many. The League of Nations was put into place to ensure that future hostility would be solved diplomatically. After the first meeting of 1920, it was becoming more and more evident that "The League" would be ineffective. Nonetheless, governments and citizens put all of their faith in it for twenty years while disarmament was ignored. When Germany’s army and supply was strong enough, they would strike again.
=========yorg=========
===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Sun Sep  1  7:54:12 2002
===subject:World War One
===message:Before this can be answered we must first understand the character of World War 1. The war itself became a terrible machine for grinding human beings into bits and pieces of wasted flesh. Its most famous battles lasted for months, not hours or days, and counted their casualties not in the thousands but in the millions. Hundreds of thousands of previously rational people lined up facing one another like animals and doggedly shot each other to pieces, day after day and year after year. And no one could confidently or clearly say why it was happening or what it was all about. The cost of the huge conflict has never been adequately computed. One approximate figure, which indicates its scale, is the fact that ten million men had died as a result of direct military action. Even such a horrible figure as this does not indicate the physical cost in maiming, blinding, the loss to families of fathers and husbands, and the spiritual havoc in the destruction of ideals, confidence and goodwill. Truly, this war was “the blood-red dawn of the 20th century.” Yet, Americans, distant from the battlefield, initially disagreed over which side, if either, was in the right. American businesspeople, in the meantime, profited greatly from the war by selling goods to the various combatants and taking advantage of European’s distraction to gain new ground in other world markets. Despite all the gains resulting from noninvolvement, American leadership was pro-British. When the shooting stopped temporarily in 1918, a kind of frantic rejoicing ensued. This eventually ended, as many parties do, in financial disaster. Perhaps J.M. Keynes, a young British economist at the Versailles peace conference summed up the post-war mood best when he wrote, “We are at the dead season of our fortunes. Our power of feeling or caring beyond the immediate questions of our own material well being is temporarily eclipsed…We have been moved beyond endurance, and need rest. Never in the lifetime of men now living has the universal element in the soul of man burnt so dimly.”
=========yorg=========
===from:Ebony Mulero
===email:csu12202@mail.claytonstate.net
===date:Mon Sep  2 17:51:31 2002
===subject:Killing Fields
===message:Peolpe thought this was the end of all wars and wanted an explanation of where and how this war came about. WWI introduced many technologically new weapons ex: machine guns, bombs, etc. These weapons along with diseases lead to many casualties. Some of the countries proved to be a little more advanced in the weapons department than others. In the late 20's the US was not prospering due to the stock market crash that put us into a depression. It was not until the second war that the US started to get "back on their feet" and the economy got put back on track. Many civilians died from malnutrition and stravation. Along with all the the women's suffrage happened because women wanted a say so in government, also the prohibiton movement was brought about. 
=========yorg=========
===from:Velkys Layne
===date:Tue Sep  3 15:58:06 2002
===subject:Episode2-Killing Fields
===message:After World War I, I believe the general view of war was negative.  World War I was a pointless war that cost millions of lives with no overwhelmingly positive outcome.  The soldiers involved in fighting the war and their civilian relatives where probably the people most against it.  After the war, the people tended to watch their governments or monarchies closely.  They did not want the factors that led up to World War I to happen ever again.  
Military and Political leaders were aware that the war had no great outcome for those considered the victors.  Since most of the coverage of the war was propaganda and censored to the public, citizens did not have a true sense of the death and destruction that occured. 
=========yorg=========
===from:Melanie Blinco
===date:Wed Sep  4 17:55:12 2002
===subject:Episode 2 
===message:After World War I, I think people viewed war as a much more dangerous event than previously thought.  Before World War I people thought of wars as being fought with the single shot rifles.  With the single shot rifles it slowed down the number of casualitites.  The soldiers realized that this new war was a serious event in which many lives would be lost due to the new type of war being fought with automatic weapons.  The military realized that with the advancement of weapons the number of casualities and injured was going to greatly increase and also with the soldiers building trenches and staying there and waiting the war was going to last longer than expected.  Civilians now viewed the war as a tragedy to try to avoid or prevent.  After the war I think people thought the best way to cope with their feelings was to try and to forget about it and try to make a better future.
=========yorg=========
===from:Keri Zink
===date:Wed Sep  4 20:23:45 2002
===subject:Thoughts on WWI
===message:People probably viewed the war with many mixed emotions.  Confusion, devastation, and betrayal are just a few examples and a lot of people thought betrayal as the worst.  War was viewed as a 'romantic' past time little did anyone know how horrendous it could end up.  No one thought about technology always evolving and defense weapons was going to be the next on the list.  I do not think even the military leaders knew what was ahead of them until it was too late.  Soldiers thought in the beginning that enrolling into the military to defend the country was the right thing, honorable and at the same time, fearful.  Family members probably had it worst of them all having to sit at home wondering if their loved ones would ever walk throught the door again.  I do not think people could ever actually 'cope' with the feelings the war brought out of the world.  I think they learned to live with it day to day.  It seemed as though even some of the people still got teary-eyed on the video talking about an event that was so devastating to their lives even 90 years later.
=========yorg=========
===from:Eric Klausner
===date:Fri Sep  6 14:47:07 2002
===subject:Episode 2
===message:There are four general perspectives on how people viewed war after World War I.  The perspectives are those of family members, soldiers, civilians, military and political leaders.  During the beginning of the war, family members were proud of their sons, husbands, and brothers going off to fight.  As the war grinded on and conditions for the soldiers worsened that attitude began to change to praying for the safe return.  As the war ended and many soldiers returned in a basket, with body parts removed, or suffering from battle fatigue syndrome, family members vowed never again.

The soldiers’ perspective before World War I was that they wanted glory.  They felt a passion that it was going to be a romantic adventure.  The soldiers also felt like they were invincible and could not be touched.  After World War I though, the soldiers were demoralized.  The soldiers had to dig trenches because they had tactics that were outdated.  The soldiers could not use the cavalry because of the machine gun.  The soldiers had to live in these trenches and these trenches had horrible conditions.  There were rats everywhere, which gnawed at the dead.  There were also lice on the soldiers’ clothing and hair.  The soldiers used these steam machines to kill the lice but they did not kill the eggs.   The soldiers had to use lit cigarettes to kill the eggs one by one.  Chemical warfare was used in World War I including gas.  This gas would destroy people’s eyes and lungs.  The gas would kill you in about 48 hours.  Before World War I the soldiers were enthusiastic about the war, but after they were horrified.  The soldiers probably coped with their feelings by drinking, gambling, or tried getting jobs and work so hard they forget about the war.  Some of the soldiers probably did not deal with it at all and probably had to be committed to mental institutions.  Some of the soldiers in trying to prevent it from happening again ran for office and became the leaders like Harry Truman.  

A third perspective is the civilian.  Some of the civilians were in the medical field and they saw some of the atrocities that happened to the soldiers.  The people in the medical field had to perform many operations a day.  Some of the female nurses would not even go near the soldiers because they were lice infested.  One female nurse kissed a solider and died and that touched her deeply.  Other civilians were the wives, children, and parents of these soldiers.  The soldiers could not talk directly about the conditions of the trenches, but they could indirectly joke about them.  The children also grew up and heard stories about World War I and some became our political leaders.  The families of the soldiers coped by trying to console the soldiers and some took jobs to care for the soldiers who could not work.  Some of the civilians also became our political leaders and refined what happens in war.

The political and military leaders felt like they were the elite and the soldiers job was to do his duty and die in battle.  They thought it was going to be a short war and that old way would work.  The political and military leaders did not see the human side of the war because they were back home living in comfort and overseeing in comfort.  They did not see and feel what the soldiers saw and felt.  Eventually they were replaced by the young soldier generation.  The leaders dealt with the war by making the soldiers no matter what the cost of lives fight and obey orders.  Deserters were given a military tribunal and shot.  The leaders dealt with foreign matters by what happened in World War II and that was by appeasing certain nations.  

There are four perspectives on World War I.  They are the family member, soldiers, civilians, and the political and military leaders.  These perspectives could not stop World War II from happening.

=========yorg=========
===from:Gena Anderberg
===date:Sun Sep  8  9:16:29 2002
===subject:WWI
===message:Before the US got involved in the war, everyone was pretty much sitting on their borders, holding the lines. It seemed that no one really accomplished anything other then a lot of death and destruction. In a way I do see why the US got evolved in this war. Since the powers where so evenly matched, once Russia pulled out, it just seemed like this war would never end. The US also did not want the German submarine warfare to start back up. 
As I watched the video, and they showed clips of Wilson saying we will not get involved in the war, I thought, wish the US felt that way about the Korean War and the Vietnam War. My husband is Swedish and he has been watching the videos with me and giving me the Scandinavian perspective on the war. You will notice they never mention Norway or Sweden. They have always remained neutral in all world wars. Even today they remain neutral as we fight over in Afghanistan. 
WWI left Germany open for someone like Hitler to come in and take control of it.  There was nothing really solved in the end. The countries where just left fighting over land that they felt they deserved. Germany was left in confusion. The total economy was destroyed because of the money that was owed after the war. 

=========yorg=========
===from:Angela Taylor
===date:Sun Sep  8 12:16:48 2002
===subject:World War I
===message:I think that people in general were in a state of shock. I'm sure that those who had been for war had not considered all the damage that was to be done.  All the lives that were lost because one country's leader was mad at another country's leader. The soldiers who were mostly kids themselves had to go and fight whether they believed in the cause or not.  They had to kill and/or capture sometimes innocent people so that they could defend their country. The civilians that were left probably regretted ever allowing their loved ones to go fight. I think that all the people involved directly or indirectly in the war had to get some kind of counseling to deal with left-over feelings about the war.  Those who were against the war in the beginning probably paid closer attention to the president's and military's motives for jumping into a war.
=========yorg=========
===from:Edith Nwosu
===date:Mon Sep  9 13:06:58 2002
===subject:Killing Fields
===message:I think people had a negative view of war after World War 1.  This is because most lost their loved ones in a war they know nothing about, or have no interest in.  Moreover, people suffered a lot of hardships during that time especially those who lived in areas where this war was fought.  The soldiers’ accounts of the war showed that they were not sure of why they fought the war.  Mr. Tela Burt from the U.S Army was told he was fighting for democracy, while Mr. Ray Fuller said he was told to go, and he went.  The soldiers’ perspective was that this fierce war that claimed 9 million lives did not make sense, and that the war shouldn’t have happened because no good reason was given for its cause.  I think these soldiers tried to cope with their feelings regarding the war by talking about it.  There was a lack of trust by the civilians towards their government, for example in Britain, where the people felt that government did not tell them the actual reason why they took part in the war, but instead used propagandas to try to make them accept the war, and to feel justified by their involvement.  Information such as the Germans chopping off the hands of Belgian children, or that the war was being fought for democracy against militarism, or fighting for civilization against barbarism, or for the abolition of war were either half-truths or false. The public confirmed this deceit after they read the published secret Entente treaties by Bolsheviks showing that both sides had ulterior motives for fighting the war.  The public who experienced hardship, and loss during this war began to challenge the government, and ask questions.  The military and political leaders were also devastated by war like everybody else, and their main aim after the war was to try to find ways to rebuild, and to gain back the trust of the governed.  Those who were against the war tried to prevent it from happening again by convening in Paris in January1919, to write the peace treaties.
=========yorg=========
===from:Janna Smith
===date:Mon Sep  9 18:37:09 2002
===subject:Episode 2
===message:After watching Episode II:  Killing Fields, it was made evident that prior to World War I, the sentiment of soldiers, civilians, military and political leaders worldwide was one of enthusiasm due to the idea that the war would be short and would put an end to further fears.  However, World War I brought with it a series of devastating battles which only laid these enthusiastic feelings to rest.		  From a soldier’s point of view, World War I reminded he/she that war is not just about becoming a hero and defeating the enemy.  I am sure they learned that chivalry does not always lead to victory, and that the cold reality of this world is that life cannot be replaced.  Of course, due to the fact that the world’s soldiers had now been exposed to death and destruction many of them lost hope in their commanders and became deserters.  This may have caused many of them to lose hope for their own lives because they may have felt like failures.  Once you are a part of something (an association, group, etc.) for a period of time, it is easy to begin seeing yourself not as an individual but as a piece of that group no matter what the outcome.  I am sure that some soldiers coped by deciding never to go to war again, and many matured after being exposed to such a harsh reality.
	Civilians may have felt a loss of hope and security after World War I.  Many civilians praised the soldiers at the beginning of the war and had high expectations for the outcome of the war.  Not only did they consider this war to be a symbol of their pride in their military, but it was supposed to add reinforcement to their sense of well-being.  World War I lasted longer than most would have expected, and so many were killed from all fronts in a period of time shorter than what they were used to.  As a result, this devastation to civilians only weighed heavier on their optimism and confidence in their leaders and nations.  To handle this loss, civilians probably stopped being in support of their family members going to war.
	When World War I ended, I am certain that many political leaders had to identify ways to regain strength and unity within their own nations in order to move ahead.  However, these leaders were reminded on a constant basis that deciding to enter their nation into a war might mean a harsh defeat and loss of many lives.  The political leaders may have come up with new tactics to help ensure that the least amount of casualties occur if a new war were to erupt.  In addition, they had to build the trust back of their people, which they may have accomplished via mass propaganda.
	Those who were against war during that time may have tried to introduce treaties and regulations as opposed to war.  They may have also spoken out publicly against it as well.

=========yorg=========
===from:Wendy Abdo
===date:Fri Sep 13 21:16:52 2002
===subject:World War I
===message:Before World War I, people had a romantic idea about war.  Parents sent their boys off to war happily and were proud of seeing them in a uniform.  They never dreamed that they were sending them to their deaths.  World War I was a horrifying war that took so many lives and really ruined the world’s economy for many years afterward.  This war, for the most part, lowered the morale of the soldiers.  Amazingly, Russian soldiers were expected to fight without their own weapons and many of them simply walked away from the war.  Civilians were bitter because the war dragged on for so many years and they became poorer because of inflation and other economic issues due to WWI.  Military and political leaders, who were so cocky and sure of themselves before the war, realized that they were not as “all-powerful” against the opposing countries as they thought they were.  They had to rethink their strategies and consider that their men were human beings instead of pawns on a chessboard.  Each person wanted to put the blame on the other party because the war cut deep into the pockets and hearts of the people.  The League of Nations was established to try to stop another World War from happening again, but even this did not stop the second war from coming.


=========yorg=========
===from:Melonie Broner
===date:Sat Sep 14 16:44:15 2002
===subject:World War I
===message:The effects that World War I had after it was over, could be considered as positive. World War I changed the ideas about the functions of government, it clarified how governments should obtain and spend money, it helped to settle the unstable Austro-Hungarian, Russian, and Ottoman empires, and the war settled many other questions. But, I believe that as much good as it did, it also placed a negative view of war on many people. Many people's lives were distroyed by the effects of this war. To many, it was not neccessary for the US to become involved in this war. The government, however, must have viewed the war as positive because they continued to "manipulate mass emotions" (Findley-Rothney, p.70). I do not believe that most people did deal with their emotions. I believe that the politicians probably dealt with theirs by continuing to tell themselves that they had done the right things, but as far as the civilians, I believe that it may have been more difficult for them, especially those that lost family and friends. I believe that those who were against the war probably rallied more, probably wrote more letters to their politicians, and probably signed petitions.
=========yorg=========
===from:Kristin Linette Crook
===institution:HIST1110
===date:Sat Sep 14 22:26:24 2002
===subject:episode 2
===message:World War I was an eye-opening war in that it brought many to the realization of the harsh realities of war.  As the declaration of war was announced people rejoiced. They felt it was high time for war. It wasn’t until the soldiers entered the battlefields and the civilian and the soldiers both saw how long the war was lasting that they realized war is not such a grand thing. As the conflict went on,  the condition only worsened.  Battles were even fought for the sake of not giving up.  There was no prize that they were fighting in the name of- except national pride.
		After WWI soldiers were sickened at even the thought of war.  They were right there in the middle of everything. The filthy muddy trenches, the lice, the rats, the death and despair. WWI veterans did not come home with feelings of pride, they lost their pride in the war. Even the “winners” of the war did not gain anything.  The death toll was nine million.  Battles went on for extra month after extra month and soldiers were contained in the trenches for the sake of being there and not giving up. 
	Civilians could not have possibly imagined what the soldiers were experiencing in the trenches.  The letters that soldiers sent home to their families were censured.  Sure they were aware of some atrocities and the filth, but they could have never imagined the inhumane acts that were becoming a way of everyday life for these men. Certainly civilian paid most attention to number of casualties being sent home and the extreme length of the war.
	Military leaders must have learned a lot from WWI.  It is wrong that most elite military leaders never even saw the trenches or experienced the horror that the soldiers were experiencing.  They just called the shots and were desensitized to the orders they were giving. They were so distant that they could not have possibly had the soldiers’ best interest in mind. Nevertheless, strategically speaking, the military leaders probably learned a lot about what to do next time.
	Political leaders were right up there with the military leaders, they did not have any idea what the soldiers were going through.  They probably freely used the term trench warfare without even think about what their soldiers must have been going through out there on no man’s land. 
	Most people chose some sort of outlet in order to cope with war. If they didn’t they probably ended up going crazy.  Soldiers were known to have created political sketches speaking out against war. Many other soldiers just tried to get injured and sent home or at least killed and put out of their misury.  Also many soldiers ended up to turning to some kind of chemical substance.
	People tried to prevent war from happening again through speaking out and educating other people. Soldiers’ accounts of the trenches and other experiences were shared with the public. Voting turn out probably increased drastically in democratic countries and authors  wrote books like Remarque’s All Quiet on the Western Front.

=========yorg=========
===from:Tomeka Mayo
===institution:Hist 1110
===date:Wed Sep 18  0:55:01 2002
===subject:The Killing fields
===message:I also believe that, after WW1, many people had to view war in a new light.  Many started the war feeling that it would only last a short time and they would return home soon.  They were fighting for national self-preservation and to prove their nation's strength. Although WW1 did create some new opportunities for some social groups, such as allowing Women to get hired for jobs that were originally monopolized by men and Blacks to migrate to areas where industrialists were hiring any type of labor, I believe that everyone realized that the costs of war greatly out weighed the benefits of war.  I believe that the soldiers who entered as young, idealistic boys came back as war-torn men who had seen death and, as the movie stated, had done anything to come back home.  I believe many civilians realized the costs of such a bloody war when many sons, husbands, and fathers didn't return home. I believe the military and political leaders, whose tangled alliances made War inevitable, realized that risking the loss of an ally is more dangerous than the risk of war.  As far as how people coped, They must have done whatever it took to cope.  Take for example, the artistic rebels who defaced artwork and poetry in an attempt to make sense of the world(our textbook, pg. 71). I agree with the author of the textbook who said, "the world had gone through an orgy of destructiveness that seemed to prove false everything the prewar world had believed in".(pg 71).  People against War must have come together to speak out publicaly against war and many people who had been in the war may have tried to influence others with their own experiences.  Also some people wrote books and publications about the tragedies of war from different countries perspectives.
=========yorg=========
===from:Tonya Harris
===date:Tue Sep 24 11:27:07 2002
===subject:World War !
===message:World War I changed everyone view about War. Military and Political leaders, which was essentially one in the same at the time, made decisions basic on their idealogy of what war was to them. For some, it show a nation's toughness and something that was quick to end. Leader today, as a result of World War I, view and know that war is not quick nor short-lived. Many lives will be lost, countries would be devastated and the psychological impact would last for every. For soldiers, most of them thought going to war would increase their with women, and as for the cilivians, war was romantic. "Our men go out to fight for us for a couple of months, we win and have total dominatant of the world. All because our brave men fought." Well, after World War I and during the War, the romance had die. Soldier and cilivain alike realize that war is anything but a romantic cause.   
=========yorg=========
===from:Shameeka Beckett
===date:Tue Sep 24 15:24:51 2002
===subject:The Killing Fields
===message:After WWI people were no longer dillusional to war.  They realized that war was destructive and pointless.  They saw that millions of people lost their lives for less gain than they were promised. The soldiers on leave wanted to do nothing but forget about the war.  They wanted to forget about the trenches they were in, the lice, the hunger, and the killing.  The civilians were no longer enthusiastic about war, as those who once lived as middle class citizens starting living poor because of inflation.  All people became suspicious and distrusted their political leaders because of the mass propaganda they used to get people ready for war.  The military leaders were unaware of the destruction the war would cause.  Germans were able to implement poisonous gas that could kill soldiers within 48 hours, due to modern day science.  No one knew the war would continue for 4 long years.  People after the war tried to cope with their feelings by turning to religion.  Those who were against the war tried to work towards a country of literal equality so war wouldn't happen again.
=========yorg=========
===from:Stephenie Buice
===date:Tue Sep 24 21:23:20 2002
===subject:Discussion 2
===message:I believe that World War I changed many people's views about war.  Other wars that had been fought provided results that were evident.  World War I had over 9 million casualties, and there was nothing that was really gained.  This war was unjustifible in many minds, as well as my own.  Countries that had nothing to do with the "argument" only participated because they didn't want others to think they turned their backs and ran.  Political leaders (who many were military men) were distant and remote to this war.  They sent men in to be killed, but had no idea what the front line was like.  Also, the leaders said that this would be a short war, and it lasted over 4 years.  I believe that this caused civilians and military to not trust what the political leaders said or did in the future.  Maybe this is where the feelings of our political leaders being dishonest was born.
=========yorg=========
===from:Mark Prosper
===date:Tue Sep 24 21:46:47 2002
===subject:World War I
===message:I think that society for the most part viewed war as a gruesome, expensive, and senseless display of violence. A majority of soldiers had no idea why they were fighting and wanted desperately to return home, they viewed themselves as pawns in the chess game in war. civilians saw the war as political propaganda that was drastically effecting their quality of life. political leaders looked upon the war like an olympic game that would prove dominance and show superiority. Most people were saddend angered and scared by the war and coped with their feelings through religion. Those against war used education, demonstrations, and suffurage rights to prevent war from happening again. 
=========yorg=========
===from:Heidi Sprinkles
===date:Tue Sep 24 22:12:18 2002
===subject:Killing Fields
===message:I think civilians and soldiers alike thought that WWI would be the last war the world would have to face.  The economy being good only made this seem more likely because we as American's thought we were untouchable.  After WWI  women started preparing to make their mark and to give their opinions and hopefully prevent another war from occurring.  Of course we all know this did not come to pass with WW2, Vietnam, and the Gulf War.  With each war we learn more and more about people of other cultures and as war ends we hope to learn to do deal with those cultures better and of course we always hope this will be the last war but as long as the there are people in the world we're all not going to get along and therefore there will always be wars and rumors of wars...until the end of the world comes!
=========yorg=========
===from:Mark Ehrlich
===date:Tue Sep 24 22:20:43 2002
===subject:Killing Fields
===message:The American peoples view after World War I was that they was against war.  They thought that America had no reason to fight a war on the other side of the world.  They coped by expressing that they don't want to fight another foreign war.  They voted for polticians that was against war.
=========yorg=========
===from:Kathleen Gibbs
===date:Tue Sep 24 22:45:39 2002
===subject:Killing Fields
===message:I think people had a sober and more realistic idea of what war in the new industrialized world  meant in terms of  the loss of live and destruction of property. The soldiers may not have understood why they were fighting but they could still take pride in the fact that they had answered their nations call to duty. The horrors of the war was imbedded  in the hearts and minds of the people for generations to come . The leaders in our country did not have an easy time convincing John Q Public to get involved in the next war.  People voiced their opposition to sending our men off to war more openly and were  more demonstrative with each new war.      

=========yorg=========
===from:Yvelle Maurice
===date:Wed Sep 25 16:15:27 2002
===subject:Kiiling Fields
===message:According to Episode 2, the people were very excited to go to war.  The women, wives children, and the men who were off to war believe that it was the proudest thing to do for their country.  The people had an attitude, which stated that their army was very strong.  As for the leaders, they had no idea how long the war was going to last, so they told the soldiers that the war would only last a few weeks, but it actually lasted four years.  After, the WWI, the people’s attitude towards war was totally different.  It wasn’t about heroism, but it was about lost lives.  Millions of dead soldiers left every country involved in grief for their love ones.  And the soldiers that did survive, I came back with low self-esteem, feeling hopelessness because their country lost the war.   The people began to have doubts about the type of politicians were running their country because they lied to them.  They also began to wonder what caused the war, just to realized that it all started because of a misunderstanding.
=========yorg=========
===from:Jason Odom
===date:Thu Oct  3  9:34:53 2002
===subject:Post 1
===message:Society had no idea what the consequences would be of WWI. There would be a rude awakening to the truths of war after WWI was over. It was hard to know what the overall effect of more advanced weapons would be, unfortunately the huge numbers of casualties would answer this unknown. The training of soldiers, or lack there of, could never prepare them for the battles that were ahead of them. All of the glory that was thought to come from war, soon dissipated with the reality of war. After WWI, people that were directly affected by the war had a much different perspective about it. Until the reality of war is experienced, it is difficult to understand the consequences of it. Soldiers would have certainly thought different about war and fighting after seeing the carnage that comes from war. Political leaders that had any conscience would have been horrified at the results of WWI. However, politicians always seem to have a way in which to brighten a darker image. When WWI was over, people that were against the war would have more facts to present in opposing future wars. It would be easy to point out the negatives of war, when people have seen the death and destruction that war brings.
=========yorg=========
