===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Sun Oct  6  6:45:20 2002
===subject:Breadline Response
===message:I think it was obvious that the American people had accepted Franklin Roosevelt as their leader. To stand four successive times as presidential candidate was almost unprecedented, to win was astonishing. To do so with an absolute majority of the popular vote was something like a revolution. And he did so in an electoral contest, which was basically one of hope versus despair. He offered confidence and the promise of action to shake of the blight of economic depression and he delivered. It was a remarkable demonstration of the ability of the American political system to deliver what the people felt they wanted. I think this, most of all, helped restore confidence in the government, and ultimately helped the economic recovery. However, the “New Deal” on which the Roosevelt administration embarked was still not satisfactorily dealing with the economy by 1939. Nevertheless, it changed the emphasis of the working of American capitalism and it’s relations with the government. A huge program of unemployment relief with insurance was started, millions were poured into public works, new regulation of finance was introduced, and a great experiment in public ownership was launched in a hydroelectric scheme in the Tennessee valley. This in the end gave capitalism a new lease of life, in a new government setting. The New Deal brought the most important extension of the power of the Federal authorities over American society and the states that had ever occurred in peacetime and it has proved irreversible. Not only did he save the country, the Roosevelt era was historically decisive. It changed the course of American constitutional and political history as nothing had done since the Civil War and incidentally offered to the world a democratic alternative to fascism and communism by providing a liberal version of large-scale governmental intervention in the economy. And it was all the more impressive in that it rested on the choices of politicians committed to the democratic process and not on the arguments of economists. 
=========yorg=========
===from:Robert Jones
===date:Sun Oct  6 18:19:37 2002
===subject:Breadline
===message:Franklin Roosevelt was by far the most influential president of modern times. Not since Lincoln had America been revolutionized through the insights of one man. Roosevelt offered promise and hope to a people who had lost all respect for their government. Coolidge and Hoover were ineffective in their outdated attempts to right the economical ship. However, as had happened before in 1861 and 1901, a fearless president stepped up, not for his own cause or political gain, but for the interest of the people of the United States. He offered the New deal which commissioned the T.V.A. and other government opportunities to decrease unemployment and stabilize the economy. Coupled with America’s entrance into World War II, these measures brought relief and restored the confidence of the common man. Once the people saw that a man of action was calling the shots, the recovery of the economy was imminent. With a people who have low morale and fear of tomorrow, it becomes more and more impossible that they can be helped. Roosevelt helped the people of the United States help themselves. On the other hand, it would be fallacious to imply that one man saved this nation. Though a great and inspiring man he was, he simply jump-started a revolutionary turn in American economics that allowed the citizens to mold this country into something even greater than before. The fruits of his actions are still felt in the twenty-first century but only Americans make America great. However, it is unfortunate that the democratic party strayed from the ideals of Wilson, Roosevelt and Truman. Now, instead of doing things in the interest of the people, the democratic party shifted to a somewhat Socialist ideal where things are done to increase the dependence of the people on democratic leadership. "How will I pay for my medicine if I don’t vote democratic?", a senior-citizen may ask. "How will I support my children without welfare?", another may inquire. Ladies and Gentlemen, we have all been brainwashed to believe that the role of government is to provide for us when that leaves us wide open to the tyranny that our founding fathers fought against. Franklin Roosevelt would not approve.       


=========yorg=========
===from:Wendy Abdo
===date:Sun Oct 13 15:03:31 2002
===subject:Breadline
===message:The New Deal that President Roosevelt established was a saving measure for the American people.  Many of the people who were on the brink of starvation saw President Roosevelt as an angel of mercy who saved them from the pits of despair.  However, the business leaders for the most part did not like Roosevelt because of the laws he passed in favor of unionization.  Before the New Deal, none of the political leaders felt they could do anything about the economic plight of the country.  So by the time Roosevelt took office, they were in no position to be choosey and allowed Roosevelt to take the lead by giving him “broad executive power.”  By setting up such institutions as the FDIC and the CCC, Roosevelt helped many Americans regain a measure of confidence in the government’s ability to lead them out of the Great Depression.  However, I must disagree with what Mancel Milligan said about Roosevelt saving the country because the New Deal did not end the Depression and did not help everyone like unorganized labor, but rather tended to help the big farmers the most.  I do not believe that benefits were distributed as equitably as it could have been. Do you?
=========yorg=========
===from:Debbie Whiteman
===date:Wed Oct 16 13:39:40 2002
===subject:Breadline
===message:The New Deal did two things:  It fostered the idea that the government could solve all problems and it created a class of people who look to the government for hand-outs.  Economic recovery occured only as a result of World War II spending and confidence and the government had little to do with it.  Mr. Roosevelt did not "save" the country.  He was president during an economic cycle during which the economy recovered in spite of the "tinkering" that the New Deal imposed.
=========yorg=========
===from:Keri Zink
===date:Wed Oct 16 19:12:17 2002
===subject:Breadline
===message:In my opinion, I do not think it was as much of The New Deal that affected the people’s feelings as much as it was the president and the situation.  By the time that Roosevelt was elected, Americans were ready for ANYTHING to make their lives better.  They began to believe anything the President was telling them, and by all means, he did sound as though he really cared.  The people in the video even viewed the new president as their ‘personal’ friend instead of their national leader.  (I once read that letters poured into the white house in the millions, from ‘fans’ all over the country.  He is the president that received the most letters while he occupied the cabinet.)  Many people were desperate and were willing to try anything to pull the country out of the depression so they and their families would not starve anymore.  Restoring confidence in the govn’t helped the economy because many Americans believed what the govn’t was saying, (the govn’t meaning Roosevelt in my terms).  Americans were willing to work and work at anything the govn’t wanted them to do.  Roosevelt and his plan worked.  I give him credit for that, but I believe that if he would have not occupied office, the up coming war would have put many Americans back to work.  Roosevelt just ‘saved’ the country before the war was an issue.
=========yorg=========
===from:Janna Smith
===date:Fri Oct 18  6:53:42 2002
===subject:Episode 7
===message:Prior to Roosevelt's presidency, people were looking towards alternatives to capitalism. After Roosevelt's New Deal was initiated, many Americans regained their sense of hope and especially confidence in their government.  Most people only wanted to provide enough for themselves and their family, the New Deal gave them this ability, thus restoring pride in themselves.  President Roosevelt definitely saved America economically through his innovative tactics and proved the notion that sometimes government intervention is necessary to sustain a nation.
=========yorg=========
===from:Melanie Blinco
===date:Fri Oct 18 14:11:46 2002
===subject:Episode 7
===message:People looked a the New Deal as the government trying to help in a time of economic disaster.  The people saw governemnt leaders pulling together to pass the New Deal programs and felt like they had someone trying to help them, that they were not in this fight for survival alone.  After President Roosevelt was elected President and Congress started passing his New Deal programs I think this was the first steps in restoring people's confidence in the government.  With this new confidence people were more willing once again to start spending money and borrowing money and that is what drives the economy.  I don't think that President Roosevelt saved the country.  If it hadn't been for World War II, I don't think Roosevelt would have been looked upon quite as favorable.  It was the war that ended the unemployment problem.  It was because of the war that there were rations on many items that people would have spent money on , but instead they saved thier money and purchased government (secured) bonds.
=========yorg=========
===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Sun Oct 20  7:38:06 2002
===subject:The New Deal
===message:I think the impact of the Great depression and the programs of the New Deal dramatically changed the relationship between the American people and their government. The federal government extended its role in many social and economic areas, becoming larger and more powerful. Americans came to accept government involvement and responsibility in caring for society’s most needy and regulating many aspects of the economy. This was probably one of the greatest and far-reaching aspects of Roosevelt’s New Deal. The depression experience discredited the extreme individualism and pursuit of self-interest that characterized the 1920s, and revived an emphasis on community, cooperation, and compassion. These values were reflected in the popular culture of the day and in political and labor movements that developed and expanded during the 1930s. The New Deal’s social programs reflected a shift in American values created by the shared hardships of this era. While many conservatives believed the New Deal was turning the United States toward socialism, other Americans felt it did not go far enough and sought more revolutionary change. The New deal did bring the United States more in line with government traditions of other Western nations by increasing the power of the state in what had been, by European standards, a rather loosely governed society. Although it did not end the Depression, the New Deal's experimental programs helped the American people immeasurably by taking care of their basic needs and giving them the dignity of work, and hope.
=========yorg=========
===from:Eric Klausner
===date:Sun Oct 20 15:01:11 2002
===subject:New Deal
===message:How did the New Deal affect people's feelings about themselves and their government leaders?  Before the New Deal, the average person knew not to depend on the federal government for a safety net.  Not only did none appear in previous depressions, but also President Hoover felt strongly that the government needed to stay out of people’s lives.  In one of the videos, a person looking back on his student days in the 1930s mentions his economics teacher saying that the cycle is boom and bust with nothing that can be done for it.  The New Deal was based on the government could do something to stimulate the economy and provide a safety net for people.  Those lives improved by the New Deal obviously felt better about themselves and President Roosevelt.  However, not everyone was “saved by the New Deal as unemployment remained at 18% going into WW II and as the New Left historians of the 1960s point out minorities and often women were ignored.

How did restoring confidence in the government help the economic recovery?  To trust in an economy, one must first have confidence in the stewardship of the economy or in this case the federal government.  Though the New Deal did not completely end the depression, as people became employed confidence that the economy will recover and the government will help grew.  This is evident by the early support to Communism and Fascism in the late 1920s and early 1930s that wane near the start of WW II because people began trusting in the capitalist economy with a strong federal government oversight.

Do you agree with Mancil Milligan's remark that "Mr. Roosevelt actually saved the country"? Why or why not?  I find Mancil Milligan's remark paradoxical looking back in hindsight.  On the one hand, Roosevelt brought back confidence to most people in the country that at a minimum the federal government was willing to try various things to stimulate the economy to include Keynesian economic theories such as prudent use of deficit spending.  Thus any paths to the political left or right extremes were halted.  On the other hand federal intervention has changed the country so dramatically from the laissez faire attitudes of President Hoover and his predecessors.  The Feds are in every walk of life today, which started with the Roosevelt administration.  I believe he did not save the country as it existed before his presidency as the “Roosevelt revolution” radically altered the major relationships within our nation.


=========yorg=========
===from:Gena
===email:genaanderberg@yahoo.com
===date:Sun Oct 20 16:36:30 2002
===subject:Bread Line
===message:Until I watched this documentary I never had really thought about how the Great Depression must have affected many other countries throughout the world. You usually only see or hear about what effects it had on the United States. It was also interesting for me to see that they had a little history about Sweden (my husband is Swedish) and how they established their Socialist Democratic Government which is still in place today. They where able to lift their country up and out of the effects that the depression had on them. I think Roosevelt did the best that he could do considering the circumstances  that he had to deal with. With so many millions of people unemployed he had to take into consideration what he needed to do for the masses. To get the most people working as soon as possible.  Of course he could not help everyone. The drought in the mid west had been so bad for so long that there wasn’t much he could do for them. What he did though was jump start the American economy. He targeted the areas that would get the most people working and back on their feet as fast as he could.  Yes I think he probably did save the American People.  With so many desolate people we where open for a radical leader to come in and take over. What if a “Hitler” had come in at this time. Desperate people do desperate things. Think about 13 million + desperate people. 


=========yorg=========
===from:Kristin Crook
===institution:hist1110
===date:Mon Oct 21 17:37:53 2002
===subject:Breadline- initial response
===message:The New Deal literally brought about a revitalization of the people and the government of America. Society went from feeling hopeless to feeling like they again had hope for a prosperous future. This New Deal came in response to the Great Depression that America was going through. Nobody even saw the economic collapse coming. Men in every occupation suffered. It seems that before this great tragedy people trusted their government, but I wonder what was there to trust? No social programs existed before the Depression, as said in the video “there was no dole.” I guess all people had to put their trust into was the competence of their government to make good decisions and the craftiness to be able to get the country out of a bind when needed. When it was needed, the government did not come through for its people, President Hoover just sat back and waited for a cyclical turnaround that would occur naturally within its own time. 
That was bull crap and people knew it. They were willing to work, yet they could not get a job, so they starved or went homeless and moved into an appropriately named “hooverville.”  In the midst of this Depression it was obvious that people all over were beginning to doubt the solidity of their government. Communism and Socialism were beginning to look better as Capitalism seemed more and more flawed and unacceptable. Small Communist and Socialist groups began to rise up in America in response to the inept Capitalist economy.
	In 1932, change was on the horizon, as Franklin D. Roosevelt stepped up to the plate. His election campaign promised people change as it promised to bring back the “Happy Days.” The American public quickly dropped Hoover and elected Roosevelt with a landslide victory. Roosevelt didn’t waste any time, during his first hundred days in office, he put sixteen major measures before congress and all sixteen of these policies were passed. 
Roosevelt did a huge thing for the men of America when he devised the WPA, thus providing jobs for those starving for work. He did more than give them a pay check; he put smiles on their faces and hope in their hearts. Our textbook states that the Great Depression was not only a time of vast economic depression, but also a time of great psychological depression. Men felt that they were losers who had failed because they could not provide for their families. Also, many people committed suicide, especially those who had most of their money tied up in the stock market, whose bottom fell out in 1929.
As people began to regain confidence in the government, they also began to feel freedom. They felt that their country was in good hands and that things would look up again. Even though the wealth was distributed unevenly in America during the twenties, most people lived a comfortable life style. One comfortable enough that allowed them to feel confident to do things like buy groceries and save for a car and a house. After the depression, as confidence in the government sector grew, so did confidence in the economic sector. The man from the video said that when he was given a job by the government, he made sure to hire people to cut his grass or paint his house, so that everybody would “get a piece of the pie.” 
So, even though every person actually did not get a piece of the pie, Roosevelt did a great job. He acted immediately and worked efficiently with the time and resources that he had. His optimism and courage to take new steps helped save the country from ruin. All things considered, I do not agree with Milligan that Roosevelt alone saved the country, but I do believe that his policies were the catalyst that put things into action

=========yorg=========
===from:Velkys Layne
===date:Wed Oct 23 17:14:20 2002
===subject:Breadline
===message:It is a little unrealistic to think that one man could actually save an entire country, but in Mr. Milligan's time that is exactly what most unemployed Americans believed.  As is evident with Mr. Milligan some still believed this into their old age.  The New Deal gave some Americans hope.  They saw it as someone doing something to help them not just sitting back and letting the economy run its course.  Most americans were unemployed and hungry.  Even though the New Deal did not create the jobs that put many people back to work, I dont think the unemployed cared about who got the credit.  President Roosevelt happened to be in office during the depression and their was a World War being waged in Europe.  Americans did not get jobs from the New Deal they got them as a result of the United States entering the war.  The depression, The New Deal, and World War II all occured around the same time.  Would the New Deal have been considered the "savior of the people" if the war had not occured?  The New Deal did have several benefits.  As a result, government had a small role in ensuring the well being of its citizens and an increase in organized labor occured.  
=========yorg=========
===from:Ebony Mulero
===date:Fri Oct 25  8:46:44 2002
===subject:Breadline
===message:Franklin D. Roosevelt was a great influential man with strong leadership abilities. While Hoover was in office he did nothing to help the American people in their time of need. When elections came up it was no wonder that FDR won with a land-slide victory. The American people were ready to see some changes they were ready for something great to come into thier lives....and that's exactly what FDR did. FDR offered promise and hope to those who did not respect and care for the government anymore. He offered the world a new democratic approach to things instead of fascism or communism that was happening in most other parts of the world; and let's face it people in these days were desperate and were looking towards any kind of solution to the Depression problem. In the video the cartoons sang a song that said "Happy days are here again." This is exactly what FDR brought back. By offering a New Deal FDR put many people back to work. With programs like the Work Progress Administration, Civilan Constrution Corps, and the Tennessee Valley Authority many adults and youths were provided with jobs. Americans gained confidence for their daily lives, the government, and in the country as a whole. The lives of many people were improving and this is what America was looking for. By Roosevelt's government giving people jobs, those people in turn provided work for others who provided work for others. Even if it was painting a house or sweeping the streets the American people did their work with much pride and dignity. By offering a New Deal FDR in a sense helped people help themselves by working. Surely, he did not save the country on his own their was a lot of help from WWII starting overseas. He initiated the process that everyone followed and loved. 
=========yorg=========
===from:Mark Ehrlich
===date:Sun Oct 27 13:59:21 2002
===subject:Hist episode #7
===message:In 1932 the year before Roosevelt took office 13 million people 25% of the workforce was without jobs.  Roosevelt was very confident that America can beat the depression.  He started many new agencies to help the people.  In the first hundred days 16 new major measures was past.  He was the first president to use the radio on a regular basis.  This built confidence in the people that a high ranking offical was talking to them.  He had a great voice and put words together very well.  I guess I agree with Mancil Milligan's remarks about Roosevelt.  It seems like Roosevelt was there at the right time and people was desperate for change and he had change that seemed to work well at the time.
=========yorg=========
===from:Yvelle Maurice
===date:Mon Oct 28 18:54:11 2002
===subject:Breadline
===message:The New Deal gave people confidence and hope for themselves as well as their government.  Restoring confidence in their government helped the economic recovery because the people where willing to listen and do anything for a government that cared for them.  President Roosevelt proposed his optimism in radio which was known as the “fireside chats.”  He constantly told them how the economy would recover from the Great Depression.  President Roosevelt did not want his people suffering anymore so he established the New Deal, which enacted several laws.  I do agree with Mancil Milligan’s statement because the New Deal did create a number of jobs.  The New Deal was also about sharing your profits.  The New Deal concepts became a cycle to the work force.  For example, Mr. Milligan did not mind sharing his profits because he too was creating jobs for people.  He hired people to build and paint his house.  Even though U.S. was still in depression, I believe that New Deal was the starting point of the economic recovery. 
=========yorg=========
===from:Melonie Broner
===date:Mon Oct 28 19:46:03 2002
===subject:Breadline
===message:The New Deal restored confidence in the government which also caused the people to regain confidence in themselves. Restoring confidence in the government made people feel safer about their economy. As the people watched the government spend, even in a deficit, in order to create new jobs for the jobless, thus creating wages for the penniless, it made the people feel safer about their futures. And when the people began feeling safer about their futures they began putting money back into the economy. For example, when the FDIC was created, depositors began putting their money back into banks without the worry that under another depression it would be lost. I strongly agree with Mancil Milligan's remark that "Mr.Roosevelt...actually saved the country." With the poverty, disease, and suicide rate at an all time high, the population was in alot of danger. The fact is that without Roosevelt's New Deal, our population may have decreased even more than it did. With new jobs, people began feeling hope again. The wages the people were now earning could provide food and shelter for themselves and their families thus, improving the way of life. When Roosevelt took office, almost 4 years after the Wall Street Crash, a quarter of the workforce still remained unemployed. Under the New Deal, many people were able to come out of this slump. The people were able to began putting back into the industry. Without Roosevelt, who knows what the present would be like and if there would even be a today the way it is.
=========yorg=========
===from:Stephenie Buice
===date:Mon Oct 28 21:13:08 2002
===subject:The New Deal
===message:The New Deal was the best deal that President Roosevelt could have constructed.  It gave confidence to the desperate individuals, not only in themselves, but in their government leaders as well.  The New Deal made people believe that Roosevelt cared for them.  The farmers were one of the most devestated by the Great Depression, and Roosevelt actually enacted a measure that would give them $35 for a cow instead of the low 2 1/2 cents per pound for the beef. The WPA (Work Progress Activity) actually created jobs (improving the cities) for people who were unemployed.  This gave individuals a brighter outlook on life.  The confidence created by the government helped the economy because individuals actually received jobs, which turned into income.  The people would put this money back into the economy by hiring people to paint their homes or bring them wood.  So the money that the government created was not just sitting under the matresses, but was in fact going back into the economy.  I do think that Roosevelt saved the country.  Herbert Hoover was in office for three years after the Stock Market Crash, and his idea of helping the people was to let the depression "run its vicious cycle."  Hoover even had fire set to the demenstrators' belongings, who were only there in protest of trying to receive employment. How long would the depression lasted if Hoover would have been reelected?  What would have happened if a different leader, other than Roosevelt, had come into office?  Would the views match those of Hoover or Roosevelt?  Roosevelt did the best he could, and I believe that his New Deal was the best deal that could have occured. 
=========yorg=========
===from:Tonya Harris
===date:Mon Oct 28 21:49:40 2002
===subject:My Opinion of the New Deal
===message:The Depression was one of the worst the world had known. America was suffering right along with everywhere else. The depression had devastating effects on the country. At this point most people willingly turned to government because there were no other options.  When Roosevelt presented the New Deal it offered people a new hope of survival.  The jobs that were created and the government support to save various industries were bound to gain the support of the people. As the new programs were put into place and the unemployment rate decreased, people were eventually able to contribute to the growth of the economy.
I think many people felt that Roosevelt saved the country. He gave them hope were there was no hope.  Programs he created were for the benefit of the people. He was the right man at the right time but only because he understood the public opinion and capitalized upon it. 
Although many of his programs, in my opinion were good (minimum wages, social security, welfare), I also feel that some were of extreme nature.  He felt the only way out of the depression was for the government to spend money.  The amount of government spending to support many of these programs would eventually cause other lasting affects.

=========yorg=========
===from:Kathleen Gibbs
===date:Tue Oct 29  1:28:20 2002
===subject:Episode 7-Breadline
===message:The New Deal gave people a new lease on life. The people who were without a job, without a home, without the knowledge of where their next meal was coming from were suffering from low self esteem. With the New Deal people began to feel self confidence again and to look toward the future with new hope. They began to trust their government leaders again. The confidence that people gained in the future of the country made them willing to spend the money that they were now making again and put more money into circulation and this helped in the recovery of the economy. I think that the measures that Roosevelt put into effect to jump start the economy did help the country recover from the depression and these measures were needed at the time that they were implemented. I  think his efforts did in a sense save the country .    

=========yorg=========
===from:Rachel Harper
===date:Tue Oct 29 12:53:15 2002
===subject:Breadline
===message:The New Deal helped many American rebuild their lives. Creating the New Deal helped FDR to restore confidence in the government with Americans and the Economy. When Americans lives were restored they began to start spending more which brought the economy up from ruins. I do beleive that FDR did saved America, because with out the New Deal America and the world could have experinced much more economic disaster.
=========yorg=========
===from:Jim Heinzel
===date:Tue Oct 29 13:53:31 2002
===subject:HIST 1110
===message:During the Great Depression there were thousands of people that were smart, ambitious and willing to work that were out of a job. They were at the mercy of conditions that were beyond their control. No matter how hard they were willing to work or how well laid their plans to provide for their families and themselves, there was just not enough money in circulation to go around. This must have frustrated many people in America because this was the land of opportunity and up until then your success at making a living mostly depended on how well you planned and how hard you worked. The New Deal provided the opportunity for many workers that were willing to work to have a job with dependable pay. I'm sure that caused people to feel they had some control over their future once again and boosted their self-esteem.

Restoring people's confidence in the government helped ralley support for the programs the government wanted to implement in order to stimulate economic recovery.

In a way the depression was the result of a capitalist economy gone wrong. Some of the programs that Roosevelt put in place went against the principles of a capitalist economy such as the United States had. However, the theory of any economic model does not work perfectly in practice. The economy was in a slump with no hope of improvement in the near future. If the United States was to remain a world economic power and maintain quality of life for it's people in the future, drastic measures had to be taken. President Roosevelt made these changes and economically did save the country.   
=========yorg=========
===from:Mark Prosper
===date:Tue Oct 29 18:30:32 2002
===subject:The New Deal
===message:The New Deal affected people's self confidence because the depression brought about dramatic changes in the lives of many american families.  Men were forced to resort to unfavorable means of providing for their families, like stealing and even standing in bread and souplines.  Many kids dropped out of school because they felt obligated to help support their families financially.  The New Deal brought promise due to the amount of legislation that was passed in what is now known as "the first 100 days".  The economy began to rebound as the GNP rose 7.7% and unemployment fell 21.7%.  This gave hope to many Americans.  Consumer confidence was rebounding which was pivotal to the rebounding of the economy.  I strongly agree with Mr. Milligan, Roosevelt did save the economy.
=========yorg=========
===from:Jason Odom
===date:Tue Oct 29 20:40:41 2002
===subject:Post 1
===message:The "New Deal" infused a sense of belief in the government within the hearts of U.S. people. It led the American people to have confidence that the U.S. could recover without the need for fascism or communism. With this new confidence people were more willing to start spending money and borrowing money. This enthusiam was the start to a recovery in the American economy. I feel that at the time it certainly would have felt like FDR had saved the country. When looking back at the situation, points can certainly be made that FDR's policies played a major role in saving the economy. He provided help to the areas of the economy that would get the most people working the fastest.
=========yorg=========
===from:Heidi Sprinkles
===date:Tue Oct 29 21:21:36 2002
===subject:Breadline
===message:The Depression was a bleak time in U.S. history.  The success that Americns  had experienced was a complete turn around from the now jobless and moneyless citizens of the Depression.  The word depression had a double meaning, first of all the economy was very low and this forced many citizens to be unemployed.  This unemployment forced the citizens into a deep depression of their own.  Roosevelt was able to jump start the situation allowing both the economy and the citizens of the US to rise from the deep depression.  Even though Roosevelt didn't do it on his own he did lead America out of the depression
=========yorg=========
===from:Shameeka Beckett
===date:Tue Oct 29 21:50:26 2002
===subject:New Deal
===message:The New Deal affected peoples feelings about themselves in the way that it gave them hope.  People began to feel like they could get out of despair and start living their lives again.  Farmers were happy that Roosevelt bought cattle from them only to turn around and can the meat and give it back.  He established the FDIC, and people began to trust their governmental institutions.  Roosevelt promoted industrial recovery, and established new jobs.  People began to put their faith back in the government and that would prove to be detrimental in the long run, as people would start to depend more on the federal government for assistance.  I don't agree with Milligan's remark about Roosevelt saving the country, but I will say he did get them on the road to recovery.
=========yorg=========
