===from:Edith Nwosu
===date:Tue Oct 15 17:51:59 2002
===subject:Master Race
===message:American ideas about what makes America special are; that Americans are able to live together in peace and harmony regardless of orientation, race, religion, or creed.  It is also a place where everybody is supposed to be treated equally according to the law.  Americans are well aware that they are technologically, industrially, and economically advanced. They have a high standard of living, better education and healthcare compared to other parts of the world.  Americans know that their government would protect, and defend them wherever they may be during crisis or war.  The mere fact that people want to come to America in order to live a better life makes Americans feel special.  Nazi’s idea of what makes Germans special was their belief of being a superior race of the Aryan origin, which included being white with blue eyes and blonde hair.   This idea of superiority led them to believe that all other races were inferior, should be hated, and should be dealt with either by extermination, or slavery.  History recorded how they tried to exterminate the Jews, and to conquer the whole world.  These Nazi ideas have been harmful to others in the United States.  There was a time in this country when the white supremacy (KKK) movement was very active.  Unlike Germany where their main target were the Jews; blacks were the targets in America.  History also recorded how blacks were discriminated against, used as slaves, hanged, or burned just because their skin was black.  
=========yorg=========
===psite:http://student.claytonstate.net/~csu10164
===from:Veronica Walker
===institution:HIST 1110
===date:Sat Oct 19 10:01:39 2002
===subject:Master Race
===message:The idea of living in America is where people come to our country for freedom and future advancements for a better life. America is a land where people are supposed to be treated equally according to the law and no one should be discriminated regardless of orientation, race, religion, or creed. In the past history, white Americans wanted to create their own "Master Race." African Americans, Jews, and Homosexual was target and discriminated against. African Americans and Jews was used as slaves, beaten, and killed because of the color of their and ethnic origin. African Americans was denied public education and voting rights. Homosexual was beaten, torture, and killed because of their sexual preference.
Our world then was no different than what Hilter was doing in his country, except Hilter was one man trying to create a master race, we had many.
Today, since the equal rights protection law was passed, all Americans are suppose to be creat equal but prejuices still do exist in some individuals. It hurts me that people have so much hatred in their heart to hate and to killed because that person's skin or behavior is different than their own. We must love one another in this world to have peace. When we die, we will all become one Master Race--"Ashes."
=========yorg=========
===from:Wendy Abdo
===date:Sat Oct 19 13:04:38 2002
===subject:Master Race
===message:In America, we have diverse populations of people from all races, nationalities, religious, and ethnic backgrounds.  We are supposed to be an example to other nations on fairness and equality.  In theory, this ideal works contrary to the Nazi ideas about their master race of Arian descent since we as Americans proclaim that “All men are created equal.”  Unfortunately, I see the United States falling short of this goal because of the individual and group prejudice against minorities that is still very prevalent in our society today.  Some of these prejudices are taught in the ideas of the Klu Klux Klan which promote feelings of hatred towards others of a different ethnic background than “whites.”  These feelings of hatred escalate into terroristic acts of crime that seem justified by the very ones who are doing the acts.  This is dangerous since these feelings of superiority cause people to hurt instead of help each other; this is exactly what happened in Germany.  I hope the prejudism in the United States never gets that far.  Don't you?
=========yorg=========
===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Sun Oct 20  8:21:13 2002
===subject:Master Race Response
===message:As WWII progressed and the Allied armies advanced into Europe, the deepest evils of a system of terror and torture were revealed by the opening of the huge prison camps and the revelations of what went on in them. It was suddenly apparent that Churchill had spoken the truth when he said “if we fail, then the whole world, including the United States, including all that we have known and cared for, will sink into the abyss of a new Dark Age made more sinister, and perhaps more protracted, by the lights of perverted science”. Although the degrees of atrocity were unspeakable, the world’s imagination was most struck by the systematic attempt that had been made to wipe out an entire race of people. Hitler’s hatred of Jews, and other groups such as gypsies and gays, ran deep. He blamed them for personal misfortunes and for movements such as socialism and excessive capitalism that in his view had weakened the German spirit. Anti-Semitism served as a catch-all for a host of diverse dissatisfactions and therefore appealed to many Germans. Although Americans, including myself, are becoming increasingly disturbed and apprehensive of Muslims (and justifiably so), I don’t believe the American idea of patriotism and freedom has ever been harmful to another race.
=========yorg=========
===from:Yvelle Maurice
===date:Wed Oct 23 17:49:46 2002
===subject:Master Race
===message:The Americans ideas were definitely similar to the Nazi ideas.  The Americans and Nazis were both about nationalism.  During the mid twentieth century, the Great Depression affected both countries.  Therefore, they both wanted a unified government, a rise in the job market, and to also raise the citizens’ confidence for their country.  The Americans also had a similar definition of who was part of the “superior race.”   To the Americans, the white men were the superior race of U.S.  And to the Nazis, the Germans and other Nordic races were the only superior race of Germany because the other races were genetically inferior.  
<br> <br>
At that point in time, the American ideas were not for everyone.  African Americans and women did not have voting rights.  Therefore, even if the U.S. established a unified government, they could not voice their opinions regarding the new laws that may affect their lives.  Even when women had a right to vote, it was for white women only.  Although slavery was abolished in 1865, Africans Americans still had no equality.  The schools, water fountains, restrooms, buses, and many more were segregated for a long period of time.  They were never given a reason to show their pride for their country.  And then, you had the Ku Klux Klan (KKK) who took matters into their owns hands just like the Nazis.  KKK and the Nazis both had the same motives, which were African Americans, Jews, and others were not part of the human race.  Therefore, if you are not part of a human race, then there is no need for you to be living.  With that type of attitude, it made a whole lot of sense for the Nazis to have gas chambers for the Jews and the KKK lynching African Americans or burning their churches/businesses.
<br> <br>
On the other hand, the Americans ideas were also good because it brought entertainment to the people.  Entertainment was a way for people to temporarily forget what was actually happening to their country.  And entertainment is still some people’s haven from the their countries political, social, and economic struggles. Today, the American ideas apply to everyone including African Americans, women, and other minorities.  However, you constantly hear about hate crimes in the news.  Why because some people still believe that their race is superior to the rest of the world.  

=========yorg=========
===from:Keri Zink
===date:Wed Oct 23 20:50:42 2002
===subject:Master Race?
===message:First of all, I am appalled by anyone who says Americans ideas, attitude, or beliefs were like the Nazi or Hitler’s.  Our ideas I believe, as Americans as a whole, are nothing like that of the Nazi.  Hitler was a man of extreme authority who devoted his time to exterminating a race and imprinting in his country’s mind that, the German race was superior.  Americans never imprinted such an image as Hitler did with Germans.  Taught early in school with picture books about how Jews were a vile to society, forced to starve, forced out of their homes and shot in the head.  NEVER in America’s history will you find something as devastating as what Nazi’s did to the Jews.  We have never poisoned anyone like the Nazi’s did because some leader of ours thought a race was immoral to our society.  We never purposely exterminated any race, never created prison camps where we KILLED the imprisoned ones, never told Americans that one race was pure, never burned bodies to dispose of, or to rid the evidence of our wrong doings, never made lamp shades out of human skin, we Americans as a whole are NOTHING like the Nazi population and never will be.  Racial discriminations in this country was and never will be like that of the discrimination in Germany toward the Jewish population.  My heart bleeds when I have to watch a film as such as I was made to watch today.  The cruelty of one human who had the power over millions and made the millions of ‘fans’ view his beliefs as SANE and moral, what the hell?  I will disagree with anyone who says Americans ideas, attitude or beliefs, are like Nazis and I will tell anyone the main reason why: we have never made an attempt to create one master human race.  This country has and always will let immigrants into it, (this country) and that right there is proof that we are nothing like Germans, Nazis, or Hitler’s children, who believed the Germans were the One Supreme Race.  We opened the doors to all of the races all over the world and never felt like our race is the “only way”.
=========yorg=========
===from:Janna Smith
===date:Fri Oct 25 13:47:13 2002
===subject:Master Race
===message:For most of America's history, Americans have retained ideas of nationalism and superiority in both the economic and ethnicity arenas.  Americans have had a sense of nationalism ever since independence was gained from Great Britain.  This is somewhat similar to that of the Nazis nationalism in Germany, although American nationalism was not as structured. In addition, the US has a feeling of economic stability and dominance as an economic world power.  America's idea of superiority of White Americans over other non-white races caused harm to others in the US.  Such is evident throught the history of America starting with Native American and leading to African-American injustices.     
=========yorg=========
===from:Kristin Crook
===date:Fri Oct 25 16:43:11 2002
===subject:Master Race- initial response
===message:As long as America, as founded by the British, has existed, a white superiority complex has always co-existed.  I think it all started when the settlers from Europe arrived and kicked the Native Americans off of their land. Those expansion-minded Europeans did not think twice about the harm they were causing; I don’t even think they viewed the natives as people. And it was all because they were different. That was the problem with the Jews and the Gypsies according to the Nazis they were different, so exterminating them would be like nothing more than killing off a certain type of animal that just didn’t belong. It had to have been this idea of white supremacy that gave the English the pride and the greed and audacity to push an entire group of people off of their land. I visited the Cherokee Indian gardens in North Carolina recently and all I could think about was how much these people knew about our earth, especially American earth. There must be so much that we could've learned from this group of people. But, we just kicked them off their land and forced them to live on reservations. No, we weren't as bold as the Nazi's; we didn't build death camps, but we did bring about the destruction of the Native Americans. We killed off their main source of survival, the buffalo, and cultivated our own food. We brought with us our European ways and pushed them on the Native Americans as if they were wrong for the way they lived.  And then, a little bit later there were the Africans who were brought over to America by force, thus becoming African Americans.  The white supremists of those days weren’t as systematic as the Nazis and they didn’t try to wipe out the entire race, but in the south as well as in other  parts of the country, a great deal of violent atrocities occurred in which these African Americans were brutally killed. I am happy to say as time has progressed, so have people's attitudes towards diversity. If we claim to be Americans, then we must not forget that we all came from the same melting pot. That was a problem that Hitler had. I don’t know the exact ethnic history of the Germany- Austria area, but its safe to say that there were very few truly pure blooded Germans with blonde hair and blue eyes, I can also say that Hitler wasn’t even one of them.
=========yorg=========
===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Fri Oct 25 20:30:14 2002
===subject:Germany and America
===message:
Adolf Hitler’s success makes it very difficult to deny him political genius despite the pursuit of goals, which make it difficult to believe him sane. Nonetheless in 1933, the National Socialist German Workers Party which he led (“Nazi” for short) was strong enough for him to be appointed Chancellor of the German republic. This could definitely be compared to the nomination of the President of the United States. And the Nazis were beneficiaries of economic collapse, as were the Hoover/Roosevelt administration in America. By 1930 the Nazis showed they were the power in the land. They attracted more support, and won backers from those who saw in their street-fighting gangs an anti-communist insurance. Doesn’t this sound similar to the resistance exhibited by American colonists against provocative British legislation in the eighteenth century? Like Stalin’s Russia, the Nazi regime rested in large measure on terror used mercilessly against its enemies. This could indeed be likened to the infamous KKK in America. Yet, when this terror was unleashed against the Jews an astonished Europe found itself witnessing revivals in one of its most advanced societies of the programs of medieval Europe or Tsarist Russia. This was indeed so amazing that many people outside Germany found it difficult to believe that it was happening. Although Hitler’s messages were simple, his appeal was complex. He preached that Germany’s troubles had identifiable sources. The Treaty of Versailles was one of them. The supposedly anti-national activities of German Marxists and Jews were others. He also said that the righting of Germany’s political wrongs must be combined with the renovation of German society and culture, and that this was a matter of purifying the biological stock of the German people, by excising its non-Aryan components. Yet, never once has the any one group of inhabitants been blamed on America’s political woes or has an attempt been made to “cleanse” America’s culture by exterminating these peoples. Nor has discrimination been analogous to nationalism, and had appeal that cut across classes as an explanation of America’s troubles. Anti-Semitism in pre-war Germany did. In addition, was Hitler’s genuine aim to ultimately create a “Master Race?” Probably a reasonable approximation to the truth is simply to recognize that he expressed the resentments and exasperations of German society in their most negative and destructive forms and embodied them to a monstrous degree. Fortunately, this has yet to happen in our great country.

=========yorg=========
===from:Melanie Blinco
===date:Sun Oct 27 13:01:58 2002
===subject:Episode 9
===message:Americans are similar to Nazis in the sense that we have a strong military and strong political system.  We also have our own social issues with things such as discrimination and social injustices.  As Americans, I do not think we ever have to worry about what happened in Germany ever happening here in the Unites States, because in our democratic process we have a process of checks and balances.  With the checks and balances systems, no one person can possess all the power.  We also have a larger more educated population.  This means that more people are educated about what is going on locally and internationally and are more educated.  Also as Americans we have strong ethical beliefs.  As with the most recent events with the D.C. Sniper, most people wanted this person to be caught and most people thought that for a person to do such a thing he would have to be truly sick.  As Americans our actions at times have been harmful to others and the two examples that come to mind are slaves and the American Indians.  We never set out to exterminate a whole race, but in the case of the American Indians that is almost what we did without even knowing it. 
=========yorg=========
===from:Eric Klausner
===date:Sun Oct 27 13:53:26 2002
===subject:Episode 9 Master Race
===message:With nationalist fervor as occurred after 9/11 and somewhat in support of a war to take out Hussein, one might make an argument that American ideas are similar to that of the Nazis.  However, the Nazis were predominately an exclusive society that pushed the superiority of the Aryan race.  While America is an inclusive society though racism and other negative "isms" exist.  In the Nazi realm, no one but Aryans could enjoy any power.  In America, the Secretary of State is of African decent.  The four-star general who heads Forces Command is also of African descent.  An Orthodox Jew ran for vice president and is considering running for president.

However, when the tolerance of including everyone is set aside for the safety and convenience of this country, groups get hurt.  For instance, Japanese-Americans were placed in internment camps during World War II though many of their fathers, brothers, and sons fought for the United States.  Native Americans have had treaties trampled on when it was convenient.  Thus our history includes moments of shame usually caused by a patriotic flag waving overzealous reaction to something.  To prevent this we must defend the civil rights of those Moslems buried in the Justice Department and that is why ACLU Jewish lawyers defended Neo-Nazis in Skokie, Illinois because if one of us loses our rights, all of us can be next.

=========yorg=========
===from:Robert Jones
===date:Sun Oct 27 18:15:37 2002
===subject:Master Race?
===message:Certainly there are similarities between the two cultures relative to how citizens feel about their country. All countries are proud, to some degree, of their endeavors, accomplishments and future. However, the  questions posed under this topic suggest a similarity between the United States, as a nation, and the fascist Nazis under the Third Reich. The two are hardly comparable. Whatever shortcomings the United States has in the implementation of a "equal" society are leaps and bounds away from any Nazi ideas. Admittedly, African-American slaves, even after the Emancipation Proclamation, were treated less than equal in a changing society. It was also difficult for some other groups to find widespread acceptance in the United States. However, millions of immigrants from all over the world were encouraged to become citizens of this country in the early twentieth century. While this does not justify the unequal treatment of the before mentioned groups, it is indicative of the ideals that were established as the backbone of the American society. Conversely, the Nazi government in Germany imposed, through propaganda, the idea that Jews were the cause of Germany’s economic and social problems. The systematic extermination and genocide of  millions of Jews under the name of German societal advancement could, in no way, be compared to any inequalities in the American society. I would grant any dissenter from my point of view that there lie things in American history that are less than favorable in the interest of ethnic equality. But to compare, or to  be asked to try to find similarities between Americans and fascist murderers is preposterous.  
=========yorg=========
===from:Robert Jones
===date:Sun Oct 27 18:58:00 2002
===subject:Comparison
===message:African-American population in 1920: 10,463,131.
African-Americans lynched between 1889-1918: 2522.
Percentage: roughly .02%  (2/100 of 1 percent).



European Jewish population in 1940: roughly 12,000,000.
European Jews exterminated under Nazis: roughly 6,000,000.
Percentage: about 50% ...There is no comparison!


Note: The number of African-Americans lynched was compiled by NAACP.

=========yorg=========
===from:Debbie Whiteman
===date:Mon Oct 28  9:19:41 2002
===subject:Master Race
===message:American ideas of what makes Americans special is based in part upon our motto:  E Pluribus Unum (out of many-one).  Reflecting the premises that we draw on the qualities of many people, and that our system brings out the best in them.  The Nazi's idea was that the Germans were superior and all other races inferior.  They felt that "racial purity" was the ideal.  The American's idea of superiority extended to many races during that time.  This was harmful and created prejudice and exploitation.  Fortunately, today the American people don't seem to be near as prejudice as they have been in the past, regardless of their race or ethnic backgrounds.
=========yorg=========
===from:Mark Ehrlich
===date:Mon Oct 28 11:40:42 2002
===subject:Hist episode #9
===message:I believe America had alot of similarities when it came to nationalism in the past but that don't exist like it used too.  Nowadays I  believe Americans are special due to finances.  America is a the only superpower left and all the other countries realize this to be true.  Our economy perdicts what the world economy will be.  So this gives us superiorty of the world due to our finances.  I believe these ideas are harmful to the foreigners and illegal aliens because Americans look down to these people and expect them to do the low graded jobs that Americans don't want to do. 
=========yorg=========
===from:Melone Broner
===date:Mon Oct 28 20:22:33 2002
===subject:Master Race
===message:The similarities between America and Germany concerning what makes them special, are not that hard to find. "Americans" felt, and in some cases, still feel, that the whites were superior to any other race in America. They tortured and bullied the Native Americans after the White Europeans trespassed onto their land. When the White Americans went to Europe to retrive Africans to bring them here, they treated them horribly also. Over the years, after slaver was outlawed, the whites would to evil things to the blacks. The blacks, Native Americans, and other non-white people were treated worse than dogs just because the whites felt superior to other races and nationalities. Germany was expressing their "right" to declare supremacy over all non-German people. They killed Jews and Gypsies and many more that were unlike them. It was highly hypocritical, to me, for America to degrade Germany for the same things they were doing here. These ideas have been extremely harmful here. Recently, a black man has tied to the back of an automobile and dragged to death and his only crime was his skin color. The four little black girls attending Sunday school were killed only because of their skin color. Throughout history, many whites have acted on their "supreme right" to kill, hurt, and degrade people because they happen to not be white. Isn't ironic that one of the main things Americans critisize Hitler for doing, was, and is, going on here in America?
=========yorg=========
===from:Tonya Harris
===date:Mon Oct 28 22:40:56 2002
===subject:Master Race
===message:One thought that comes to mind for this discussion is that Americans have always been a leading power.  Many Americans felt they rose above all others.  When comparing Germany, they had to fight to become a leading power and after that success, of course there would also be a special feeling that they would have gained.  

However, this question can be interpreted a few different ways.  Another thought would be the ways that both American and Nazi Germans separated people into social classes.  Germans who were of a “pure bread” (i.e. Blond hair, blue eyes) were of the elite class.  Jews, Gypsies, & blacks were looked upon and subhuman.  The same separation happens in America even today. Of course there are laws in place to protect all races, but the mentality of many people are still close-minded to this separation of races. Americans were not as outward with these feelings as Nazi Germany, but they existed still.

=========yorg=========
===from:Velkys Layne
===date:Tue Oct 29 10:22:05 2002
===subject:Episode 9
===message:I had a very difficult time writing this discussion.  Anytime the topic of race is up for discussion, it is hard to speak of it without offending anyone.  I understood the questions as asking me to compare the views of Nazi Germans, and what made them special, to Americans.  Americans consist of a very large group of peoples from every ethnic background imaginable.  Personally, I dont think americans, as a group, shared any of the views of racial superiority with Nazi Germans.  The only "americans" I can think of that shared views about superiority about their race were certain americans of caucasian or european background.  Because of these views, many persons who were later considered to be americans were kidnapped, enslaved, tortured, mamed, and murdered.  When I use the term "persons" I mean people of non-white background like native, african, and even mexican americans.  Nazi Germans were a very proud people because of these "special" views they held about their race.  The United States is full of americans who are very proud to say they are from this country because of its opportunities, freedoms, and so-called acceptance and tolerance of others.  I suppose they did have some things in common if you really think about.  
=========yorg=========
===from:Ebony Mulero
===date:Tue Oct 29 10:50:44 2002
===subject:Master Race
===message:In the past American ideals of what made them special were similar to Germany's but in some cases not as bad. For a long time in the United States white people thought that they were superior to blacks, native americans, hipanics, and anyone else who was not "pure" white. A group known as the Ku Klux Klan (KKK) made it very known of their feelings that only the white race was the better race. They did things from marching with burning crosses to even brutally killing non-whites. Americans overall feel superior to other countries because of our technology, medical, and ecomonic advances over others. Americans are different from the Nazis because even though some whites were killing others, it was not the whole country that feel more superior then others. I wonder back then how could people talk about what Hitler did when the same thing was happening on our homefront? Even though in the past years we have gotten better and racial prejudice and discrimination are decreasing. There is no inferior or superior race in this world and it's about time that people began to recognize that. If your name is not GOD then you are a regular person just like everyone trying to make it in this rapidly growing world.
=========yorg=========
===from:Kathleen Gibbs
===date:Tue Oct 29 11:16:52 2002
===subject:Episode 9- Master Race ?
===message:Adolph  Hitler and the Nazi Party did not plan to enslave the Jewish population but they did plan to exterminate them from the face of the earth. Adolph Hitler was a genius at propaganda ,and he used this skill to convince the German people that their ancestors were the original race of  superior beings who were meant to be the rulers of the world. He put the blame for the German people having fallen short of what was their supposed destiny at the foot of the Jewish population . Timing is everything so they say, and the time was right in Germany for this type of propaganda to gain the  support of a desperate people. 	
Once this type of mass hysteria is used to focus and unite a nation’s people against a different factor of fellow citizens of a nation, then the  unspeakable cruelty  that man is capable of inflicting on another man is unleashed and it takes on a life of its own. The Jewish people of Germany even though they were German citizens and the Jewish people in all other nations  that were conquered by the Germans were robbed of their families and worldly possessions, they were segregated from the rest of society, they were loaded into box cars and sent to concentration camps where some were murdered on their arrival, they were used as laborers, they were used as guinea pigs for medical experiments, and  they were lined up in front of a great big hole in the ground and gunned  down because the ultimate goal was the extinction of the Jewish people. 
I do not think that the American people as a whole see themselves as the supposed rulers of the world. We cannot claim to be the original race of superior beings because this country is a combination of all peoples from all nations around the world . Our uniqueness  as  a nation has been the ability of so many people in so large a nation to rise above our petty differences and co-operate with one another to  work for what is best for the nation as a whole and what is best for the nation as a whole is our continued freedom.  Yes , there have been periods in our history where people were enslaved , where people were  persecuted  for their differences, and where  barriers were erected to deprive some groups of people from enjoying all the freedom guaranteed to an individual by our Constitution. These are not periods to be proud of because these periods in our history contradicted all of the ideals this nation was built on. The American people as a whole as far as I know have never supported the extinction of any race of  people from the face of the earth. I have to add an exception to the last sentence because in truth maybe for  one moment in time on September 11, 2001 this thought of the extinction of a whole race of people  did cross the minds of the American people. As they say timing is everything. 

=========yorg=========
===from:Gena Anderberg
===date:Tue Oct 29 11:36:54 2002
===subject:Master Race- different idea
===message:In my psyc1101 class we just had to watch the movie "Gattaca". If you have never seen the movie it is about being able to pick your own genes or even as in this movie change yourself to something better. The basic idea here is if you can pick the genes for your children, decide everything about them, then they will be superior. As this would elimate desease which is alot of the basis for this type of argue, is it also like trying to make a superior race? Who decides what is superior. Hitler decided the Arian race was superior, but who gave him that right? Who gives government the right to decide what is superior? Hitler tryed to play God. Is that what we are trying to do as we develope Genetic Engerneering? 
=========yorg=========
===from:Rachel Harper
===date:Tue Oct 29 13:47:23 2002
===subject:Master Race
===message:I feel that Americans do believe that they were more special than others because of their way of life. Americans in general do tend to live better lives and have more freedom than people in most in countries in the world. Now most Germans dealt with the belief that they were superior to every one else in the world. Even though we do have people in America who share those same beliefs. Most of the the country do not share those beliefs as most of the population of Germany did. Even today less and less people are stating to live in nations that are filled with diversity and the idea of a master race is being believed by fewer people. But the Darwin theory of a superior race still lives in the minds of many.
=========yorg=========
===from:Stephenie Buice
===date:Tue Oct 29 13:54:47 2002
===subject:Episode 9
===message:I think that Americans are very dissimiliar to Nazi Germans, but I also believe that some American's actions have the same undertones that Hilter instilled in Germany.  Today's society is based on beauty and fitness.  Posted over every television station and movie screen are images of the "perfect" human.  Hilter desired a "fit and healthy" Germany.  Americans that are overweight or have a handicap are not exterminated, but they are seen as very different than the "norm."  This is were there is a gray line for me.  While Americans would never kill off the mentally ill or disabled, these people are an outcast in our society.  They are viewed as "different" and not like the "ideal" American (or German). So, to me the views of Americans are similiar to what Hilter had in mind, but we would never try to exterminate an entire race just to have a perfect America.  African Americans and Native Americans were tremendously insulted and hurt by what white Americans thought was the ideal just because of the color of their skin (just as the Germans disliked anyone with a different eye color).  Even though all races have equal opportunities today, there is much racism that still exists.  There are still the dumb "southern rednecks" discriminating against black Americans, some black Americans think that the whites owe them something for the many years of torture seen by their ancestors and therefore do not like white people, there is rivalry between Latin Americans, Native Americans, and now Muslim Americans.  There is discrimination between homosexuals and heterosexuals, men and women, and the rich and poor.  Maybe one day everyone will grow up and realize that we are of the same race -- the human race.
=========yorg=========
===from:Mark Prosper
===date:Tue Oct 29 19:49:21 2002
===subject:Master Race
===message:This is my personal opinion, but to me it is all propaganda technique.  The American ideas are similar to those of the Germans in that aspect alone.  The Germans were way more extreme by killing those who did not fit the mold.  But instilling pride in the population to be a part of a particular country creates situations between people and conflicts while the undertakings of the government are suppressed.  Harmful indeed.  Most people aren't born with this type of thinking.  It is all sold to us in a stategic manner.  How else could Hitler get away with slaughtering millions of people?  So in closing ideas such as the American dream and German's master race are all subliminal propaganda.
=========yorg=========
===from:Jason Odom
===date:Tue Oct 29 21:25:54 2002
===subject:Post 1
===message:America has a very diverse population and most of us have been brought up to accept different races. Germans had a belief that "true" Germans were the leading race. All Americans are supposed to be treated equal and this is the complete opposite of what Germans thought. The hatred of Jews by the Germans parallels the hatred of blacks by some Americans. Both the Jews and the Blacks were persecuted because of their appearance.
=========yorg=========
===from:Angela Taylor
===date:Tue Oct 29 21:46:21 2002
===subject:Master Race
===message:Some Americans believe that their race is superior to others and yes this is just how the Germans think of their race.  This thinking in American has went so far as to expand within America and divide the races into color and/or class. Some Americans believe that if you live in a trailer park and drive a Pinto that you are trash but if you live in Buckhead and drive a Mercedes then you have class. Some American groups like the KKK believe that if you are not white then you are trash. This thinking has been very destructive for America. Lots of lives have been lost over the superiority of one race over another. Everyone wants to be over someone else but it would be a much better world if people would just accept everyone else based on nothing but the person.
=========yorg=========
===from:Jim Heinzel
===date:Tue Oct 29 22:21:44 2002
===subject:HIST1110
===message:Of course we as Americans are special. But Russians are special people as well. So are the Japanese, Brazilians, Israelies, Czechs, Ethiopians and every other nationality in the world. Each country and nation offers a unique blend of culture and society to our world that can be appreciated by all. Our world is made up of people of different races and ethnic backgrounds. All of these people are special in their own way and they make valuable contributions to the balance of the planet. If all of these people did not have a special purpose, then God would not have made them all. Everyone should believe that he or she is a special part of humanity and that all others are equally special. Problems arise when people believe that certain groups of people are inferior to themselves simply based on their race, culture, religion, ethnic background, etc. The German people as a whole were led into a false belief of superiority by Hitler and as a result millions of people were killed or had their lives ruined. Unfortunately we have had and still have some people in this country that are infected with this belief of superiority. Harm has come to various groups of people in our country because of this flawed thinking. Of course slavery and the oppression of black people on through the last century is the most predominate example of harm caused to a race of people in this country. Asian people and people of other races have suffered as well. Thank goodness our society as a whole has not been led down the road of these ideas. We may not always agree with what another person believes or how he lives, but we should never believe ourselves to be simply born superior to another.
=========yorg=========
===from:Shameeka Beckett
===date:Tue Oct 29 22:51:04 2002
===subject:Master Race
===message:Hitler brainwashed the German people and had them believing that they were superior to everyone.  He tried to create a race of blond-haired, blue-eyed individuals and wanted them to reign supreme in everything they did.  I think there are some Ameicans that feel the same way.  When the Americans first came to this land, they disposed of millions of Native Indians.  I believe that the Americans back then were just like Hitler.  There are several different races in America that would consider themselves to be special in their own ways.  I don't think it's harmful to feel this way about your own ethnic group.  I feel it is harmful when people go about killing, segregating or expulsing a group because of race.
=========yorg=========
