===from:Debbie Whiteman
===date:Tue Nov 12  8:48:48 2002
===subject:Brave New World
===message:Soviet citizens thought that the United States was a violent racist society, where the people were oppressed by their captitalist system.  United States citizens thought that the Soviet citizens were oppressed and exploited by their government.  Public relations were the same in both countries, however, the United States spoke the truth.  We acknowledged our short comings, and in the final outcome were proved correct.  Each government tried to illustrate the best of each system by painting the other as a "mortal" enemy.
=========yorg=========
===from:Gena
===date:Wed Nov 13  9:25:22 2002
===subject:Brave New World
===message:The US thought that the soviets lived a dismal life. Of course as being from a Democratic Country we are going to think that anything any different is not good.  The people of the Soviet Union had no choice in their lives because of the communist rule. Life was bad there for the common people. Of course on both sides of the fence each government was using propaganda to make the other country look bad. The US wanted us to think life was very bad in the Soviet Union so we would be behind them in whatever actions they had to take against Communism. The Soviet Union wanted it’s people to think we where and evil nation and that Democracy was bad so it would have complete control over it’s people. They did not want any internal uprising as they where of course trying to conquer all the other small Communist Countries around them. The Soviet Union wanted to be the biggest power in Europe and control all the smaller communist counties. If the countries did not conform they would invade them and take them over. This was seen in 1956 when the Soviet Union invaded Hungary.  During the Cuban Missile  Crisis, the US of course had complete Media Coverage of  the 13 day stand off between the Soviet Union and the United States. The US portrayed the Soviets as evil people that would destroy the world. I am sure the Soviets in turn portrayed us in the same way.  As we all know the media plays a big part in how things look. They often make things seem a lot worse then they really are. Sometimes though they even don’t know what is really going on or how bad things are. In this case though I am not sure if everyone really knew how close things where to World War III.  It could have as easily been underplayed as it was overplayed.

=========yorg=========
===from:Kristin Crook
===email:laydbug268@aol.com
===institution:Hist 1110
===date:Wed Nov 13 20:58:27 2002
===subject:episode 11-initial discussion
===message:It was so interesting to see the power of propaganda in the film when the meeting on the Elbe was depicted in two drastically different ways. The episode opened giving the viewer the same feelings of peace that were felt by the actual Americans and soviets directly following World War Two. The soldiers were so excited that they hugging each other in that original true to life footage of the actual meeting on the Elbe when the East and the West came together to celebrate the victory that they had achieved as one.  Later once the tensions had flared up, the Soviets created a feature film that was thought to depict the meeting on the Elbe. In the film American generals were exhibited as bloodthirsty and bent on the domination of Europe. Such Soviet officers who experienced the meeting were even forbidden to speak of the truth. 
	The Soviets also felt the American culture was evil. They saw Jazz music as vile and American art as immoral and demented. Soviets who were caught showing an interest in Louie Armstrong or Impressionist art were condemned and charged as idolaters of the west.
	The U.S. saw the Soviets as a wicked people. They also saw them as an inferior people.  At the end of the Second World War, right before the start of the Cold War, the alliance of three was seen as equals.  Later propaganda depicted Stalin as “Uncle Joe”, a scheming despot forcing whole countries into submission.  Also the blockade of Western Germany only backed up the beliefs that the Russians were evil. America saw itself as the hero who overcame the evil schemes to starve West Germany into submission.  Operation Vittles also confirmed the people of West Germany’s ideas about how good the Americans were. 
	Its clear to see that both sides utilized whatever tactics they had. Both used political cartoons, media including feature films and newspaper headlines.  Each side managed to demonize the other.  Also manipulative language played a very significant role in controlling the mind of their citizens. 
	American propaganda appealed to the individual family. The government launched such public announcements as those that use horrifying images that were intended to bring panic to families while whipping up some hatred towards the evil communists.  Soviets appealed to the hopes and fears of their people as well, but in a much different way. Stalin was idolized and all of their many hopes and fears were focused on this one man. So, the Soviet people were manipulated by becoming an army or entourage all for the glory of stalin. 

=========yorg=========
===from:Doug Purnell
===email:csu10138@mail.claytonstate.net
===date:Sun Nov 17 11:21:41 2002
===subject:Brave New World Comment
===message:Soviet society had relaxed a little after Stalin’s death. In the next few years there was what some called a “thaw.” Marginally greater freedom of expression was allowed to writers and artists, while the regime appeared to be a little more concerned about its appearance in the eyes of the world over such matters as its treatment of Jews. It seems clear only that after Stalin’s death, particularly during the era of Khrushchev’s ascendancy, the party had re-emerged as a much more independent factor in Russian life. This makes it now seem odd that some came to think that the United States and Soviet Russia were growing more and more alike, and that this would help to make Russian policy less menacing. This theory gave a distorted emphasis to an undoubted truth: the Soviet Union was a developed economy. In the 1960’s some still thought socialism a plausible road to modernization because of that. However, it was often overlooked that the Soviet economy was also inefficient and distorted. Soviet industrial growth, though faster than that of the United States at least in the 50’s, has long been overwhelmingly a matter of heavy manufacture. The private consumer in the Soviet Union remained poor by comparison with the American, and would have been even more visibly so had it not been for a costly system of subsidies. Russian agriculture, which had once fed the cities of Central Europe and paid for the industrialization of the tsarist era, had been a continuing failure; paradoxically, the Soviet Union often had to buy American grain. Yet, the USSR, in comparison with many undeveloped countries, was undoubtedly rich. In spite of the obvious disparity between them as consumer societies, to the poor the USA and USSR sometimes looked alike. Many Soviet citizens, too, were more aware of the contrast between their stricken and impoverished country in the 1940’s with one much less so in the 1960’s, than of comparison with the United States. Moreover, the contest of the two systems was not always one-sided. Soviet investment in education, for example, was thought to have achieved literacy rates as good as, and even slightly higher at times, than the American. Yet, there had been a long legacy of backwardness and disruption to eliminate in the Soviet Union. Only in 1952 had real wages in Russia even got back to their 1928 level. 
=========yorg=========
===from:Gena Anderberg
===date:Wed Nov 20  4:48:11 2002
===subject:Guantanamo Bay, Cuba.  Something we all need to read!
===message:Last night I was sitting here at my computer and listening to World News Tonight with Peter Jennings. What I saw really has upset me, and made me mad. I thought I should post about it in this class. 

Tonight, a report on what it's like to be a prisoner of the U.S. military in the age of terrorism. We have been looking at interviews with a man who was imprisoned by the United States at Guantanamo Bay, Cuba, and then released. The prisoners spent much of their time in cages before being moved to proper cells. They received just 10 minutes for meals, and were beaten for calling one another to prayer. The men who were released without being charged have yet to receive compensation or an apology. 

(http://more.abcnews.go.com/sections/wnt/worldnewstonight/jennings_journal_feature.html)
The man also said that they would put them in a small cubical for isolation with cold air pumped in. Since they where not used to any form of air conditioning, this was torture to them. They where also taken 2 times a week, chained to be interrigated. They showed this man back home with his wife and 9 little children.

(http://more.abcnews.go.com/sections/us/dailynews/detainees021108.html)

(http://artbell.com/letters88.html)
These are some pictures of them being transported.

Ok You know I know we are mad about what happened to our country, but is this right? We are acting no better then Hitler did when he persecuted the Jews. What gives America the right to do this? Because we are the US and we think we can do anything we want? And it seems to me that they are more worried about how these pictures got released then how these people are being treated. Yes I know we are all mad, but still does that gives us the right to treat people like this? You can say well look at what they do to us. They would treat us worse then this if we where captured. I am sure of that too but still do 2 wrongs make a right? Aren't we doing to other people just what we are fighting against, what we fought for in WWII?
Please post your comments if you have time.
=========yorg=========
===from:Velkys Layne
===date:Sat Nov 23 21:13:33 2002
===subject:Brave New World
===message:During the Cold War soviet citizens had very limited if any information about the lives of people outside the socialist bloc.  The information the soviet citizens did receive was all propaganda filtered into society by the Communist government.  The people of the Socialist bloc understood the people of the United States lived under a capitalist economic system.  The average citizen in the Soviet Union believed capitalism was a greed-driven form of economics.  Capitalism consisted of citizens who were extremely wealthy or desperately poor.  To the soviets, capitalism had no moderate standard of living.  The poor were exploited and oppressed by those who were successful at capitalism.  In the soviet propaganda films, Americans were depicted as lacking culture, being racist, and greedy.  The U.S. government was the major source of information about the Soviet Union to its citizens.  Communism represented a threat to all of the rights and freedoms Americans were so proud of.  In the propaganda released by the U.S. about the Soviet Union communism was seen as an evil virus that had to be stopped from spreading itself to other nations.  Both governments used the same sort of tactics to influence the views of its citizens regarding the other nations economic and social policies.  Each government played on the fears of its citizens in hopes to have the support of the general public during the cold war.  
=========yorg=========
===from:Eric Klausner
===date:Mon Nov 25  6:13:05 2002
===subject:American and Soviet Propaganda
===message:The Soviet people were painted a picture of capitalism being a world of impoverished losers with high crime and many starving homeless people.

The American people thought the Soviet people lived in a 1984 environment where Big Brother watched over everything.  One could not even whisper a bad thing if one wanted to avoid Siberia.  

My dad told me a story that he used to use when he taught HS social studies in the Bronx about the dual track meets between the USSR and the USA in the 1960s.  The American men’s team would win and the Soviet women’s team would win.  The Americans insisted that there were no combined score as they won one meet and the Soviets won one meet.  The Soviets insisted on a combined score as they would score higher and win the event.  Thus, a simple track meet turned into a Cold War squabble between the merits of capitalism vs. that of Communism.  On a humorous propaganda note Pravda would report the men’s score.  The Soviets came in second while the US came in next to last.  

Bottom line is both sides used propaganda as a means to “sell” their message to their citizens and perhaps as important to persuade third world nations to buy the idea that the enemy system failed in comparison.

=========yorg=========
===from:Wendy Abdo
===date:Mon Nov 25 15:46:48 2002
===subject:Brave New World
===message:The Soviets thought that Americans were poor, starving, and mired in immorality.  Information about the West was totally controlled inside this Communist country, and they believed what their leaders told them.  It was a massive brainwashing effort on the part of “Papa Stalin.”  In the United States, citizens became paranoid of the communist treat. Senator McCarthy headed a massive witch hunt to root out any and all communists within the country (many of which were innocent law-abiding citizens). Both sides used their own propaganda tactics to promote their interests.  Each side was motivated primarily by fear.  Wouldn't you agree?  For instance, the Soviets were constantly being reminded of the great patriotic war and were warned that if they didn’t defend themselves from the West, they would be attacked and subjugated by their enemy.  Likewise, Americans were warned that if they didn’t root out any and all traces of communism within their country, they would also be subjugated by the enemy.  Literature and movies were produced encouraging this mindset and this just made matters worse between the two big nations.  Consequently, each country built up an enormous arsenal of missiles and warheads and were in a constant catch-up game to outstrip the other one.
=========yorg=========
===from:Tonya Harris
===email:teh2001@bellsouth.net
===date:Sat Nov 30 11:47:38 2002
===subject:Brave New World
===message:I believe that Soviet citizens felt a sense of envy when viewing life in the United States.  The U.S. way of life was free and prosperous in their eyes and so far advanced from the Soviets.  Many Soviets listened to American radio stations and tried to envision that way of life.   Although this was a dream for many Soviet peasants, this was an unreachable dream because of the communistic hold by the Soviet government.  The citizens of the United States saw the Soviet life as imprisoned.  The lower class citizens were slaves of their own country with no say in how life should be.  Both countries painted to their own citizens a picture of prosperous life that only the upper elites actually experienced day-to-day. They also painted bad pictures – using propaganda - of the other country as a way to enhance the light shining on their own country. The Soviet nations were dealing with many hardships in efforts to catch up with the United States in areas such as transportation, agriculture, and various industries.  There was growing tension between the two countries because the U.S., while trying to maintain its Superpower label, also wanted peace with the Soviets, while the Soviet Union was constantly challenging the U.S. stating they were not far behind.  This was evident from the debate between President Nixon and Khrushchev in 1959 where Khrushchev argued that the Soviet Union would eventually take over the United States.
=========yorg=========
===from:Janna Smith
===date:Sat Nov 30 23:01:45 2002
===subject:Episode 11
===message:After viewing Episode 11, it seemed as if Soviet Citizens believed Americans were power hungry individuals who wanted to end all forms of communism by any means necessary.  Many Americans believed that since Soviets valued communism that they were an unlawful group of people who should not continue to spread the "evils" of communism.  Both the US and the Soviet Union used propoganda in the form of movies, television, and radio to convince their people that the other nation was in the wrong.  In addition, the Soviet Union contained its citizens from the propoganda of other nations by restraining them from traveling outside of the USSR's borders.

=========yorg=========
===from:Shameeka Beckett
===date:Sun Dec  1 16:57:05 2002
===subject:Brave New World
===message:After WWII ended, the Soviet troops and the American soldiers embraced each other.  As the Cold War gradually developed, each side began to distrust and despise one another.  The basis of this evolutionary change was fear.  The U.S. began to fear that the Soviet Union's will to expand would contest its world dominance.  The U.S. began to detest communism so much it wanted to rid itself of all people that were for communism, using propaganda as its tactic.  The Soviets were against capitalism and all the U.S. stood for. They also used propaganda as a means of slander and dramatized in films.  One particular film "Meeting on the Elbe" depicted the American General as being "blood thirsty."  Jazz music was said to be evil and was banned. People listening to the music were known as idolators of the west and could be tried.  Both countries were pitted against each other, it was the communist east against the capitalist west.  Americans feared that the Soviet's power would undermine their own and to reassure its people they would make threats of massive nuclear retaliation for any Soviet transgressions.  However, the Soviets would come to even up the arms race when they exploded their own hydrogen bomb, months after the U.S.  Both governments tried to appeal to the hopes and fears of their citizens by using propaganda and making threats, but there was no denying that there were two superpowers.    
=========yorg=========
===from:Ebony Mulero
===date:Tue Dec  3 12:04:40 2002
===subject:Brave New World
===message:The Soviet people thought the people of the United States were greedy, racists, violent, and self-absorbed. They felt the people were oppressed by the capitalist system. The people of the United States thought that the Soviets lived a depressing life, where they basically had no say for themselves. The US thought the Soviets were demoralized and exploited by their government. Each government tried to illustrate the greatness of each system by painting the other as a living enemy. They did this by using propaganda and the media to make the other look more corrupt. The both used cartoons, movies, the newspaper, etc. to lure the people into thinking one way, which was effective. Even though they both preceived the same things about one another they targeted the people two diferent ways. The US's propaganda targeted the individual families, they used horrific images that were intended to unnerve the families and also encourage hatred toward the communists people. The Soviets targeted the emotional fears, hopes, and dreams of their people, also. Stalin was the people's idol and was like a father to many of the children. The people wanted to live up to his standards and be everything that he wanted them to be, even if it meant hating the US.   
=========yorg=========
===from:Keri Zink
===date:Wed Dec  4 15:13:04 2002
===subject:Brave New World
===message:This discussion will be difficult for me to answer because this subject is NOT interesting to me.  The Soviet and US citizens were both, in my opinion, exploited by each other’s country.  Both countries said a lot of false statements about the other, even though there might have been some truth to their beliefs of one another.  The tactics used by the governments were similar in the press and comics that were printed by their newspapers, pamphlets, etc.  Both countries were basically competing for power.  Power for weapons, money, etc. etc.  I am not a big fan of politics so this subject has not interest me enough to be able to discuss an in-depth response.  Both Govn’ts tried to appeal to their citizens by reassuring them that their country was not in danger.  They tried to appeal to the hopes by standing strong of their beliefs of their leaders.  As an example, we believe in our government when times get as rough as it did after September 11th. 
=========yorg=========
===from:Robert Jones
===date:Fri Dec  6 15:58:24 2002
===subject:Brave New World
===message:After Churchill’s speech in 1946, America’s eyes were opened to the Soviet Union as an political and military aggressor. The propaganda wheels began to spin initially in a political nature as communism and capitalism are natural rivals. Americans became somewhat obsessed with routing out any communist factions in the United States dubbing them traitors and accusing them of acts of treason. The Soviet government which - unlike the United States - regulated the media, Capitalism was demonized to such a degree that  the Soviet people began to posses disdain for Americans in general. It seems to me that it there was almost an underlined sense of jealousy that fueled Soviet impressions of Americans. They were evidentially appalled  to see how Americans lived when they saw U.S. exhibits at international conventions (Of course, without the clearance to travel abroad, the only conventions the Soviet people were allowed to attend were those in  the Soviet Union). As different as the "ends" would eventually be for these two countries, the "means" were somewhat similar. Both governments did a thorough job in painting the other as a cold-blooded enemy. And with that, the toe-hold for the entire cold-war was established. The stalemate that followed was sustained by the idea instilled in the average citizen that the enemy posed a constant threat. Even to this day, Americans think of "communism" as America’s inherent enemy as if the rivalry has existed since the dawn of time. Certainly it has not. For less than one generation had passed since Soviet and American troops had joyfully met in Berlin to defeat fascism. That time-frame, in itself, is a testament of how different international relations became after the Atomic Bomb was introduced. Negotiation is handled a little differently when the guy on the other end of the phone has his hand on the button.   
=========yorg=========
===from:Mark Ehrlich
===date:Sat Dec  7 19:36:36 2002
===subject:hist 1110-11
===message:Soviet's impressions of the west was that we were evil.  The Soviet government used propagada and also banned certain things such as jazz music and art because they said these items are what made the west so evil.  The art was said to depict imperailism, and depicted killing woman and children.  They always showed the Americans as evil capitalist.  The Soviet government controlled everything that their people could read or listen to.  They was told that capitalism was terrible and the people was exploitted.  The Soviets were told that they were the envy of the world.  The American government done simliar things as well.  The soviets were depicted as evil.  Both governments made films show how evil one another is and bloodthirsty each was.  The Soviets used a tactic of shutting down all the city of Berlin in order for the west to leave and said it was to defend against the west.  The Americans then airlfted supplies to Berlin in order for survival.  Americans used a radio station where the Soviets could pick up to tell them the truth about communism.  The US media shown the Korean war as to stop communism, while Soviets shown the war as the US invading a peaceful Korea for no apparent reason.  Newspapers on both sides used cartoon characters to show evil characters of each side.       
=========yorg=========
===from:Mark Prosper
===date:Sun Dec  8 23:35:27 2002
===subject:Brave New World
===message:To the soviet citizens, life in the United States was driven by greed and a mentality of world dominance.  This portrait was painted of the U.S. along with the help of the communist controlled media.  Similarly in the U.S., communist views and ideas were rejected and were considered a threat to the freedom that the U.S. provided.  These negative views were somewhat induced in part by the respective propaganda techniques that each nation employed to influence the public opinion.  Soviets were taught and believed that capitalism is harmful and conflict with the capitalistic enemy is justified in the name of preserving the imperialist system.  Conversely, in America the communist Soviets had to be dealt with in order to preserve freedom and the American way of life.
=========yorg=========
===from:Yvelle Maurice
===date:Mon Dec  9  8:44:38 2002
===subject:Brave New World
===message:Soviets citizens believed that U.S. was imperialist because they wanted to control or influence the weaker nations or peoples.  And U.S. citizens believed that under communist government that the Soviet citizens had no say in a lot of things, especially the freedom to express their opinions.  Both countries feared each other.  U.S. feared that the Soviets would spread communism through out Europe, and Soviet feared that U.S. would abolish the ideologies of communism.  They both used films, newspaper, and radio to show the citizens why their government system is the best for their country.
=========yorg=========
===from:Jason Odom
===date:Tue Dec 10 11:01:18 2002
===subject:Brave New World
===message:During the Cold War the Soviets’ did not have much information about life in the U.S., except what they learned through propaganda. They were aware of the Capitalist government that existed in the U.S and thought of the U.S. as a greedy nation. The U.S. thought the Soviets lived desolate lives because they were under Communist rule. Certainly, propaganda played a role in influencing the viewpoints of both U.S. and Soviet citizens. Propaganda led U.S. citizens to believe that Soviets and Communism was based in evil. They thought if Communism was allowed to spread that it would turn the world into an evil empire. Propaganda led Soviet citizens to believe the U.S. was full of greedy people and democracy oppressed the poor citizens. Both countries used propaganda via television and radio to spread negative information about the other country.
=========yorg=========
===from:Rachel Harper
===date:Tue Dec 10 13:41:27 2002
===subject:Brave New World
===message:Well the citizens of the Soviet Union view the U.S. as this evil country trying to dominant the world. The citizens of the U.S. states view the Soviet Union the same way. Through the media citizens of both countries feared each others governments, but tried to not let that influence of each others governments spread across the world.
=========yorg=========
===from:Heidi Sprinkles
===date:Tue Dec 10 18:48:56 2002
===subject:Hist 1110
===message:People in the Soviet Union were taught that the U.S. were all full of lies and were evil.  On the other hand after the expedition the Soviet Union allowed the U.S. to have the people of the Soviet Union couldn't believe the wonderful things the people of the U.S. had.  They were already familiar with America's music as it was broadcast into the Soviet Union to try to fight some of the bad propaganda that the Soviet Union was distributing.  The Soviet's weren't the only ones who used negative propaganda.  The U.S. also proclaimed that the Soviets were liars and overall evil.  As the Cold War drug on the Soviet Union tried to show their "good side"  the propaganda was not so much negative againist the U.S. but more positive about their own government and what a wonderful life they were able to provide.  
=========yorg=========
===from:Jim Heinzel
===date:Tue Dec 10 18:52:52 2002
===subject:Brave New World
===message:During the cold war, people on both sides (Soviet Union and United States) distrusted the other side. Each side felt the other was bent on world domination. They each thought their ideas and way of life was the best and they feared the other was trying to destroy what they had. The governments tried to use anything negative from the other side to convience their people the other side was evil. Sometimes just plain lies were manufactured about the other on each side. I believe we had a more correct view of the Soviet Union than they had of us because we were more free to information from the outside world than the citizens of that country. 
=========yorg=========
===from:Stephenie Buice
===date:Tue Dec 10 20:44:17 2002
===subject:Brave New World
===message:The Soviet government protrayted the United States as being an imperialstic country.  They believed that the U.S. was after world control and that the American way was the wrong way.  The United States also protrayed the worst about the Soviet Union.  The U.S. used television, radios and movies to make Americans think that the Soviets were targeting the people and their homes.  Soviets also used the same propaganda to show the "bad" side of America.  They showed our art (flashy dresses), our sports (boxing at its worst), and our animals receiving manicures while unemployed humans had no food.  They tried to portray Americans as having indecent morals.  Both countries tried to demonize one another through propaganda.  Each blamed the other country for the war on Korea.  Brave New World does not give a good description for the way of life during the Cold War.  There was no bravery because each accused the others for different venues of activities.  This may have been a different way of life, as opposed to life before the war, but the same tactics were used.  Slandering through propaganda has been around for many decades, so what is so "new" about that?  The Soviet Union tried to ease the fears of their people by telling them that communism was going to one day dominate the world.  Americans eased the fear of their people by telling them that they were a great power that could not be defeated.  Luckily for us, the Soviet Union was wrong.
=========yorg=========
===from:Melonie Broner
===date:Tue Dec 10 22:33:47 2002
===subject:Brave New World
===message:I believe that some Soviets, those that were forced into submission, thought the United States was a wonderful and free nation, but the teachings of the government made many more believe that the United States was an evil place. The United States did not believe in Communism, so any country that was under a dictatorship, in their opinion, was not as developed as the US. So, I do not believe that there were many US citizens awaiting a chance to move the the Soviet Union. Most US citizens believed that the Soviet citizens lived a dismal and depressing life. To them, having someone control your every move and thought, was horrible. Both countries tried to make their citizens believe that the other country was the evil one. The Soviets were made to believe that the Americans were the ones who wanted to take control of the world, while the American government was telling their citizens that the Soviets were the ones wanting total control. Each government made it seem like it was their duty to save the world from the other's domination. Both governments instilled their beliefs into their citizens through the use of mass media (i.e., television, radio, and newspapers).  
=========yorg=========
===from:Kathleen Gibbs
===date:Tue Dec 10 22:41:31 2002
===subject:Brave New World
===message:The Soviet citizens thought that our life in the United States was one of  self serving, decadence . The people who were in  the have group lived life at a fast and loose pace, always excessive in their behavior in every activity they took part in. The people who were in the have not group had to stand in long lines just to get something to eat just like in the time of the depression years, actually it was newsreels of the soup lines during the depression that the Soviets were shown. Our leaders were depicted as war mongering , uncouth, blood thirsty, manipulative, power hungry oafs. The U.S. citizens thought that life in the Soviet Union was dreary, dull, full of hardship, restricted, suspicious and fearful of everyone, and just plain old not a life you would want to live had you ever experienced real life in the United States. Both governments used the news media through newspapers, television and radio to influence the thoughts of their citizens. Movies were also used as a tool to  spread more propaganda. Each government used the threat of the possible use of nuclear arms as a weapon against one another to strike fear in the publics hearts and to make each of us distrust the other. The thought of living with no freedom as the Russians were living under Stalin and the thought that all your efforts would go into a combined pot to be doled out equally to each person was not a life style that most Americans wanted. The Russian people thought their world would eventually evolve to the point where each person would share equally in their combined efforts, but they forgot one thing, the people at the top of the ladder usually end up with the best of everything while the ones on the bottom get what is left over.
=========yorg=========
