===from:David Paulson
===date:Wed Jul 16 17:46:59 2003
===subject:Capitalism
===message:I find it hard to understand this man’s point of view mostly because I have never been around Muslims and don’t know what the teachings of Islam are. The best way I know to reference it is to associate it with my own religious ideas, Christianity. In reading the speech he gave, on pg 1123, I would assume he was against progress. I guess he is trying to keep the Islam religion from changing with the times by saying that if God wanted his people to change he would have said so in his teachings. To compare it with the teachings I understand it would be like saying that the Old Testament is the only way to live and anything not in the Old Testament is against God. The reasons he is against America and considers us to be “Great Satan” is because our beliefs are different than his and our way of life is based on tolerance of other peoples beliefs.    
<p>
<br>
In Ayatollah Khomeini speech about America being the “number-one enemy of the deprived and oppressed people” I think he talking about Capitalism. The fact that America is based on the pursuit of money and not religious pursuits. When business go into a foreign county they goes there to make money for the owner or owners of the company. They do not go there to change religious preferences or ideas but when people of other country’s see the benefits that tolerance and capitalism bring it is bound to change a few ideas.

=========yorg=========
===from:Tim Fitzgerald
===date:Fri Jul 18  6:27:20 2003
===subject:US vs. Islam
===message:Khommeini was an Islamic fundamentalist leader. Many practices of Islam were in direct conflict with the imported cultural practices of the US. Those conflicting practices are considered crimes by Islamic fundamentalists. Khomeini's group took over Iran, a country whose previous leader, had been propped up by the US for years in order to promote US national interests. With support from the US, Iran had become secular in nature and had adopted more Western cultural practices than any Islamic country in the world. This change occurred only as result of US interests. Over twenty years later, two Gulf Wars, and the 911 terrorism have given the average American only a slightly clearer perception of that part of the world where almost no true understanding existed previously. The average American just knew that the area was oil rich and important for national interests.
<p>
<br>
The Islamic world views US presence and intervention as an unwanted intrusion into their lives and culture. The US is perceived as an ally of Israel. The Islamic world views Israel as an enemy and any ally of Israel is an enemy of Islam, also. Couple that with US intrusions, over the years, into the affairs of Egypt, Iran, Iraq, Lebanon, etc. for the purpose of promoting US national interests, then the perception of the US by the average Arab could be nothing less than negative. Mix the extremist Islamic terrorist and fanatic into the equation along with the duplicity of various Arab governments feigning friendship with the US while sanctioning terror against US citizens, then the "oil mixing with water" relationship between Islam and the US comes into much clearer focus.
<p>
Another phenomena in the world today with the US as the only remaining "superpower" is that the US and it's citizens have become almost universally despised and hated around the world. Many times this animosity is not entirely rational or justified. It seems as if we are hated for the power, national wealth and freedoms that we enjoy as Americans.
=========yorg=========
===from:Anthony Shealey
===date:Fri Jul 18 10:38:48 2003
===subject:US vs Islam
===message:I think the reason why the relationship is troubled because of the history of the United States imposing itself on other nations. The US has a history of taking war to new heights and doing evil things to indegenous people in other countries. An example is when the US dropped Atomic Bombs on Japan and killed an injured so many people and to this day people are still giving birth to deformed children who parent parents were exposed to radiation. THe US is also known to spread their religion where it is not welcomed in other countries where their religion has always been their custom. The islamic know quite well the history of imperialism.
=========yorg=========
===from:Shemika Williams
===date:Fri Jul 18 22:19:32 2003
===subject:US vs Islam
===message:I’ll trace the relationship of the United States and the Islamic world back to World War II.  America was interested in the Middle East because it was important in that it was the supplier of oil for industrialized nations.  During WWII, the Allied powers occupied Iran, with the provision that they would leave within six months after the war ended.  Well Great Britain and the United States withdrew, but the Soviet Union remained.  There began a demand for oil concession and threat of American action eventually forced the Soviet Union to depart.  Since then the United States had always maintained its interest in the Islam world.  The U.S. has intervened in the Islamic territory through small and large battles. From the time when Truman recognized Israel as a state, through the Israelites acquisition of more territory when Iraq invaded Israel, through the Iraq-Iran war, the U.S. had shown its support.  Through all of this the United States intervened for one reason and for one reason only and that was to protect its interest.  The United States was concerned with maintaining both regional stability and uninterrupted supplies of oil and therefore used its influence to bring fighting to an end.  While protecting it’s interest the United States has been trying to “westernize” the Islamic people.  America is basically telling them that their way of life is not the right way, and therefore imposing upon them America’s politics, religion, and cultural. The Islamic people see this as a   The Islamic people do not want to change and they would rather “die a bloody death than submit to humiliation and abjection” from the United States.
=========yorg=========
===from:Heather Felice
===date:Sat Jul 19 14:12:42 2003
===subject:Retreat from Empires
===message:The relationship between the United States and the Islamic world has always been on very shaky ground.  Muslims believe in a divine unity and the teachings of Islam to be the final say in everything that they do.  Islam believes that the United States has too much influence and presence over other nations.  They also seem to believe that any nation that is not Islam is also hostile against them.  


=========yorg=========
===from:Jordan Berkow 
===date:Sat Jul 19 20:24:50 2003
===subject:U.S. & Islamic differences
===message:<p>I believe that Ayatollah Khomeini was a man who was a die-hard Muslim, which opposed everything that had to do with American industrial and capitalism.  The status and influence that America has in the world is a serious threat in the eyes of this man.  Since the United State supports Israel, this also lifts a red flag in the eyes of some Muslim people.  This man does not understand the economic, cultural, or political drives of the United States.  Whenever the U.S. intervenes or supports causes in the Middle east, the Muslim people usually just see this act as intrusion and aggression. </p> 
  <p> The major reason why I believe Ayatollah said that “America is the number-one enemy of the deprived and oppressed people” is because not many other nations in the world are equal with the United States, in means of wealth and power.  This is not the case though, since this is just the way of an industrialized nation.  In retrospect with this last quote, how could any Muslim consider Saddam Hussein a just leader?  While he lived in his castles of gold, the peoples of the nations starved to death and were tested on with chemical warfare.  This is just an example of one man, who takes the ideals of his people to the extreme, at the cost of his own nation and twisting of his people's religious beliefs.</p>  
   <p>There is a tremendous difference between the United States and the Islamic world.  One major difference is that religion drives the Arab world with practices and rituals that basically partake in the entire lives.  On the other hand, the United States is consumed with material possessions, power, and status.  These two different approaches on life, could be at the very least disputed amongst among the peoples of these societies.    Another difference is the freedom that all American peoples are allowed to have.  If my memory serves me right, I do believe that in Afghanistan if a woman reveals her face on the streets, she could be killed.  It not sure if things have changed in the Middle East, but I think women are viewed as no more than near slaves or second class humans.  While the American people are virtuously wealthy compared to other nations, the Arab people probably aren’t considered so lucky in this day in age.</p>
   <p>After all this is said and done there are some major contrasting truths about the societies of America and the Middle East.  I understand that the Muslim people are opposed to change, and they should not be forced to change their views or religion.  As long as there is continuous conflicts in the Middle East, and with American support for freedom, there will always be some terrorist force, or misled Muslim group over there, who will have angry feelings towards the United States.</p> 

=========yorg=========
===from:Stephanie Chadwick
===date:Sun Jul 20 15:48:18 2003
===subject:US and Islam
===message:The Islamic world has always felt inferior to the US. I believe that they feel threatened by the power and beliefs of the American people. The political, economic, cultural, and military progress of the US is against everything that the Islamic world believes in. The US has religious beliefs that are very important, but Islams take religion to the extremes and those who don't believe as they do are criticized for it. Islams are opposed to "a life of shame" and believe that America takes from the deprived or oppressed people in order to maintain power. Therefore, we are considered "Great Satan." If the Islamic world would open up to a little change, they would not be so troubled and they would live in a much happier nation. Don't you think?
=========yorg=========
===from:Al Desmond
===date:Mon Jul 21 17:42:43 2003
===subject:The Retreat from Empire
===message:  The United States should have taken the region when it had a chance too.  But do to sorry treaties they found themselves relying on the regions that they gave away to allies or failed to take the region when they had the chance.
I’ll trace the relationship of the United States and the Islamic world back to World War II. America was interested in the Middle East because it was important in that it was the supplier of oil for industrialized nations. During WWII, the Allied powers occupied Iran, with the provision that they would leave within six months after the war ended. Well Great Britain and the United States withdrew, but the Soviet Union remained. There began a demand for oil concession and threat of American action eventually forced the Soviet Union to depart. Since then the United States had always maintained its interest in the Islam world. The U.S. has intervened in the Islamic territory through small and large battles. From the time when Truman recognized Israel as a state, through the Israelites acquisition of more territory when Iraq invaded Israel, through the Iraq-Iran war, the U.S. had shown its support. Through all of this the United States intervened for one reason and for one reason only and that was to protect its interest. The United States was concerned with maintaining both regional stability and uninterrupted supplies of oil and therefore used its influence to bring fighting to an end. While protecting it’s interest the United States has been trying to “westernize” the Islamic people. America is basically telling them that their way of life is not the right way, and therefore imposing upon them America’s politics, religion, and cultural. The Islamic people see this as a The Islamic people do not want to change and they would rather “die a bloody death than submit to humiliation and abjection” from the United States.
=========yorg=========
===from:Ramon Yarde
===date:Mon Jul 21 20:29:10 2003
===subject:Retreat from Empire
===message:<p>America is renowned for interfering with the affairs of other countries especially when it affects their politics, economics, culture, and military. To prevent the spread of communism the US sent technical and military assistance to Afghanistan, South Korea, and South Vietnam. The US illegally prevented elections, the same popular elections that they value so much, in South Vietnam to prevent the spread of communism and ensure that Ngo Dinh Diem was the country’s first president. They almost caused a nuclear war when Special Forces were secretly sent in to overthrow Castro’s communist regime at the Bay of Pigs. They also illegally sent in CIA operatives to overthrow the legitimate Arbenz government in Guatemala because it had seized control of land owned by US investors. They did this by funneling weapons to Guatemalan rebels and outlawing the communist party. They interfered in the affairs of another county all because they wanted to protect their own interests.</p>

<p>The US and the Islamic world are and have been at difference for many reasons. The most obvious one is America’s support for Israel. The US has always been at the aid of Israel and has supplied them with numerous technical assistance and weapons. The reason why America’s support for Israel is so strong is because of the major influence Jews have in American politics. Israel and Islam nations have been at odds for years and the fact that US fully supports Israel is the cause of much of the difference between the US and the Islam world. The other major reason is that Islamic people do not appreciate the need for America to try to influence affairs and control resources in their countries. An example is when America provided military assistance to Iran to prevent the spread of communism. When they achieved this they also took control of the finances of Iran’s oil industry and used the money to help finance industrialization back in America. However, the Islam people were able to revolt and take back control of the country from the secular regime that had been installed by the US. Islamic extremist have now began to use the concept of jihad to legitimize terrorist attacks on the US and American owned sites.</p>
=========yorg=========
===from:Travis Ellis
===date:Tue Jul 22 12:50:37 2003
===subject:US influence and Islamic influence
===message:The Middle East is called the "Middle" because in mideval times the Europeans had to go through and deal with the arab traders to get to the Orient or Africa. The Arabs became succussful middle men of world trade. Now that world trade is no longer directed through the middle east, the once strong Arab socities begain to weaken. The success of the US and our free culture has created a lot of resentment in Arab socities that were once strong. As a result they rely more and more on what they still have, their religion and culture. Perhaps the US government and CIA has been involved in under handed deals in the region that the natives don't accept, but for the most part the US has done the right thing in protecting the innocent and assuring the rights of a lot of people. Our culture and lifstyles are very different, and a lot of conflict stems from that.
=========yorg=========
===from:Diane Mercer
===date:Tue Jul 22 13:41:04 2003
===subject: U.S.  vs  Islam 
===message:I think that many of the Islamic countries feel inferior to the United States.  We have great military power, a great economy (most of the time), great wealth, and a good job market.  There is, I'm sure, a bit of jealousy.  We do live in a free country.  We wear what we want, do what we want, express ourselves, and have opportunities that other countries will never see.  Who wouldn't want that???  I think a lot of the times that we (U.S.) want other countries to be like us, free, and not live under the thumb of a ruler who doesn't allow its people to even have an opinion.  Why wouldn't we want that for our neighbor?  Take for instance, Saddam.  Look at how he lived.  He lived like that off of the money that belonged to the people of that country.  They had absolutely nothing.  I think it's only natural that we would want good things and opportunities for others.  That's what makes us the great Americans that we are.  What country wouldn't be jealous of that; and we all know that jealousy is the "green-eyed monster."
=========yorg=========
===from:Lesa Tolbert Bilotti
===date:Tue Jul 22 14:20:12 2003
===subject:Retreat from Empire 
===message:Ayatollah Khomeini was a religious zealot who was angered by the interference of foreign powers in Iran that often supported Iranian leaders who promoted modern policies that violated Islamic traditions.   To him this was unconscionable and prevented  the establishment of a religious dictatorship. 
<p>
There are many views as to why relations between the U.S. and the Islamic world are so strained.  American interference, exploitation of resources, political alliance with Israel, etc.  It seems that the most pervasive issue is religion.  The feelings of Muslim radicals are that the Islamic world has embarked on a Holy War against the West, especially the United States, that is being waged primarily through international terrorism. 
<p>
The U.S. government often seems content to stay out of religious affairs for the most part and has even made an admirable effort to separate the acts of terrorism from the Islamic culture in the minds of American people.  They have stated repeatedly that terrorist attacks are a perversion of Islamic doctrines and that the killing of innocents is a horrible distortion of the religion.  The word on the street is a little different.  Many Americans have begun to associate terror attacks with Islamic ideals because the attackers are male Muslim extremists in almost all cases.
<p>
I’m discouraged by the attitude held by so many that America had this coming and should have been attending to their own business.  There is certainly a time to do just that but I feel we need to trust our leadership to make that call.  Doing nothing is not always the answer.  I wonder how many lives may have been saved if the appeasement policy had been different when Hitler was gaining power.  That is the unknown that our leaders face when they make decisions. 

=========yorg=========
===from:Jesse Caudill
===date:Wed Jul 23 10:31:41 2003
===subject:Islam/America
===message:Ayatollah Khomeini’s statement is true, to an extent. Why wouldn’t any deprived or oppressed person in the world be mad at America?  I think they are envious of America and decide to hate America solely on their leader’s decision to hate America.  Their leader made them oppressed and deprived.  The leaders of these deprived countries try to put their own fault on America.  The relationship between the US and the Islamic world is that we are always having conflicts with each other. These conflicts come from America’s ambition to stay at the top. 
=========yorg=========
===from:Leon Aguilar
===email:aguilar14@juno.com
===date:Wed Jul 23 22:18:40 2003
===subject:Retreat from Empire
===message:Oops! Sorry Mr. Rosenburg for stealing your thunder. I accidentally posted a "new" topic. Below is my response to yours:

In my opinion, I see Khomeini's statement reflecting the frustrations of the Islamic world. It has become a war against civilizations per se. In Khomeini's statement, reflects the clashes of ethnic, religious, and cultural turmoil between the US and the Islamic peoples. In his statement echoed the aggression, humiliation, imtimdation that is felt throughout. As recent as the bombing of Iraq, we have yet to find any nuclear weapons? Have we? Now, I am not taking sides with terrorists, but let's face it, we have made this war an "us" (American) versus a "them (Islamic). A clash of civilizations. This war has caused more anger and embittered the Islamic peoples spreading myths, discrimination, and creating assumptions that "all Muslims" are terrorists. On the other hand, it has caused many Muslims to believe that "all Americans" are of the Devil! There is a great unbalance in thinking between Americans and Muslims. We have killed innocent people in the wake of finding the guilty ones. Now, I am not trying to down play the 9/11 incidents. Surely, we had innocent lives lost as well, but does two wrongs make a right? Khomeini advocated his people to repel, restore, and resist these imtimidations. Khomeini was embittered about the Iraq/Iran war and stated that America had "urged Iraq to spill the blood of our young men..." and it (America) has "compelled countires that are subject to its influence to boycott us..." Khomeini was not willing any longer to "submit to humiliation and abjection" and was ready to committ to a "bloody death". I see terrorists acts as a result of a highly frustrated Islamic world, reacting to the agression and humiliation of their lands. 

 
=========yorg=========
===from:Tiffany Charles
===date:Thu Jul 24 19:09:58 2003
===subject:Retreat from Empire
===message:One reason the relationship between the United States and the Islamic world is so troubled is our focus and drive is on two different things. The U.S. wants to be the "superpower." We want the World to change and adjust to our ways since we believe that it is the best way. We have to remember, our way is not the only way. The Islamic countries are governed by religion. Everything they do and want to do is based on what their religion dictates. The United States is governed by the people. We don't necessarily rule by religion because we have religious freedoms here. My neighbhor might not believe in the God that I believe in, but that's OK. Until we try to understand and respect each countries differences we will always have trouble.
=========yorg=========
===from:Tonya Burns
===date:Thu Jul 24 21:08:36 2003
===subject:U.S. vs. Islam
===message:In Khomeini's speech he calls on all Muslims, the true believers of Islam to regain their rightful position in the world.  He contends that the U.S. is an unholy place, filled with unclean people and ideologies.  Khomeini rallies his cry with a heavy religious sentiment.  He asks the people to consider their righteous past and promises them if they unite against the superpowers, namely America, that their righteousness will be restored.  The U.S. and Islamic worlds are truly on opposite ends of the spectrum.  The U.S. contends that the government, without the manupulation of religion, is able to secure a more stable political and economic force.  The Islamic world proclaims that only through unified religion can there be a successful movement. 
=========yorg=========
===from:Jasmine Heard
===date:Thu Jul 24 21:40:46 2003
===subject:Retreat from Empire
===message:Mr. Khomeini was an Islamic extremist. His outlook on life came from a merely Islamic perspective with no room for influence. Khomeini was one of the leaders who felt the influence of the United States would endanger his people more than add to their life experiences. He had "tunnel-vision"- only Islamic people for an Islamic world. The relationship between the United States and the Islamic world is one that needs work. The leaders of Islamic nations, like Ayotallah Khomeini, did not think that America could help his country but harm it because as Khomeini explained it,"there is no crime America would not commit in order to maintain its political, economic, cultural, and military domination." The main reason for the "great divide" between America and the Islamic nations is ultimately religion. Islamic people feel that Christians are "devils" because their morals and backgrounds are different from Americans. What they do not seem to understand is that America is made of different backgrounds and religions- that is what we call FREEDOM! Hopefully, Islamic nations will feel as though America is not full of "devils" and is willing to help any way possible becuase every nation is not so blessed.
=========yorg=========
===from:Carmen Ramos
===date:Thu Jul 24 21:52:46 2003
===subject:The Retreat From Empire
===message:The US v. The Islamic World
Everything has to do with the way the US has maintained power through out history.  
After the UN proposed dividing into two, Palestine and Israel, which later accepted the aid of the Americans, the Islamic world has been in conflict with the Americans.  The Americans have managed to control to a certain extent the government movements with regards to Irak and Iran.  
Economically, the Americans have great interest in the oil control of these countries, among other things, this is the one that gives the Americans power and control.  In a way is like there is still a "cold war" taking place regarding the controversial and continuous disagreements with the Americans and the Islamic world.
=========yorg=========
===from:Alfonso Boyer
===date:Thu Jul 24 22:10:54 2003
===subject:Retreat from Empire
===message:The number one problem between the Islamic world and the US is that the US tends to involve itself in situations where their interests are at stake.  The Islamic world own most of the vital oil sources that the US depends on.  So whenever it is to US benefit, it will involve itself in Islamic affairs.  A prime example is the situation going on right now with Osama bin Laden.  Even though there might be some truth to his involvement in the September 11 incident, accompanying this reason for invading Iraq is that of oil.  This is why Ayatollah Khomeini would say that, “America is the number-one enemy of the deprived and oppressed people of the world.”
=========yorg=========
===from:Ayana Wisdom
===date:Thu Jul 24 22:29:43 2003
===subject:Retreat from Empire 
===message:My personal opinion on why the relationship between the US and the Islamic world is so troubled is the dramatic difference in their foundations. The US and its popular culture have a completely different set of standards than the Islamic world. Also for political reasons there is this clash, the US is much too liberal for a portion of the Islamic world. <the portion that the media likes to focus on> The type of freedom that women have for an example can be, and is considered dangerous in some Islamic countries. 
The two totally different sets of views often lead to misunderstandings. Also the lack of knowledge on both sides contributes to the thought as America as the enemy. To be honest America has earned that title, but the lack of information on both sides only magnifies it. 
Most Americas have no understanding what so ever of how the varies Islamic nations operate. They tend to generalize too much, as does everyone else around the world. They don’t take the time to understand the religion, traditions or culture of this area. And lack of knowledge can lead to unintended disrespect of the culture. That goes both ways. What is most damaging is the lack of understanding between the two cultures. For these two regions there are two totally different religions. The principles of the religions are in essence the same but the ways in which they are practiced and the ways in which certain issues are dealt with are totally foreign to each other. I feel this is the root of most problems that have developed between the US and the Islamic world. Certain things are done certain ways in certain parts of the world. If you try to come in and do things your way with no regard to those who are already there, of course there is going to be some ‘ill feelings’. 
America, as does every other country, tends to work for their own perceived needs to the detriment of other nations. So taking advantage those who economically and socially aren’t as advanced to fight back or say “you know what I’d rather not have your business here” is going to give you a bad rep. Tampering in economic and military affairs that you technically have no business in and then completely ignoring others that demand your attention isn’t exactly helping to build relationships. 


=========yorg=========
===from:Conswella Walker
===email:swellawalker@aol.com
===institution:History 1112
===date:Fri Jul 25 19:28:31 2003
===subject:Do you think US and Islamic nations will ever unite?
===message:I feel that the US and the Islamic nations will never compromise as long as Religion and Power are at constant tug of war. Think about it the two most powerful resources to have is at constant battle. Religion is a very strong belief as well as power a  very strong influence to hold. If there is ever a compromise than there is a chance that the two nations could see eye to eye on a lot o f matters. Otherwise it will not be possible to ever have the two nations to come together. I hope this fighting stops very soon for the good of the people. 
=========yorg=========
