===from:Stephanie Chadwick
===date:Tue Jun 24 10:19:04 2003
===subject:The Great War
===message:Due to the extreme casualties of WWI, people were afraid of war. The trench warfare and introduction of potent weapons such as poisonous gas was frightening. People viewed WWI as the war to end all wars. The war changed the lives of many. Women were forced to fill the gaps of the labor force while men marched off to war. Many women believed the war to be a liberating experience, freeing them from older attitudes that had limited them (pg. 985). They felt important to the war effort. Many countries induced economic problems, some of which were permanent and damaging. This put alot of strain on the people causing riots, strikes, and mutinies. This in return added pressure on political leaders to form peace settlements while colonized people wanted self determination and national independence. They did not want any more wars. As far as soldiers and military leaders, I'm sure that their experiences at war were very damaging and devastating. Although many survived and were victorious, they had to be glad it was over. They must have coped by talking with people and loved ones about their experiences and feelings while others did not cope well at all. Maybe they discussed ways to make things better and ways to prevent it from happening again. the Paris Settlement, Wilson's 14 Points, peace treaties, the League of Nations, and the concept of self-determination all played a big role in the war prevention process. Are all wars inevitable? I would say that in most cases, yes they are. As long as there are dominant powers and others who want to dominate, there will be war. When one country wants the power of another and believes they can take it over, their attempt will inevitably result in retaliation. The only way that war could be avoided is if every nation had equal assets and power and none of them had the hunger or greed to be in control of the other or take away their assets.

=========yorg=========
===from:Laura Johnson
===date:Tue Jun 24 16:42:34 2003
===subject:After the Great War
===message:Based on the isolationism in America, and Europe’s appeasement of Hitler leading up to the second World War, it seems reasonable to assume that, after the Great War, people viewed war with some trepidation – and with good reason. The League of Nations was established in the hope that collective security would deter future wars (997). In the late thirties, those who opposed war for economic and political reasons used appeasement in an effort to establish “peace for our time” (1043).
<p>
The war had disillusioned the European intellectuals who had enthusiastically supported it in 1914 – they became the “lost generation” (1005). Established traditions had been shaken and the desire for national unity strengthened (1004). Political, social, scientific, and theological ideas and theories shifted toward a new perspective on world governed by irrationality and uncertainty. How did they cope? They resorted to conservatism and pessimism, jazz and abstract art, communism and fascism.
<p>
There is no absolute answer to the last question. Some wars are inevitable, some are not. The Great War was probably inevitable because of the entangling alliances entered into and the precise military timetables constructed by the countries involved. Were it not for insatiable imperialism and aggressive nationalism, perhaps the assassination of Archduke Ferdinand could have remained a regional conflict only -- or perhaps never have happened at all. It is difficult to speculate. The second World War was an inevitable result of the first – an effect of the economic and political instability unresolved after the Great War. Other, more recent, wars have been unnecessary and probably preventable.

=========yorg=========
===from:Yvonne Turner
===date:Tue Jun 24 20:12:02 2003
===subject:World War I Aftermath
===message:World War I was supposed to be the end to all future wars.  After the horrifying events of world war one, a lot of things changed.  Because of the mass amount of casualties during the war, I think people felt tortured, doubtful and scared.  Soldiers in the war were exposed to poisonous gases, which deteriorated their bodies from within and without; thus causing a slow torturous death.  In addition, the survivors of the war had to deal with the pain and anguish left from the loss of fellow soldiers.  World War I was considered a total war in which everyone was involved and faced the potential of being a casualty, even civilians.  This must have been a scary feeling even when the war ended because they didn’t really know if this would be the final war of all wars.  
<p>
Because most of the men went to war, the women had to take care of things on the home front.  During the war, women became liberated to a degree because they were able to work in jobs that were formerly held by men.  This liberation came with consequences.  According to our book, many women died in munitions factories because of the explosives they were exposed to.  
<p>
I think the political leaders felt virtuous and praiseworthy because of the establishment of the peace treaties and League of Nations.  A person has to wonder if the diplomats were more concerned about making the history books or if they really thought the establishment of the League of Nations would help prevent future wars.
<p>
Wars are inevitable as long as people exist because their will always be conflicts of interest.  Some wars may be avoided through arbitration and negations, but their will always be a few strong leaders who will stand firm on their position even if it leads to war.

=========yorg=========
===from:Jordan Berkow
===date:Thu Jun 26  8:10:18 2003
===subject:After the Great War
===message:<p>I think that people had different views of the war, but similar in some regards.  The civilians looked at war as a time of stress and heartache back in the homeland.  Women and sometimes children had to take part in the jobs of the husbands and fathers.  The stories and the massive deaths probably also inflicted fear in the hearts of any civilian also.  Fear resided in the hearts of civilians, especially with when the Germans were attacking civilians with submarine warfare and the zeppelin.  In similar respects the soldiers probably feared and hated war.  They were the ones on the front lines who witnessed millions of losses in life.  To these brave men who fought, war was nothing but a recipe for death.</p>  
<p>Military leaders and political leader too probably saw the war as great loss and tragedy.  Commanders in the army could now see that war wasn’t of noble or great.  They also probably realized how wars in the future would turn out, since the new warfare technology brought so much destruction in the war.  Political leaders could see the war as damaging to the economy and bringing fear into the people of the nation.  Nicholas II realized that war times brought heartache and loss of patience into his people, when he abdicated the throne.  For the most part, I believe that everyone had negative feelings towards wars.</p>
<p>After the war people probably cooped with their feelings in different ways.  Civilians weren’t there so they probably pushed it out of the consciousness and focused on other things.  Soldiers probably tried to forget the war time stories, since no civilian would ever understand the horrors of war.  Another way to forget or coop with the aftermath of the war was building up the home and trying to get stable again back in the family and social lives.  I would have to say that it wasn’t easy for anyone to deal with the after effects of World War I.</p>
<p>People who were against the war tried many different measures to prevent it from happening again.  The creation of The League of Nations was a multinational effort to allow countries to support each other and try to discuss problems among each other.  The creation of new nations also was a way to try and bring stability to the world.   Many ideas were conceived and practiced, but they didn’t last but only a few decades until the next world conflict.  Since no amount of provisions have stopped war in the past, I don’t believe that all wars are inevitable.  When there is discord among nations and people don’t get along, eventually there will be arguments, fights, and possible wars.</p>

=========yorg=========
===from:Anthony Shealey
===date:Thu Jun 26  9:47:00 2003
===subject:The Great War 
===message:     After the great war people viewed the war as exhausting and barbaric, some people probably viewed it as necessary for the greater good.
     Soldiers are the most affected by the war because they are the ones on the front line.I would think the soldiers would feel tramatized from the war.Alot of them probably would feel isolated and alone because they are dealing with what they have seen and done.Theirs a feeling of resentment towards war thereafter.
     Civilians would feel some resentment towards war, but also nationalistic towards their heritage and what they stand for in the idea of war.
     For military political leaders it all depends on what they are going to war for. Some would oppose war, but if it was necessary for the greater good of the people, they wouldn't oppose it in fear of retribution.
     I think they cope with their feelings by turning to alcohol. Speaking amongst other people that view the war as they do.Those that were against war probably stayed silent in fear of retribution towards them and their family. All wars can be avioded, it is the greed and petiness of man that causes war. 
=========yorg=========
===from:David Paulson
===date:Fri Jun 27 15:36:55 2003
===subject:The Great War
===message:I believe most people saw war as a terrible thing after WW1. They did not understand the destruction the industrial age and new weapons would cause. There are those that like conflict and war so there will always be people that want to be mercenaries or people that believe they will make a profit on war. You also have to look at war from the perspective of the individuals that lost friends and family during the war. These people would hold resentment and hatred for the people that killed there husband, son, best friend or neighbor.
     
I think most people tried to copy with there feeling of the war by just going on and living day to day. I don’t see were they had any other choice. They could lean on something like alcohol or drugs, talk to family or friends or discuss there feeling with a doctor but basically they just did there best to move on. 
    
The people that tried to keep war from happening again reminded individuals of what happened the last time. The loss of life, the destruction and the morality of what war is all about. The political leaders have to think about the best position for there nation. Some times the best position for a nation is war. War is quick way to jump start an economy, it creates new jobs while eliminating people from the work place. Economic hardship and resentment of the first world war is what caused the second world war.
     
I believe that many wars can be avoided but there will always be wars. As long as there are people with different believes and people that aggressively want more in this life, then there will always be conflict of one kind or another.
     

=========yorg=========
===from:Jasmine Heard
===date:Mon Jun 30  0:05:52 2003
===subject:The Great War
===message:Some of the soldiers who could give the best feedback on the Great War are no longer with us (may they rest in peace); however those who survived were definitely bewildered at how long the process took and saddened by the numerous amounts of casualities. Political leaders wanted the war to end as soon as possible, not so much because of the casualties, but because of the expenditures, or cost, of war. The soldiers played key roles in the Great War, but so did the women. Women had to leave their babies, get "bobbed" up and attack the workforce while the men were attacking enemies. Also, not only did the soldiers encounter casualties, but some of the women working in the munitions factories died or were poisoned by TNT. The sadistic element of the situation is that the casualties that women encountered on behalf of the bombs they were building inevitably killed others as well as some of their own. Sadly, most of the women were never recognized like their male counterparts that warred for the good of their country. Ways for people to cope with war are: church, family (and the memory thereof), and friends. Thankfully, America has never had to face war first hand (terrorism, not war). Ultimaltely, to prevent war from happening again, treaties between countries were written and put into practice. War is not inevitable because an assassination caused this Great War; however America has had assassinations take place, but no other real casualties came from them. War has a root: control- regulate, dominate, rule. If one country does not agree on how another country handles its affairs, and the livelihood of its people are not in danger, why bother in its affairs?  If no one asked for help, do not offer it. As some might say, "If it ain't broke, don't fix it." All-in-all, the Great War had many tragedies and lasted for five years, but the world would not be what is today without those things that happened in the past.
=========yorg=========
===from:Diane  Mercer
===date:Tue Jul  1 13:58:10 2003
===subject:The Great  War
===message:I believe people viewed war after WWI the same way they would view the after-effects of any war.  War is tragic.  Nobody said that war was a likeable event.  Soldiers fight and the majority of them, I imagine, are severely affected. They are wounded, sometimes beyond repair, they lose friends and loved ones, they become depressed, and those are the ones lucky enough to make it home.  Only those who have fought and lived to tell can really explain what their views on war are.  Although some women were "liberated" (985) during the war with their new jobs and pays during WWI, they were greatly effected by the war also.  It was their loved ones who were gone and fighting, some coming home and some not.  They also felt that they played a big role in the war.  They worked the factories, were nurses, physicians, postal workers, policemen, and clerks (984).  Liberation also came after WWI when they were given voting rights.  I believe military and political leaders were concerned with the great number of casualities and the cost of war; how it effected the social economic system, and how great the debt of conflict was.
<p>
As of war of yesterday and today, who can say how they coped with their feelings.  There are so many ways to deal or not to deal with it.  I'm sure many were depressed, angry, disgruntled with their government, suicidal, and those who weren't left in their right minds to deal with it.  Maybe the government and military staff were left with feelings of "did we do the right thing?"  "How can we be more sufficient the next time, not lose as many lives, and achieve our goals?"
<p>
I think people have tried whatever they think will work to prevent war.  People protest, they campaign for new administration, become human shields, and try to make themselves be heard.  As government does now as I'm sure they did then, they do what they think is necessary to make our country a safe democracy - "the land of the free and home of the brave."
<p>
As far as war being inevitable, I think sometimes it is.  We'd all like to avoid war.  From personal experience, I am prior military and my husband is still serving.  We, like the rest of the country, are not for war.  Who is???  We are for standing behind our government and fighting to keep our country and our families safe and able to live with the freedoms that we have.  And sometimes that means having to fight for them.
=========yorg=========
===from:Lesa Tolbert Bilotti
===date:Wed Jul  2  6:57:11 2003
===subject:The Great War
===message:People of all nations, classes, ages, and genders had a terrible awakening as the war came to close and in the years afterward.  What so many expected to be a catalyst of change leading to a better world, turned out to be just a horrific loss of life that most had trouble justifying or even understanding.  Much that was once innocent and hopeful was replaced with suspicion and disillusionment.
<p>
Soldiers who survived the war often returned home with physical disabilities that prevented them from rejoining the work force, while many others suffered "shell shock" preventing them from psychologically adapting back into civilian life.  Millions of civilians were killed in the war and millions more were left widowed and fatherless dealing with very severe emotional loss and economic hardship.  Military and political leaders were forced to look at the world with a new perspective and realize that they had to react to the sense of distrust citizens had developed as a result of being misled through propaganda. This is evidenced by their efforts to avoid future destructive conflicts by creating the League of Nations whose mission was to maintain world peace.  Some leaders began to lean toward the philosophy that self determination was the key to world peace. 
<p>
There were many different means of trying to deal with the residual feelings that the brutality of the war left behind.  Artists began depicting the sordid realities of modern life, psychologists researched explanations for human aggression and civilized peoples’ capacity to slaughter each other mercilessly.  Philosophers, poets, and writers bemoaned the decline of human nature and the death of society, and people who once believed the war effort would bring positive effects became resolute pacifists.  
<p>
It seems very unlikely we will ever see a world without war.  With so many difference viewpoints and worry over self interests governmental agendas will never satisfy all parties perfectly.  For instance, though many thought it was only fair and appropriate for responsible Germany to pay reparations for the war, it ultimately led to lingering feelings that they had been treated unfairly at the peace conference.  This opened the door for Hitler to come into power by taking advantage of this sentiment.  
<p>

=========yorg=========
===from:Jesse Caudill
===date:Wed Jul  2 14:45:53 2003
===subject:WWI
===message:Many people came across a rude awakening when they entered WWI. Many were excited to enter war because for them it meant change for them. Post-WWI, war was fast and victorious with out many casualties. After WWI I think that people become frightened of war and put war on a last resort list. 
With the new advances in weapons, civilians were now involved in war. Airplanes, subs, tanks, and machine guns brought war into then city. Most leaders and soldiers were unprepared for this war. As the war went on, they had to act and think differently than before. War had changed forever and they had to react to the many changes that came with it. 
Everyone was dumbfounded when they found out what war has become and started to fear war tremendously. War forced people to act in a different way. Many had to find a settle grown to go on with there lives. To do this, I think this I think people went to each other for support. It was kind of an “I got your back, you got mine” kind of idea. They had no where to go to coupe with the war because of all the deaths then to each other.
Those who wanted to prevent the war protested. Others who wanted to make a changed revolted, similar to Lenin. 
War is evil. Since evil is impossible to get rid of there will always be war. War has always been and always be. There is no way to avoid war. We live in a selfish world and nothing will change that. It is our nature to want our way yesterday and we will force our way if we have the power to do so.

=========yorg=========
===from:Travis Ellis
===date:Wed Jul  2 19:29:59 2003
===subject:Modern Warfare
===message:World War 1 saw the introduction of poisoness gas, tanks, and airplanes. Machine guns changed tactics, the traditional war formations and manuvers were no longer effective. With the new technology, new tactics were needed. I see World War 1 as the war where all the new stuff was being tested out. The stalemate at the Marne showed that each side was slow in developing offensive tactics with the new stuff. Most the toys of war today, were first developed from the beginning of World War 1 and the end of World War 2. The Great War is an example that with technology comes responsilibties. I still not sure how responsible people were in World War 1, but they definitely learned a lesson in World War 1. Then they learned not to forget it in World War 2.
=========yorg=========
===from:Alfonso Boyer
===date:Wed Jul  2 23:24:41 2003
===subject:The Great War
===message:I would think that they saw war as a brutal massacre of human flesh.  World War I was the first war that showed how gruesome and inhumane war can be.  I know it totally changed their mentally and perspectives of what war really is.  This war must have had detrimental traumatic effects on the soldiers and military involved in this war.  I don’t think they had any real way of coping with these irreparable visions, but therapy certainly couldn’t hurt.  As for the civilians, they might have seen and experienced some gruesome parts of the war, but I seriously thought that their experience could compare to that of the soldiers fighting in the war.  Even with all these horrors going I think the political leaders were the least swayed by this war.  The only thing they cared about was getting what they wanted out of this war.  They were even ready to start another war if their demands were not met. Now that doesn’t sound like somebody who hates war to me.  Supposedly, those who were against war formed another alliance called the League of Nations.  Somehow I don’t think the majority of these participants really wanted peace.  There is no real way to prevent war from happening.  As long as people take nationality seriously, war will always occur in the most unlikely of places.
=========yorg=========
===from:Al Desmond
===date:Thu Jul  3  2:55:06 2003
===subject:The Great War
===message:How do you think people viewed war after World War I? Consider the perspectives of soldiers, civilians, and military and political leaders. How do you think they coped with their feelings about war? How do you think those who were against war tried to prevent it from happening again? Are all wars inevitable or can they be avoided?

I guess the way people viewed war depends on the person you are talking about.  Civilians viewed war as a constant nightmare that had several chapters that seemed to never end.  The path that this war took was a path that was never expored with total destruction and carnage.  It hit at all the emotions of the people, emotional, mental, financiall and political.  It took all as prisoners young and old.  From the poisioning of our women and childrend in the munitions to the total carnage of our soldiers.  I feel just as today political leaders always justified war as the greater good.  It had its way of justifying itself for the sake of pride and dignity.  Many politicians are very digestive of war because once involved its very hard to admit that they were wrong but the irony is that not many politicians are quick to call for war when thier family members will be involved.  I am not talking about cousins and Uncles I am talking about thier children.  Many military leaders were leaders because they usually came from military backgrounds so thier patriotism overwhelmed thier emotions but I would be considered heartless to say that when they are all along they regret the actions and planning that was involved in the countless loss of lives.
I don't feel all wars are avoidable.  The American involvement in this war was based on the sinking of the ship by the German submarine.  Diplomacy was tried and we did turn the other cheek a number of times.  Thier are some wars that I do feel are avoidable.  The recent conflict that we are involved in I feel was avoidable.  Yes lives were being lost but it was not American lives.  I do feel that sometimes force is needed to prevent a war but to use total all out war tactics should be the last resort in a conflict such as what we are involved in now.  For those who are agianst war I feel that thier voices are heard but seldomely listened too.  Thier is no way that they can truly prevent a war because they are not in the positions that can prevent a war.  I think public outcry doese more than political interest.  We as a people elect and relect those who sponsor war and I feel we are the greatest weapon against war.
=========yorg=========
===from:Shemika Williams
===date:Fri Jul  4  9:47:06 2003
===subject:Great War
===message:The Great war was no doubt the biggest strain on all the nations involved.  I am sure many of the nations entered the war with the hope that they would come out successful.  They were probably not prepared to engage their whole nation, including the women and sometimes children, in such bloody fury .  Many of the people expected the war, in hopes that it would end the political , social, and economic crises that had been mounting between nations and empires over the years.  Most hoped that the war would be a quick and victorious one.  As the nations made war plans, many of them did not take into account that this very large uprising would inevitably lead to massive casulties.  War was most devastating for the young soldiers who entered the war  anticipating  quick victories that would result in them being deemed as heroes and their nation's economy being properous. Of course this was not the case.  By the time war was over about 15 million soliders were dead and many national economies were in tremendous debt.
=========yorg=========
===from:Tim Fitzgerald
===date:Sat Jul  5 18:07:54 2003
===subject:WWI
===message:WWI consumed an entire countries resources, population, economy, manufacturing, and military might on a global scale unlike anything ever before experienced. The huge loss of life in and of itself would almost assure that almost every family in a participating country would share in that grief and war would never again be viewed as a path to glory and honor but only death and destruction.
<p>
The average soldier finding himself caught up in the first major conflict of the Industrial Age to be completely unprepared for how war would be fought in this new era. The horror of the new weaponry's capabilities to kill massive numbers coupled with military leaders lack of tactical and strategic experience with those weapons could only have left front line survivors questioning why they were allowed to live while others around them died. It would be hard to imagine that they would not return home and pray for peace for mankind forever. 
<p>
Civilians, touched by death of family and friends in the military, product shortages at home, and dangerous civilian wartime industries were very glad to return to some semblance of a normal life and viewed the war as something to not be repeated. How can almost any normal human being not view the misery, carnage, death, and destruction of WWWI as no less than an abomination to avoid again at almost all costs?
<p>
Military leaders had to realize that new tactics and strategies must be developed for fighting wars with the advanced weapons being produced and in development. The days of charging up a hill with numerical superiority would no longer mean victory but catastrophic casualties. The focus had to change from the numerical size of the military to how to best deploy the new weapons of the military. 
<p>
Political leaders were forced to rethink the effects of their actions and alliances on a global scale that had perpetrated the causes of WWI. The world had become so increasingly interdependent that new ways of viewing one's country in relation to the rest of the world had to be developed in order to avoid a repeat.
<p>
People coped with their feelings about the war the same as each individual copes with life's hardships. Many people concentrated on returning to a normal life and the values that give their life meaning to try an put the horrors of war behind them. Others took a more proactive approach by becoming politically and socially involved in efforts to improve their societies and nations in order to try and prevent another war of this magnitude. Still other lives were shatttered by the horrors of the war and they never really coped with what they experienced.
<p>
The biggest way people against war tried to prevent it is speaking out publicly against it. Civic organizations were probably formed to give a common voice and lobby against future war. Others became politically active and either ran for office or supported candidates with antiwar views. Others made efforts to reach out to other citizens and cultures to promote understanding and tolerance.
<p>
Historically wars have been waged and sometimes avoided and/or averted. Can all war be averted? NO. The evolution of the human species as a more tolerant, loving creature that would eschew war at all costs is not a reality that will soon be seen...if ever. The sad truth is that as technology has evolved the human species, as a whole,has devolved. Fundamental ethics, morals, and values of the political leaders down to the basic citizens have been declining more each decade. Avoidance of responsibility, greed, dishonesty, and deceit all becoming accepted and expected behavior in people's daily lives are not the basis of a society or world that will have the insight or courage to avoid future wars.
<p>
<br>
 
<br>
 
=========yorg=========
===from:Ramon Yarde
===date:Mon Jul  7 20:32:06 2003
===subject:The Great War
===message:<p>Everyone expected the war to end quickly as they all believed they were fighting with the God on their side. World War I started out with massive, positive support from civilians for the war as "jubilant crowds threw flowers at the feet of departing men" (976), and soldiers and political leaders dreamt of glory and honor, and expected to return victoriously after a short period. However the war turned into a bloody stalemate in which millions of soldiers as well as civilians were killed.</p>

<p>The war had different effects on different people. First of all, many people either lost their lives or lost loves ones as a result of the war. The majority of Americans believed that they should not have entered the war and felt as if their government had unnecessarily forced themselves into the war by giving financial aid to the Triple Entente. The British and French saw it as a victory for themselves because by the end of the war they were able to reduce the power of Germany and dissolve the Ottoman Empire. The people of Germany and Austria were devastated by their defeat in the war. Not only was their empire split up and military power reduced through the Treaty of Versailles, they were also required the payment of reparations for the damage of the war.</p>

<p>World War I can be viewed as a political victory for the Allies and devastating loss for the Central powers. However, the eventual result of the war was a decline in European power. The event that that stuck out to me from the war was the British directed campaign at Gallipoli. The campaign in which British commanders led Canadians, Australians, and New Zealanders into battle with resulted in 250,000 casualties for their side. This was an important event that changed the perspectives of the people of these countries and eventually weakened imperial ties between them and England.</p>

<p>I cannot confidently state how people coped with there feelings as a result of the war. There had to be a period of mourning for all of the lives that were lost in the war. There also had to have been some reflection done by soldiers and political leaders alike because they had underestimated the effects of the war. I would think that they would not have wanted to participate in a war of that magnitude again.</p>

<p>Woodrow Wilson was the main person behind the peace process to make sure that a war of such magnitude did not occur again. The League of Nations, which was created during the Treaty of Versailles, was formed to promote world peace. In his Fourteen Points, Wilson also aimed to promote the concept of self-determination because he believed it was the key to international peace and cooperation. The disarmament of Germany was also essential to peace process because of its aggressiveness towards nationalism.</p>

<p>Wars can be avoided depending on the leadership of a country. If the leaders of countries are concerned with the well being of their countries as well as world peace, there will always be peaceful way of settling disputes between nations.</p>
=========yorg=========
===from:Leon Aguilar
===email:aguilar14@juno.com
===date:Wed Jul  9 21:45:44 2003
===subject:The Great War
===message:War has and will always be a devastating event to mankind. It was designed to be that way. Power, domination, and control are the key at any costs. Even as far back as Biblical times, and until now, it has been bloody, costly, and devastating. Even in times past, soldiers have enlisted with excitement, courage, a sense of purpose, with many hoping for fast victory.   

The Great War, contrary to the adventurous heroic journey (so they anticipated), I believed was viewed as a disappointing disillusionment to all. Soldiers, military leaders, and civilians all were disappointed. Military leaders had to re-think their strategies as they saw the war drag on and on. As they came to strategize new ways and developed new weaponry (poisonous gases, artillery, machine guns) to win the war quickly, it unfortunately complicated matters more so and caused great losses on both sides. As hopes of a quick victory became fragmented, soldiers were beaten to despair and discouragement. At the home front, civilians were threatened by opposing forces whereby their lives were at risk. Many lost their lives as German forces dropped bombs from mid air on civilians. Many also suffered losses in munition factories working under dangerous conditions.

I think people tried to cope with their feelings through expressions of art, poetry, writings, religion, and music. Writings by Oswald Spengler helped to relieve the discomforts of some that were dealing with despair. In addition, many governments were loosing the support of the people because of the stresses that the war brought. Many economies suffered. Many lost hope in their leadership. Many political movements (such as the fascists and Bolshevik movements) and other take overs began to take shape whereby this too was a way for people to have the option of trying "something new" in hopes of a successful economic future for the sake of the people.

The development of the "League of Nations" (whom Woodrow Wilson was a key figure behind) was an effort to avoid future wars. It was the first international effort designed and set in place to promote and keep world peace, which later became the basis for the "United Nations."

Are wars inevitable? Can they be avoided? In my opinion, some wars are inevitable if the opposing parties are not able to reach a peaceful agreement. If and only if both parties are not willing to work out their differences and come to an agreement, then I would consider war inevitable.

=========yorg=========
===from:Tiffany Charles
===date:Thu Jul 10 20:11:59 2003
===subject:The Great War
===message:I think the average person viewed the war as an economic disaster. The military viewed it as a massive loss of life and probably questioned why? I understand the whole fight for your country mentality but to what extent? The political leaders viewed the war as a way to gain power and a way to take powers from smaller and weaker countries.  I think people internalized their feelings about the war. They probably turned to their religions and families, while governments made decisions as a collective whole. Decisions regarding peace and responsibilities for those who began the war. I don't believe all wars can be avoided or even should be avoided. I guess it boils down to what is at stake and who will benefit the most from war. In my opinion, monitary gain is not a reason for war. World domination is not a reason for war. Crimes against innocent people can be a reason for war and should be a reason. 
=========yorg=========
===from:Carmen Ramos
===email:vorypr@bellsouth.net
===date:Thu Jul 10 21:47:52 2003
===subject:WW1
===message:Considering that it was the first time that people in 1914 were exposed to such a war and were able to survive it, its unbelievable.  According to the lecture, the soldiers went to war expecting to return heroes, advance in their career, bring home a victory, but many of them did not return.  Soldiers did not face the reality of war until they arrived at the front.  However, political leaders kept pushing forward, expecting great victories and triumps while sacrificing hundreds of lives. For civilians, mainly women and children, it meant that they had to go and work long hours and even risk their lives working while preparing amunitions for the war.  This chapter focused on the events that lead to a war that made people num, because it was to sad and to real to try to make sence of it.  Families were broken, many were left with no one in the world, and, eventhough evereyone put together their efforts to support and supply for the war, it was a very high price to pay.  In the end, I can imagine a feeling of uncertainty once the guns are no more an every day event.  The Allies, the Associated Powers, and even the Central Powers, in my opinion were ways to try to avoid the war.  Through association these countries tried to protect and defend their believes and their way of life, mainly against dictartorial liderships.  In the end, most countries wanted freedom, economic gain, land, and goods, amongs others.  War is a very unexpected and undesired event in our World history, but without these events, the world would not be what it is today, most of us get along.  I think that  the war is not avoidable, considering the aggression of the Germans and the Japanese, (no offense), when your people is threatened and talking does not appear to aliviate the other party, then force is how we got to be the great nation that we are today.
=========yorg=========
===from:Tonya Burns
===date:Thu Jul 10 22:20:43 2003
===subject:Great War
===message:After World War I people viewed war on a more global and undobtedly a more devastating level.  Nations had never engaged in such brutal and horrifying battles.  While many civilians were astonished of the thought of war, many were celebrating in the streets.  They celebrated the awesome revolutionary change war was sure to bring with welcome enthusiasm.  On the warfront soliders dreamed of the "heroes welcome" that would be awaiting them at home.  But the cruel reality of the "no-man's land" would soon over shadow their dreams.  The military advanced tremendously during this time.  The invention of new weapons and massive armored vehicles insured great success.  World War I also inspired the feeling of nationalism and self determination.  War in of itself is selfish.  If presumes that under developed lands need to be rescued from themselves.  All war is a source of power and economic control.  As long as nations feel the need to assert their own agendas onto others war will always be inevitable.    
=========yorg=========
===from:Ayana Wisdom
===date:Thu Jul 10 22:49:36 2003
===subject:Great War
===message:After World War I people didn’t see war as a way to go off and become a hero, it was a way to go off and die. Going into the war many people had no idea how far the ramifications would reach and how deep they could and would go. I feel that military and political leaders felt a bit like the dog that attacks and realizes it’s bitten off to much it can chew so from then on attempts to pick its fights more carefully. 
Those who didn’t want the war to come to the scale attempted to put protective obstacles in the way for future political leaders. Wilson’s 14 points would have been one such obstacle if it had been taken as it was given. “Open covenants of peace …” would have taken away the need to be suspicious of your neighboring country or kingdoms potential treaties. Also “Absolute freedom of navigation …’ over the seas would have negated the need for great navies and should have in theory made trade better. 
If political leaders were not so willing to take insult concerning trade or lands wars would not need to be fought, of course there does come a time when action needs to be taken; if one kingdom/country/republic decides they want to up and kill everyone on their neighboring kingdom/country/republic’s board then war may be the only way to stop them if compromise doesn’t work. I honestly have always thought that most wars were started from pride.   

=========yorg=========
===from:Conswella Walker
===email:swellawalker@aol.com
===institution:History 1112
===date:Fri Jul 11  3:41:01 2003
===subject:Do you feel Great War was necessary?
===message:I donot feel that the Great War was necessary. The reason I say this is because wars are suspose to create a sense of purpose and common ground, power. The Great War occurred in 1914 and we are not any better as a whole than we were then. Yes, there have been a few acccomplishments but at what cost? I have often heard stories of elderly men and women who talks about their husbands, and fathers, brothers and other family members that went off to war and never returned. A person who is taken from their happy, productive home and sending him to a war  and to never return is not necessary or good. I feel that all wars are advoidable and should not take place.
=========yorg=========
===from:Conswella Walker
===email:swellawalker@aol.com
===institution:History 1112
===date:Fri Jul 11  3:52:22 2003
===subject:Great War
===message:I believe that the people coped with the war the best way they could. They had feelings of insecurties, anxiety, distrust in governement, feelings of sadness and anger.  I believe that people were very concerned about the purpose and goal of the war. There were still questions and the feelings that war was wrong and was not the answer. The time was in 1914 and the people were not as receptive to war as they are today. People that were against war made attempts to slow down the war tactics and efforts. However they failed.  The Allies, Central Powers, and Associated Powers were another organization that was against the war.I believe that all wars can be advoidable. Wars are no different from anything else that you can prevent from happening. It is just sad that the only answer we have to war is fighting and killing.
=========yorg=========
