===from:Amy Metzger
===email:ptflute@bellsouth.net
===date:Thu Sep 11 19:47:28 2003
===subject:White Man's Burden
===message:I think the American in general isn't racist or we couldn't be so demographically mixed.  There have been times in history when certain leaders, politicians, writers etc were in favor of being elitist or keeping the doors of the country closed.  Strong in his book, Our Country, appeared to be open to all but in the end was really a precursor to white supremists.  The creation of the high culture also belied this thinking:  that there was an hierarchy that put people into categories, classes, that really divided people culturally and socially and fiscally.
=========yorg=========
===from:Stephanie Junca
===email:stepherchik@aol.com
===date:Sat Sep 13 22:53:48 2003
===subject:The Burden of the White Man
===message:The cartoon seen in the cd shows how most Americans at that time believed that peoples of most other countries were savages and that they needed to be controlled or "liberated" as they said. Americans acted as hunters trying to get their prey just to hang the heads on their walls. Yes, Americans are racists and exploitists because they believe that the white color of their skin gives them the right to control everyone who is different. For example, currently the Americans are trying to gain control of a country who has been controlled by a dictator. These people are used to living this way and changing their life from night to day does not work well with them. Americans believe that democracy is the best way to live but just because it is good for us does not mean that it would be good for them. Unfortunately, believing that we are the best ends up making us believe that what is best for us is ultimately best for the rest of the people. Kiplings views in that we would gain something as a country by taking the freedom of another country is crazy to me. Twain and Tillman bring out what would be best for those people. They do not need to be controlled by a strange country. There is no way that  the US' actions can be considered as justifiable. They believe that they are taking away the bad way of life for those people because of their supposed "savageness" but in reality they are just taking away their freedom. To anyone taking away ones freedom is taking away one's soul.
=========yorg=========
===from:Jordan Berkow
===date:Sun Sep 14 15:54:19 2003
===subject:White Man's Burden
===message:<p>This cartoon does a decent job exposing the meaning of the “White Man’s Burden”.  It does do a good job graphically showing that the imperialistic nations sought to conquer a nation and educate them and change these people of foreign lands to a “proper” way of life.  I know from my readings in other history books that the English sent the Indian people to schools, and taught them all the proper mannerisms and political system of Great Britain.  This drawing shows a man carrying off a non-white person to the school house for educating.  During the time of imperialism the English saw that they were supreme among the other races, and felt that they were doing people of foreign lands a favor by changing their ways of life.  The ideals and beliefs of the imperialists can not be described in any photo, and this is just one area which the drawing does not suffice.</p>   
   <p>After my readings in the text, I believe that Americans have been at time racist, exploitive and elitist, while dealing with other peoples of the world.  On page 588 in our text book, it says that McKinley believed he annexed the Philippines because they were near savages and unfit for self rule.  The book also says that the Philippines had a literate population, churches, schools, and a centralized government.  Racism and exploitive reasons pretty much self explain McKinley’s statement of an “unfit for self-rule” while the Philippines actually had a good state of civilization at that time.  One of the definitions of exploitive is “to employ to the greatest possible advantage”.  During this time of imperialism nations sought colonies and trading posts.  On page 583 a US senator stated that, “we will establish trading posts throughout the world as distributing points for American products.”  This statement and McKinley’s annexation of the Philippines express that the U.S. Government was primarily focused on becoming a international agent in trade and also a growing world power.</p>
   <p>Rudyard Kipling was an advocate of American Imperialism.  He found that it brought stability and civilization to the foreign lands and would bring purpose to the lives of the conquered.  Kipling also believed that these actions of imperialism were moral.  Tillman was of course against imperialism since he didn’t condone the annexation of the Philippines.  Mark Twain was also against the occupation of the Filipinos.  He thought it was pure hypocrisy to help bring this nation to independence and then turn around and take away their new freedom.</p>
   <p>After reading about McKinley's reasons for anexation and the United States support for free nations, it is difficult to justify the action taken against the Philippines.  It appears that these people were taken advantage of and oppressed by the U.S. decision to rule.  If there is any justification in the matter, then it is in the pure fact that the U.S. was competing in a period of time where trade and colonial possessions mattered.  With the U.S. interest in the global market, the Panama Canal and the acquisition of territories were on high priority.  The Philippines were just a nation under conflict, while the U.S. took advantage of the situation and acquired the colony as its own.</p>

=========yorg=========
===from:Jodi Combs
===date:Sun Sep 14 18:24:32 2003
===subject:White Man's Burden
===message:I believe that the cartoon shows that the White man was superior to any other race.  I also believe that since the beginning even though we are a diverse society now.  Back then the white elite man always seem to prevail in almost every circumstance.  I do believe at one time in history that we were racists in some aspect, but over a long period of time, American's realized that we all are a mixed society.

I do not think that Kipling's point of view, the white man's rule was something that we should base all Americans voice on.  Tillman and Twain had exact opposite views on the Philippines rule.  They did not believe that the White man should make their views in counties were they were not under the same upbringing.  Why should we inflict our values and beliefs on the whole world?  Democracy is best, I agree, but that is all we know.  


=========yorg=========
===from:Jade Lee
===email:jadelee@bellsouth.net
===date:Mon Sep 15 16:21:30 2003
===subject:White Man's Burden
===message:The cartoon on page 4 of "Exploring America" captures the meaning of "White Man's Burden" in the fact that it shows a Native American (a "non-white" man) being exposed to an aspect of American civilization.  But it also shows the white man carrying the Native American on his back as if he is being forced to assimilate into American culture.   This may have been the case in many instances such as annexation of foreign countries by America, where the people may not have had a choice, or in the case of African Americans being brought over to America against their will.   However, many people, including foreigners, welcomed imperialism in hopes to improve their country's economic and social welfare.   Throughout history, America has, in many instances, proven to be racist, exploitative, and elitist by making American values and standards the "ideal" for ALL people and often forcing that ideal on unsuspecting foreigners or newcomers.   Kipling was an advocate of imperialism because he thought that it would beneficial to the Phillipines in an economic and social aspect.   Tillman and Twain were opponents of imperialism; they both believed that it was more of an insult and degradation to the people than a benefit to them.   Due to the extensive bloody battle that occured as a result of the annexation of the Phillipines, it may have not been justified for America to annex the Phillipines. 
=========yorg=========
===from:Jeremy Banes
===date:Mon Sep 15 21:53:32 2003
===subject:Not all white men
===message:I believe that the cartoon is exactly what Kipling had in mind when he wrote the poem.  He truly felt that white people could conform any group to their beliefs if they just tried hard enough.  I believe he also thought it was the best thing for the "half devil half children" (exerpt from poem). Kipling simply thought his way of living was best for everyone.  This narrowmindedness leads to racism, exploiteveness, and obviously an elitist attitude.  Kipling's attitudes really are not much different than one you might see in a cult of some kind, except he was well respected, so his opinion counted.  Of course, he was not the only one with these beliefs.  Tillman took the poem a bit farther.  He stated "those people are not ready for our institutions".  He essentially believed that it was not worth our time to try to conform these people.  Twain, of course, had a different opinion.  He felt that forcing liberation would not be very liberating.  You might think these views died in the early 1900's, but you would be wrong.  Clear up until the 1970's, the government in Australia tried to "whiten" the Aberidgnie (spell?) people by interacial coupling.  they even hade it done to how many generations it took to make them appear completely "white" and join the rest of the country.  I won't bore you with details, but you can rent a movie about it at Blockbuster called "Rabbit Proof Fence", but honestly, it is morally distrubing.  Anyway, the point is that many people thought that the white way was the right way, which is truly unfortunate and closedminded thinking.
As far as to whether the United States was justified in annexing the Phillipines, that certainly depends on your point of view.  From a strategic standpoint -- ports for American goods and possible military uses -- it seems like a good idea.  From the standpoint of the people already there -- I bet you would get a different opinion.
=========yorg=========
===from:Jodi Combs
===date:Thu Sep 18 23:21:58 2003
===subject:White Man's Burden
===message:Just from reading the material and what I know in History about the United States, American's seem to feel that they are Elite from other countries.  We seem to have been the most powerful all through History.  Why wouldn't American's want to put their views and beliefs on other countries? They only feel that they are helping them. The US has never been viewed as a weak nation.  I think that the US sees it as their duty to help others and be proud of it because they can help.  
=========yorg=========
===from:Norris Jones
===date:Fri Sep 19  8:17:15 2003
===subject:White Man's Burden
===message:The attitudes of American back then the 1800’s is the same attitudes of Americans today. America is a very dominate force in the world and somewhere along the way we have felt we had to judge and jury of the world.  Believe me, I have traveled around the world and have listen to comments and views about American prejudice and racial attitude. I love this country and wouldn’t want to live anywhere else. Now, I still don’t agree with the action taken by our government when dealing with foreign policies. Yes, we do set ourselves above everyone, it either our way or no way. From a military point of view and tactics I think it was justified in annexing the Philippines. The views by Kipling, Tillman, and Twain were shared by many American. During that time it was important to support whatever the masses of the people supported.  
=========yorg=========
===from:Connie Walton
===date:Sat Sep 20 16:15:22 2003
===subject:White Man's Burden
===message:I fell that the cartoon shows the white man as being superior to other races at this time.  I also feel that  yes Americans are seen as racist and trying to push their views on other cultures.  I do not agree with this however.  I feel that our actions often times are necessary to perserve our freedoms.  I also think that we are known for helping other people to find the same kind of freedom that we enjoy.
Kipling thought that being superior gave you the right to control everything, while Twain and Tillman felt the opposite.
The overtaking of the Phillippines was a controversial action after we helped them end Spanish rule.  It's really hard to decide if we acted correctly in this situation.
=========yorg=========
===from:Pamela Carter
===date:Sun Sep 21 20:56:12 2003
===subject:White Man's Burden
===message:The cartoon is a perfect depiction of the "White Man's Burden". Retain superiority at all costs. Based upon what I have read in the assigned chapter and experiences I have had, Americans are racist, exploitive, and elitist when it comes to dealing with other groups. Again this goes back to the superiority complex they have. Kipling was a full supporter of imperalism while Twain and Tillman were opponents of it. As far as the U.S. being justified in annexing the Phillipines, I don't know if I agree or disagree. We have been unjustified in so many acts carried out in history that are now being seen as being justified so that our great leaders can look good.
=========yorg=========
===from:Chrisi Davis
===date:Sun Sep 21 21:42:09 2003
===subject:White Man's Burden
===message: I have several different thoughts while viewing the cartoon of "White Man's Burden" I feel that the illustration is an adequate depiction of the views felt by people like Kipling. Because of these attitudes and actions I do feel that America has at times projected an image to be racist and elite. I do not agree with the thought of the white man carrying this burden of rescuing the poor Indian to bring him to the ideal American life...I wonder what the white man would think if the Indians felt they were carrying a burden to enforce their beliefs and ideals on the white man. It seems like Kipling and others felt that it was necessary to educate the Indians and other groups of people in the American school...I do not understand why Kipling and others felt that their ideas and beliefs were superior above all others...I do feel that America has been exploitive to different groups of people by sweeping in and stripping them of their own ideals. Kipling and his supporters viewed imperialism as a saving grace and were staunch advocates...while Twain was quite the opposite reacting with his writings in reference to the annexing of the Phillipines..."To the Person Sitting in Darkness"  I think if there is a burden to carry it should be to respect other cultures and diversity and to not to impose your beliefs on them just as you do not want their beliefs imposed on you. I do not necessarily feel that currently today America is racist and exploitive...I do not think that our country could be such a diverse melting pot if we were. I do think that many foreign people run to America to live the American dream of freedom and at times we are forced to protect our country and often times our actions are viewed as racist,elite, and explotive. 
=========yorg=========
===from:Veronica McKeehan
===date:Sun Sep 21 22:28:12 2003
===subject:White Man's Burden
===message:I think that the picture on page 4 was a extremely accurate portriat of the way Americans felt at that time.  I do not feel that Americans are racist. (No more than any other culture or group!!!) Almost every culture/group consider their group to be superior. And to an extent I do feel that we are elitist. An elite is defined as powerful people who can influence the politcal process.  I believe that's why so many immigrants come to the US because of our power which gives us our freedom.  Tillman and Kipling were in favor of imperial power over the Philipines and Twain  was opposed. Was the US justified in annexing the Philippines? I am torn and don't really have a suitable answer for this one.
=========yorg=========
===from:Brenda Miller
===date:Mon Sep 22 11:01:40 2003
===subject:White Man's Burden
===message:The cartoon shows that the White Man feels it his his responsibilty to show others the better, right way of life.  It does not matter if other races or cultures do not like it or belive in it.  The white man feels he lives correctly and everyone, if shown the light, will agree.  American's are egotistical...which leads many of us into being racists, exploitive and elitist.  Our own belief of our greatness and the greatness of our country lead us into pushing our beliefs and ways of life onto others.  This has been reinforced by all of the immigrants coming to our country.  We feel that so many people are willing to come to America, that everyone should want to live like us and be like us.  Americans have tunnel vision and sometimes it is hard to put ourselves in the shoes of others and understand their beliefs, fears, and love for their culture.  Kipling believed that the people of the Philippines were half savage people who would benefit by being imperialized by the United States.  He saw it as a good thing for both the Philippines and the United States.Tillman saw it as another burdern for the United States.  He felt that we should not want to incorporate more people of other nationalities into our country.  He was very opposed to annexing the Philippines and tried to use Kiplings words in favor of his arguement.  Twain felt that annexing the Philippines was an injustice to the people of that nation.  In essence, how dare we feel that we should impose our beliefs on this country by gun point because we feel our way of doing things is better?  These were three very different men with three very different points of view!  I don't know if the U.S. was justified in annexing the Philippines.  I would like to say no because no one should fight with a country and tell them how to live and how they should be ruled, by force.  We would not stand for it!  But, times were different then...the United States was becoming powerful and setting the stage to be a super power.  Our country would be very different now if we had not fought the battles of our history.
=========yorg=========
===from:Linda Simmons
===institution:Hist 2112
===date:Mon Sep 22 13:19:06 2003
===subject:White Man's Burden
===message:I agree that this was the view of white Americans then.  They wanted to portray themselves as the savior, always helping the savages. In reality there was always an ulterior motive, behind their actions($$$$). Why did they think their culture & beliefs was so much better?? Because according to Mark Twain the Chinese people were good, clean, intelligent, hardworking people. He disagreed with annexing the Phillipines, because he knew America wasn't interested in the people and didn't always do right by them. Kipling felt as many Americans did, they justified the exploitation of people(slavery), and excused what the government did to the native Americans.  Tillman was afraid too many people of color would dominate(be a whiteman's burden). Things have improved tremendously over time but racism is still very much alive, here in America. 
=========yorg=========
===from:Kim Calleiro
===email:calleiros@aol.com
===date:Mon Sep 22 13:54:11 2003
===subject:white Man's Burden
===message:(lost first GREAT message!!!!) here goes...The cartoon did relfect the view of most American whites.  With domination of a culture or land comes a lot of responsibility and "Burdens". B. After reading the text I would agree that America, during that time, was indeed racist, they did expoit others, and did have an elitist attitude.  C. The views of Kiplin, Tillman, and Twain represented the views of Americans and the world.  People have views that are directly correlated with the way the are brough up(mostly) and the one who wins is the one who yells the loudest, whether it is ethical or not(there are exceptions)D. At that time, America felt it was justified, but of course today, no one country should dominate unles that country is calling out for help and wants to become one w/ another country.
=========yorg=========
===from:Petrina Davis
===email:csu17930@mail.claytonstate.net
===date:Mon Sep 22 17:49:54 2003
===subject:White Man's Burden
===message:Yes, some Americans are racist, exploitive, and elitist. If people did not live a certain way or act a certain way they viewed them as inferior. How ignorant is that? Different does not always mean better. The cartoon, to me, portrayed the white man struggling to make the land a better place to live for them. The school on top of the hill could symbolize knowledge which leads to money which leads to power. The dead man in the grass symbolizes what could happen if anyone stood in the way of their imperialistic journey.
=========yorg=========
===from:Petrina Davis
===email:csu17930@mail.claytonstate.net
===date:Mon Sep 22 18:03:10 2003
===subject:Kipling, Tillman, and Twain
===message:I think the three men all agreed with imperialism in different ways. Twain disagreed with the methods the U.S used to gain power not with the idea of imperialism all together. Kipling was all for it. Which I really didn't understand. He had such strong views and he wasn't from America. Tillman did not feel as strongly as Kipling, but if he could maintain the "superior race" he was all for it. I think he hid his true feelings on imperialism. 
=========yorg=========
===from:Ashley Spillers
===date:Mon Sep 22 21:07:01 2003
===subject:White Man's Burden
===message:Americans tend to be jaded and opinionated when it comes to other countries and the people of other countries.  Americans tend to have an attitude of "our policies and our ways of doing things are the best, so other people are completely wrong."  Without taking into account that other people are just "different",  Americans believe that their way of doings things is not the best way.  In other words, they believe they are the "elite" of the world.  At this point in history, at present day, we take foreign affairs in other countries into our own hands, kind of like a pity for other countries.  Americans can be racist in this way, believing that other countries should be subservient to us in a way, because of all that we do to try to help them.  In this way, Americans can exploit other cultures by trying to "westernize" them;  Americans will try to push their culture as the best way to live, instead of taking their own culture into account.  
=========yorg=========
===from:Esther Kathleen Evans
===date:Mon Sep 22 21:28:48 2003
===subject:White Man's Burden
===message:The carton. to me, portrayed the white man struggling to enforce his way on someone else, even if it has to be an uphill battle the whole way, and regardless of who might stand in the way (the dead man). The schoolhouse reminds me of how America tried to assimulate Native Americans with the "education" of their children. When America enforces its beliefs on another country, it crosses a fine line between protecting our own freedoms and infringing on the freedoms of other people. I think Tillman had a somewhat racist view of imperialism in that he did not want large numbers of "other races" associated with the United States. Kipling had a go and get it attitude. He believed it was the "White Man's Burden" to civilize "backward" peoples. This idea is somewhat similar to the United States current desire to "protect the free world." Twain believed it would be a mistake to continue with America's imperialism. He thought that America should not continue to force ourselves on other cultures and countries. The "tutelage" justfication that the US used to justify our role in the Phillippines, I believe, was at best a weak excuse to get at a good thing. While the Phillippines economy improves with unrestricted free trade with the United States, so did the United States greatly benefit. The United States did help the Phillippine to set up a government, but it was a government that mimicked ours. While this is not necessarily a bad thing, why not let them set up their government their way? But by having such strong influence in their governing body means that the US will still have a good trading partner in the future. It also allows us to continue to use their ports, which in turn help the United States greatly during WWII.  
=========yorg=========
===from:Delvanie Williams
===date:Mon Sep 22 21:45:41 2003
===subject:White Man's Burden
===message: Based on the reading, Americans are not racist but they are exploitive and elitists. If they see something that they want or need, they take it without any regard to whether or not they are entitled to it. When America made the decision to annex the Philippines it was influenced by their need for a naval base and a coaling station. The Filipino's strongly opposed colonization and didn't want to be annexed. But the Americans didn't care they only saw that the Philippines had something that they needed. This action alone shows the disregard America had for non-Americans. Kipling and Tillman, were in favor of imperialism, because they felt that non- whites were inferior. Whereas Twain, felt that imperialism was morally wrong. In conclusion, we were not justified in our annexation of the Philippines.     
=========yorg=========
===from:B. Kornegay
===date:Mon Sep 22 22:02:17 2003
===subject:Burden of Proof
===message:The cartoon well depicts the view that Rudyard Kipling had of the U.S.  He truly felt it was a benefit to the captured nations to be dominated by the U.S. I know Americans are racist. History and current events prove this fact.  I also think that Americans are exploitive and elitist when dealing with other nations.  The U.S. uses its' position as the richest and most powerful country in the world to force other nations to do what it commands.  As evidenced by the war on Iraq, the U.S. will use any means to accomplish what it wants. The U.S tried to use 9/11 as the force behind war against Iraq. This was a lie, but will eventually become the truth in the History books.
<br>
Kipling agreed with Imperialism.  He thought it made "savage nations" become civilized and that it was the "duty" of America to capture other nations and make them "better". Tillman was a racist from the south and did not agree with the decision to annex the Philippines. He felt that 2 races could not "mix and mix without injury to the civilization of the higher race". AS IF THERE IS A SUCH THING AS A HIGHER RACE!! Ridiculous. Twain felt that American Imperialism, or the forcing of other nations to do as the U.S. pleases, is wrong. He felt that Kipling’s view of the "White Mans Burden" was hypocritical and that the flag for America should be the Skull-n-crossbones of pirates.  
<br>
I do not think the U.S. was justified in annexing the Philippines. They fought bloody wars with the Spaniards, then with the Filipinos, to gain and keep control of the island.  The U.S. is such a powerful country that other nations must obey or suffer the consequences. This is still true today, though it will not last forever.

=========yorg=========
===from:Michael White
===date:Mon Sep 22 22:09:05 2003
===subject:White Man's Burden 
===message:Americans almost always have been prejudice toward others that are from other countries or that are from completely different backgrounds as them. They have a hard time of tolerating and understanding the cultures and differences of others. Many Americans think that America is  the most elite country in the world and that nothing can stop us or hurt us, but many Americans post-9/11 have seen that we can be hurt, and see how easily our freedom could be taken away. I think 9/11 opened up a lot of people’s eyes and has drawn American from all different cultures together. 
=========yorg=========
===from:Tamanika Sims
===date:Mon Sep 22 22:31:43 2003
===subject:White Man's Burden
===message:The cartoon on page 4, in my opinion, captures the meaning of "White Man's Burden" quite well.  In my opinion Americans are racist, exploitive, and elitist when it comes to dealing with other people of the world.  Americans tend to think that other people are inferior and need to be civilized.  Americans see other cultures as barbaric and uncivilized.  Kipling and Tillmans views were similiar.  They saw brown people as needing to be rescued and to receive the blessings of liberty and civilization.  Twain saw this as hypocrisy as noted in "To The Person Sitting In Darkness".  His Elitist views show in the name of his Poem. I do not believe the United States was justified in annexing the Philipines.            
=========yorg=========
===from:Annmarie Corrow
===date:Mon Sep 22 22:35:45 2003
===subject:White Man's Burden
===message:The cartoon does depict the burden by showing an American carrying away a “half-savage” person to be educated in an English-speaking school.  Once America annexed a country in order to gain trade superiority, it also would subject its culture, whether the country wanted it or not. Depending on the goals and views of America at any particular time, they were racist, exploitive and elitist.  Americans felt they were superior even though other countries, such as the Philippines, had an educated and professional population.  If a country had what America wanted, such as an interest in international trade, then America felt it had a right to have a portion of it, if not all.  Kipling was an advocate of imperialism.  Tillman, although impressed by Kipling, was against imperialism and felt that if America would annex the Philippines, Filipinos would have a loss of “self-respect.”  Twain also was against imperialism saying it was “the newest form of greed.”  I don’t believe the U.S. should have annexed the Philippines because like Carnegie felt, the tax money spent on foreign problems could have been spent in the U.S.
=========yorg=========
===from:Myesha Cottom
===date:Mon Sep 22 22:54:20 2003
===subject:White Man's Burden
===message:Is it just me or is the soldier in the cartoon holding a monkey?  I think the picture captures what the government thought/thinks is an accurate depiction of the "White Man's Burden".  Yes, I do believe Americans are racist, exploitive and elitist when it comes to dealing with other people.  I believe foreign policy and peace efforts are excuses to exhort the power that we have over people.  We help people to show the world that we can.  We go to war to show the world that we can.  We annex countries to show the world that we can.  Kipling felt that imperialism was the white man's moral obligation and that it would civilize the people.  Tillman thought that it would continue to create more burdens for the white man and force them to try to live with more "intolerable" people or peoples.  Twain thought that imperialism was hypocritical and that it would against all that America stood for.  America the free, trying to inhabit a country that doesn't want it.  No, America was not justified in annexing the Phillippines -- it is hypocritical, but then America always has been.
=========yorg=========
