#!/usr/bin/perl -si

require "ctime.pl";
require "/local/classnet/cgi-bin/netforum2/lib/sys_config";
require "/local/classnet/cgi-bin/netforum2/lib/forum_config";
if($allow_forum_config){
require "/local/classnet/cgi-bin/netforum2/AGRON206/forum_config";
}
require "/local/classnet/cgi-bin/netforum2/lib/main";
require "/local/classnet/cgi-bin/netforum2/lib/variables";
require "/local/classnet/cgi-bin/netforum2/lib/utilities";


$which_forum = "AGRON206";
$script_name = 'a';
$netforum_url = "$base_url/AGRON206/$script_name";

$forum_name = "AGRON206";
$forum_owner = "ClassNet Instructor";
$forum_owner_code_name = "cnet";
$forum_monitor = "Cinzia Cervato";
$forum_monitor_email = "cinzia\@iastate.edu";



if ($ENV{'REQUEST_METHOD'} eq 'GET') {
	&get_url_vars;
	&get_command;
}

if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	&ReadParse();
	&get_url_vars;
	&post_command;
}

