===from:Chris Schmidt
===email:chris@d2dtech.com
===date:Sat Mar 29 11:38:32 2003
===subject:Women in the '50s
===message:<p>During the '50s, the number of women in the workforce actualy increased, but I think this belies the actual trend in society at the time. Looking at '50s television gives a good idea what society's ideals were at the time. Just as it does today, television depicts our social ideals if not our reality. Women in general wanted a traditional maternal life in the home. The only real reason there was to enter the workforce as a woman (and take a grossly underpaid position) was to supplement a low income husband. I think the rise of women in the workforce was related more to the increased tax burdon on the family than on women's desire to persue careers.</p>
<p>Educational institutions reenforced society's ideals, by requiring homemaker oriented classes for women and trade oriented classes for men. I think the middle century was the decisive turning point in the American education establishment's focus from education to indoctrination. The enforcement of women's roles in the educational sector is evidence of this. Indocrintation took precidence over critical thinking and reasoning.</p>
<p>Women weren't better off as far as personal liberty in the '50s, but the family unit probably was. However, the rising tax burdon on the middle class to pay for higher defense expendatures and social welfare programs would eventualy force more and more families into dual income dependency.</p>
=========yorg=========
===from:Lorena Lockhart
===date:Sun Mar 30  9:35:24 2003
===subject:Women in the 50's
===message:Women still had to fulfill a double duty both as mother and wife after the war. The war forced women to work when her duty was at home raising her children. Now with the economy struggle to make ends meat women are forced to work like their husband to be able to survive in the 1950's. Also, single mother had to work, probably even harder, to take care of their children because they did not have a husband or a man to help them out. The education system promoted a woman place is in the home so women were schooled in typing, etiquette, and cooking. What popular culture should have portrayed women as were super natural, mutli talented, multi task, and can get many jobs done at one time, and until today it still should but instead popular culture portrayed women as cozy helpmates, dumb blonds, and happy little homemakers. So the standard of women in the 1950's compared to now in my opinion really hasn't changed, yes more top level jobs are open for women to apply for as men, top paying position are out there for women to apply for as men and overall the opportunity looks better for the women in today's society compared to those of the 1950's but the underlying truth of the matter is that to society's top level executives and even to some women themselves a woman place will always be in the home and no where else; what always look better isn't always better. Our history, what brought us to this point hasn't gone any where we are still living it today, the wars, slavery, discrimination, hatred and many more, but it looks better than the pass and it is called something new but in the end it is all the same.     
=========yorg=========
===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Thu Apr  3 10:00:09 2003
===subject:Chapter 9 Discussion
===message:"American culture emphasized that women found their truest fulfillment and made their greatest contribution to national life as wives and mothers."  In the midst of the Cold War and the Red Scare of the 1950's, women found their role as the wives and mothers who provided a safe haven for the working men and the goal for the country to be reunited.  Women were portrayed as fixtures in the kitchens of America.  Although this was certainly a pretty picture of the calm and normality that the country was seeking, it was not always the truth behind closed doors.  Certainly not every woman was happy being the housewife, which became apparent in the Women's movements of the 60's.  Men were encouraged to seek higher educations while women were encouraged to have babies.  I do not think it can honestly be said that women were "better off" in the 1950's than they are today; however, times were different and the majority of women then thought they were better off than we might believe.  I really think it depends of which time you live in for you to be able to determine who was "better off".  Women of today might disagree that being a housewife and mother should the primary goal of all women.  
=========yorg=========
===from:Robert Napier
===date:Fri Apr  4 13:32:21 2003
===subject:Women in the 50's
===message:It took about a second of thought to realize that women had no work force in the 1950, but on the home front it was a different story. The times dictated that the only role that a woman could have was to be a stay at home mom. Now I realize that some women went out into the work force, but the vast majority stayed at home with their children. See the miss conception was that a women could bear children and run the household effectively, but she didn’t have capability of running a company, or group of men. Now just like in every generation, someone comes along and tells us how we should be as a family and in the fifties was no exception, because it had the likes of Dr. Benjamin Spoke, author of Baby and Child care, tell America at that time that women needed to be at home raising their children. Did television and movies portray women the way they were in the fifties? I say yes, because the only programs on television were the ones that showed women in the kitchen, cleaning the house, or waiting for their husband to come home. I think television and movies always portray what is happen at that time. The educational institutions did nothing for women in fifties, but give them the impression that college was only good for the men in society. A few women did receive their degree, but this practice was far from the norm. The women of today are far better off than their great grandmothers were, because they truly do have the ability to be what ever they want to be. They have the ability to go to college, be president of company, start up their own business, and have a spouse that supports them in what ever they decide to do. In closing, I like to say that one of the most important things that women have today is their ability to speak for themselves.
=========yorg=========
===from:Kathryn D. Hambrick-Mateen
===date:Fri Apr  4 15:30:49 2003
===subject:women in the 1950's
===message:During the 1950's middle class white Americans were romanticizing the ideal of the good life,and trying to forget about all the choas from the decades before. The trend at that time was marry young have a large family which meant a woman's place was in the home, beig a mother, raising her children, and being the ultra feminine wife. That was a good thing.This was the age of the Baby Boomers,from the Vietnam generation to the Me generation.It was said that motherhood, was the most truest, fulfilling,and greatest contribution to national life a woman could be in.Television had sitcoms of the idea girl next door,the perfect wife, the perfect and best father images played by movie stars. Girls were not encouraged to obtain higher education,but if the did it was in the fields of home economics or primary education. I believe women were passive and felt obligated to conform to societial pressures. Keeping up a facade that everything was perfect on the home front sent women back to work. World War II introduced to women a since of individuality that was their own,a since of power and self worth,that they could do other things than just be a baby making machine. Also if the wife did not dance to the tune of the music another ballerina took her place.High divorce rates were not uncommon in the 1950's.Women worked to supplement the house hold income, to get that little something extra they wanted ,or because they had to work. The woman wore different hats and still was considered or expected to remain a "girl". War makes strange bed partners, women were trying to balance the emotional roller coaster their husband may have been experiencing from being in the war, and the rapid changes in the world along with societal expectations.If one was a middle class,white American woman in the 1950's things were good,but if you were any other class of women during the 1950's it was "HELL".Was things better for women during the 1950's really depends on who,what and where you were during that time. Woman today are awesome,it makes no difference who you are,or where you come from if you got the know how and the will you can do just about anything.We are living in the greatest time in history. Women are better off today than our mother's. We are "WOMAN"not girls,if we want to play that role it is by choice only.
=========yorg=========
===from:Ursula Davis
===date:Sat Apr  5 15:44:43 2003
===subject:Sex roles and women in the 1950's
===message:Women in the 1950's played a supporting role in regards to the workforce as well as family.  Women were expected to prioritize getting married, having children, and taking care of said children and husband.  They were to be a support to their husbands who were the bread winners and providers for the family.  After WWII, women were not expected to work although many still did.  Those that worked, did so in order to help support and add to their families income.  Working only helped to sustain the American image that was being portrayed in society.  These jobs did not pay alot and had no prestige, so they probably did not give the women any sense of self-worth or satifaction.  Television and movies helped to encourage and normalize these stereotypes.  Women were seen as sweet, submissive beings who's sole purpose was to take care of their men, home, and children, in that order.  Any women who did not conform to this stereotype suffered from a psychological disorder or had the desire to be a man.  The television shows like "Leave it to Beaver" and "Father knows Best", were probably correct in their portrayal of women in the 1950's and were instrumental in continuing the psychological reinforcement of these stereotypes as the norm.  The educational system was another institution in which women were forced into the role of nurturer.  Girls were given courses in typing, etiquette and cooking in grade school and girls were discouraged from seeking higher education.  Those who did pursue college degrees did so in professions like teaching and home economics.  I do not think that women were better off on a personal level in the 1950's because they were(and still are) second class citizens whose very existence was to bear and raise children, and support their husbands.  There was no personal choice or thoughts of self.  The very freedoms the U.S. had fought two wars for did not apply and I am sure that this caused some psychological issues like depression.  Women today have more freedoms, and are able to make more choices and try to achieve what they want.  Other issues make it hard like the battle to be a good mother, wife, and career women.  Economic equality remains and issue as well as  basic views of the dominant sex no matter the culture.  The future for women is ever changing and I have no doubt that someday the tides will turn. 
=========yorg=========
===from:Kristi Smith
===date:Sun Apr  6 13:02:58 2003
===subject:Chpt 9 discuss
===message:In the ‘50’s women’s biggest role seemed to be as a housewife and mother.  This role was the one portrayed as the most important and beneficial to the “family”.  Popular culture did reflect the reality of women’s lives with shows such as “Father knows Best”; portraying the woman/mother of the house, in the title alone, as the least influential.  Educational institutions also reinforced these roles on women by allowing men to take classes like carpentry and auto mechanics, while women/girls were taking classes geared more towards home life of home economics.  Allowing the girls to take typing classes was somewhat of a change, because this was not something used “in the home”. 

What a loaded question about being better off!  In the 50’s it seemed as though the social aspect of the “woman’s role” was accepted as a housewife and mother only.  From what I read, I gathered that is what women wanted in those days and they were happy with that.  On the contrary, obviously women today are totally different in what they want and how they go about getting it.  I think that women are better off now for numerous reasons.  First, they don’t have to rely on a man/husband to get what they want, i.e. education, money.  Second, women are given the chance to succeed in school, just as equal as the man; however we all know there are still problems with that in the work force but they do seem to be diminishing.  

=========yorg=========
===from:Chad-Everett Tisdale
===date:Tue Apr  8 15:33:54 2003
===subject:the movement halted
===message:It seems to me that the movement to better women's place in society and promote gender equality was slowed extremely.  Television set up the standard by which women were judged in the characters of Mary Tyler Moore and so forth.  These were the neatly dressed women rarely seen without a cooking apron on and always had warm cookies just out of the oven.  Perhaps many women followed this template because they had little choice.  Less women were working that in previous decades but more of those that were working had children as well.  According to Dr. Spock and others, women were bred to stay in the home.  While women were given more respect as mothers they were probably looked down on if they left the home.  It seems to me that they were seen as helpless creatures that had to hold a man's arm when they left the house because they were so weak.  To sumise all of this, women were not seen as being able to survive independent of men
=========yorg=========
===from:Kevin Tyler
===date:Tue Apr  8 16:16:05 2003
===subject:Discussion
===message:In the 1950's women did not play a significant role in the work force, but they played a major part in the household.  The work force was a male dominated group.  This is not to say that woman could not handle working outside of the home.  This was a period when woman were just begining to transition out of the traditional role as it were in the early 1900's with woman taking care of the house and the man working.  Popular culture back then did reveal a reality because more woman were staying at home during that time. Educational institutions contributed by only training woman for domestic tasks.  I think it is hard to say which era of woman were better off because they are too different to compare and contrast.  Their are alot of things happening today that were un heard of back then and vice versa. 
=========yorg=========
===from:James Pike
===date:Wed Apr  9 18:22:58 2003
===subject:Chapter 9
===message:During the 1950s, women played a small role in the work force and a large role in family life.  Within the workforce, women were confined to roles that kept them as “girls”.  This probably means that they were kept as secretaries and other small jobs. They definitely did not support themselves or their family in the way than any women do today.  Even though their role in the workforce may have seemed menial, women slowly gained more and more jobs and many women began to work.  I think that the statistic in the chapter is 60 percent of women held a part-time or full-time job by the 1960s.  So even though they were doing small jobs, more and more women saw work as acceptable.  
Popular culture, such as movies and television, hardly ever demonstrates any reality of actual life.  This was the case in the 1950s.  With the television shows portraying women in housewife roles and in the kitchen, television limited the reality of life for women.  Granted, some women may have lived the way that they were portrayed on television and in the movies, but this was more than likely the exception, not the rule.  Within movies, women were given the role of the “dumb blonde”.  This role was definitely not true.  Women have not gotten smarter over the past 50 years; they have just begun to demonstrate their intelligence more often.  Many women, housewife or CEO, can run a household and deal with the responsibilities that go along with this task.  Furthermore, women can hold jobs while handling business at home.  They did it then, and they can do it now.  
Going along with my statement that women have been given and display their intelligence, women in the 1950s were given a sex role in educational settings.  Through this, the educational system supported the role of women being in the home.  Through sewing classes, typing, and cooking, women were given the training in what was considered to be their areas.  Men were also trained in what was accepted as their areas, such as carpentry, auto mechanics, and career training.  Furthermore, men were influenced to move on to higher education while women were persuaded and lead to marry and start a family, not go to college.  
Were women better off in the 1950s?  Well, I guess that depends on what you see as “better off.”  If being expected, by society, to cook, clean, and raise children as being better off than being forced, by an irresponsible significant other, to cook, clean, and raise a child, while holding a job to support yourself and your child, then women were better off in the 1950s.  Personally, I think that women have a better opportunity in life than they did in the 1950s.  Many women go to college, run businesses, and control their lives in a way that women 50 years ago could not do or were not supposed to do.  However, with the rise of divorce in America, many women are forced to do take on the role of both mother and father, something that was not common 50 years ago.  This could be for several reasons, but that is not why we are to discuss.  But because of the ability of women to support themselves on their own, dependency on a man is not as relied on as much as in the 1950s.  
I am curious to hear the thoughts of anyone on anything that I have written above or left out.  I am also willing to hear if you believe that the rise in divorce is in anyway related to the independence of the “modern” women.      


=========yorg=========
===from:Carla Foster
===date:Sun Apr 13 18:11:24 2003
===subject:Chapter 9 Reply
===message:A women's role during the 1950s was, in some cases, double duty - housewife and mother, and a working woman.  However, working was only to add to the family income and not to establish their own identity or business.  Poplar culture glorified marriage and depicted the women's primary role as being a wife and mother.  Domesticity was considered the right thing to do and everything else was secondary.  Domesticity was to provide "true fulfillment" to a women even though this thinking may have been a little overrated.  Shows like "Make Room for Daddy" showed the wife at home.  The show's stories depicted the home and working life of Danny Williams, a man whose career often leaves him with little time to spend with this family.  This was acceptable as the head of the household and breadwinner.  The educational system also reinforced the sex roles.  Girls learned typing, cooking, sewing, and etiquette while boys were directed to careers or skills that would provide them with an income to take care of a family.  Were women "better off" in the 1950s than they are today?  It is difficult to address this question as times were different then than now.  I feel, of course, women are "better-off" now because of the opportunities available, but women in the 1950s may have also thought their way of life made them "better-off" at the time.
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Mon Apr 14 10:34:46 2003
===subject:ch9
===message:What role did women play in the work force and in the family during the 1950s? Did popular culture (television, movies) reflect the reality of women's lives? How did educational institutions reinforce sex roles in the 1950s? Were women "better-off" in the 1950s than they are today? 

women's role in the 1950's basically consisted of them tending to the home. they raised the children, cooked the meals, and kept house. in the work force, they didn't receive equal pay against the men they worked with. they did not get jobs of executive positons or that were considered "men" jobs.
popular culture glorified marriage and parenthood and depicted a woman's devotion to life in the home with her children as the most cherished goal. tv usually showed a woman at home in the kitchen. films made working women appear to be neurotic and the stay at home mothers to be loving. this of course was a stereotype but did exist in reality due to society's influence encouraging women to "be this type of woman" to be a real woman.
education institutions would gear the girls towards home economics,sewing and "girlie" classes and were urge to not further their education through college, the boys would be urged to take, woodshop,carpentry, and business courses, and urged to go to college. even after college,the women who did attend ended up in careers such as primary education where they were still functioning as mother figures.
no i don't feel that women were better off in the 50's. women today have the opprotunity to do and become anything and anyone they please. women then, were suppressed and trapped into roles that they may not have necessisarly intended on.they were limited. and nowadays there are no limits for women, because we are strong enough to tear down any obstacle that may attempt to hold us back from getting what we want from life.
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Mon Apr 14 10:44:32 2003
===subject:stay at home mom in the 2000's
===message:what do you guys feel the reason is today for stay at home mothers who tend to the home?

do you think that it is due to economics,or by choice. do you feel as though more and more women are showing a reminiscent attitude of taking care of home?

i am a stay at home mommy,and fulltime student. i do it by choice and because it is economically feesable. i see no logic in paying$1500 to complete strangers to raise my 2 little men, while i work just enough to pay them, and try to attend school. so i home school my 4 year old while caring for my 12 month old. i find it pleasure in what i do and it is very rewarding, however it is nothing compared to what it once was in the 50's. not only do i have to do all of what they did, but i have to teach additional material being that he is home taught, and i have to try to earn a nursing degree. so at times it can be very hectic and rough. just wanted to know what you guys thought about present day stay at home mothers.
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Mon Apr 14 11:16:36 2003
===subject:response to carla
===message:hi carla,

yes i agree with you as well as chris. expelling a baby from your womb is definately not and indication of a good mother. that's an indication of a good pusher LOL. seriously, you are right as well. parenting is a joint effort thus requiring both mom and dad to be present extremely often. my husband brings in the only income in our family, i homeschool my 4 year old and 12 month old while earing a nursing degree, and i also manage the household bills, coordinate play groups, do freelance graphics work, and we have the happiest home. yes, throughout the chaos i loose my mind some days, as do any other woman in the workplace or out. we're entitled. hormonal imbalances along can cause this to occur LOL!!! but i am one of the happy stay at home mom's. i feel it's worth it if it's possible. and i feel that those who work can be just as happy or unhappy in the workplace. life is what you make it. happiness is how you perceive life. i work with what i have and i feel i'm blessed. a woman who has to work may feel the same or may wish that she was at home. it all depends :0)
=========yorg=========
===from:Bethany Ballard
===date:Mon Apr 14 20:17:14 2003
===subject:chapter 9
===message:In the 1950's, more women began to work outside the home in order to earn extra money and to contribute to the household income. The number of those women who were married and had children also rose during the 50's.  Popular culture did not reflect the reality of women's lives because it depicted a woman's devotion to life in the homew with her children as the most cherished goal.  It almost always depicted the mother at home in the kitchen, which was not the case of many women working outside the home during that time.  Educational institutions reinforced sex roles by teaching girls things such as typing, etiquette, and cooking, while boys learned carpentry, auto mechanics and courses leading to careers.  Guidance counselors encouraged young girls to marry instead of going to college and told them that men were not interested in college degrees, but in the warmth and humanness of the girls they marry.  Therefore, very few girls attended college and very few received degrees. Women are definetly better off today than they were in the 1950's.  Today, women still don't receive equal pay as men, but their wages have improved, and women are allowed to be more independent as far as whether or not they want to have kids, or get married, or go to college.  Women are not discouraged from getting an education and have a lot more freedom.
=========yorg=========
===from:Lucille Clayton
===institution:HIST 2110
===date:Tue Apr 15  6:09:00 2003
===subject:Chapter 9 Women in the 1950's
===message:After men returned home from the battlefields, women workers in factory and businesses were replaced by them. Most women returned home and satisfied themselves with the role of housewife and mother, while their husband "bought home the bacon."  This role was encouraged and exalted throughout society.  A woman's place was at home and taking care of her family was to be delighted and satisfying.
Television portrayed women as happy housewives and pedestal dolls.  They stayed at home and took care of the children while the father worked outside of the home, providing for his family.
Educational systems also help define the role of the sexes.  While young men were encouraged to take courses that would prepare them for outside the home work, young ladies were taught how to be good homemakers.  They took classes such as home economics.  If they decided to pursue a higher education in college they were often steered in such fields as secretarial or teaching.
I think that women were better-off in the 1950s because they had men that wanted to take care of the family and "bring home the bacon."  Being a housewife and mother was a very respected occupation.  It had its downfalls, but it gave the family unit more stability and warmth.  This is something that is missing in our society today.  Because of the demands of jobs and the desire to have more, parents are normally under so much stress to do more that the family unit usually suffers.  Women have accomplished alot but we have had to and are still paying the price.
=========yorg=========
===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Tue Apr 15 14:25:47 2003
===subject:Women not paid as much?
===message:Where does everyone keep getting the idea that women are still not paid as much as men?  I know this was an issue at some point in time, but having worked in a law office for a number of years and knowing that Title VII protects against such sex discrimination, I am not sure why some still believe this is frequently happening.  Even when it does still occur periodically, it's illegal and the person who was discriminated against has every right to sue.  
=========yorg=========
===from:Raychele Ryans
===date:Sat Apr 19 12:09:28 2003
===subject:Hist2110 chpt9
===message:Women's roles in the 1950s was that of a housewife and mother.  Women were not encouraged to have careers.  Television and movies depicted the same believes that a happy women is one that stays at home and is devoted to her husband and children. Career women were depicted as unhappy and neurotic.  The educational system reinforced these notions that a women's place is in her home raising a family.  Schools encouraged girls to take typing, cooking and etiquette classes, whereas boys took classes that lead to careers such as carpentry, and auto mechanics.  I feel that women have it much better today.  We can raise a family and have a career!
=========yorg=========
===from:Al DEsmond
===date:Sun Apr 20  2:00:53 2003
===subject:Chapter 9 Discussion
===message:In the 1950's, more women began to work outside the home in order to earn extra money for various reasons.  Thier was first of all a lot of single women who now was the only income for the home due to the war. We also must acknowledge that TV only dipicted the caucasion women and not the total spectrum of the women of this time.  With that being said televesion did not reflect the spectrum of the women's lives. The number of those women who were married and had children also rose during the 50's. Popular culture did not reflect the reality of women's lives because it depicted a woman's devotion to life in the home with her children as the most cherished goal. It almost always depicted the mother at home in the kitchen, which was not the case of many women working outside the home during that time. Educational institutions reinforced sex roles by teaching girls things such as typing, etiquette, and cooking, while boys learned carpentry, auto mechanics and courses leading to careers. Guidance counselors encouraged young girls to marry instead of going to college and told them that men were not interested in college degrees, but in the warmth and humanness of the girls they marry. Therefore, very few girls attended college and very few received degrees. Women are definetly better off today than they were in the 1950's. Today, women still don't receive equal pay as men, but their wages have improved, and women are allowed to be more independent as far as whether or not they want to have kids, or get married, or go to college. Women are not discouraged from getting an education and have a lot more opportunity to enjoy thier freedom without persecution!
=========yorg=========
===from:kevin g
===date:Sun Apr 20 17:03:21 2003
===subject:honey im home!
===message:While many women were having to leave the work force (last hired first fired),there were still many women having to remain in the workforce.  There are several reasons for this: 1. it was considered a womans job (phone operator, secretary, etc...)2. they were now the sole survivor in the family unit (husband died in war, etc...) 3. Women were having less children and less frequently getting married.  Pop culture did not reflect womens lives because it depicted them as; at home, with children, vacuuming with pearls, and waiting for the man of the house to come home so she could fix him a martini and his favorite pipe.  Education was glad to teach women as long as they were teaching them how to sew, cook, clean, and be a beautician.  Women are much better off today than they were in the 1950's.  They now hold executive positions in major corporations and enjoy the equality they deserve.
=========yorg=========
===from:Johnnetta
===date:Wed Apr 23 22:03:56 2003
===subject:hist 2110
===message:The roles women played in the 1950s were housewives and they really did not work. Most women had to stay home and take care of the house and kids. Yes, the movies and television did reflect the lives of women because the shows portrayed the roles of women in the home. A good example would be I love Lucy that show, shows how the woman stays home and take care of the man of the house. The educational system believed that girls were to learn how to type, cook, and etiquette styles in order to become a wife one day. Then boys were to learn about cars,and having a trade that will lead to a career later in life. No, women are better off today because we can have the choice to stay at home or get a education. Today most women choose to enter the work force and the family share the household responsibility.  
=========yorg=========
===from:Connie Plowden
===date:Fri Apr 25 14:04:48 2003
===subject:Women in the 1950's
===message:Women in the 1950’s and 60’s, especially married, entered the labor force. Although working, they earned only 63 percent of what a man would make. In 1963 women found inspiration and courage in a book called The Feminine Mystique published by Betty Friedan. Betty Friedan argue that women had no outlets for expression other than finding a husband and bearing children. She encourage her readers to seek new roles and responsibilities, to seek their own personal and professional identities rather than have them defined by the outside, male-dominate society. Also, in the 1960’s organization such as NOW was established to bring American women into full participation in the mainstream of American society. 

Popular culture did not reflect the reality of women's lives in the 1950’s. Women in the 1950’s were depicted through television shows as happy loving housewives and mothers homes with their children. Television glorified marriage and parenthood, and tried to induce the stereotype that women that worked was neurotic and women that stayed home was happy. In actuality, women were entering the workforce, organizing women groups, and finding their own identity and respect in society.  

The educational institutions reinforce the issue that there was nothing more rewarding than being a mother and a housewife. Therefore, they were taught to type, cook, and be etiquette. On the other hand, boys were taught carpentry, auto mechanics and took courses that led to careers. 

In some aspects, I feel that women were better off in those days than they are now. Some women today, have found themselves having to be the mother, the father, the educator, the doctor, the worker, the counselor and the list goes on. This is all in part of cohabitation and the rising rate of divorce. Family values are not instilled in the same manner as they were 50 years ago. Whereas in the 50’s, a single mother would have probably been frown upon, but today it’s almost like the going thing. I personally think that it’s a shame and unfair, for a child not to be raised with both parents in a stable and well-nourished environment.  

=========yorg=========
===from:Kathryn Hatch
===date:Fri Apr 25 14:27:08 2003
===subject:Chapter 9
===message:Women played many roles in the work force and in the family during the 1950s.  It is true that many women did not work outside the home at this time because men were the primary “bread winners”; women were definitely encouraged not to work outside the home and to take care of their children (which, I think, is a great idea even today…it would be wonderful if it were possible in more families).


In response to the next question, when was it ever true that television reflected the reality of any person’s life?  If the people we saw on TV had normal lives like you or me, we wouldn’t want to watch it, because it would be boring to us.  I think TV in the 1950s represented, for the most part, the “ideal” family and paid little attention to anything else.  American families at this time were interested in harmony and happiness because they were tired of war and depression.


Educational institutions reinforced women’s’ role as housewife by steering them in domestic directions.  As it has been said many times, women took sewing and typing classes.  Also, colleges and universities were only considered as options for the woman who wanted a career, and I believe that many women at this time wanted to stay at home and take care of their families.  However, there were also many women who wanted to work outside the home and they found it more difficult to achieve this.


To reply to the last question: NO!  Women today are much better off.  Like I said earlier, many women in the 1950s were steered toward domestic roles that they might not have necessarily wanted to play.  Women at that time were encouraged to marry young.  Women today have the option to marry young and raise a family immediately (if that is what she wants to do) OR to go to college, backpack across Europe, have a career, and marry when she is 45 (or not at all).  Today, it is definitely a woman’s choice.

=========yorg=========
===from:LINDA DAWSON
===date:Sat Apr 26 19:16:49 2003
===subject:HIST2110
===message:By 1952, 2 million more women worked outside the home than had been employed during the war, and by 1960 nearly 40 percent of American women held full or part-time jobs. The proportion of working wives rose from 15 percent in 1940 to 30 percent in 1960. Yes, popular television and movies reflected the reality of women's lives with such TV hits as I Love Lucy and Ozzie and Harriet. Educational institutions reinforced sex roles in the 1950s becuase women constituted a smaller percentage of college students in the 1950s than in the 1920s and 1930s, and women received fewer advance degrees in those decades. Almost 2/3 of the college women in the fifties failed to complete a degree, and except in the most presitgious colleges, most of those who did graduate concentrated in fields such as home economics and education.
=========yorg=========
===from:Ashley Hughley
===date:Sat Apr 26 22:25:01 2003
===subject:HIST 2110
===message:In the 1950's, although women were able to enter the labor force they were still discriminated against.  The women who worked outside of the home were paid less than the men though. A lot of the women stayed at home, cooked, cleaned, and raised the children, while the men worked for the money to support the family.  To me, it's unfair how some of the way things were back then are still looked upon up to this current day.  A lot of women are still stereotyped because of their gender.  They are seen as the person who should do all the cooking, cleaning, and raising of children.  Women now can do just as much as a man can, if not, than more.  Men could also be the ones to stay at home and do everything, while the women go out and work.  For some reason I see more guys are able to cook and clean nowadays than a lot of the females anyway.  So all of the house work can be done by both males and females.  During the 1950's, t.v. showed programs that had women working only in the home, and thats not how it really was.  There were some women who had to work outside of the home in order to get money for the family, even if it was less than what a male would get.  What is even worse is how educational institutions only taught the males how to do "manly" things and the females how to do the "girly" things.  Of course women are better off now than they were back then.  Now it's against the law to pay people a certain amount because of their gender, and many women today are strong enough to voice their opinion as to whether they would want to stay at home and do everything or work outside of the home, unlike the 1950's, where the women who did stay at home did it because they just assumed it was their duty, since that's how they were raised. 
=========yorg=========
===from:Star Tomlinson
===date:Sun Apr 27 15:44:01 2003
===subject:Women's roles in 1950's
===message:During the uncertainty of the 1950’s, women played diverse roles in the U.S. while popular culture emphasized what it deemed to be a woman’s place in society.  Although the United States greatly depended on women labor during WWI, they were soon laid off once the war ended.  Society dictated that women simply slip back into their aprons and return to their lives as stay home wives and mothers.  Society did not take into account that many women now had the taste of slight independence and hungered to reenter the work force and did.  If a woman chose to pursue a career, she had to overcome many obstacles and society was there to influence her decision at every turn.  

Although women still had many of the same values of traditional housewives and mothers and their main purpose of working was not to change stereotypes but to increase household income, societies’ psychology about women’s role attributed to higher divorce rates.  Many men considered women who pursued careers as “unfeminine” and “man haters” and often cited this as grounds of divorce.  Women of the 1950’s, just as many women do today, desired to create a safe haven at home for their children and husbands while still developing and nurturing their individuality by pursuing an education and a career.

Influences urging social conformity of the expected roles of women were seen at all avenues.  Even  child psychologists such as, Dr. Spock, urged women to remain home.  Women’s roles were stereotyped on television and motion pictures also.  In entertainment, women did not work and usually appeared in the kitchen.  Entertainment even went as far as to stereotype career women as neurotics while the happiness of the stay home mother and wife seemed endless.

Women were to accept that their greatest contribution to society was that of wife and mother and were made to feel guilty that their children may not be well-adjusted adults if they chose to work or desired an education.  Of all the constant influences directed towards women during this period, that of the education system seems to hit me the hardest.  Educational institutions promoted same traditional women’s roles; extracurricular activities reinforced males as leaders and women as assistants.  Even guidance counselors cautioned young girls not to miss the opportunity of getting married for something as invaluable as education.  Feminism was the lowest point of the century during the 1950’s.  There were less women in college than in the 1920’s and 30’s of which up to two-thirds failed to even complete their degrees and if one was achieved, it was often limited to majors such as home economics or primary education.  

As for the last part of the discussion question, I am at my wit’s end debating it within myself.  Reading through this chapter, I find myself trying to grasp the idea of someone, or a mass majority of the population, trying to dictate to me, a woman, that it would not be “acceptable” to fulfill my life long dream of pursuing my education and practicing law.  With these feelings comes sadness and remorse for women who were not given the opportunity to enrich not only their lives, but those of their children and spouses as well, by furthering their education and/or pursuing a career.  Then I realize that my ancestors may just as well be mourning for my lack of opportunity.  I question whether, during the course of striving for equality to pursue our education and career goals, if we may have forfeited something much more valuable, our choice or ability to raise our children full time if so desired.  After having children, will the majority of our generation sit and ponder, “Do I want to go back to work?”  Many women of my generation would think it foolish to rely on whimsical ideas of getting married, having a large family and then actually having the option of being a full time mother and wife.  I believe that those with that choice are the minority and not the majority.  With two incomes being the necessity of many American households, rising divorce rates and increasing numbers of single parent households, the questions of our era are “Do I have enough maternity leave?  When do I have to go back to work?, ”  and “Do I have adequate childcare?”  When thinking of the women who have fought for women’s rights over the years, I often wonder if, in a quiet moment of reflection, they yearn to turn back the hands of time to witness their son’s first step, to be okay with the fact that their daughter volunteered them to be “Room Mom” for her fourth grade class or to just simply be there when they got home for school.  Were women “better-off” in the 1950’s?  It’s hard to say but I would agree that sometimes ignorance is bliss.
 

=========yorg=========
===from:Ebony Bonner
===date:Sun Apr 27 20:03:40 2003
===subject:Ch9 Response
===message:The role of women in the work force and in the family during the 1950 gained a new independence. Women gained a supporting role in society as they were able to contribute in making more decision financially. While the men were at war the women began working in the factories along with maintaining the household.  Although, women were not given equal pay they worked alongside men.  Popular culture did reflect the reality of women’s lives on a middle class standpoint.  On television and movies the role of the women was always in the home.  In the 1950 the educational institutions like society thought the role of was in the home. I believe women are definitely better off today as opposed to in the 1950s.  Today woman are able to have a career and family.
=========yorg=========
===from:Michael E. Elbe
===email:csu16286@mail.claytonstate.net
===date:Sun Apr 27 23:40:33 2003
===subject:Ch. 9 Discussion
===message:Women worked in industry in greater numbers than even during WWII.  They often took low-paying jobs to supplement their husband’s salary.  They also were the mother, housewife and homemaker that popular culture depicted them as being.  TV and movies portrayed women as the happy wife and mother who stayed at home to take care of the children and cook dinner for the family.  This was promoted as early as middle school and high school where the girls were taught etiquette and cooking while the boys were taught career courses.  I feel women weren’t better off in the 1950s because they weren’t really afforded the opportunities  to follow their dreams, unless the dream was to be a housewife.  Any women who pursued careers in the 1950s were either frowned upon or denied the opportunity.  They have much more freedom of choice these days than they did in the 1950s.
=========yorg=========
===from:Vickie Saunders
===date:Mon Apr 28 12:18:03 2003
===subject:Chapter 9
===message:American culture in the 1950s showed that the epitome of womanhood and citizenship was to be good wives and mothers.  The average woman's goals was to find a good husband and have children.  Thereby creating a new career of homemaker. 

Popular culture (television, movies, magazines) reflected the reality of women's lives in the 1950s.  White women were portrayed as happy wives tending to the needs of the family or had careers of being primary school teachers, while black and latino women were portrayed as domestic servants. Women who pursued careers deemed for men were often portrayed as having a mental disorder, being un-natural, or imitating men.  I believe popular culture was major in helping to shape the psyche of the majority of women in the 1950s.

Educational institutions further reinforced sex roles in the 1950s by steering little girls into learning typing, etiquette, and cooking, whereas boys learned mathematics, mechanics, and science. Guidance counselors discouraged young women from higher education in favor of the married life.

I believe that women in the 1950s were not better off than women of today because they were brainwashed by society into not discovering their full potential but instead being limited to certain roles in society.
=========yorg=========
===from:TONYA
===date:Mon Apr 28 13:16:21 2003
===subject:CHAPTER9
===message:Women cherised the value of bing housewives.  They felt as if it was more rewarding then any other Job.  Women devoted their lives in their homes with their children.  Television pictured loving mothers at home with their families, giving  the impression that it is the  best thing a young lady would want, would first delay becoming educated and dont miss the opportunity of becoming married with kids. Education promted the same notion , girls learned typing and boys learned capentry, It was always enforced that males were the leaders. I feel that women today are better off than, then those in the 1950s.  not only do we carry out the duties of the mother, wife and career woman,  but it is also, by choice.  
=========yorg=========
===from:Brenda Miller
===date:Mon Apr 28 15:43:42 2003
===subject:Ch 9
===message:The role of women in the 1950's was dominated by that of a loving mother and wife, in large part due to the baby boom.  Popular belief was that normal, healthy, femine women should want to be married with children at a young age.  This belief was endorsed by movies, television and educational institutions.  Women were not encouraged to continue with higher education, and the education they received was directed toward the role of a housewife.  I think that the media really pushed the idea of the happy homemaker, but towards the end of the 1950's more women were looking to work outside the home to improve the family's financial picture.  The notion of keeping up with the Jones' was driving women to work outside the home in order to keep up with the technological advances being made in society.  I think that women are better off today than they were in the 1950's.  We have more options today in terms of the type of jobs available.  In the 50's and 60's women were expected to take lower paying "girl" jobs.  Today women have the option of whether to work or stay at home without a lot of pressure from society.  I think it is a little more difficult for a family to make ends meet in a one income family now than it was in the 1950's because two income families are the norm in our society.  Overall, women today are much more likely to be treated fairly in the job place and their are few limitations to the type of profession a woman can choose.
=========yorg=========
===from:Hannah Terrence
===date:Mon Apr 28 19:09:03 2003
===subject:Discussion 9
===message:The role of women in the 1950's was constricted to servitude. In the workforce, a woman could perform secretarial tasks until marriage. Or one could be a maid, a waitress or a stewardess for a time. A woman who chose a career over having a family was an unwelcome anomaly. In the family, she existed almost exclusively to fulfill the needs of her husband and children. Her worth was measured by her ability to create an environment which fostered her husband's success and her children's appropriate behavior. As for pop culture, we had "Leave It to Beaver", "I Love Lucy", "The Dick Van Dyke Show"; obviously, a woman's role was reinforced in our culture with an almost cult-like extremism. In educational institutions, home economics and typing were encouraged over academics as desirable virtues of femininity. Women who found themselves alone were often ostracized and viewed with suspicion in their community, even if fleeing an abusive situation. The children of single mothers were assumed to be future juvenile delinquets, even if the mother actively pursued the acquisition of a widower at Sunday School. What many do not consider, is that a time warp existed in the South and these constraints persisted into the mid-seventies here. Are we better off today? Women do have more choices today; with their bodies, their families and their careers. Choice is essential for freedom, so in that way, women have made some strides. But we have this bizarre backlash going now. Somehow, as conservatism made a comeback, we've gone beyond the initial pressure to "have it all" into demands from those around us to "do it all" with rebounding success. Today's woman to admire keeps physically fit with a 5AM workout, rouses the family, serves and cleans up breakfast, takes the children to day care and school and goes to work. Later on, she juggles her schedule between her evening college courses and her children's extracurricular activities. She cooks and cleans dinner, oversees homework and bathtime, does two loads of laundry, scrubs the toilet, tucks everyone in, works on her own homework, bathes and slips into a Victoria's Secret negiligee, lights some candles and makes love til 2AM. This bizarre blend of mother, career-woman, athlete, scholar, and goddess is the woman that many today feel pressured to aspire to become. The pressure is coming from within, from pop culture, from pressure to maintain an image in the community and often from partners too. Wouldn't it be great if a single person or a couple could get back to the initial goal? I think that it was supposed to be about being free to choose what's important to you. My view? Betty Friedan and Jerry Falwell can both go to hell. Me and my kid are heading for the beach.   
=========yorg=========
===from:Holli Armstrong
===date:Mon Apr 28 19:44:54 2003
===subject:Chapter 9
===message:I think that it depends on what kind of woman you are.  If you desire to be a stay at home mom, then you are probably better off being in the 1950s.  But, if you are career oriented, then you have a better chance of doing so today.  Moreover, many women in the 1950s never even had the chance to find out if they are career oreinted or not.
=========yorg=========
===from:Andrew Bell
===date:Mon Apr 28 20:00:31 2003
===subject:Chapter 9
===message:In the 1950s, women were still looked upon as needing to be at home with the kids.  I think that their was this fairy tale role of a women in America's minds.  All the men believed that they had to be out supporting the wife and kids.  Meanwhile, the wife is at home cooking dinner and taking care of home needs.  This was a restriction that women had working against them.  Many of the media that was available around this time also put the women in these fantasy roles.  America actually believed that it was wrong for a women to be the one providing for the family.  Many of those feelings still linger in todays society.  Lots of "old school" individuals that were around in the 50's still have these thoughts and beliefs.  Many shows on TV had the women being at home taking care of business.
=========yorg=========
===from:Sharon Stanley
===date:Tue Apr 29 18:58:55 2003
===subject:Ch 9 Discussion
===message:Whether women are better off today than they were in the 1950s would depend on the woman that you're asking.  I personally see that we're in a better position than we were in the 1950's but I definitely wouldn't say that women are in a good position yet.  We've made major strides in fields that we can work in, in getting closer to equal pay for equal work, and in having freedoms that we once didn't have.  Women didn't play a major role in the work force in the 50's.  They were relegated to being secretaries, typists, and nurses.  There weren't a lot of opportunities for women even if society approved of women working outside of the home.  Popular culture of the time adequately reflected the reality of womens' lives but I don't believe that women were as happy with their roles as they were portrayed to be.
=========yorg=========
