===from:Robert Napier
===date:Sun Apr  6 14:10:20 2003
===subject:Chapter 11 discuss
===message:The lessons that future presidents should learn from the Watergate scandal are, that you should not lie about your misfortunes and never try to wire tap your fellow opponents office. Nixon would have been better off just to tell America that he was wrong and to ask for forgiveness, but he chose to cover the whole mess up and caused a whirl wind of trouble for himself. Nixon was so paranoid about having the upper hand in everything, that he was to blind to realize that goal had already been, accomplish. I think that the Nixon scandal was good for our political system, because it made the public aware that men in great power also abuse that that power. It set fourth a message to future Presidents saying that if you steal, lie, or cheat it will come back to haunt you in the end. This type of event I feel could not happen again, because there are probably procedures set fourth to stop such a thing from happen again. Nixon or Bill that’s a good question. During Nixon time am sure that was the worse thing that could have happen to the presidency, and the same could be said for the Clinton area, but one thing is for sure both men lied and tried deceive the America public. The only difference that I can see between the two is that when the Clinton scandal started we were more concern with our money, than if the president had an inappropriate relationship with a Whitehouse intern. I may not always agree with the actions of the President, but I will always respect the office of Presidency. So, yes I think that it is un-American not to respect our President.
=========yorg=========
===from:Chris Schmidt
===date:Sun Apr 13 10:47:52 2003
===subject:Chapter 11 Discussion
===message:<p>I don't think there was alot of difference in what each man did, but there was alot of difference in their skills and in the attitude of the nation at the time. In both cases, the primary cause for impeachment was obstruction of justice and misuse of the powers of their office to facilitate that obstruction.</p>
<p>In the case of Nixon, he was not a skilled politician. He wasn't able to misdirect or redirect citizens in another direction. He just vainly waited for it to go away and when it was apparent that impeachment was inevitable, he resigned. I think Nixon had some serious issues. He has an internal dichotomy of a massive lust for power and guilt complex over it. I think this is why he resigned to save any further tarnishing of the Presidency as some sort of repentence gesture.</p>
<p>Clinton was a master of politics and popular opinion. I think he did alot to misdirect the population as to why he was being impeached. The population ate it up and most people you talked to would say that Clinton was being impeached for infidelity, which is not an abuse of office or a high crime and therefor not impeachable. I think Clinton saw the polls and knew that the "Republican Revolution" had lost all of its momentum and would fold on the vote to avoid voter backlash. He dragged the nation through and successfull impeachment hearing and a subsiquent aquital.</p>
<p>I think both did equal damage and that this sort of abuse continues to happen and always will. Only about half of our population even votes. Out of those that do, I'd say two thirds are just myrmidon voters who follow which ever politcal demogogue is getting the most airtime. As long as the Americans are so apathetic toward governemnt, you only only expect government to grab more power and abuse it more frequently.</p>
=========yorg=========
===from:Kathryn D. Hambrick-Mateen
===date:Sun Apr 13 17:00:53 2003
===subject:Watergate/Nixon
===message:The impact of Watergate showed that no matter how powerful one may be, or how high your political position is, if you are conducting illegal operations within the government of the United States you will have to answer to the people and face the consequence of your actions.It is sad that the bribes and hush monies were taken from the American people for the wrong doing of others (The President).With the  Watergate scandal,it only made the American people more suspicious of politicians.This seem to be a historical habit in these United States. Yes, I believe there will be other scandalous behavior in our government if it has not already taken place. There are already innuendoes regarding this administration,who knows, only time will tell.As far as to which president did the most damage, makes no difference, two wrongs does not make what they did right. They both were equally wrong. They were suppose to have moral  characters befitting there position.I think the question should be,is it un-American for the president to disrespect the people of this Country.If we can't trust our president to do the right thing,then we are no better off then the people in some of the communist or 3rd world societies.
=========yorg=========
===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Mon Apr 14  8:54:24 2003
===subject:Chapter 11 Discussion
===message:The Watergate scandal was the tip of the mountain of disappointment, distrust and lack of confidence the American people felt towards its government in the 60's and 70's.  The Watergate scandal "capped a turbulent time" for the American people and resulted in a limited ability for future leaders to effectively lead the country.  Such lack of trust in our nation's leaders is certainly a grave impact on our political system.  After all, who can we vote for if we don't trust any of these men?  The "plumbers" of the Nixon scandal sought to discredit Nixon's opponents and maintain executive secrecy.  Isn't this what every presidential nominee does?  Look at the commercials we see on a regular basis--every nominee for any position as senators, house members, presidents, vice presidents, etc. attempt to discredit their opponents.  The difference between current tactics and those of Nixon was the intensity.  No human on this planet is perfect, so I feel we cannot look down on Nixon for his intentions, but for the intensity of his intentions.  In addition, Bill Clinton is human, also, and I do not feel that I personally can condemn him for his intentions, but rather for his disloyalty to the country (not that I think his situation should have been such a big issue in the first place--seemed more a personal matter between he and his wife than a public matter between he and the country--just my opinion!).  Between the two situations, I would certainly say that Nixon's Watergate was the more damaging to our country and our trust in our world leaders.
=========yorg=========
===from:Carla Foster
===date:Fri Apr 18 22:11:34 2003
===subject:Chapter 11 Discussion
===message:The lessons of the Watergate scandal are:  1) whatever is done in the dark will come to light; 2) all men are imperfect; 3) we all have to face the consequences of our actions; 4) when you do wrong to others, it always comes back with a vengence; and 5) everyone has to answer to someone.  The scandal shocked the American people and intensified their lack of confidence in their government.  If we think back to Chapter 8, our first sign of Nixon's cover-up tactics and deceit was during his famous Checkers Speech to save the GOP ticket when it was revealed he had a "slush fund."  Although I do believe there is still corruption within our government, I do not think such an event will happen again.  This event was embarrassing and a disgrace - who would want to go through that (besides Clinton)?  There have been changes in campaign reforms since this scandal and the media has exhibited a more confident and aggressive attitude - maybe too much at times.  Although both reputations were tarnished, I believe the Watergate scandal damaged the presidency more than the Clinton/Lewinsky matter because Nixon's scandal involved "dirty tricks" - spying, burglary, conspiracy, lying, and many of his subordinates were jailed.  The Clinton scandal centered around his inappropriate actions with a woman who was not his wife.  I believe we do not have to respect the President as a person (respect has to be earned), but we should all respect the "Presidency."  After all, that is why he is called "Mr. President," but sometimes, unfortunately, the President doesn't bring honor to the Presidency. 
=========yorg=========
===from:Kristi Smith
===date:Sat Apr 19 13:54:24 2003
===subject:Chpt 11 discuss
===message:Watergate caused a decline in the trust and dependence of the government.  Americans began to come to the realization that the government was not all it was cracked up to be.  I believe that Watergate damaged the presidency more than Clinton’s escapade mostly because Watergate happened first.  The Americans had confidence in the government before Watergate, although the confidence had been diminishing because of the Vietnam War, the fight for equality and the economy at the time, I still believe the public had a good opinion of the Federal Government.  After Watergate, America realized the power it had given the President, and what it could do to destroy the presidency.  I believe that anything can happen, a scandal similar to Watergate, not likely but I feel the government is corrupt in several areas and you never know what is going on behind closed doors.  (Just my opinion!!!)  Clinton’s “escapade” caused me to loose what little respect I had for him in the first place.   I don’t believe it is un-American to not respect your President when it is not earned.  The office of the Presidency is a very respectable position and I will respect who holds that office as long as the respect is earned; however when the “President’s” morals are so totally different than your own I don’t feel it is reasonable to expect me or any one else who agrees to have respect for the “President.”
=========yorg=========
===from:Kevin g
===date:Sun Apr 20 18:17:39 2003
===subject:I am not a crook!
===message:If Watergate has taught us anything, it is to not incriminate yourself while speaking in the Oval Office and being recorded.  The impact of this action led to distrust, fear and anger of the american people (which is funny because its still the same way today during an election year).  Such an event could easily happen again and it wouldnt surprise me if it hasnt already.  Perhaps in 20 years we'll be hearing about it.  Watergate affected the american people more than the Clinton thing because it showed people the evils of politics.  It is not unAmerican to not respect the president because people have the right to their own opinions.
=========yorg=========
===from:Lorena Lockhart
===date:Tue Apr 22 21:16:59 2003
===subject:Funny Business in the White House
===message:The biggest lesson that was taught was the fact the governmental system truly works. The lessons of Watergate are that power can be abused and unfortunately were. I believe that if it happened then it has or can happen again. We as common folk need to be ever watchful and informed to what OUR government is doing. The removal of Richard Nixon demonstrates as array of accountability processes. The President is accountable to the House of Representative, the chamber that most directly reflects the most recent opinion of the nation. However, in keeping with the Federalist values of the Founding Father, it is only the Senate, where two Senators, who may remove the President, represent each state, regardless of population. *Impacts of Watergate: *the increased level of cynicism about politics*the media becomes more confident and aggressive. The Washington Post reporters, Bob Woodward and Carl Bernstein unraveled Watergate. Their work led to the development of teams of "investigative" reporters on newspapers around the world. A new wave of Democratic congressmen is elected in 1976 *Many of Nixon's subordinates are jailed, some discover religion, and others write books. Could this happen again: I hate to answer this so simply, but after September 11th, I believe that absolutely anything can happen at anytime. Nixon and Clinton both lied to the American people but over all the in my opinion the Watergate scandal was the most damaging during its era. The Lewinskygate scandal in my opinion was not a damaging issue outside of using out tax dollar and TV time on something that a lot of men get done but just because it was the President it turns into a big issue. I do believe that the Clinton was not the only man cheating on this wife or engaging in oral sex in the White House he was just the only one who got caught. I really don't care about the President sexual life but can he or she run this country effectively is the real question. We as people sometime put our Presidents, Pastors, and Judges just to name a few on pedestal above everyone else but we must remember that before they were Presidents, Pastors, and Judges they were and still are and will always be a human being who is not and never will be above the next person. Also, just because the hold high positions don't mean they don't face some of the same issues that everybody else face because they are only human, a human being with a title. I don't feel that it is un-American not to respect your President. I do respect the office of the President but for every man that has held that office I can't say the same simply because I think if there was an issue of respect there would be no need to vote. I have a hard time believing that all the people who did not vote for Bush respects him.
=========yorg=========
===from:Kevin Tyler
===date:Wed Apr 23 13:36:41 2003
===subject:Discussion
===message:I think one of the most important lessons learned from the Watergate scandal is that the President is not above the arm of the law.  These events had a major impact on our political system because it spread an uneasy feeling throughout the citizens.  It made the government appear as if it could not be trusted.  I think both the Nixon and Clinton scandals had a significant effect on the office of the President.  If I had to choose one I would say the Nixon scandal had more of an impact because it was a clear abuse of authority and effected a number of people working for the Nixon administration.  President Clinton's was more of a moral issue there was no clear cut abuse of authority.  I do not think that it is un-American not to respect your president simply because being American means you are at liberty to form your own thoughts of whomever you come into contact with, that is what makes this country so great.  I do feel like the office should be respected simply because the President is the Chief Executive of this country and that in itselfs deserves respect even above what your preception of the person may be.    
=========yorg=========
===from:mayumi harris
===date:Thu Apr 24 13:02:38 2003
===subject:ch.11
===message:What were the lessons of the Watergate scandal? What was the impact on the U.S. political system? Could such an event happen again? Which damaged the presidency more, Nixon's Watergate or Clinton's Lewinskygate? Is it unAmerican not to respect your President?

i think the lessons learned were honesty over cover up. i think that the degree of the embarassment helped to forewarn future politics of the ineffectiveness of scandalizing. the watergate scandal left a huge impact on the morale of the u.s. it left the american people feeling betrayed and insecure of their government. i feel that anything is possible so an event such as the watergate issue could arise again. it may be a current issue as we speak. who knows what goes on durning a presidency until all is said and done. well of the 2 "gates" i feel that the watergate did the most damage. the monica lewinskyGATE was more of a comic relief than any real issue. the president was human and felt the need to be sexually gratified by someone other than his wife who probably didn't have the public portrayed marriage behind closed doors. it's not right, however he did what half the men in america do everyday. to lie about it was what i didn't agree with. although he should have had the right to his privacy.nixon was involved with the government. this affected our nation. clinton just wanted a little something on the side, he didn't commit a crime that no other man isn't committing.
if it is amercian to have freedom of speech and to feel the way you want to feel, then it is amercian to have your own views and feelings toward the president. i personally respect no one who does not respect me or humankind indiscrimantly. 
=========yorg=========
===from:mayumi harris
===date:Thu Apr 24 13:13:03 2003
===subject:bush....a watergater? (iraq)
===message:hello all. question: do you guys feel that bush initiates secret missions to not just discredit opponents, but to achieve personal goals. do you guys think that any such issues have anything to do with the current war in iraq?
=========yorg=========
===from:Tawana Mcghee
===date:Thu Apr 24 13:39:18 2003
===subject:Chapter 11
===message:The American people can learn alot about the Watergate scandal.  One is that you really don't know what is going on in the White House.  To the people that had to live through this time, they learned the hard way that the president had his own agenda and was not going to let anyone or anything stand in his way.  The impact on the political system is that many changes were made to take away some supreme authority from the president.  Now he is a figure head, under the strict control of his senate and congress. However, it is possible that these events could be repeated.  Politicians seem to be at the whim of anyone's political donation.  So who is to say that they won't or haven't comprimised themselves nor their country already.  Nixon's Watergate scandal by far out ways the indiscretion of President Clinton because what Nixon did directly affected the country as a whole.  If anything what Clinton did affected nothing more than the trust he and his wife had.  It is our right as Americans to view our president as we see fit. 
=========yorg=========
===from:Ursula Davis
===date:Thu Apr 24 15:07:53 2003
===subject:Chapter 11 response
===message:The lessons learned by the Watergate scandal is that everyone, even the President is human and that there have to be checks and balances in place to make sure the power is not abused on every level of government.  Just because Nixon did positive things for the nation in a public manner said nothing for him as a man or what he would be capable of doing.  The Watergate scandal had a negative impact on the United States political system.  Americans were disillusioned by the fact that someone with whom they trusted and had done so much good, had lied to them.  Americans lost confidence in government.  Starting with the inability of Kennedy and Johnson to improve schools, reduce crimes, offec affordable health care and improve race relations, Watergate was the last straw.  Americans no longer trusted the government and still do not.  Based on this mistrust, many do not take advantage of our voting rights and feel that it doesn't matter(although it really does).  Events like the Watergate scandal could definitely happen again for that very reason.  If everyone does not become involved in government regarding who is for what and what have they done lately, politicians with ill intent will have easier access to high ranking positions that affect our everyday lives.  We must vote, and let our voices be heard, we must make sure that we get what we pay for, and make government accountable for what they do.  I think that the Nixon scandal was more damaging then the Clinton situation.  The fact that Clinton had an affair with Monica was really none of my buisness, as we soon found out, many men in government have and are cheating on their wives.  The issue became a national one only when he lied about it.  The fact that he lied like Nixon became the impeachable offence.  Nixon's issues before and after were illegal.  I don't think it is unAmerican to not respect your President.  That is part of being an American.  You can have your own opinion about anyone and everyone.  What becomes unAmerican is if those feelings become actions.  Disrespectful actions against anyone is wrong, and to the President I think would wrong.  If I don't like the President then I make sure that I don't vote for him at the next election and I get out and talk to others, assist in his opponents campaign and make sure others don't vote for him.  That is the American way. 
=========yorg=========
===from:Connie Plowden
===date:Fri Apr 25 14:09:32 2003
===subject:Watergate
===message:The story of Watergate is a complex and deep one full of intrigue and back room deals, public politics and personal motivations. There were two major lessons that were learned. First of all, people do not suffer easily the betrayal of their trust, and they will not abide those ultimately responsible. Secondly, people's trust, once lost, is not easily regained. Watergate could happen again, if the intent is personal. 

The impact on the U.S. Political System, was the lost of Republican seating to the Democrats. 

Yes, I believe a cover-up could happen again, if the issue would prove once again to the public dishonesty in the government. 

Protecting the interest of a nation vs. private conduct. The scope of Nixon misdeeds was triggered by Daniel Ellsberg’s illegal leaking to the press of the top secret Pentagon papers, which described the Johnson Administration’s handling of Vietnam War. On the other hand, Clinton misconduct was of personal interest only. Both events were damaging, but the Media in the Clinton/Lewinsky misconduct case, played a vital part on public opinion and in my view was more damaging than the Watergate Scandal. 

One could be considered un-American for not to respecting their President, but looking back at the past it is hard to trust the President when it is evident that they will lie, and will try anything to cover up. To be frank, there is no such thing as a tiny lie and a big lie. A lie is a lie. Presidents are human too.

=========yorg=========
===from:Chad-Everett Tisdale
===date:Sat Apr 26 11:49:06 2003
===subject:mistrust
===message:The Watergate scandal helped many people see just how corrupt politicians can be.  Sadly, the result of the Watergate scandal was the general mistrust of government and politicians.  People began to believe that politicians were only in office for their own egotistical reasons.  While this may be true of many, I believe that not all politicians are crooks.  Unfortunately something like this could happen again.  While it may not be easy, the President could use his influence to have his enemies' reputations destroyed much like Nixon used the FBI and CIA to harass people.  I believe that Watergate was more damaging to Nixon than the Lewinsky debacle to Clinton because it was almost a sure thing that Nixon had to resign.  Due to the public's acceptance of sexual promescuity, Clinton was not as affected by his scandals.  Americans seemed to almost expect the President to have affairs.  French people did not understand why people were making such a big deal of the whole thing.  I believe that America should respect its President but when they do not it shows that they were either misled or didn't care enough.  Which reason is worse is for you to decide.
=========yorg=========
===from:Johnnetta
===date:Sat Apr 26 17:33:46 2003
===subject:hist2110
===message:The lessons of the Watergate scandal is that once the political system has been proving to be mistrusted it will be hard for people to trust the system again. Then the people in the system are to serve and protect the people and set the example for unity for American, but instead they are being greedy for their own self-interested. It’s hard for the system to gain trust from people, once people have discovered the corruption in the system. I do believe that this event could happen again. I think Nixon was worse off then Clinton because sleeping with a woman is wrong, but Nixon scandal was worse. No, everyone have their own opinion and the can like or dislike whom every.         
=========yorg=========
===from:Johnnetta
===date:Sat Apr 26 17:34:18 2003
===subject:hist2110
===message:The lessons of the Watergate scandal is that once the political system has been proving to be mistrusted it will be hard for people to trust the system again. Then the people in the system are to serve and protect the people and set the example for unity for American, but instead they are being greedy for their own self-interested. It’s hard for the system to gain trust from people, once people have discovered the corruption in the system. I do believe that this event could happen again. I think Nixon was worse off then Clinton because sleeping with a woman is wrong, but Nixon scandal was worse. No, everyone have their own opinion and the can like or dislike whom ever.         
=========yorg=========
===from:Bethany Ballard
===date:Sat Apr 26 21:49:25 2003
===subject:chapter 11
===message:I think the lessons learned by those involved was that being honest and not going against the laws would have benefited the Nixon administration in the end.  They learned what happens when you are dishonest and scandalous.  After the Watergate Scandal, the American's lost their trust that Washington could govern effectively.  American's no longer had optimism or confidence in the government which largely affected politics.  I definetly believe that such an event could happen again.  In the future, we could have another dishonest President who is secretive.  Who could really stop it from happening now if they couldn't then? Nixon's Watergate definetly affected the Presidency more because the scandal involved politics, which affect the American people, whereas, the Clinton-Lewinsky Scandal, was more of a personal affair that would not have as much of an affect on the political system.  I do believe it is un-American not to respect your President.  Even if you don't agree with the way they govern, or who they are as a person, you must respect their position which is The President of The United States.  Even though I didn't care for President Clinton during the Lewinsky scandal, I still respected his authority as President.
=========yorg=========
===from:Ashley Hughley
===date:Sun Apr 27  2:21:18 2003
===subject:HIST 2110
===message:It's sad how something like the Watergate scandal had to occur.  The lesson Nixon and the other people involved in this scandal learned that lying never gets you anywhere, it just makes matters worse, and that lying about something so major can cause a lot of years of embarrassment.  People are still mentioning things about the scandal.  The lesson the people of the U.S. learned from it was that putting so much trust into someone, like the President, can always backfire.  A lot of politicians are crooked anyway.  They lie in order to get what they want, because that's how they make a living.  As a result, the Watergate scandal did help the people of the U.S. become more aware of how politicians can be.  So this kind of hurt the political system, since they need the people to believe them in order to become whatever they want to be.  I believe something scandalous could happen again, but nothing like that.  Hopefully, after experiencing two Presidents being impeached for lying that politicians would know better than to do the same thing.  Nixon's Watergate damaged the presidency more than the Clinton's Lewinskygate.  A lot more people were involved in the Nixon scandal than the Clinton.  To me, what Clinton did wouldn't have been blown so out of proportion if he would have just told the truth.  I'm not saying what he did was okay, because cheating is wrong.  But he could have at least waited until his term was over, because while he was our president he was supposed to be setting an example for all of us.  Of course it's not unAmerican not to respect the president.  People can respect whomever they want, especially after the scandals have occurred I can understand why people would not be able to respect them.
=========yorg=========
===from:Linda Dawson
===date:Sun Apr 27 11:54:40 2003
===subject:Hist 2110
===message:The Watergate scandal crippled the presidency and the political system during the 1970's.  During this time frame the country was dealing with a hard economic situation and  the President's strong arm tactics and intimidation to achieve his personal goals, caused the people of this country to have little faith in our political system. His distrust and his own insecurities caused him to illegally use the FBI and CIA, to police the democratic party. The lessons that were learned from this great scandal were; The president is not immune from prosection and using the highest law enforcement agency in the country for the presidents personal gain, should have been restricted. I believe that an event as that could never happen again in this country. The president could not control the FBI and CIA in such an illegal manner, that they would begin to illegally investigate the people of this country or the other polictical parties without having just cause or probable cause. The Watergate scandal and the scandal involving President Clinton are to completely different situations. The Watergate scandal used its own government to wiretap and intimidate those that went against Nixon's government. Although Clinton lied and attempted to cover up his scandal by using executive privilege, he never used his powers to intimidate or wiretap those that went against him. It wasn't the lies nor the cover up that hurt Nixon's presidency, it was the total misuse and illegal use of the government. It is not unamerican  when you don't respect the president. It's not the man that make the presidency-- what it is, it is the offce within itself. The people of America have a right not to respect the man or woman in the office, but they have a duty to respect the office itself. All humans can fall short and become corrupt and be removed from the presidency, but the office of the presidency will continue on with all of its presitige and honor.    
=========yorg=========
===from:Kathryn Hatch
===date:Sun Apr 27 13:21:17 2003
===subject:Chapter 11
===message:I think the lesson that can be learned from the Watergate scandal is simple: you can’t always trust people to tell the truth.  This is especially true, I believe, with politicians.  If we were looking for a present-day example of Nixon, we would have to look no further than Bill Clinton.  I believe Clinton to be somewhat worse than Nixon…if a man will lie to and cheat on his own family, what makes us think he will be honest to the rest of us?  Clinton was aptly named “Slick Willy” - this characteristic of being “slick” is the only reason he got away with his lies.  If he was bumbling and ill tempered like Nixon, he wouldn’t have been likable, and he would have gotten in trouble for what he did.  However, because times were good and he was a good liar, he was able to successfully lie to the American people and get away with it.  The sad thing is, if there were no term limits, I am sure he would have been reelected to a third term.  
=========yorg=========
===from:James Pike
===date:Sun Apr 27 15:09:10 2003
===subject:Chapter 11
===message:I believe that eh main lesson o be learned from the Watergate scandal was that people are not always what they seem.  Furthermore, this often taught lesson made any Americans distrustful of the government.  This distrust led to the tainting of the American political system.  Through the investigations, allegations, and resignation of Nixon, the American political system gained a reputation for dishonesty and corruption.  As to the question of could such an event happen again, surely, if it has not happened already.  Both the Nixon Watergate and the Clinton Lewinsky events damaged the respectability of the presidency.  I think that it is the time frame that one was born in that determines which one damaged the presidency more.  For instance, I was still young when the Nixon scandal was coming out, so young I do not remember anything about it.  On the other hand, I was very much aware of the going ons during the Lewinsky saga.  So, I am more apt to say that the Lewinsky trials and tribulations had a negative affect on my generation.  However, many of my peers did not feel that Clinton had done anything wrong.  In this case, I think that the Nixon scandals had a greater impact on the American political system, when age and experience are taken out of the picture.  Any president is a leader of the American public, even if they are stupid, sleazy, or the greatest thing since sliced bread.  So if the American public does not respect the president, then many other leaders may not respect the president.  I do believe that it is all right to lack respect for someone, even the president, but the lack of respect for anyone should not be demonstrated in a manner that takes respect away from oneself.  
=========yorg=========
===from:Al Desmond
===date:Sun Apr 27 16:51:48 2003
===subject:Chapt 11
===message:The Watergate scandal allowed the country not just the USA to see the corruption possible in our government.  It crippled the presidency and the political system during the Nixon Presidency.  But what even made it worse is the pardoning of all crimes.  This act put the President above the law of the land.  During this time frame the country was dealing with a hard economic situation and the President's strong arm tactics and intimidation to achieve his personal goals, caused the people of this country to have little faith in our political system. His distrust and his own insecurities caused him to illegally use the FBI and CIA.  The lessons that were learned from this great scandal were; The president is not immune from prosection and using the highest law enforcement agency in the country for the presidents personal gain, should have been restricted. The president has the power to control the FBI and CIA but it should not be misused.  The Watergate scandal and the scandal involving President Clinton are two completely different situations. The Watergate scandal used its own government to wiretap and intimidate.  Although Clinton lied and attempted to cover up his scandal by using executive privilege, he never used his powers to intimidate or wiretap those that went against him. It wasn't the lies nor the cover up that hurt Nixon's presidency, it was the total misuse and illegal use of the government. The people of America have a right not to respect the man or woman in the office, but they have a duty to respect the office itself. 
=========yorg=========
===from:Antonio Mahone
===date:Mon Apr 28 14:17:05 2003
===subject:Chapter 11
===message:Watergate offered a serious set of options for American people.  The amount of disappointment, frustration, regret and ultimate dissatisfaction with our government during those times became quite evident.  Americans truly lost confidence in the political system and clearly understood that “no one was above suspicion.”  The American people had to decide to sink or swim with the political system and understand that politicians are “human” that they do, will and always have made mistakes, errors in judgment and just “flat-out” lied.  The Watergate scandal gave the American people the opportunity to rid itself of the “perfect person for the job” image of persons in power.  With great power comes great temptation, it takes a unique person not to abuse his/her authority when challenged or lured into negative circumstances.  As for which damaged the presidency more, I’d believe that Watergate was very damaging. Because it discredited our political  system and spoiled our belief in government for many years. It offered no justification for why it happened nor was there any “true” sorrow for what happen and the effect it had upon millions of people.  Whether is it un-American not respect your President depends on whether the President respects himself in arenas.  The office of President is and always shall be held in the highest esteem; however those persons representing the office can and should be held accountable for their actions.  


=========yorg=========
===from:Lucille Clayton
===institution:Hist 2110
===date:Mon Apr 28 16:19:03 2003
===subject:WaterGate Scandal - Getting Caught!
===message:Personally, I think the lesson learned was that criminal misconduct can happen anywhere, even in the Oval Office. The most powerful men in the United States are still human and not above wrongdoings.  What bothers me more, is the fact that he had so many people in "his corner".
The impact on the American people was great, of course.  They felt betrayed and embarrassed.  The President of the great U.S. had "stepped" low enough to authorized illegal tapings and invading the privacy of another party's office, while trying to ensure a vote of confidence from the American people.  But whose to say it's not happening as we speak?  The last election for our present President took how long to be tallied?  How many children did President Jefferson father?  And by whom?  President Clinton did what many have done before him, he just got caught.  I think the beauty of our society is such that in time we heal and become better people than before the incident.  The Political System tries to implement procedures that will not allow mishaps such as these to happen again.  But, we have to forgive and more onward.  I respect Hillary Clinton and other First Ladies that, atleast by the outward appearance, signified that they forgave and moved onward.
=========yorg=========
===from:Brenda Miller
===date:Mon Apr 28 19:50:35 2003
===subject:Ch 11
===message:I think the main lesson of the Watergate scandal is that the President is not untouchable.  Nixon used the services of the CIA and FBI for personal gain.  Those divisions of the government were not designed to be at the beck and call of the President.  Nixon had promise to be a very good leader, but his fears and quest for greatness ran is life.  I think he depended upon the belief that everyone under him would protect his interest, but when the truth started to come out there was no way to protect himself.  I think that history could repeat itself under the right circumstances.  It would depend upon the president and the persons at the head of other government agencies.  I think our government is so large that the right hand is not always aware of the actions of the left hand.  I beleive that Watergate damaged the presidency more because of the state of the nation at the time.  We were already realing from the effects of Vietnam and needed time to heal.  The country was more naive at the time and set a higher standard of morals for its leaders.  I think that Lewinskygate was more of a joke to the public than Watergate was.  Many watched Clinton squirm with amusement as details of his problems came to light.  It played out like a nighttime soap opera.  I am not sure how I feel about whether or not it is unAmerican not to respect your President.  I feel like I did not respect Clinton as a family man or a person during Lewinskygate, but as a President I did respect his position.  But I have a problem with people now bashing Bush as a person based on political decisions he has made.  You do not have to agree with his governmental decisions, but I do not think that gives people the right to bash him personally and show disrespect.  I guess my feeling is that the office of the President should be respected along with the decisions that are born there (that does not mean you have to agree with them) but the the person who is President does not have to be respected based on things he does in his personal life.  For instance, the Kennedy's are very respected politically, but as a family they have been shown to not have the highest moral values.
=========yorg=========
===from:Andrew Bell
===date:Mon Apr 28 20:16:59 2003
===subject:Chapter 11
===message:The lessons of the Watergate scandal are that the governments are sometimes left open to lies and backstabbing.  The scandal made it apparent to the American people that the president is just a likely to do these things as anyone else.  He lied to our faces, made a mockery of the US, and was the first president to resign.  All of these were unacceptable to do.  This series of events really put a doubt in people’s minds about our political system.  The American people still have leftover feelings from this array of “trickiness”.  Then some years later, President Clinton lies to America’s face again.  His scandal was a little different in the aspect of sex.  He still lied to our faces.  Choosing one of these scandals is hard to do.  The Watergate scandal ended up being the harshest towards America.  It led to a resignation.  Clinton got off easy for what he did.
=========yorg=========
===from:Raychele Ryans
===date:Mon Apr 28 20:34:30 2003
===subject:Chapter 11
===message:That the abuse of the presidents power will not be tolerated.  Peoples trust of our political system was defintely shaky.  The WaterGate scandal damaged the presidency more than the LewinskyGate.  I donnot believe that people should be considered unamerican for not having respect for the president especially when they are deserving of that lack of respect.
=========yorg=========
===from:Hannah Terrence
===date:Mon Apr 28 20:38:06 2003
===subject:Discussion 11
===message:The lesson of Watergate is: If you instigate a conspiracy, you will get busted. Somebody always talks. 

The impact of Watergate on political mistrust is that many, if not most of us, assume that politicians are dishonest by nature, and that their goal is to assume power rather than to serve the people. There is a pervasive bitterness in our culture that we have been unable to purge since the War in Vietnam and the betrayal of the Watergate scandal.

Could it happen again? Ever hear of the Iran-Contra scandal? How about Savings and Loan? The bidding war currently going on for rebuilding Iraq? I left Miami the year too many dead people cast ballots. In Dekalb County, the new sheriff was assassinated. Political corruption will always be around. Its level of effectiveness will depend on our citizens' responses to it each and every time it is uncovered.

Clinton clearly did not unzip for Lewinsky in order to secure a bid for re-election. In this country, it's over for him, for a long time to come. No matter that we had eight years of peace and prosperity, this is a nation obsessed with tabloids rather than the New York Times. I remember Nixon's resignation, though I was very young at the time. People all around me cried and argued incessantly and his face was very grave. I'll never forget the tension surrounding those times. The Clinton-Lewinsky scandal was like watching hyenas stealing the prey of a lion, with frenetic tittering and shredding. But an attorney from Kenya recently told me that Clinton knew how to talk to other nations and that he felt that we were now in grave danger without him. And I think that I've noticed that lately. But I heard that Monica...

Yes, it is un-American to disrespect a president as long as he is fairly elected to his office. It is not, however un-American to voice dissent. The dialogue should be about the issues, not about personal attacks. Whether I voted for him or not, I imagine that the President might be more capable of leadership than myself, and his commitment to our nation does command my utmost respect. 
=========yorg=========
===from:Chris Comer
===date:Mon Apr 28 21:32:00 2003
===subject:Chap 11
===message:The lesson of Watergate is pretty simple. Keep your eye on your elected officials. I think that such an event today would be much less likely. With the many reporters keeping tabs on our politicians they can’t sneeze with out someone knowing. Overall the Nixon years were worse for our country. He committed blatant criminal laws and perjury while Clinton broke moral rules and committed perjury. As for not respecting the President. I do not feel that that is un-American. That is one of the core foundations of our country.
=========yorg=========
===from:Michael E. Elbe
===email:csu16286@mail.claytonstate.net
===date:Mon Apr 28 21:53:42 2003
===subject:Ch. 11 Discussion
===message:Watergate taught the American people that not even the President is above illegal activities or above the law.  The political system was thereafter viewed with skepticism and doubt about the type of people that were being elected and what these people were actually doing.  I believe Nixon’s Watergate did more damage to the Presidency than Clinton’s Lewinskygate.  Nixon used his “Plumbers” to perform illegal activities and then lied about it.  He only resigned to avoid impeachment and possible prison.  Clinton simply got caught in an extramarital affair and tried to lie his way out of it.  The only significance was that he was the President of the U.S. at the time and not just Joe Average.
=========yorg=========
===from:Holli Armstrong
===date:Mon Apr 28 21:57:33 2003
===subject:Chapter 11
===message:The lesson of both the Watergate Scandal and the Clinton deal is that you never can trust anyone.  No matter how much you put your faith in someone, they usually are out to benefit themselves.  I think that the Watergate Scandal set the stage for uncertainty and distrust in the government as a whole.  Clinton increased that view.  I think that the media has a lot to do with this also.  Everyone's lives are broadcated live over the internet, tv, radio, etc. You can't make a mistake without someone knowing about it the second it happens.  So, could this happen again?  Sure it could.  Everyone screws up.
=========yorg=========
===from:Vickie Saunders
===date:Mon Apr 28 23:30:55 2003
===subject:Chapter 11
===message:The lessons of the Watergate scandal was too much power can lead to corruption.  Watergate had a negative impact on the U.S. political system, citizens began even more to distrust the government and politicians.  Such an event has already happened with George W Bush presidential election.  Many believe that he stole the election and how there was widespread sabotage of the ballots and ballot machines.  I believe Nixon’s Watergate damaged the presidency more because of his blatant misuse of power and his reluctance to comply with congressional orders.  If the president who is the representative of the entire country won’t comply with law…how can the average American trust any government to rule justly.  No it’s not un-American not to respect your President, it’s our right to free speech protected by the Constitution.
=========yorg=========
===from:Sharon Stanley
===date:Tue Apr 29 19:16:48 2003
===subject:Ch 11 Discussion
===message:Lessons from Watergate?  Don't get caught.  I sincerely believe that politics are corrupt.  Richard Nixon took his paranoia way too far and managed to get caught.  I believe that politicians these days no longer stoop to bugging offices or subversive harassment of political opponents but there is still covert activity going on.  Watergate has made politicians much more careful about their methods of "monitoring" their opposition.  It's entirely possible for another incident like Watergate to occur however it's quite unlikely.  The whole Lewinsky "thing" was not really damaging - merely embarassing to our country.  Watergate was more damaging.  Although we all generally assume that politicians are not honest it's very difficult to negotiate with other powers/countries when we show that our own example (President) is corrupt and can't be trusted.

It certainly is not un-American to not respect our president.  The beauty of our nation is that we are not required to respect his decisions (or his office) nor are we required to agree with him.  All Americans have a right to their opinion (as long as they're not openly threatening the President).
=========yorg=========
===from:Star Tomlinson
===date:Wed Apr 30 22:49:24 2003
===subject:Watergate
===message:The lessons learned from Watergate is that Politics is a dirty business and many times power and money is the wrong hands.  The impact on the U.S. political system was massive.  It tainted the presidency and the moral decay was so public that there was no denying the facts and then there were the tapes, those infamous tapes.  No "spin doctor" could have pushed those facts in another direction.  Watergate type events could, will and probably are happening again.  Unfortunately now, the public knows that in politics people are bought and sold, lives and reputations made or destroyed from day to day for reasons that may be known to the public at times and completelysecretive at others.   The damage inflicted by Nixon's Watergate definitely out that of "Slick Willy's" affairs on his wife that continued (surprise!) after he was elected president.  Who cares that a man who was already known to cheat on his wife used his power to have sexual affairs with some younger women who admired him?  It happens everyday.  At least his mistress didn't end up dead like JFK'S Marilyn Monroe.  As far as it being unAmerican to not respect your President, I would lean more towards yes more than no.  I respect authority but I don't fear.  There is always room for constructive criticism even if you are the most powerful person in the world.
=========yorg=========
