===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Fri Feb 21 15:16:08 2003
===subject:Chapter 5 Discussion
===message:I do not feel that Reconstruction was a solid success or a solid failure, but it was one step closer to improvement.  Although the 13th, 14th and 15th Amendments were produced from Reconstruction (which are all good in theory), they were not followed or implemented completely.  The main theme the government sought to express during Reconstruction was unity and nationalism, but it was hardly present when it came to racial conflicts.  Freedmen were granted property rights, but those rights were hindered by other setbacks that were necessary to successfully exercise their right to own land.  So, even though it was not a total failure, it also was not a total success.  It was simply a step in the right direction.  The Radical Republicans insisted on immediate Freedmen rights and abolition of slavery, which is a good cause, but did they really think they were going get the support of the whole country, especially the Confederates?  I think they are considered radical because of their radical ideas of immediate unity and acceptance of Freedmen.  There were several limits on Reconstruction.  The government made new laws that granted rights to Freedmen yet prejudice still continued to exist and oppress the Freedmen, regardless of their new rights.  The major limit on Reconstruction was the inability of the nation to truly come together as a whole.
=========yorg=========
===from:Antonio Mahone
===email:aysiah1997@aol.com
===date:Wed Feb 26 15:03:32 2003
===subject:Discussion 5
===message:Reconstruction's success is somewhat difficult to measure. Becuase its impact varied depending upon the cirucmstances. Several noteworthy ideas were created and implemented, the  13th, 14th and 15th Amendments. These amendments sought in part to provide opportunity for those persons whom were denied privelages such as: voting and suffrage. Along with these compromises came the abolishment of slavery. Or did it? Freedmen's Bureau constituted the most crucial issue of the postwar era, because emancipation had set in motion a profound rukus in our nation's brief history.  Along with the political challenges that faced our nation, Congretional reconstruction. This drama reared its unsubdued head mightly and often.  In lieu of the political obstacles, succession and African American status in society.  Reconstruction often times resembled destruction because of the mounting issues surrounding each and every idea, philosophy and party policy discussed or promoted.
=========yorg=========
===from:Carla Foster
===date:Thu Feb 27 11:59:29 2003
===subject:Chaper 5 Discussion
===message:It is very difficult to take a firm stand on Reconstruction because it had both successes and failures.  The government addressed two major isues during Reconstruction - 1) readmission of Confederate states to the Union and 2) status of free blacks.  Although the 13th, 14th, and 15th Amendments provided a way for freedman to gain independence and participate in American government, it did not address their main concern - economic future and security.  Most freedman wanted to secure independence through land acquisitions but there were many obstacles that prevented this from happening. The Radical Republicans were considered radical because they were forceful in creating and implementing extreme changes.  Reconstruction had limits because the country was not united and ready for all the changes being made and, therefore, resistance to Reconstruction grew as evidenced through "Redemption."
=========yorg=========
===from:Chad-Everett Tisdale
===date:Thu Feb 27 17:44:20 2003
===subject:failure
===message:reconstruction can only be seen as a failure.  The one shining moment of the reconstruction years is that there were some people who were willing to fight for black suffrage and civil rights. These radicals as they were called were only briefly influential with their leaders Senators Sumner and Stevens.  They were radical in that they differed from the common idea that blacks should not be allowed to vote and that they were inferior.  After a few years and the deaths of Sumner and Stevens, fighting for black civil rights became undesirable politically.  Other politicians saw that they would hurt their career if they supported further legislation of this nature.  Since the movement no longer had effective and vocal leadership it fell through the cracks and Jim Crow came in.  Reconstruction failed because the Supreme Court did not uphold the legislation.  Also, the military force necessary to enforce the Reconstruction Acts was never sent.  it became more of a paper tiger than anything else.  
=========yorg=========
===from:kevin g
===date:Tue Mar  4 19:59:34 2003
===subject:chap. 5 disc.
===message:Reconstruction while prosperous in idea was pathetic in practice.  Reconstruction in the south was a total failure because devastation was so severe both agriculturally, economically, and emotionally.  The only thing good resulting from reconstruction was the formation of the radical rebublicans.

Radical rebublicans were persons who fought for black sufferage (the right to vote).  It is unfortunate when main leaders of the radical rebublicans died, so did their cause.  After these great leaders the topic of black sufferage was considered political suicide.  

Limits were set to reconstruction to comfort the south that changes were to be made but a northern way of life would not take over.


=========yorg=========
===from:Lorena Lockhart
===date:Sat Mar  8 12:08:19 2003
===subject:Chap. 5
===message:The Radical Republicans were partially successful. The major power against the Radical Republicans was the President, Andrew Johnson. Andrew Johnson was perhaps the worst president in U.S. history. Being a Democrat from Tennessee, he tended to disagree entirely with the Republicans black and Radical Republicans. One radical Republican, Thaddeus Stevens stated hat any valid plan to restore the Union must "revolutionize Southern institutions, habits, and manners... or all our blood and treasure have been spent in vain." The Radical Republicans were in favor of complete black suffrage, but this didn't happen for a while. However, the Radical Republican was able to sway the majority of congress to allow black enfranchisement. One of Johnson's goals was to destroy the aristocracy of southern plantations. He also did not want blacks to gain rights and freedoms. The Radical Republicans could have been more radical and passed more laws in favor of blacks if Johnson had not been president. Johnson even vetoed the Freedman's Bureau bill and the civil rights because he believed that it would "operate in favor of the colored and against the white race." And this low-life was president! It’s ashamed that somebody did not assonate Johnson instead of Lincoln. I believe that if that were the case, blacks would have been granted their "full" rights during the 1860s and 1870s; there would have been no segregation and suppression. Blacks would not have had to fight for their rights during the 20th Century because they would have been just as free as white.
=========yorg=========
===from:Chris Schmidt
===email:chris@d2dtech.com
===date:Sun Mar  9 10:57:20 2003
===subject:ch5 discussion
===message:
<p>I think Reconstruction was a massive failure. The main purpose of it was to quash political dissent in the South, which it failed to do. While the Republicans succeeded in temporarily establishing political control, it was very short lived and usurped at every turn. The secondary goal of Reconstruction evolved into black sufferage, which was, for the most part, another failure. Congress passed some ambitious legilation and ammendments, but enforcement was never fully implemented. The bitterness in the South over federal involvement in state affairs, including the emancipation and enfranchisment of blacks, proved to substantial a obstical for halfhearted Northern support to overcome.</P>

=========yorg=========
===from:Andrew Bell
===email:csu12497@mail.claytonstate.net
===date:Tue Mar 11 16:20:00 2003
===subject:Chapter 5
===message:The Reconstruction was neither a failure nor a success in my opinion.  I think that the Radical Republicans were on the right path in restructuring the South to fit the Union.  They just didn't act to their full potential in order to get the Restructuring to a 100%.  One thing that comes to mind is that they didn't offer the Freedmen land to get on their feet.  It was like someone gave them keys to a car (the freedom) and no car to put the keys in (the land).  The Radicals were called Radical Republicans because they wanted to reform the South to fit their needs.  They (Radical Republicans) wanted the use of Military to preserve their beliefs in the South.  

The limitations on the Reconstruction were due to Veto after Veto, compromises between parties, and the fear that Freedmen might gain too much power.

=========yorg=========
===from:Robert Napier
===date:Wed Mar 12  4:50:26 2003
===subject:Chapter 5 Discussion
===message:Reconstruction was a failure and a success. The reconstruction failed, because President Johnson had his on personal goals for reconstruction that included making the common person more powerful than the elite. This approach would have been honorable, if it also included everyone. There were several successes in the reconstruction, the Thirteenth Amendment, Fourteenth Amendment, and Fifteenth Amendment. The Radical Republicans were consider crazy, because they supported African Americans having the same equal rights as Caucasians. These rights included owning land, voting rights, and personal freedom. I feel that reconstruction had no limits, because each party had its own agenda and they would say or do anything to persuade the other person to vote for their beliefs. 
=========yorg=========
===from:Al Desmond
===date:Thu Mar 13 18:05:52 2003
===subject:Chapter 5 Diss
===message:I feel reconstruction was a success because it served the greater goal of admitting the succeeding states back into the Union.  Though it had it pitfalls and its mountians.  All sides tried to benefit from a conquered region.  Though many of the same leadership went back to being leaders and the 13 14 15 amendments were implemented these amendements were pretty self serving for those who honored them.  The radical republicans was considered radical only because they truly wanted the freedman to truly to be free. They wanted the freedman to recieve something for the many years of slavery that was indured but many then felt that that was not warranted. Both sides had thier problem with that which again was self serving but over all Reconstruction was a success because it joined the Union back as one.
=========yorg=========
===from:Johnnetta Elam
===date:Sat Mar 15 13:27:08 2003
===subject:Hist 2110
===message:The Reconstruction period was after the Civil War and the plan was a failure. The plan never reaches any of its goals that were intended to shape up the North and South. However, the plan did get six states to rejoin the Union. The Radical Republican was trying to deal with the problems after the Civil War and abolition slavery. They were trying to get everyone equal rights to own land and several other things. 
=========yorg=========
===from:James Pike
===date:Sat Mar 15 13:51:42 2003
===subject:Chapter 5
===message:Reconstruction, considering all that happened to the South during the Civil War, was a success.  Of the countless possible happenings that could have taken place during the time immediately following the Civil War, the fourteenth, fifteenth, and sixteenth amendments, along with the extension of the Freedman Bureau for three years, came as a result.  Reconstruction, as with everything, was not without negatives.  These negatives, however, were the result of ill thinking on the behalf of a few.  Included in these ill thinkings were the results of the Supreme Courts rulings affecting the Freedman Bureau Act, Fourteenth amendment, Enforcement Act, Civil Rights Act of 1875, and the Klu Klux Klan Act of 1871.  Though the Supreme Court may have limited some of the accomplishments of the Radical Republicans, the Court did support the idea of Reconstruction.  This allowed for the reuniting of the United States of America.  
	The Radical Republicans were considered so radical, because they stepped outside of the box; or maybe the Radical Republicans gained their name from their attachment and willingness to achieve the idea that “any valid plan to restore the Union… must ‘revolutionize Southern institutions, habits, and manners ... or all our blood and treasure have been spent in vain.’”  This whole idea, stated by Thaddeus Stevens, was profoundly simple.  After a war beginning from fears of becoming subordinates, as both the North and the South felt, the “field” had to be leveled.  To do this, the Radicals supported legislation to do just this.  The Radicals, in doing so, created morally correct legislation that supported the Constitution, but went against the majorities’ thinking.  
	Reconstruction had limits for several reasons.  The first and most obvious is that not everyone agreed with the Radicals, especially southern democrats.  The second reason stems from the changing attention from reconstruction to other National matters.  One such national matter concerned the economy.  Furthermore, the Republican parties’ demise contributed to the decline in momentum and attention to Reconstruction.  The contributions of the Republicans and momentum for their cause, after all, could not have continues forever. The gross actions of some Southerners could have contributed to the limitations of Reconstruction, as well.  With the influential scare tactics in some Southern states scared away many who may have wanted to continue the path of Reconstruction by the Radicals.  Furthermore, these scare tactics limited those in support of the Republicans, thus limiting the vote and possibility of re-election.  

=========yorg=========
===from:Ursula Davis
===date:Sun Mar 16 13:45:26 2003
===subject:Chapter 5-Reconstruction
===message:In my opinion, Reconstruction as a whole was a failure, but it did have some positive outcomes to the freedman.  African-Americans experienced freedom from slavery and were afforded some opportunities like education, religion, political participation, and ability to earn wages.  The African-American family was also able to build itself which could not be done during slavery when family members were separated and sold.  The failure of the Reconstruction has to do with the Governments inability to enforce the laws and amendments passed during this time.  The South was not going to cooperate with Reconstruction without either force or getting something out of it.  Neither was done, and Reconstruction's collapse was inevitable.  The Radical Republicans were at first interested in black suffrage and assisted in the fight to change the South.  They soon turned their attentions on the plight of the government and economics and although they still thought that slavery was wrong, they felt that with emanicipation, governmet focus needed to change and blacks could fend for themselves.
=========yorg=========
===from:Lucille Clayton
===institution:HIST 2110
===date:Sun Mar 16 15:08:09 2003
===subject:Chapter 5 Discussion
===message:Reconstruction should not be labeled a failure because there were several good laws established as well as the confederate states reunited to the Union.  The Fourteenth and Fifteenth Amendments were added to the Constitution, allowing Blacks an opportunity to gain some rights.  These amendments acknowledge their citizenship and desegregated public facilities.  Although not perfect, these were steps towards freedom and equality.  There were errors made along the way, with President Johnson contaminating the plan for reconstruction with his personal goals but great crusades often times have personal gains hidden subconsciously.   Even Grant’s terms in office proved to be condemning because of personal appointments of friends that had greedy, crooked personal goals and very little concern for passing laws for the betterment of the people.

The Radical Republicans were seeking the abolition of slavery immediately and wanted all people that didn’t abide by the laws to be jailed.  There was no “middle of the road” when Radical Republicans voiced there feelings.  If people did not go along with the Radicals they quickly decided to dismiss that person and move to work against them.  They had good ideas but very little patience.  

As with any plans, there are limits and Reconstruction had limits and loopholes and changes of heart.  Reconstruction had limits because many states were not agreeable to stiff terms that were being mandated on them.  The Civil War had just ended, slavery had been abolished, and the South was in ruins.  Democrats and Radical Republicans both had different ideas about how the South should be reunion back into the states.  Plans to govern the South’s return to the Union was suppose to be over seen by military forces, but was not carry out firmly.  Ex-confederates, who served as officers in the Civil War, were not to serve in political office in the legislature.  This was changed and Ex-confederates were able to be return to elected offices.  

=========yorg=========
===from:Ebony Bonner
===date:Sun Mar 16 22:24:11 2003
===subject:Ch 5 Disc.
===message:Reconstruction was a success and a failure.  Reconstruction was a failure because Congress did not promote freedmen independence through land reform, without property southern blacks lacked the economic power to defend their rights and interest as free citizens.  The federal government also neglected to back congressional Reconstruction with military forces.  The federal governments’ failure to fulfill its own goals and create a biracial democracy in the South resulting in the nation’s adjustment to the consequences of emancipation would continue into the 20th century.  As a success, Reconstruction brought about emancipation which reshaped black communities allowing former slaves to seek new identities as free people and transforming the southern economy as a new labor system.  Due to Reconstruction the 13th  Amendment abolished slavery, the 14th Amendment affirmed the rights of federal citizens, and the 15th prohibited the denial of suffrage on the basis of race.  Reconstruction gave southern blacks the opportunity to be reconstituted with their families, create new institutions, allowed them to take part in the transformation of southern agriculture, and participate in government for the first time in history.  Radical Republicans were considered so radical because they supported black suffrage.  Radical Republicans cried out for the abolition of slavery along with supporting a demanding reconstruction policy during and after the war.  Reconstruction did have it limits and loopholes because not everyone in the south wanted southern blacks to have rights.  A prime example is the 15th Amendment which prohibited the denial of suffrage on the basis of race, but did not guarantee black office holding, nor did it prohibit voting restrictions such as property requirements and literacy test.
=========yorg=========
===from:Kristi Smith
===date:Mon Mar 17 11:35:37 2003
===subject:Chpt 5 Discussion
===message:I believe Reconstruction was partially a success because of the readmission of Confederate states, the ability for Freedmen to participate in politics, the development of schools and the strive for education by all (although not received by elders) etc.  The Freedmen had such aspirations and were given the small chance to fulfill them.  Not to mention the development, less the implementation, of the 14th and 15th amendments.  Reconstruction as a failure- the unity aspect.  As I mentioned in a previous discussion, prejudices of the people (whites and blacks) stopped so many of the “dreams” of unity and equality.  Reconstruction had to have limits, the Radical Republicans were so strong willed and extreme they wanted everything to happen now!  To implement all of the views of the Radical Republicans as fast as they wanted, I think, would have cause a tremendous uproar in the government, not to mention the people.
=========yorg=========
===from:Kevin Tyler
===date:Tue Mar 18 21:04:48 2003
===subject:discussion
===message:As with most things are were some good, and not so good aspects of reconstruction.  To begin with the good it emancipated the slaves.  It allowed slaves to become citizens of the U.S. giving them the liberty to become wage earning productive citizens.  It also transformed the south into a major economic entity.  The amendments which freed the slaves, gave each citizen federal protection of their rights, and disallowed suffrage on the basis of race.  The not so good was that it failed to give the freed slaves power in regards to being property owners.  Nor did reconstruction solidify the rights of the freed slaves or provide them with equal citizenship. Reconstrution did not have the full support of the federal Government which severly weakened it's potential.
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Thu Mar 20 19:40:04 2003
===subject:ch5
===message:reconstruction was a failure. had it put forth effort to insure blacks rights and backed the reconstruction with military force, it would have succeeded. it had limits as does just about everything in life. opposers would have detested reconstruction even harder had it no limitations.they were radical because they were ready to get things on the ball and jumping. this is why they thought lincoln's program was too weak. 
=========yorg=========
===from:Connie Plowden
===date:Sat Mar 22 19:52:29 2003
===subject:Reconstruction
===message:Reconstruction was successful in reuniting a nation. On the other hand it was unsuccessful in given equal rights to blacks. Although the emancipation of slavery became law throughout the land, racial inequality was still present. Radical Republicans was considered radical, because they supported and fought for equal rights for all blacks. They also looked at reconstruction as an opportunity to teach the South a lesson and to punish them. Reconstruction had limits because, it allow measures of revision to be place to satisfy the southerners.
=========yorg=========
===from:Ashley Hughley
===date:Sun Mar 23 12:46:38 2003
===subject:Chapter 5 Discussion
===message:I believe Reconstruction was a success even though it failed.  There were more positive outcomes for blacks that came from this period.  Not only were the 14th and 15th amendments added, it brought the blacks voting rights, slavery was replaced by a labor system, and schools were built for the children to have an opportunity (although it was unequal) to learn how to read and write.  The negative outcomes that came with these changes included the formation of the KKK and the discrimination against blacks although they were supposed to have equal rights.  Radical Republicans wanted certain things to be done at a quick pace, like the abolition of slavery.  When they didn't agree with people, or a group, they turned against them.  The only limt I could think Reconstruction had was how ex-confederates weren't allowed to serve in the legislature, at first, but other than that every party did basically do whatever they wanted to do, in which most of them didn't even last long.
=========yorg=========
===from:Michael E. Elbe
===email:csu16286@mail.claytonstate.net
===date:Sun Mar 23 19:07:54 2003
===subject:Ch. 5 Discussion
===message:Reconstruction was a failure in the direct sense and was eventually abandoned as a program only a few years after it began.  It did help create and push through several key amendments, specifically the 13th, 14th and 15th. However, laws such as the “Black Codes” and the treatment of sharecroppers limited any chance of success for Reconstruction.  Radical Republicans called for the abolition of slavery during the war and a harsh reconstruction policy after the war.  They wanted to make broad sweeping changes in the Southern culture and ideals.  They were also very much in favor of black suffrage, which originally had only a small political backing.  Reconstruction was limited by the fact that there were several different schools of thought in regards to how the Reconstruction should be handled.  Lincoln, Johnson, Grant and Congress all had their own ideas on how Reconstruction should be handled.  This inability to agree on how to carry out Reconstruction limited its success.
=========yorg=========
===from:Vickie Saunders
===date:Mon Mar 24 16:20:51 2003
===subject:Chapter 5
===message:Reconstruction was part success and part failure.  It succeeded in readmitting the south to the Union, reconstructing the state governments, and passing several acts and amendments related to black enfranchisement.  It failed to promote freedmen’s independence through land reform.  Which would have given blacks the tools to economically empower themselves and hence allow them to defend their interests as free citizens.  The federal government also neglected to back congressional Reconstruction with military force. Without the true right to vote and land ownership, Reconstruction did not free the slaves but merely created a new type of slavery…not equal and always separate.

Radical Republicans were considered so radical because of the ideals they had in reference to the status that the freedmen would play in American society.  They rallied for the abolition of slavery during Lincoln’s tenure.  During the Reconstruction years they supported black suffrage, called for federal support for public schools, and extended period of military occupation in the South.  They also supported confiscation of Confederate estates, and black economic independence.

Reconstruction had its limits because of the social climate.  America was simply not ready to view blacks as equal citizens.  The hatred and violence displayed against blacks after the granting of all the voting rights demonstrated this.  If the government had in fact enforced these acts with the military, another civil war would have exploded.

=========yorg=========
===from:Brenda Miller
===date:Mon Mar 24 18:43:57 2003
===subject:Ch. 5 discussion
===message:I feel that reconstruction was more of a failure than a sucess.  Although the reconstruction acts and the 13th and 14th Amendements were passed, there was little enforcement of them.  The south was allowed to continue in their own right with little action in opposition.  Creation of the black codes is an example of how the south felt about the reconstruction; they created their own policies even though they were not in compliance with law.  Reconstruction had limits based on enforcement of national policy.  Although the north won the civil war, it did not mean that the south agreed with its laws or policies and it was difficult for a government recovering from war to enforce its rulings.  Further, corupt government on the state level prevented action that would have helped reconstruction efforts and been in the best interest of the state.  Reconstruction was performed in baby steps because the country could not have withstood another civil war and both the north and the south knew it.  I believe the radical republicans were considered so radical because they were so unbending.  They had their beliefs and they would not compromise; they were harsh in their treatment of those with views different from their own.
=========yorg=========
===from:Hannah Terrence
===date:Mon Mar 24 22:12:15 2003
===subject:Discussion 5
===message:Though I doubt that anyone on any side could see Reconstruction as a success, some clearly benefited more than others. To me, this period demonstrates racism in a very profound way. We make it through this bloody, horrific war that we fight because a few rich guys insist on owning human beings in the South and a few rich guys want to get richer in the North. Then, when it's time to pick up the pieces and clean up the mess, we ask the same guys what we should do next. We promise rights to blacks, then allow Southern states to create the Black Codes to take it away. And I have to wonder... who the hell were we afraid of offending? So, true to American form, the few folks who have the courage to step up for human rights for all, were pegged "radical" Republicans. That's what we do when someone asks us to think about something that will inconvenience us as individuals---we use derogatory terms to ostracize our most courageous citizens. Usually, its the good Christian folks who sanction the hate and come up with the nasty things to say. I guess they skipped John the Baptist in Sunday school, because the voice crying in the wilderness gets annihilated in America. I think that reconstruction failed miserably and that we still pay for that today. If it had worked, Georgia would not be fighting about putting the Confederate flag on display; it would have been buried deeply long ago in shame. My family tree traces all the way back to the Revolutionary War and yes my great grand-whatevers fought in the Civil War, for the South. In the name of God, Country and Liberty, they fought and still fight to keep other people enslaved simply because they don't look like them. So I'm a radical by this state's standards in 2003, because this is not okay with me, and today's Republicans like to spew words of hate about people like me. Not enough has changed, even now, slander wins over respectful debate. Drive around here five minutes and count the number of Confederate flags. You'll never convince me that those are anything other than symbols of hate, intimidation and fear. Reconstruction failed, in that not all can feel safe walking down our streets, a century and a half after they started the debate.             
=========yorg=========
===from:Bethany Ballard
===date:Mon Mar 24 23:15:07 2003
===subject:chapter 5
===message:I think reconstruction was both a success and a failure.  Even though blacks were now free citizens, the issue of land reform was not promoted by congress.  The blacks were not allowed to own property which meant that they lacked economic power.  Also, the government made the laws of setting the blacks free and of ratifying the 14th and 15th amendments; but they did not enforce the laws.  Perhaps if military force was used in the south to help support the rights of the blacks, reconstruction would have been more successful.  Yet the successful part of reconstruction was the beginning of freedom and opportunity for the blacks.  I believe that the "radical" republicans were considered so "radical" because they had very "black and white" views.  They seemed to be the only party that truly wanted equality on all levels for the blacks.  Reconstruction had limits, as I had stated earlier, because the government did not enforce the rights of the freedmen.  They cared more about having a good relationship between the north and south than ensuring equality for the freedmen.
=========yorg=========
