===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Tue Feb 25  8:37:45 2003
===subject:Chapter 6 Discussion
===message:During the time of World War I, the nation was in such a feeble state that the government easily promoted support of the war.  The country was in an economic crisis, there were more and more immigrants pouring into the country every day, and exercising right to free speech was not used so liberally as it is today.  The people of the country were filled with anxiety about the current economic conditions, and, having nowhere else to turn, depended on the government to lead them in the right direction.  The government argued that anyone who did not support the war and buy war bonds should either join the army or be forever labeled a friend of Germany.  Immigrants continued to come to this country in search of jobs and pledged their allegiance upon by supporting the war.  The government specifically targeted this group of people to ensure their support by providing foreign language pamphlets and editorials.  The America of the early 1900’s did not so freely and liberally express their opinions as that of today’s America.  In today’s world, the government should not dare declare anyone who does not contribute financially to the war a “friend” of the opponent.  These types of generalizations of the early America forced many people into supporting something that probably the majority of them deeply did not want.  The government felt that ideological conformity and repression were necessary.  They needed to feel overwhelming support from the country as a whole in order to proceed.  Probably if anyone attempted to present their true feelings about the war, they would have been punished, as happened many times in the past (i.e. raids on merchants during Revolutionary War).  People were more likely to burn your house down in that time should you disagree with the rest of the country.  Rather than be seen as an instigator, people conformed to the government.  At this time in our country, we are facing a similar question of conformity or speaking your mind.  Luckily, people are now more able to say what they really feel and not worry about being hanged in the process.  Unfortunately, it appears that our government will probably do as they wish regardless of what the people who elected them to their position feel.  
=========yorg=========
===from:Tawana McGhee
===date:Mon Mar  3 12:38:02 2003
===subject:Chapter 6
===message:The people of this era were easily blinded by the propaganda tactics used by the government because the people were naive to the ways of the world.  They didn’t know what was going on outside of their small towns and cities.  They trusted the government to take care of them, and the government manipulated it’s people into believing anything they told them.  This conformity, according to the government, was necessary to keep the people in line, but the repression of the people was unnecessary.  Sure there would have been unrest in the country if the opponents of war had been allowed to speak freely, but isn’t that what this country was built on?  Free speech?  Or do the people have free speech when it is convenient to the government?  Even post 9-11, the people of the US are so open minded to the ways of the world that the same propaganda tactics would not work. You cannot pull the wool over our eyes now, we would see it a mile away.  The past has taught us (the current generation) not to totally believe everything we see or hear.  We question everything.  During wartime governmental power usually dominates the country.  But this is 2003, the people of this country are not as naive nor trusting as they were back in the early 1900’s.     
=========yorg=========
===from:kevin g
===date:Tue Mar  4 20:27:19 2003
===subject:world without mass media
===message:It is easy to control a group of people when you are the one controlling the information they receive.  Propaganda, thought control, and repression were used with such success in the United States during World War I, because a mass media i.e. internet, television, liberalist talk radio did not exist; hence, only one viewpoint was being expressed to the american people.  Ideological conformity was necessary, because it is the only true patriotism.  Repression while in context is "un-american", it is the best way to win a war.  Because there was no mass media i dont think that opponents would have made much of a difference.  Because of 9/11/01 free speech is not so free.  Speaking on the behalf of somone who is of middle eastern descent, they suddenly become a terrorist sympathizer.  The government may do as it pleases during wartime, whether the country knows it or not.  It reminds me of a quote by Benjamin Franklin who said "those persons willing to give up some civil liberties for protection, deserve neither."  
=========yorg=========
===from:Carla Foster
===date:Wed Mar  5 19:24:26 2003
===subject:Chapter 6 Discussion
===message:Propaganda was successful because it was one-sided and the government made sure it kept control of it.  The government even went as far to make any negative feelings toward the war a crime (The Espionage Act and Sedition Act).  The postmaster general had authority to go through the mail and ban certain material from reaching the public.  Can you imagine someone deciding what mail you should and should not receive?  Also, it was easier to support the war than to be labeled a friend of the enemy.  The ideological conformity and repression was necessary in order to ensure support and enthusiam for the war and to spread patriotism throughout the nation.  If opponents of the war were freely able to speak out, I do not think it would have made any difference.  As President Wilson stated "I want peace, but I know how to get it, and they do not."  After the events of September 11, 2001, people do speak their minds more freely but there are still some individuals who allow the government and media to control their beliefs of right and wrong and prejudices.  During wartime governmental powers increase and civil liberties decrease; government does what is pleases supposedly for the interest and protection of its citizens.
=========yorg=========
===from:Robert Napier
===date:Wed Mar 12  4:54:42 2003
===subject:Chapter 6 Discussion
===message:Propaganda was a huge influence during World War I, because it allowed anyone in any social structure the opportunity to read, or to hear about the viewpoints of government. The government also was able to influence the women during this time by encouraging them to stop wasting food and to only eat what was necessary for every day survival. They would also run films in local movie theaters encouraging the war. By constantly showing people that going to war was right and good for America, they gained the support that was needed. During this time it would have been difficult for any person opposing the war to express their views, because tensions were high and they would have put their life at risk. In saying this, I believe that the war would have still taken place regardless of anyone or group that opposed America going to war. It seems that our civil liberties are put on hold during war, because the main goal at hand is winning the fight, not securing our rights.	
=========yorg=========
===from:Chad-Everett Tisdale
===date:Sat Mar 15 14:08:49 2003
===subject:Big Brother
===message:Without resources like the internet and television to give more than a few sources of information, people were more likely to believe what the government was telling them.  Moreover, since the goverment stifled all information not in line it's agenda, and maybe even due to the fact that people were more likely to believe what the government told them, propaganda was very successful.  I believe that America should be united, but not at the cost of individual freedoms.  For example, now we see in the media an enormous amount of dissent from Bush's stance on a impending war with Iraq.  The liberal media seems to portray the entire American population as not supporting the president.  However, I refuse to believe that these demonstrators represent America.  If there were suppression techniques in place today, like we used to see in Russia and China, then we would not hear of, or probably not even have these demonstrators protesting the war.
=========yorg=========
===from:Chris Schmidt
===date:Sun Mar 16 10:44:01 2003
===subject:Nationalism During Wartime
===message:<p>While tighter government control of war related industry is necessary in wartime, repressive control of the media and the populace is detrimental. There is a line between drumming up popular support for the military and suppression of the voice of dissent that should not be crossed.</P>
<p>In World War I, Wilson thought he could ride the tide of unchecked nationalism to his altruistic final goals of extended world peace, but he mistakenly identified the intolerance and conformity as universal support for his administration. When the war ended this same force was bent on the failure of his liberal ideals. By allowing nationalism to fuel a climate of fear and susipicion of anything not 100% American and patriotic, the League of Nations was doomed to failure.</p>
<p>In present day America we are faced with a similar problem. The treacherous friend, nationalism, is again rearing its head. When any argument against the interventionism is unamerican, we facilitate a world where the US can excersise unrestrained power and, thus, be the target of more hatred and possible attacks. That will, of course, create a greater cry for global intervention... which will in turn lead to even more mistrust of the US and its foreign policies. While many "protestors" are poor excuses for politcal dissidents, not fully aware of the underlying facts regarding the policies they are against, legitimate voices of protest are silenced as enemies of freedom or haters of America.</p>
<p>This is unhealthy for our government, and bad for all citizens whatever their political views. America functions best when differing views are debated instead of being cast out as simply wrong. What better way to prove your case to those who do not agree with you than to debate them and illustrate the superiority of your arguments? Unfortunately, in the wake of nationalism, it is all too easy to simply discredit those opposed to a majority view. We should take a lesson America's past on the dangers of nationalism.</p>

=========yorg=========
===from:Antonio Mahone
===date:Sun Mar 16 13:21:26 2003
===subject:Chapter 6
===message:Why were propaganda, thought control, and repression used with such success in the United States during World War I? Was ideological conformity necessary? Was repression necessary? What would have happened if opponents of the war had been allowed to present their views without restrictions? How do these questions apply to events of post-9/11/01?  Wilson, like his European contemporaries, chose war rather than accept a diplomatic defeat, and, again like them, justified himself by claiming that the Unite States was entering the war to uphold peace, liberty, democracy, and the rights of smaller nations.  The most important of the reasons for the American action in World War I, however, was none of these things- it was instead the attitude of mind in this country the product of propaganda.  People under the influence of propaganda came to look upon the war as a simple conflict between the forces of good versus evil.  There existed a blind hatred and ideas that malevolent individuals had gained control of an autocratic government-wanting to dictate this ideology to the rest of the world.  Because of  this ideological conformity and repression of such thinking was very necessary to preserve the integrity of government and its people. I believe the American sentiment on terrorism prior to 9-11 was one of “that could never happen here.”  Therefore our ideology about terrorism and those whom support it were completely distorted.  We as a nation somehow developed a sense of invincibility – believing that no one could ever “get to us.”  Since the tragic events of 9-11 our ability to voice our opinions does in some instances influence our governments decisions.  We as Americans have the civil right to make changes, decisions and express our opinions about such things as war, via the legislative body.  However our ability to change situations are limited by the same body that allows us to influence change.
 What happens to civil liberties and governmental power during wartime? There are no civil liberties during wartime, hence governmental power increases three-fold despite public sentiment and outcries from anti-war groups. 

=========yorg=========
===from:Kevin Tyler
===date:Sun Mar 16 18:04:41 2003
===subject:Discussion
===message:The propoganda and thought control campaigns were used to gain support for the War.  These campaigns may have been neccessary because many americans still had ties with the European nations.  If the public wre allowed to express their disagreement it may have very well put pressure on the President to not enter the war.  I am pretty sure if open demonstration was possible the next presidential candidate would have used this anti-war feeling as his political platform.  It would very much resemble the state our country is currently in.  We have so many people opposed to war with Iraq and a number of people very much for the war.  I beleive that it leads to division within our country.  Many people are protesting the war, but what about the soldiers who had to leave their families and have committed to defending the liberties that we sometimes take for granted.  Don't they deserve support? We still need to remember that it is because of war that we have the freedom to demonstrate openly against our own government.  People have already lost lives to give Americans the rights that they enjoy everyday. 
=========yorg=========
===from:Ursula Davis
===date:Mon Mar 17 19:10:42 2003
===subject:Chapter 6 discussion
===message:Propoganda, thought control, and repression were effective tools because people are strongly influenced by desire to go along with the crowd.  Just as advertisers do today, the government felt that by flooding the media with prowar information, people would naturally agree with it based on constant exposure and conditioning.  If the "radicals" had been able to speak their mind, then people might not have gone along with the idea of war as easily, because they would have been given another set of ideals to think about and something to compare the prospect of war with no war.  This technique is still used to day to sell soap, clothing, cars, and war.  After 9-11-01, the media was flooded with pictures of the bombed sites, interviews with loved ones, and background of those killed.  With this constant reminder day in and day out, Americans were further saddened and angered and I am sure the government uses these emotions to fuel to call for retaliation and now war.
=========yorg=========
===from:James Pike
===date:Tue Mar 18 12:54:20 2003
===subject:Chapter 6
===message:"It is not an army we must shape and train for war, it is a nation.”  This statement by President Wilson sums up why propaganda was used during the First World War.  Americans were fighting and dieing in a country far from home, with horrors far from conceivable to many Americans back at home.  If the nation was not a collective unit, then the United States would be fighting a two front battle- one at home, the other in Europe.  For this reason, ideological conformity was necessary.  Though ideological conformity was necessary, it far less necessary than repression.  Repression of certain ideals that went against the war became necessary as soon as these ideals gained support and displayed resistance for the war.  Once again, this goes back to the idea that Wilson summed up so well.  If opponents of the war had been allowed to express their opinions, then some would have joined in there support; however, many more would have repressed them in a far harsher way than the government did.  Most everyone has meet the fanatic, and after all of the propaganda that America was fed, I am sure there were many fanatics for the war.  With this irrational thought, there could have been the chance for violence.  When faced with such a destructive act in the face of Americans, literally, I do not feel that the events of 9/11 had immediate differences in ideological thought; everyone was shocked, abhorred, and vengeful.  Over time, these feelings were replaced by the feelings dealing with prevention.  During times of war and times when national security is of the essence, civil liberties and governmental powers must be changed from that of peacetime.  This is needed for the unity of a nation at war.  To tell everyone everything about the war would be detrimental for any effort in a war.  To tell everyone everything about who is where, why, and how, would limit surprise, expose information to the enemy, and provide information that may not be understood.  Some Americans would not understand the entire concept of some of the actions by the federal government; this would cause unneeded outlashes from the population.  These outlashes, though justified sometimes, would hinder the efforts made by the leaders of a country.  
=========yorg=========
===from:Lorena Lockhart
===date:Thu Mar 20 18:52:31 2003
===subject:Chap. 6
===message:I believe that propaganda, thought control, and repression were used successfully in the United States during World War I because of the German's sinking of the Lusitania, in which 128 American were killed; the Arabic, which killed 2 Americans; and the Sussex, in which several Americans were injured. These actions attacked the sense of security of the American people. When American lives are taken as in the recent World War Center and Pentagon tragedies, we as American are more than ready to take up arms to defend our way of life. Regarding ideological conformity, for a nation to be successful at war it must be united. The disunity in Russia is a prime example of this. Not only was Russia unsuccessful in the war, but also it didn't even "finish the race," and worse, became like traitors to the Allies. My thoughts on repression are probably considerably different now than they would have been before September 11. Before that time, I probably would have said that no repression should be taken at any time, as it violates individual rights, but in light of recent years, I feel that any action or attitudes that are anti-American should be investigated and dealt with as appropriate. If someone lives in the United States, then they need to support the United States. I feel that repression was necessary during WWI, but that it got somewhat out of hand. I am sure there were many innocent people who were hurt by the overreaction to questionable attitudes. However, if opponents had been allowed to present their views without restriction, the US may have never entered he war and Germany most certainly would have overtaken the Allies after Russia withdrew from the conflict. One thing is certain; we must remain united as Americans in our fight against terrorism. Anyone who is not for the United States is against the United States and needs to be dealt with appropriately. Our world as a whole is depending on our unity against this evil.   
=========yorg=========
===from:Kathryn Hatch
===date:Fri Mar 21 16:31:37 2003
===subject:Chapter 6
===message:Americans at this time were, as many people have already said, not exposed to as much media as we are today.  Radio and newspapers were pretty much their only sources for news.  Even these news sources were only beginning to be commonly accessible to all people.  Because of this, I think Americans were more trusting of these sources because they were new.  I think that America was more trusting of the government and media as a whole than today.  Nowadays we have all been raised not to believe everything that we hear.  Americans were on the verge of technological breakthroughs, and they were, I believe, more innocent and trusting.
=========yorg=========
===from:Lucille Clayton
===institution:Hist 2110
===date:Fri Mar 21 20:15:56 2003
===subject:Chapter 6
===message:President Wilson used some of the most skilled and influential people to attack anti-war enthusiants to promote unity among Americans for World War I.  His attacks were against socialist, pacifists and other dissidents that wanted peace without a war.  Using his presidential power, President Wilson forbade constitutional rights and had people jailded for their disbelief in the war.  I don't think repression was necessary because the war would continue regardless to the different views of some people.  America had entered the war and it was going to be fought regardless to anti-supporters back at home.  
Whether it's the tragedy of 9/11/01 or any other occurrence, there will always be someone that will not agree with actions taken by the government.  I would like to think that we have elected officials that will make the best decision for America and its people.  Am I dreaming?
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Sat Mar 22  0:05:39 2003
===subject:ch6
===message:civil liberties were out the window duing war due to governmental powers. propaganda and other tactics were successful because they came with coercive methods. much like peer pressure. i think the government intilled fear into many and fear will cause you to take on a government desired attitude. i don't think idealogical conformity nor repression were necessary. i don't understand the overly importance of having every single citizen on the same emotional accordance as the governmet as far as the war goes. there seemed to have been an obsession with it. maybe the president suffered from obsessive compulsive disorder.(non pon intended...i myself am a sufferer). if people were allowed to voice their true feelings on the war i think the nation would have become divided and this is probably what the government feared.if the nation wasn't on the same accord how would they succeed in war without the total support of their country. i think that times are somewhat different in our day. of course our right to freedom of speech is far more respected than it once was. after the tragedy on 9/11, americans were free to say whatever they pleased. sadly enough, comidiens even profitted from distasteful jokes of 9/11. however, it seems as though the nation was on the same accord in the desire to hunt down osama bin laden. 
=========yorg=========
===from:mayumi harris
===email:mayumiharris@yahoo.com
===date:Sat Mar 22  0:24:47 2003
===subject:ch6.THE WAR IN IRAQ-i propose a question
===message:many of our soldiers are away fighting a war in iraq. some of our people are prowar, however there are many who detest the idea of this war. many people are sore with bush right now because they feel that he is just taking over where his father left off. the thought of loosing loved ones and innocent lives due to personal issues between bush I and bush II, is simply atrocious to many of us. WHAT DO YOU GUYS THINK ABOUT THIS WAR IN RELATION TO THE WAR INVOLVING WOODROW WILSON? his american people also developed ill feelings toward him for his desire to take the nation to war. it seems like there are several similarities in the 2 presidents. CAN ANY OF YOU POINT OUT ANY OTHER SIMILARITIES IN THE WAR WE ARE FACED WITH NOW AND THE WAR OF THE 20TH CENTURY?
=========yorg=========
===from:Kristi Smith
===date:Sat Mar 22  8:43:38 2003
===subject:Chpt 6 Discussion
===message:I think the success of propaganda, thought control and repression was mostly based upon the need of the American people to be united.  The Revolutionary War had separated our country, the government brought it back together and the people needed to be supportive to keep it together.  The confidence in the government had gotten stronger over the previous years and the people felt the need to support whatever decision was made.  Obviously if they didn’t there were prices to pay; they were outcasts and considered “friends” of the enemy (Germany).  I don’t know that ideological conformity and repression was necessary, I think it helped, but I feel it was to an extreme.  The people were afraid to voice their true feelings.  If the opponents of the war had been allowed to express their views so freely, I think if would have resulted in a separation of the people again.  Nowhere near the separation the Revolutionary war caused but a significant change in the people as a whole.   I don’t think it is a relative comparison to the events of post 9/11/01.  Freedom of Speech is much stronger now than it was then; it is more outlined and has more meaning.  The government does what it thinks “best for the people” during wartime, whether or not the “people” agree.  Unfortunately the government controls what “the people” are allowed to hear through the media, I don’t feel that we, the people, are told enough to make an educated decision on whether war is or is not necessary.  That does not mean that the government makes the right decision either!
=========yorg=========
===from:Connie Plowden
===date:Sat Mar 22 20:03:09 2003
===subject:Chap 6
===message:Giving that the United States is a democratic society, and most of the public views were against the war, Woodrow Wilson had to come up with a plan to change the attitudes of the public. Wilson knew that he could not control the people by force, but he could possibly control what they think. On April 13, 1917, Wilson created the Committee on Public Information (CPI) to promote the war domestically while publicizing American war aims abroad. The CPI main goal in WWI was to convince the American public that their livelihood was in danger. Pamphlets, magazines, posters, and theatre commercial were all tools in which the CPI successfully used proganda to promote the war. These tools portrayed the Germans as being depraved, brutal aggressors, which made thought control and repression also successful. In order to get a group of people on the same page, I think ideological and supression was necessary. True democracy and unity would have been established if the opponents of the war had been allowed to present their views. If the American public were to give up their rights of voicing their opinions, propaganda, thought control, and repression could have been used today with the September 11th tradegy. Domination, of the government usually occurs during wartime. 
=========yorg=========
===from:johnnetta elam
===date:Sun Mar 23 10:07:56 2003
===subject:hist2110
===message:The propaganda, thought control, and repression was used to bring unity among the American people. I think repression was necessary because if Americans are being attack we should take action and not try to restrain the government form taking action if any thing we should support the government. Far as if there was no restriction on others views, I think there would a lot of confusion on what is actually happening, a lot of the media would send out untrue facts. What happen on 9/11, there were many people who lost their lives and we should have done something about the situation then, when we are being attack the only fair thing to do is to attack back. 
=========yorg=========
===from:Ashley Hughley
===date:Sun Mar 23 14:57:34 2003
===subject:Chapter 6 Discussion
===message:Propaganda, thought control, and repression was a success in the United States because it gave all Americans a chance to relate with one another.  Although some of the news the government was telling the people may not have been true, they didn't know any better than to listen to the government because it was their source for news.  I don't think there is a need for anyone to go to war with someone else unless if it's the last option.  Since the government felt that ideological conformity and repression were necessary, they influenced Americans into supporting them.  If opponents were allowed to present their views without restrictions that would cause a whole different war.  These questions apply to events of post 9/11 because of what had happened that day and ever since then many conflicts have lead up to the war that is taking place right now.  Media does have a major impact on people's perspectives.  It can either cause them to support or to go against everything.  The country suffers as a whole during war time.  The economy drops dramatically because taxes and prices of things are increased in order for companies and the government to survive, which means many people are laid off from their jobs.  Money is needed for war, so if the government can't supply enough of it, then it's taken away from the citizens.  Everyone will not be satisfied either way.  
=========yorg=========
===from:Michael E. Elbe
===email:csu16286@mail.claytonstate.net
===date:Sun Mar 23 20:14:06 2003
===subject:Ch. 6 Discussion
===message:Propaganda was used so effectively during WWI because it was a call to the patriotism of the nation.  People’s loyalty to America was called into question if they opposed the war.  Sometimes, people who spoke out against the war were arrested or physically attacked.  No one wanted to be thought un-American, and this created a great outpouring of support for American involvement in WWI and caused those opposed to keep mostly silent.  A similar wave of patriotism swept through post-9/11 America, as the nation came to grips with what happened.  Often during times of crisis and war, civil liberties are diminished as the government exercises increased authority in an effort to protect its citizens and interests, both at home and abroad.
=========yorg=========
===from:Brenda Miller
===date:Mon Mar 24 19:41:54 2003
===subject:Ch 6 discussion
===message:Propaganda, thought control and repression were used with success during WWI because of the fear throughout the nation.  The president needed to have the backing of the American people because the miliatary was not prepared for war and the country had to rally together or possibly perish.  Our quick entrance into the war left Americans unprepared for what was ahead and it was easy for the government to influence the opinions of most.  Also, the economic boon the country experienced helped to make the government very influnetial.  I believe these controls were needed because without the full support of businesses and individals, the US would not have made such quick progress in building the equipment necessary for the war.  If opponents of the war had been allowed to present their views of the war it would not have made much of a difference.  The war changed the US and most people were happy with the rapid changes.  I think that when you apply these questions to events post 9/11 you will find that we do not believe government as easily.  There were members of our government who were aware of how dangerous Bin Laden was before the attacks but the American people were not made aware of it before the attacks; members of our government only give us the information they want us to know, but I do not think that any of us could sleep at night if we knew the whole truth about governmental affairs.
=========yorg=========
===from:Bethany Ballard
===date:Mon Mar 24 19:49:07 2003
===subject:chapter 6
===message:Propaganda, thought control, and repression were used with such success because the American people were informed about the war, which in a way, controlled the minds of the American people.  Those that opposed the war were arrested and punished. Underneath all the propaganda, control, and repression, were the works of coercion, even though the American people were not fully aware of it.   I don't think that idealogical conformaty and repression were necessary, yet the government back then must have felt it necessary in order to get America to become more patriotic and to help support the financial aspects of the war.  If opponents of the war were allowed to express their views, the government might not have had enough money to pay for the war and it might have affected the economy in a negative way with so many people against the war.  Since 9/11, their are many who oppose going to war, and yet many who are in favor of it.  With all the propaganda and so forth, America has become more patriotic since 9/11.  Yet, today, we are not repressed, as we are allowed to state our opinions and express them freely.  Yet even today,during wartime, civil liberities decrease while government power increases.
=========yorg=========
===from:Sharon Stanley
===date:Mon Mar 24 21:31:52 2003
===subject:Ch 6 Discussion
===message:Propoganda, thought control, and repression appeared to be used with so much success because the American people were scared.  With so many years since the last war that the U.S. had been drawn into, Americans initially favored neutrality or not getting involved at all.  Once the country was drawn into the war, it was imperative to keep morale at an all time high.  Propoganda achieved this goal. If opponents of the war had been allowed to present their views the tide of public opinion may have very well been reversed.  Could the U.S. have pulled out of the war at that point?  That's a question that's beyond my meager knowledge however I would imagine that there would have been significantly more pressure on the politicians to end the war much sooner.  During times of crisis and war the government is given WAY too much power to act.  Whether or not we have a responsible government that can be trusted to act in the country's best interest is a topic that could be debated to infinity however there must be a system of checks that says that there are specific criteria that must be met for our country to enter into or declare war on another country.  Our country is a great one. Because of this I don't believe that our civil liberties suffer very much during war time.  We remain free to conduct our lives as we see fit at this time.  Even with the events that are unfolding in the world at this time, we remain free to express our opinions (pro or con) on what's going on and to not be persecuted for our views.  This of course is very different than what was allowed during WWII.  It is one of the things that continues to set us apart from other repressive countries though.
=========yorg=========
===from:Vickie Saunders
===date:Mon Mar 24 22:13:54 2003
===subject:Chapter 6
===message:Propaganda, thought control, and repression was used with such success in the United States during World War I because the majority swelled with patriotism.

Ideological conformity and repression was necessary in mobilizing the nation’s productive and economic strength behind the war, because originally we were not prepared for war abroad.

If opponents of the war had been allowed to present their views without restrictions, the support gathered by the government form the people would not have been what it was.

After 9/11/01 it was propaganda that convinced Americans that one man (Bin Laden) was responsible for the attack.  Now we are convinced that another man was also responsible for terror (Saadam).  I wonder who will be responsible for terrorism after America topples Iraq.

It seems to me that during wartime civil liberties are retrained and repealed while governmental power increases.

=========yorg=========
===from:Holli Armstrong
===date:Mon Mar 24 22:18:40 2003
===subject:Chapter 6
===message:Propaganda and thought control became such a success in the United States during WWI, because no one really knew about war like we do today.  Our whole lives are so televised now that national t.v. viewers can choose our husband or wife!  The federal government was not talked about especially like it is today.  We had freedom of speech then, but it wasn't utilized like it is today.  I do think that since 9/11 we have gone a little too far in protecting our country.    
=========yorg=========
===from:Hannah Terrence
===date:Mon Mar 24 22:40:03 2003
===subject:Discussion 6
===message:It's much easier to employ psychological manipulation to get what you want when you're in power than it is to commit to educate the people and to create an intelligent, thoughtful nation. Back then, I'm quite sure I would have been arrested, because I still think that the theories that sparked the Red Scare are quite intriguing. I simply have the benefit of historical hindsight and can see that their experiment failed, on some levels. I don't know that socialism itself failed, but rather the totalitarian state that it evolved into failed. One of my favorite quotes is from Emma Goldman, an expatriate who was deported to Russia, "If I can't dance, I won't come to your revolution."  It does scare me, post 9/11, that the same methods used then to intimidate free speech are working like an old charm today. The hatred and defensiveness among fellow Americans hurts me deeply. I'm disappointed in us. I'm disappointed that someone can still use religious rhetoric to control a nation. I guess it is facinating to watch the tides of it all. Civil War, KKK. Bolshevik Revolution, Red Scare. Women to work in World War II, back to the kitchen in the 50's. We seem to have this romance with authoritarianism in this country. Whether I agree with dissenters at all times in this nation or not, without them and their freedom to speak, I feel absolutely terrified, I see a Hitler for us on the horizon. It is imperative that we forever honor dissent in our nation, no matter how noxious we find the opinion we disagree with.        
=========yorg=========
===from:Raychele Ryans
===date:Mon Mar 24 22:58:39 2003
===subject:Hist 2110
===message:Propaganda, thought control and repression was successful int the United States because it appealed to people and pity.  It also encouraged the feeling of patriotism.  To go against that would brand you as unamerican and may result in physical harm.  Some of the methods used were less than honorable, but it swayed people in their direction.
=========yorg=========
===from:Raychele Ryans
===date:Mon Mar 24 22:58:51 2003
===subject:Hist 2110
===message:Propaganda, thought control and repression was successful int the United States because it appealed to people and pity.  It also encouraged the feeling of patriotism.  To go against that would brand you as unamerican and may result in physical harm.  Some of the methods used were less than honorable, but it swayed people in their direction.
=========yorg=========
===from:TONYA
===date:Wed Mar 26  5:21:59 2003
===subject:HIST2110
===message:Proganda was a success in the United states regardless of the initial resistance of the war.  Ideological conformity was necessary because of the tolerance for radical ideas.  I feel there is a need to defend our freedom.  We fail to aggresively defend our own constitutional rights because we dont appreciate their origin and importance.
=========yorg=========
