===from:Lindsay Bowie
===email:lindsaybowie@yahoo.com
===date:Tue Feb 25 11:55:17 2003
===subject:Chapter 7 Discussion
===message:There were several contentions between the US and Japan, of which four were significant:  (1) Japan's alliance with US opponent Germany, (2) Japan's expansive aggression into China, (3) Japan's resistance to the Open Door policy, and (4) US propoganda of "yellow peril".  These contentions showed different views of US and Japan in that the US wanted equal commercial access for the world into China, so that the goods in China would be equally available for all.  Japan wanted total control of the commercial China and proceeded to force aggression on China to gain control.  This threatened the US's proposed Open Door policy.  In addition, the nation was already convinced that the immigration of Japanese workers contributed to "yellow peril" and the country did not have strong approval for most any actions committed by Japan. A real threat existed in that no one country should be entitled to complete control of such a major commercial industry (China) and I believe the US was right in wanting to put a stop on Japan's continued expansion.  With Japan's support and alliance with Germany (with whom the US was also at odds), tension grew between the US and Japan.  Both sides began taking small steps to decrease luxuries for the other (i.e. boycotting Japanese silk) and the Japanese continued to violate the Open Door policy and continue expanded their powers in China.  Finally, the Japanese sought a quick blow to US powers and bombed Pearl Harbor, which led to US attacks on Hiroshima and Nagasaki.  I believe armed conflict could have been avoided for some time if Japan had not bombed Pearl Harbor, but more than likely, eventually war would have broken out between the US and Japan.  Although the US and the Allied Powers sought to convince Japan not to continue expansion, Japan did not stop and further continued to support Nazi Germany.
=========yorg=========
===from:Robert Napier
===date:Wed Mar 12  4:57:31 2003
===subject:Chapter 7 Discussion
===message:There were several points that led to the disagreement between the United States and Japan. First, Japan wanted to invade China and the United States felt this type of action would led to millions of dollars lost in the cotton business every year and that the Japan textiles would take over the world market. Second, Japan also wanted to expand its control of the world by taken over Asia. Finally, Japan sign a treaty with Germany and Italy that stated if the United States evaded anyone of its allies, then all parties would declare war on the United States. Also, the United States felt that Japan was not honoring the Open door policy and they also disagreed with Japan starting the New world deal in Asia. The United States wanted to avoid war with Japan, so they began peace talks, but during the time of the peace talks Japan was attacking Pearl Harbor. This decision by Japan led the United States to drop two Atomic bombs, one on Hiroshima and the other on Nagasaki. We as nation will always see war and destruction as long as money and power dictate control.  
=========yorg=========
===from:kevin g
===date:Sat Mar 15 17:53:36 2003
===subject:show me the money
===message:The United States and its growing desire to police the world, was afraid tha Japan would invade China.  Which conveniently was one of America's largest trade partners.  The idea of losing this economical giant, was cause enough in  the American eye to see Japan as a blanket wanting to cover all of Asia.  When America realized that they had gotten in over their head, they tried peace talks which were only met with violence.  ie. Peral Harbour.  Armed conflict is never avoidable is never avoidable when money is involved.  America felt they had to "save" the Chinese, but also protect their wallet on the side...funny, sounds like something you'd hear on CNN now.
=========yorg=========
===from:Carla Foster
===date:Mon Mar 17 20:26:23 2003
===subject:Chapter 7 Discussion
===message:The points of contention between the U.S. and Japan were a) Japan's aggression against China, b) Japan's violation of the Open Door Policy, and c) Japan's signing a treaty with Germany and Italy (Rome-Berlin-Tokyo Axis), which provided political alliance and defense assistance.  The Open Door Policy guaranteed all nations equal commercial access in China.  Japan's agression violated this policy because they wanted complete control over China and felt the Open Door Policy was irrelevant.  A real threat existed in that if Japan's aggressive expansion continued, it would affect U.S. economy and Japanese goods, not U.S. goods, would flood the world market.  Steps that brought the U.S. and Japan into armed conflict were the U.S. boycotting of Japanese silk, total embargo on trade with Japan, and freezing of all Japanese assets in the U.S.  Japan continued to violate the Open Door Policy and pursue its goal to take China and further expansions.  Then came the Japanese attack on Pearl Harbor which led to the U.S. counterattack using the A-bomb on Hiroshima and Nagasaki.  I do not think war could have been avoided because Japan did not want to compromise and continued its expansion efforts.  War may be avoidable if both sides are willing to make some compromises, but it is most likely to happen when it concerns freedom, economy, and control.
=========yorg=========
===from:James Pike
===date:Tue Mar 18 12:56:10 2003
===subject:CHapter 7
===message:Contention, described by The American Heritage Dictionary, is the striving to win in competition or rivalry.  Now, what were the points of contention between the United States and Japan?  Firstly, the contention between the U.S. and Japan came from America’s fear that the Japanese were threatening America’s Open Door Policy.  This policy maintained the interest of big business in foreign markets, and since money is an important part of government, the continued profits from markets in China were of high interest.  Secondly, the underlying racial prejudice for the Japanese played a decisive role in the contention.  Mainly on America’s side, because I read nothing of the prejudice towards Americans by the Japanese, the prejudices harbored by Americans failed to cease this contention.  The differing view of the United States’ right to its Open Door Policy of China by the Japanese further heightened the contention between powers.  Was there a real threat?  Well, that depends on what type of threat.  There was the potential for a substantial threat to American business in China.  As for a immediate threat to freedom for Americans, the answer is no; in the same sentence, allow me to say that the potential for Japan’s want for expansion could have proved threatening towards the United States, especially if Japan and German succeeded in controlling the vast empires that they almost did.  
The alliance of Germany, Italy, and later Japan contributed to the armed conflict between the United States and Japan; however, the immediate confrontation of Nazi Germany, Japan’s attack on Pearl Harbor, and Roosevelt’s dealings with the Japanese all could have contributed to the armed conflict of America and Japan.  Though this sounds like a slippery slope, I am not saying that the removal of one of these actions would have destroyed the need for World War II but may have only delayed or lessened this need.  Without needing to be explained, the alliance of the Axis Powers, as they came to be known as, obviously contributed to the Second World War.  The immediate confrontation with Germany may have contained the Hitler’s obsession with world domination; but more realistically, by not allowing Hitler to expand his empire, Britain and France could have confronted Hitler’s army before he gained momentum and a larger fighting arena.  Both of these actions could have prevented Japan’s introduction into the War, thus ending America’s need to fight with them.  The actions of Britain and France were just, being that memories and horrors of war were still lingering in the minds of Europeans.  Japan and Roosevelt’s unwillingness to concede certain abilities furthered the moves to war.  
Could all of this have been prevented?  Well, that is hard to say.  After all, if a frog had wings, would he still bump his butt every time he jumped?  I do not, however, feel that this war could have been prevented.  Hitler was in a different mindset than many other leaders around the world.  Furthermore, Japan wanted expansion, and they wanted the lands of China and the resources that come along with it.  The war may have been contained a little bit more.  With early interaction by America, or just an earlier realization globally of what Hitler and Mussolini wanted, World War II possibly could have been kept to a far lesser area.  The possibility of early interaction lessening the devastation of war, in general, is the reason that I say that war is, at times, inevitable.  Even when a war is for the freedom of another country, aiding and assisting other countries can be beneficial.  By doing so, a country can limit the power and support for an expansionist country.  This does not always require the use of manpower, but it can at times.  A country that is expanding, and expanding with a hate or oppressive regime must be stopped, because eventually, this country will spread its hate, gain power, and turn on its neighbors.  

=========yorg=========
===from:Kevin Tyler
===date:Tue Mar 18 20:33:15 2003
===subject:discussion
===message:The rivalry between the U.S. and Japan was based on the facts of Japan feeling a need to increase it's territory.  As a result of Japan's take over of China the U.S. viewed this as a threat to the "Open Door Policy".  The Chinese was a major consumer of American exports, if Japan had successfully taken over China this could have had a profound effect on American business.  There was a legitimate threat if Japan successfully invaded China this invasion could have impacted a major portion of America's economy.  Next, this invasion could have indirectly effected American liberty by giving Japan a huge advantage strategically considering what the Germans were doing in rope.  The U.S. and Japan finally came into conflict because neither side was willing to concede.  The fact that there was strong racial tension between Americans and the Japanes did not help this situation any.  America did not want to lose the financial benefits of China, while Japan sought to expand.  Armed conflict could have been avoided had either side been willing to negotiate and compromise some sort of resolution.  War is always avoidable but this avoidance weighs heavily on the people who are directly involve with the conflict.  
=========yorg=========
===from:Kevin Tyler
===date:Tue Mar 18 20:51:58 2003
===subject:A different view
===message:We all agree that the conflict between the U.S. and Japan aroused because of the losses the U.S. would suffer financially because of the violation of the "Open Door Policy".  Many of us will look at the Government as greedy, money and power hungry.  Realistically, how many of us would not be willing to react if a person's actions would drastically reduce the size of our paychecks?  Why would we expect the government to be any different?  Most working people are tolerable about pretty much anything, but if you mingle with their wages then most people quickly become intolerant.  I think this is just the way we are as a society.  Is it right or wrong, I don't know.  Is it greed or survival?
=========yorg=========
===from:Kathryn Hatch
===date:Fri Mar 21 19:00:29 2003
===subject:Chapter 7
===message:I feel that the first four questions have been answered quite adequately and I will focus on the last two.  I do feel that war is avoidable.  Of course it is…it has been avoided many times in the past.  However, I don’t believe it is always in our best interest to avoid war.  It is hard to say how things would have turned out had the U.S. not been a part of WWI and WWII, but I think that hindsight makes is pretty clear that the choice to enter these wars was the right one.  The U.S. had the manpower available not only to fight in battle but back at home to produce the goods to help fight.  I believe the U.S. made invaluable contributions, especially in WWII, to stop murderous fascist governments.  Had the U.S. not fought, no one can predict how long the fighting in Europe would have continued or what the map would look like today because of it.  No one likes war, and I don’t believe anyone wants war.  However, I think that when it comes to cruel dictators that inflict horrors on even their own people, force is the only language they understand.
=========yorg=========
===from:Chris Schmidt
===email:chris@d2dtech.com
===date:Fri Mar 21 21:43:08 2003
===subject:US interventionism and war
===message:   <p>The Japan-US crisis that lead to open conflict is typical of all prior US military campaigns. Beneath the propaganda and rhetoric, the US fought to preserve markets for our goods and favorable trade. It wasn't necessarily greed, but the government responding to the business and overall intrests of the American people. Military force was rarely the first method used, but we routinely resorted to it. </p>
<p>Against Japan we tried various forms of economic pressure, but the military regime of Japan was willing to face conflict to continue their expansion into Asia. I think they saw conflict with America as inevitable so they chose to strike the first blow before American production could confront them with a superior military force. </p>
<p>I don't think the conflict was avoidable since there was significant pressure on the government to preserve the Chinese market for American goods. Aside from that, Roosevelt was itching to jump into the European theater and eventualy would have propelled us into war without the Japanese helping. America has changed a great deal since that time. We are now a net debter nation and preserving foreign markets for our goods is not a real issue any more. Now we see more of a trend toward protection of regimes favorable to importing needed goods to us. One of the reasons we are embroiled in Middle-Eastern affairs today is preservation of our need for foreign oil.</p>
<p>In addition to needing to protect our energy sources, we have sworn ourselves to protecting the majority of the Western world. One of the reason Europe is so dead set against our current war is that they have been sheltered by US protection. With no need of great military strength they view world risks as tolerable. They have the assurance that if any risk directly threatens them, they have the US to clean it up. In this respect, we have commited ourselves to always be ready to armed conflict. We have taken away our choice in avoiding war so that our allies can have that luxury.</p>

=========yorg=========
===from:Kristi Smith
===date:Sat Mar 22 11:59:56 2003
===subject:Chpt 7 discuss
===message:The points of contention were the violation of the Open Door policy by Japan along with the invasion of China and the alliance with Germany.  These points of contention resulted in aggressive and deteriorating views of each other.  Neither country wanted to fight a war against the other; however, neither country was willing to negotiate any of these points.  I believe the real threat came with the violation of the Open Door policy.  China was a vast nation with enormous possibilities for the world, and Japan’s aggressive behavior to dominate these possibilities and keep them for themselves was the breaking point.  The U.S. embargo of much needed materials to Japan and Japan’s resistance to negotiation was the point in which armed conflict was seen as the only resolution and I am not sure that it could have been avoided.  Both countries were out for resolution in their favor, neither was willing to give into the others requests/requirements.  Japan was seen as an egotistical and materialistic, wanting China for themselves, whereas, I gathered from what I read that the U.S. wanted to free China from Japan’s hold for the world.  I feel that war must be avoidable at times, because there have been many occasions in which it was avoided.  The circumstances are what make it avoidable and in the country today, the public is so guarded by governmental classification that we are still being influenced by the media with only the information the government allows.  ALL of the circumstances, whether it be in World War II or now, are only know by few people and never always totally disclosed to the public.
=========yorg=========
===from:Ursula Davis
===date:Sat Mar 22 15:20:13 2003
===subject:Chapter 7 reply
===message:In the beginning, Japan became a threat based on two things: 1)Their invasion of China, which threatened American commerce
2)Japan's allegiance with Italy and Germany in mass expansion
Japan was bond and determined to expand irregardless of America's Open Door principles.  The United States was of course against this move which effected trade losses, but tried to remain cautious in dealing with them.  The U.S used words instead of actions to attempt to convince the Japanese that they were in violation of the Open Door principle.  The U.S. was not prepared to fight Japan, nor were we looking to fight anyone at that point.  If Japan had been willing to make any attempts at negotiations, there may not have been a need for War.  The bombing of Pearl Harbour, just as the 9/11 bombings, pushed America against the wall and made it almost impossible not to want to retaliate.  I don't think any American outside of government and probably inside can say with 100% certainty whether War at this point could have been avoided.  Based on the issues of World War II, no it could not because Japan was bound and determined to fight no matter what.  We may not know until after the current War whether it was really unavoidable just as it was discovered after Vietnam, that it was not.  The art of War is very complex, although the takings of life seems extremely easy.
=========yorg=========
===from:Connie Plowden
===date:Sat Mar 22 20:14:49 2003
===subject:Chap 7
===message:After World War I, peace treaties were drawn up for the defeated countries. Japan, one of defeated countries, was dissatisfied by the peacemakers, because of their failure to endorse the principles of the equality of races. As a result, Japan violated treaties and expanded in Southeast Asia, seize Indochina, and joined forces with the Axis. Japan under dictatorship, knew what they wanted and grabbed. The democratic countries responded with timidity and indecision to the aggression of the dictatorship. The real threat was the spreading of dictatorship. The United States opposed Japan's expansion in Southeast Asia. In response, the United States cut-off important exports to Japan. After the seize of Indochina, Roosevelt barred the withdrawal of Japanese funds from American banks. The attack on Pearl Harbor proved disastrous for Japan. It propelled enraged Americans to arms. Arm conflict was necessary, because the crippling of the U.S. Pacific Fleet enable Japan to expand in Asia. Looking back on history, war in some cases is never avoidable. Mainly because of political unrest and poor economic condition, even now.
=========yorg=========
===from:johnnetta elam
===date:Sun Mar 23 11:36:47 2003
===subject:hist 2110
===message:When Japan invade China, which threaten the open door policy for the United Stated commercial access in China. Then Japan joined forces with Germany on the attack on the United States. The United States tried to stay out of the war but like any other time it’s hard for us to stay neutral. I don’t think any thing could have been avoided after the result of the attack on Pearl Harbor. I don’t think the war could have been avoided; even though the United States did try to stay out of the war. At this present time we are at war and I do believe that there was some negotiation done to avoid war but when there are no agreements made we had to take action. 
=========yorg=========
===from:Michael E. Elbe
===email:csu16286@mail.claytonstate.net
===date:Sun Mar 23 23:34:10 2003
===subject:Ch. 7 Disc
===message:Japan’s expansion into China threatened America’s trade potential with China.  Japan wanted to create an empire that included China, Southeast Asia and much of the western Pacific.  This conflicted directly with America’s Open Door Policy towards China and their desire to maintain the existing balance in the remainder of Asia.  To Japan, the US appeared to be trying to keep them from the materials necessary to support their growing empire and to the US, Japan appeared to be a military bully trying to take whatever they wanted.  The escalation of tensions between Japan and the U.S. was a back and forth affair.  The U.S. allowed a treaty to expire, Japan started its plans to conquer Asia, the U.S. imposed an export embargo on Japan, and Japan expanded its empire and entered into a pact with Germany and Italy, and so on.  As this chess match continued, the two countries drew closer and closer to war, until it was triggered by the Pearl Harbor attack on Dec. 7, 1941.  War is avoidable to an extent, even today.  Whether or not war can be avoided is directly related to how willing the potential warring sides are to compromise instead of fighting.
=========yorg=========
===from:Chad-Everett Tisdale
===date:Mon Mar 24 16:35:22 2003
===subject:sometimes war is inevitable.
===message:Each case is different, but I would have to say that war can be averted for the most part.  It seems like some leaders have decided that they are going to war regardless of what diplomacy may take place.  Hitler was determined to expand his borders and no amount of appeasement was going to deter him in my opinion.  As for the United States and Japan, war was probably not avoidable.  The Americans were easily swayed to prejudice towards a group and had already had a fierce distrust of the Japanese.  So, with each new conquest, the Japanese only made the situation worse for the American fears as the press exaggerated the accounts of suffering.  The Japanese, an entirly different culture, were determined to sieze the lands they wanted and were willing to do whatever it took to attain them.  Studies show that they had been planning the attack on Pearly Harbor for quite some time.  In many ways, the Japanese had been moving to check the American economic expansions.  For example, we learned in the last  chapter that the Japanese and Russians had hastily signed a treaty dividing Manchuria between themselves so that the Americans would be unable to enter there.  Both countries had it's goals and it's ways of accomplishing them.  Given the setting in which both nations lived at the time, I would say that war was inevitable.  
=========yorg=========
===from:Ashley Hughley
===date:Mon Mar 24 18:26:54 2003
===subject:Chapter 7 Discussion
===message:Japan not only tried messing up America's commerce by invading China, but it had also formed an alliance with Germany, which was one of America's enemies.  So this was a big mistake because this caused the America to go to war with them.  Japan was trying to get all the power by doing this, in which the U.S. was not going to let them get away with it.  I believe an armed conflict could be avoided if the two rivals were able to come to a mutual agreement.  If one side is willing to cooperate with the other than there wouldn't be a need for war.  We are at war now because Saddam wasn't willing to come forth and surrender.  Just becuase of this, innocent lives are being taken. 
=========yorg=========
===from:Raychele Ryans
===date:Mon Mar 24 19:01:33 2003
===subject:Hist 2110
===message:Japans expasionary moves toward china threatened the open door policy. Japans invasion threatened commerce between the united states and china.  The united states would face a lost of millions of dollars in annual sales.  The japanese felt that the open door policy was not appropriate to the present and future conditons.  Japan and Germany joined forces to go to war against the united states, which prompted the united states to defend its country and its citizens.  The two opposing sides need to come to a mutual agreement about the issues that they are fighting for.  Compromise may be the key in preventing armed wars.
=========yorg=========
===from:Raychele Ryans
===date:Mon Mar 24 19:32:54 2003
===subject:Hist2110
===message:Propaganda, thought control and repression was successful in the united states because it appealed to the people.  It encouraged the feeling of patriotism.  Appealed to pity.  Not all stories were necessarily true.  They used methods that would surely sway peoples attitude in a certain direction.
=========yorg=========
===from:Lucille Clayton
===institution:HIST 2110
===date:Mon Mar 24 20:14:56 2003
===subject:Chapter 7 Discussion Question
===message:The points of contention between the U.S. and Japan were Japan's attempt to take over China, Japan ignoring the Open Door Policy, and the signing of a treaty by Japan with Germany and Italy.  The U.S. saw the invasion of China by Japan as an attempt to gain control of a large area of the world that could threaten America's democracy and its influence on the world.  Economically, the U.S. would suffer if Japan continued to invade China.  Armed conflict resulted when the U.S. boycotted Japanese silk, levied a total embargo against Japanese trade, and froze all of Japan's assets in the U.S.  The final act that bought about war was the bombing of Pearl Harbor by the Japanese.  The U.S. declared war and commenced to use the atomic bomb to counteract against Japan's sneak attack on Pearl Harbor.  In this situation, I don't think war could have been avoided because America was dealing with a Japanese leader that wanted control of the world, not just his country or China.  I think Japan's leader was out of control and needed to be stopped.
=========yorg=========
===from:Brenda Miller
===date:Mon Mar 24 20:26:04 2003
===subject:Ch 7 discussion
===message:The major point of contention between the US and Japan was the open door policy.  Japan's expansionary moves towards China threatened the US economic future.  Barring the US from trade in China meant a loss of $100 million in annual cotton sales alone.  Further, Japan appeared to be a powerful nation that could overtake many nations, the more it conquered, the stronger it would become.  I believe a stronger stand earlier in the conflict could have lead to armed conflict being avoided.  I think that taking a stand when Japan overtook Manchuria may have stopped or slowed the power of Japan.  Our military forces may not have been strong enough for an immediate war, but maybe that would not have been needed.  I think we stand a better chance when the US is an aggressor rather than the one waiting for the other to make a move.  I don't think that war can always be avoided.  There are many people with differing goals and opinions.  As long as there is conflict, there will be war.  Dominance must be demonstrated in order to keep rebel forces from gaining too much power.  I think that when a country shows no force it becomes vunerable to the power of others.  The more powerful and/or rich in economic resources a country becomes, the more it is target by others.  I would like to offer a quote that I think is on point at this time by Martin Niemoeller on the failure of German's to speak up against the Nazis, "First they came for the Communists, but I was not a Communist so I did not speak out.  Then they came for the Socialists and the Trade Unionists, but I was neither so I did not speak out.  Then they came for the Jews, but I was not a Jew so I did not speak out.  And then they came for me, there was no one left to speak out for me."  Sometimes you can not wait until there is a direct threat against you; you must take the offensive to ensure that there are others to stand with you.  
=========yorg=========
===from:Andrew Bell
===email:csu12497@mail.claytonstate.net
===date:Mon Mar 24 21:09:00 2003
===subject:Chapter 7
===message:Japan was a major problem.  They (the Japanese) sought to invade China and gain control of a major portion of Asia.  They ignored the Open Door Policy.  As things escalated from an embargo on Japanese products to the bombing of Pearl Harbor, the United States was left with no choice but to launch a massive attack in retaliation.  
=========yorg=========
===from:Sharon Stanley
===date:Mon Mar 24 21:44:18 2003
===subject:Ch 7 Discussion
===message:The points of contention between Japan and America were:  Japan's not honoring the Open Door Policy, Japan's invasion of China, and a treaty Japan signed with Germany and Italy that said that if the United States attacked one of its allies then all of the allies would declare war on the United States.  And let us not forget the bombing of Pearl Harbor.  Japan's decision to bomb Pearl Harbor was the step that brought the two countries into armed conflict.  The U.S. tried peace talks however they proved to be unsuccessful.  The only way armed conflict could have been avoided would have been for both countries to try peace negotiations BEFORE the bombing of Pearl Harbor.  As for the question of whether war is ever avoidable - the answer is a resounding YES.
=========yorg=========
===from:Vickie Saunders
===date:Mon Mar 24 22:16:15 2003
===subject:Chapter 7
===message: The causes of the contention between the United States and Japan was when the Treaty of Trade and Navigation expired with the Japanese, leading President Roosevelt to freeze Japanese assets and an embargo of trade on Japan.  With no other option the Japanese watched their fuel drop to empty, and their metals, chemicals, machine parts, and other products important to them get embargoed.  

This resulted in a very bitter attitude towards one another, and at this point retaliation was the only thing on their minds, so it was definite that a war was going to start sooner or later.  The reason why conflict started between the two nations was in 1940, when the Japanese implemented its New Order in Asia.  Then Roosevelt retaliated by freezing their supplies, which made them very upset and they attacked Pearl Harbor on December 7, 1941.  

Nevertheless, conflict couldn’t be avoided in their case because neither would compromise even they both wanted to avoid a war from the beginning.  Personally, I don’t think that war can be avoided because when one country doesn’t have a legitimate reason, the other will find a reason to hold a grudge. For instance, the war with Iraq now could have been prevented the tension between these two nations was over twelve years ago, and President Bush just re-lit the fire and this is doing a number on the American economy because of his mistake to invade and bomb Iraq.

=========yorg=========
===from:Linda Dawson
===date:Mon Mar 24 22:30:41 2003
===subject:HIST2110
===message:The points of contention between the United States and Japan were the expansion of Japan into China's territory which would decrease the trade and economic development of trade for the United States. Also, the mistreatment of peasants in China and the loyalties formed between Germany and Japan to gain economic trade dominance by expanding into other countries. There was no real threat to the American people and the only reason the U.S. felt that they had to intervene was because of the expansion into China and the downfall that it would have on the United States economic development. The steps that brought the two nations into armed conflict were the loyalties formed between Germans and the Japanese and the bombing of Pearl Harbor. The armed conflict could not have been avoided during that time period because of the devastation caused to Pearl Harbor, which forced the U.S. into the war. War is avoidable and all measuures to avoid war should be taken and diplomacy must be given first priority before we take steps to engage in a war. All diplomatic efforts were taken during this timeframe as well as the current war that the U.S. is engaged in.
=========yorg=========
===from:Hannah Terrence
===date:Mon Mar 24 22:53:31 2003
===subject:Discussion 7
===message:I would like to see humanity step up to a higher plane. War will be avoided when individuals cease trying to dominate each other and focus on the needs of their people. The trick to it is that to avoid war, you have to have all nations and peoples commit to this at one time. This is unlikely since we still seem to be more like chimpanzees when it comes to being territorial and waging war. I tend to think of Jane Goodall's apes when I see world leaders, past or present misbehave, and hurt and kill solely for dominance. Japan? Yes, I guess I think that war is rather unavoidable when an emperor who thinks he's God sends young men to bomb Pearl Harbor. I know that there are complex layers of politics and many battles, but for me, it boils down to survival in a world where the apes periodically go insane.      
=========yorg=========
===from:Al Desmond
===date:Tue Mar 25  0:31:12 2003
===subject:Diss 7
===message:The causes of the contention between the United States and Japan was when the Treaty of Trade and Navigation expired with the Japanese, leading President Roosevelt to freeze Japanese assets and an embargo of trade on Japan. With no other option the Japanese watched their fuel drop to empty, and their metals, chemicals, machine parts, and other products important to them get embargoed. This resulted in a very bitter attitude towards one another, and at this point retaliation was the only thing on their minds, so it was definite that a war was going to start sooner or later. The reason why conflict started between the two nations was in 1940, when the Japanese implemented its New Order in Asia. Then Roosevelt retaliated by freezing their supplies, which made them very upset and they attacked Pearl Harbor on December 7, 1941. Nevertheless, conflict could have been avoided. First all the Japanese knew that the one strike was thier only strike.  The attempt was more of David and Goliath.  David knew he only had one stone to throw and it had better hit the vital part. I personally feel that America knew that the Japanese was not a threat.  If so they would have taken them more seriously.  Armed conlfict could have defenitely been avoided but sometimes it takes a lot of bending from one and a little from the other but the greater goal is achieved.  I definetely feel war was avoidable with IRAQ.  People can support whatever they think they are supporting but the truth of the matter is IRAQ has been doing what they are doing for longer than 12 years so why now.  If you really want to take a diplomatic approach then let diplomacy work.  I do not feel that the US was in any more danger than it is now and would not have been if Bush would have waited!
=========yorg=========
===from:Lorena Lockhart
===date:Tue Mar 25 17:25:04 2003
===subject:Chap 7
===message:There were many issue that the United States and Japan wanted to get to the bottom of like the invasion of China by Japan, the world market, Japan wanting to expand and the list goes on. Everybody was out for self and in these cases somebody will always loose. In the case of the United States and Japan there was really no need for war in my opinion but when you don't want on body to get a piece of the pie you will do anything and I do many anything to stop them. By doing anything Japan trying to fool the United States that they were really concern with peace they were cont. with there own underhanded plans by attacking Pearl Harbor and this was the straw that broke the camels back for the United States. I do feel that war can be avoid and when it is not the people behind have more of a personal issue than one that would be good for the American people
=========yorg=========
===from:Bethany Ballard
===date:Tue Mar 25 23:03:47 2003
===subject:chapter 7
===message:There was contention because of Japan's expansionary movies in Manchuria, and then against all of China.  The U.S. did a lot of cotton trading with China, and if that were demolished, it would greatly affect the U.S. cotton sales.  Plus, the U.S. was very sympathetic to China already.  The U.S. tried to negotiate with Japan, yet they refused and then the attack on Pearl Harbor is what forced the U.S. into war with Japan.  I don't think that armed conflict could have been avoided because Japan was unwilling to negotiate.  I think armed conflict can be avoided, but at least one side had to be willing to negotiate somewhat.  Japan wanted their control and power and weren't willing to give it up at any cost.  I think today war could be avoided in the same way, yet today, like Suddam Hussain, he cares more about his power and control than he does of his own people.  He could care less about going to war and that many of his own people will be killed. In a situation like that, there is no other option but war when trying to rid the world of someone like him.  Today,there is no other way in this case with Iraq.
=========yorg=========
===from:Tonya Wyche
===date:Wed Mar 26  6:19:23 2003
===subject:hist2110
===message:Japan is our most dangerous enemy.  Both Japan and the United States hoped to avoid war, but neither would compromise its goals in return for peace.  War is not avoidable because it challenges judgement, anlysis and prognosis all sides.
=========yorg=========
