#!/usr/bin/perl
package main;

#
# Editor
#

BEGIN {
   unshift(@INC,'/local/classnet/cgi-bin/lib');
}
    
# Modules to include
require CLASS;
require EDITOR;
require TESTEDITOR;
require INCLASSEDITOR;
require JAVAEDITOR;
require DIALOGEDITOR;

# Turn off file mask
umask 000;

# Parse incoming query into query object
$query = new CGI;

# Instructor and course setup
CN_UTILS::verify_pairs($query,'Class Name','Ticket');
$cls = CLASS->new($query->param('Class Name'));
($cls->exists()) or
   &ERROR::user_error($ERROR::CLASSNF,$query->param('Class Name'));
$mem = $cls->get_member($query);
if (!(($mem->{'Priv'} =~ /assignments/) or ($mem->{'Priv'} =~/owner/) or
   $query->param('cn_option') =~ m/^Submit/ )) {
    ERROR::user_error($ERROR::NOPERM);
}

#get the editor for this assignment
$asn = $cls->get_assignment($query,$mem);
if ($asn) {
    $editor = $asn->{'Editor Type'}->new($asn);
} else {
    CN_UTILS::print_cn_header("Assignment?");
    print "Select an assignment name by clicking on a name in the Assignment Listbox.";
    CN_UTILS::print_cn_footer();
    die;          
}

# Perform the option
$_ = $query->param('cn_option');
SWITCH: {
   /^Edit/	   &&  
       do  {   # edit assignment
               $editor->open();
       	       last SWITCH;       	   
       	   };

   /^Command/	   &&  
       do  {   # edit assignment
               $editor->command();
       	       last SWITCH;       	   
       	   };

   ERROR::user_error($ERROR::NOOPTION);

}


