#!/usr/bin/perl
package main;

#
# Get_login gets remaining login information from a class member
#

BEGIN {
   unshift(@INC,'/local/classnet/cgi-bin/lib');
}
    
require "optimize.pl";

# Parse incoming query into query object
$query = new CGI;

# Get class name
$cname = $query->param('Class Name');
$_ = $query->param('cn_option');
SWITCH: {
    /^Get Login/    &&
        do  {  #
               if (defined $cname) {
                   $cls = CLASS->new($cname);
                   if ($cls->exists()) {
                       $cls->print_login();
                   } else {
                      CN_UTILS::print_cn_header("$cname?");
                      print "The class '$cname' doesn't exist.  Check 
your spelling and capitalization and try again. ";
                   CN_UTILS::print_cn_footer();
                   }
               } else {
                   CN_UTILS::print_cn_header('Class?');
                   print "Select a class name in the Class Listbox by clicking on it. Click on <b>Back</b> now and try again.";
                   CN_UTILS::print_cn_footer();
               }
               last SWITCH;
            };

    /^Get Menu/    &&
        do  {
               CN_UTILS::verify_pairs($query,'Class Name','Email','Password');
               $cls = CLASS->new($cname);
               my $email = $query->param('Email');
               $uname = $cls->get_uname($email);
               if ($uname eq '$requests') {
                   ERROR::user_error($ERROR::ENROLLREQ);
               } elsif ($uname eq '') {
                   ERROR::user_error($ERROR::MEMBERNF);
               }
               $query->{'Username'}->[0] = $uname;
               $ticket = "$$";
               $tfile = "$GLOBALS::TICKET_DIR/$ticket";
               open(TICKET_FILE,">$tfile") or
                   &ERROR::system_error("CLASS","get_login","get_menu",$tfile);
		 print TICKET_FILE "$uname\n";
                 print TICKET_FILE $query->remote_addr();
               close TICKET_FILE;
               my $dname = CN_UTILS::get_disk_name($uname);
               $mem = $cls->get_member($query,$uname);
               $mem->check_password($query);
	       $mem->{'Ticket'} = $ticket;
               $mem->print_menu($cls);                   
               last SWITCH;
            };
   ERROR::user_error($ERROR::NOOPTION);
}
