#!/usr/bin/perl
# main-menu prints the main menu
#
package main;

BEGIN {
    unshift(@INC,'/local/classnet/cgi-bin/lib');
}

require CGI;
require CN_UTILS;

my $query = new CGI;

CN_UTILS::print_cn_header("test2");
my $v = $ENV{'HTTP_COOKIE'};
print "value=$v\n";
