===from:Nick Cavill
===date:Tue Sep 30 14:09:34 2003
===subject:FPT : Topic, 9/16
===message:I am going to research, and discuss the attempts to prosecute the individuals trading songs over the internet.  Using the Kazaa song-sharing website.
=========yorg=========
===from:Nick Cavill
===date:Tue Sep 30 16:22:19 2003
===subject:CA : Hack's Questions, 1 & 2, Sept 9
===message:1. Hack believes that it is wrong to allow men access to the female floors at all hours of the day, and vice versa.  Also, she believes that it is wrong to promote how to have safe sex and alternate ways of making love.  She believes that is something that should be left for marriage.  Yale is supposed to be a school that listens to the views of it's students, and is a "community based on constant reflection and reappraisal".
2. Hack states that Yale should reappraise thier policies and beliefs.  I don't think that Yale refuses these beliefs, I think this is more jaded to the opinion of the authour.  I don't disagree that to a point, schools don't do enough to enforce the rules it sets.  The authour states that her religion is Judaism, and her views may differ vastly from another.  Yale is attempting to make their living environmet as neutral as possible, and make the majority as happy and comfortable as possible.  The only solution that she offers, which I agree with, is to allow underclassmen to live off campus.  She never states what the answer was from the administration about the off campus rule.
=========yorg=========
===from:Nick Cavill
===date:Tue Sep 30 16:44:11 2003
===subject:CA : Jacoby's Q's 1 & 2 , Sept. 9
===message:1. The strongest evidence in this article is the section about what is important to today's youth.  It was very easy for me to even recall the answers to the questions in the essay about Eminem and Fred Durst.  The point was that anyone can basically learn whatever they want to learn.  We learn who inspired Eminem because we may like his music and want to know more about him.  If we were to take that same enthusiasim to the class room we could learn our history or our math that much better.  The SCAM argues that the test doesn't take into account all of the other things that should make a difference, like athletics, art, music, etc. I believe this argument has validity, but it isn't strong enough to stand on its own.  I you were to think about it, to graduate from high school without taking a test, you still have to pass all those classes that teach everything that is on one of those tests.  The test just makes sure that you were paying attention in those classes.                      2. The first sentence of the last paragraph states that "the exams to have faults, but pressuring kids to master realms of facts isn't one of them".  This stands out to me stating that the authour supports the testing.  Jeff agrees that the tests do have some faults, but he believs that it is important to make kids learn necessary areas of study that is necessary for todays world.  I think that this article is not written to push you in one direction or another, I think he is very subtle about what he says, but he does a good job of getting his point across.
=========yorg=========
===from:Nick Cavill
===date:Tue Sep 30 16:56:32 2003
===subject:CA : Q's 1 & 2, Ad pg. 188
===message:1. The strong emotional appeal that this ad makes is obviously hurting the kids, and the family.  It is saying that gas heat is bad for the family, and your children will be hurt by it.  The woman looks almost concerned, and the child looks sad, almost saying, LOOK, do you really what to do this to your little girl?  I think the appeal that this ad makes is justified, to a point.  Is is an oil company trying to make you think gas is bad for your family, so swith to oil.  I have to ask myself, if gas is so bad, why is the vast majority of homes and business using gas heat.  This over emphasizes the danger of gas heat.  2. To verify the validity of this article, I would have to find some statistics about how many health problems are caused by gas heat, and how many deaths are caused by gas.  Also, I could find out how prompt the service really is by testing it myself.  The big red flag it, I would relly like to know if it was true that the supplier of oil if I had an oil heated house, really actually knew my name, or my family. I would have to say probably not.
=========yorg=========
===from:NIck Cavill
===date:Tue Sep 30 17:10:01 2003
===subject:CA : Question 8e, pg. 193, Sept. 23
===message:There has always been talk about how beauty contests are degrading, or not degrading to women.  I think all of that is just stupid.  Beauty contests are not anymore degrading to women, than playing football is to a man.  I have never heard of a woman being taken at gunpoint and being forced to walk on stage in a contest.  Women who enter beauty contests know exactly what they are doing and what they will be wearing.  Why would you enter a BEAUTY CONTEST, if you think it is degrading to get judged on how you look in a dress or a bikini.  If you have a talent, and you are not afraid to show it, why is it so degrading.  The only reason that anyone objects is probably because they are jealous they couldn't do it.  Frankly, if you don't agree with beauty contests, don't watch them.  Nobody is forcing you to watch them.  I say if that woman on stage is up there because she wants to, who are you to tell her that she is wrong.
=========yorg=========
===from:Nick Cavill
===date:Tue Sep 30 17:29:43 2003
===subject:CA : Survival Project
===message:My group all agreed to keep the same seven people.  Our decisions were mostly based on the ability to reproduce, and to rebuild.  We kept Dr. Dane because he is still fairly young, he is educated in history, he is in great health, and he is interested in politics which will help to rebuild a political system.  Mrs. Garcia is young and is obviously able to reproduce because she has a three month old.  Mary Evans is also young and able to reproduce, and is also trade school educated.  Mr. Newton is only 25 and is a fitness buff.  Also, he is in his last year of medical school so he has a good knowledge of medicine.  Mrs. Clark again is still young and at an age to have kids.  She has a college degree and an electronis engineer so she has a wide range of knowledge.  Mr. Blake has experience with construction which will be very important, and he also has a BS in mechanics and is very handy.  Father Frans was the last person we would save because he is only 37, he is a former college athlete, and he has a farming backround which could be very valuable.  Also he being a priest doesn't hurt.
=========yorg=========
===from:NIck Cavill
===date:Tue Sep 30 18:06:41 2003
===subject:CA : Q's 1-3 for AD pg. 221
===message:1. This ad stresses that the use of natural gas is good for the environment. It burns cleaner and is better for the environment.  Butterflies are used to represent the fragility of nature.  I tree looks big and powerful, a butterfly is delicate, and fragile.  2. This advertiser uses the approach that whoever is looking at the ad cares about the environment.  They also assume the audience to be heads of households, or others that make the decisions about whether to use fossil fuels or natural gas.  3. Personally I like the positive advertisement much more than the negative ad.  I think the ad on page 188 is much weaker than this ad.  That ad brings you down just looking at it.  This is positive and makes you want to read more about it.  The butterflies are colorful (probably) and that is always eyecatching in an advertisement.
=========yorg=========
===from:Nick Cavill
===date:Wed Oct  1 12:30:00 2003
===subject:FPT : Topic, New
===message:I was not able to find the type of information that I was looking for about my other topic. So...I have decided to switch my topic to the other one I was thinking about.  I am going to research the types of security measures that banks are taking to protect us from stealing our money, or even identities.
=========yorg=========
===from:Nick Cavill
===date:Wed Oct  1 12:36:37 2003
===subject:FPT : Weekly Journal #1
===message:I have begun to research the type of Journal that I would want to send my paper to.  I have also found a few contacts that I will be speaking with to research my topic. My sister is a branch manager for Valley Bank, in Davenport.  I will be heading to the Quad Cities this weekend, so I will interview her then.  Also, I am going to interview the regional manager for Valley Bank, who is located in Bettendorf.  I also plan to speak with someone in Wells Fargo.
=========yorg=========
===from:Nick Cavill
===date:Wed Oct  1 13:10:15 2003
===subject:CA : Patterson Q's 1-4, Sept. 23
===message:1. Patterson makes his claim statement in the first paragraph.  He states that "misinforming the nation is dangerous, since it fuels fears of decline and displacement among some whites, anxieties that are not only divisive but groundless".     2. Introduction, state of claim;  Articles stating statistics;  Reports of misinformation;  Policies of the Census Bureau;  Stages of racial classification;  conclusion, Let's keep the facts straight.     3. The danger in releasing inaccurate information is it causes people who don't know any better to worry about things that are not true.  Whites are presented with information that they will soon be the minority, which is proven to not be the truth in this century.  This also causes racial tension between whites and black, for example.     4. I don't think each is equally as decisive.  You cannot argue with history, it has already happened, so how can you say that it is inaccurate.  The only problem is, that was the past, and things do change.  Statistics can be powerful, but they also can be fought, due to who the organization is that took the stats.  The national cencus bureau is very respeced, so its stats are powerful.  Political analysis is what is happening today, but like I had said things change.  Politics are always changing, so it is hard to judge purely by that.  I think as a whole, the combination of all of these is very powerful, which states a powerful claim.  I think in this case, the stats are the most up for challenge.  It was stated in the writing that the people had the choise to choose more than one type of ethnicity.  This can cause defeciencies in the statistics.
=========yorg=========
===from:Nick Cavill
===date:Wed Oct  1 13:50:56 2003
===subject:CA : Goodman Q's 1-6, Sept. 25
===message:1. Intro, Abolish Grading;  Disposal of Objection;  Grading is not necessary for getting a job;  History of Examination;  Chief objectors of grading, Students and Parrents;  Good reasons for grading;  Goading students;  Balking in doing the work; Weeding out.   2. Of course there are stronger parts than others.  Goodman sets off what he wants to empahsize by telling you.  If it is something he wants you to pay attention to, he will say, MOST IMPORTANT OF ALL, or other attention getters.  Also the use of () sets off an entire paragraph.   3. He only calls out six of the prestigeous universities for a simple reason.  If the best schools in the nation can do this and it works well, all the other universities could them follow suit.  Everyone knows about Harvard and Yale, so they would pay attention when they do things like this.  If some community college were to do this, who would take notice?    4. The entire first paragraph is his purpose of this proposal.  The proposal to abolish grading.    5. Teachers need to continue to give grades because otherwise, graduate schools and other foundations would not know who to try to get.  Grades are the indication of who to recruit to your program.  Goodman attacks this claim right away in the third paragraph by disposing of the objection right away.     5. Goodman thinks "testing should be used only and entirely for pedagogic purposes and as teachers see fit".  Grading makes students see test taking as studing to get a grade, and not learning the information for the love of learning.
=========yorg=========
===from:Nick Cavill
===date:Mon Oct 20 12:38:42 2003
===subject:FPT: Weekly Journal #2
===message:I have spoken with my sister, and another manager at Valley Bank and recieved good information about measures that banks are taking.  I am still searching for the journal that I want to send my paper to. I have narrowed it down to two or three, but I would like to get more information about them before making my decision.
=========yorg=========
