===from:k533
===date:Tue Sep  9 11:23:13 1997
===subject:assignment 2
===message:1.  p533K
<br>
2.  9/10/97
<br>
3.  557-81-4402
<br>
4.  9/9/97
<br>
5a.  Frame Theory.  Source: Minsky (1975) in Pressley.  Explanation:  Frame theory represents one of the theories that psychologists and educators use to describe how declarative and procedural knowledge are represented in the mind.  A frame is defined as "a data structure for representing a stereotyped situation" and includes additional information, such as how the frame can be used and expectations related to the situation.  Frames contain a "top-level", which represents things that are always true about the situation, and a lower level that provides information about specific instances. 
<p>
5b.  Script Theory.  Source:  Schank and Abelson (1977) in Pressley.  Explanation:  An alternative theory of knowledge in which it is proposed that knowledge is represented or stored in a script format.  Scripts describe a sequence of events.  In applying the script theory, individuals store knowledge about event sequences pertaining to life events, such as going to the supermarket, going on a trip, attending a wedding, etc.
<p>
5c.  Schema Theory and Mathematics Problem Schemata.  Sources:  Pressley.  Explanation:  Schema refers to "a chunk of information stored in long term memory, specifying how a number of concepts relate to one another."  Additional information related to the schema may include the purpose of the event and information about the when and where the event occurs.  Activation of a schematic representation constrains/limits thinking about details related to the event.  Mathematics problem schemata refers to schematic representations of mathematics problem types that are store in long-term memory and aid in the identification of critical information needed to solve a problem.  
<p>
5d.  Referential Connections.  Source:  Pressley.  Explanation:  Paivio (1971) proposed the idea that knowledge is stored in a complex associative network made up of both verbal and imaginal representations.  The concept of referential connections refers to the link between elements in the imagery representational system and elements in the verbal representational system.  The referential connections between the two systems allow a word to bring to mind an image of the object that the word refers to and, vice versa, a picture can bring to mind names for objects seen.
<p>
5e.  Situated Knowledge or Cognition.  Source: Pressley and Hattie, Biggs, & Purdie (1996).  Explanation:  Situated knowledge means that knowledge is a result of the interaction between the environment and the mind and cannot be separated from "the actions that give rise to it nor from the culture in which those actions occur."  Hattie, et al. (1996) apply this concept to teaching  and interventions.  Through meta-analysis, they conclude that effective skills training and interventions should occur in context, should use tasks within the same domain as the target content, and should promote both increased learner activity and metacognitive awareness.
  
<p>
6.	The concepts of frame theory, script theory, and schema theory all refer to different theories proposed to explain how declarative and procedural knowledge is represented and stored in the human mind.  All three represent useful conceptualizations of knowledge and cognitive processing.   For my application, I will be teaching a class of students with special needs.  This is a self-contained classroom of students whose disabilities range from mild to moderate.  They have a variety of individual needs:  attention problems, learning problems, speech/language delays, motor problems, visual and hearing  impairments, and mental retardation.  A functional curriculum is used in the classroom, focusing on teaching functional academics and life skills.  The use of a functional curriculum will demonstrate the concept of situated knowledge, in that the students will acquire skills and strategies as a result of the actions they take within an environment (i.e. the supermarket).  
<p>
	The focus of my class will be on domestic and community living skills, with an emphasis on the skills needed for grocery shopping.  Students will be instructed on how to use a shopping list, how to use signs in a grocery store to shop for items, how to identify shopping list items, and how to use a calculator.  Instruction will include both in-class activities, such as basic math and calculator skills, and class trips to the local supermarket. 
 
<p>
	Prior to going to the grocery store, I will ask the students to help me generate a list of events or steps that are involved in a trip to the grocery store and making a purchase.  I will supplement their input with a story about going to the grocery store.  Students will also role play different grocery store activities.  Through these activities, students will be examining and adding to their script for "going grocery shopping" (applying the script theory).  They will also be framing their knowledge of what "going to the store" means be developing an idea of what things they can expect to see at the store and what activities they can expect to participate in (frame theory).
<p>
	An additional in-class activity will involve learning supermarket-related vocabulary words through flash cards.  Flash cards will include both pictures (from print ads) and vocabulary words.  This will help the students in dual processing the new vocabulary words as both visual representations and verbal representations and making a link between the two (referential connections).  Students will also be learning how to do basic decimal addition and subtraction using a calculator.  In-class problems will be presented with the context of making purchases.  Some of the students may also need additional instruction in the use of money.  Direct instruction in the identification of coins and bills will be provided, along with lessons in monetary value.
<p>
	Early  in the lesson, students will accompany the teacher on a trip to the store.  The teacher will model how to make a list prior to going shopping, how to find coupons in the newspaper, and how to use the list and store signs while shopping.  Students will be asked questions relating to in-class instruction while shopping with the instructor.  The instructor will also demonstrate how the students will use calculators while shopping to calculate whether they have enough money to make purchases.  After the initial trip, students will be asked to reflect back on how the trip matched their previous expectations and what additional information they should add to their "script" or "frame" for shopping.
<p>
	Future trips will be more student-centered, with the students performing shopping activities under the direct supervision of the teacher.  Students will be given money, a shopping list, coupons, a calculator, and a chart for figuring out tax on items.  Students will use signs to locate items, make price comparisons, do subtraction (item costs and tax) on their calculator as they shop, and will purchase items at the counter.  To do the subtraction on the calculator and give money to the cashier, the student will need to use the steps and strategies that they were taught in the classroom and apply them to the real world situation.  Students will use their schema for math problems from the classroom to solve real-life problems that arise while shopping.  (application of math schemata to problem solving)
<p>
	As the students become more comfortable with the steps and skills involved in shopping at the grocery store, they will be given more independence.  They will eventually shop independently in the store with the instructor present in the store for minor support.    

=========yorg=========
