===from:PP533
===date:Wed Sep 17 16:43:06 1997
===subject:Assignment 3
===message:2.  9/17/97
3.  537-96-8027
4.  9/17/97
<br>
5a.  Benefit of prior knowledge in learning new material.  Source:  Pressley Ch #4.  An individual is better able to learn new information if that information is related to and is in agreement with an area of knowledge the individual already has.  
<br>
5b.  Prior knowledge may interfere with new learning.  Source:  Pressley Ch. #4.  This concept, while apparently contradictory to 5a is actually quite consistent.  This concept states that if an individual is presented information that contradicts that individual’s prior knowledge of the area, the individual may not learn the new material and may instead retain their prior knowledge, even if the prior knowledge is incorrect.
<br>
5c.  Development of expertise.  Source:  Pressley Ch #4.  Experts are not born experts.  Expertise, rather, develops over a long period of time, after multiple exposures or attempts in the area.  Expertise develops best when the individual is an enriched environment, with good teachers and mentors and when the individual has a great deal of motivation and interest.
<br>
5d.  Perception and expertise.  Source:  Pressley Ch #4.  Experts are able to quickly perceive the critically important information when presented with scenarios in their field.  They do not become "bogged down" in irrelevant information.  Novices, on the other hand, focus on the surface features of the scenario, which may inhibit their ability to perceive the important information
<br>
6.  In the teaching of psychology, there are two major goals:  a) teaching the content of psychology and b) training students to be psychologists.  A major part of becoming an expert in the field of psychology is the ability to properly design psychological studies and interpret and critique the designs of other studies.  Thus, the focus of my applications will be on training introductory psychology (Psych 101) students to begin becoming experts in research methodology.  To do this, I would first introduce the topic of research methodology and use examples of psychological studies in a field in which college students are relatively expert—education (since they have all been students for at least 12 years).  That is, I would speak of studies in which variables include things like test scores, GPA’s, test style, etc.  Thus, by teaching the new concepts in methodology in the context of their prior knowledge of school and education, they may be able to understand methodology more easily (5a).  Further, by using this intervention, it is likely that they would not focus as much on the unimportant aspects of a particular study, but would be able to perceive the higher level and relevant information about what the particular study teaches about research design (5d).  Second, I have noted that many upper-level psychology students have incorrect ideas about research (which interfere with their ability to later correctly learn) that are the result of the manner in which they initially were taught the information (5b).  For example, many students believe that not finding a significant difference means one must accept the null hypothesis.  This is incorrect.  One does not find a significant difference, on fails to reject the null hypothesis.  Although subtle, the difference between these two conclusions is vitally important in understanding the logic of experimentation.  However, because it is difficult to clearly explain this logic to introductory students, may professors teach the easier (and incorrect) conclusion.  However, because the goal is to enable these students to one day become experts, I would teach the correct logic (realizing that I may be asking for many headaches).  Finally, because expertise develops over a long period of time and with many exposures to the field (5c), I would have introductory students begin designing simple experiments and analyzing simple experiments during class.  Further, as I introduce the classic studies in psychology and the conclusions that have been drawn from them, I would take time to describe the design used by the researchers and why that design was used to address the particular issue.

=========yorg=========
