===from:Ap533
===date:Wed Sep 17 16:58:02 1997
===subject:Critic 1 Assign 2
===message:Prior knowledge of science can be useful in the understanding of Latin terminology if the Latin name for a process or thing is connected to a literal translation each time a new Latin term is introduced.  In this way the unfamiliar term is associated with a language the students may already know or are already learning.  If it is followed by a mental image as suggested by T. Andre in class this connection could be further strengthened and cognitive load diminished. In this way lower level, or what should be entry level skills, could be learned in a manner which reinforces their developing schemas about science and its shared latin vocabulary.  Of course, we might do what has not been done in recent memory and require that students learn Latin and English early in their careers and receive the benfits it would proceed from that in whatever discipline they chose, science included.In either case, the closer the Latin term comes in being related to the actual charateristic or process the better the student will do with subsequent relations of a similar type.For example, our prior knowledge of spelling relating to the word "possess." "Possess" consistently has the letter "s" appearing four times.  When this frequency does not occur, such as in the first paragraph of Hp533's problem description, those with prior knowledge add the missing "s" into the decoding process often unconsciously. Perhaps a list of the  most common Latin roots and their translations would be of some help in Hp533's (pre)(dic)a(ment).Hp533 seems to have a good understanding of the difficulties involved in teaching those who do not possess entry level skills.  The techniques and processes we study about in class I believe will go a long way in dealing with that issue.    
=========yorg=========
===from:Ap533
===date:Wed Sep 17 16:58:22 1997
===subject:Critic 1 Assign 2
===message:Prior knowledge of science can be useful in the understanding of Latin terminology if the Latin name for a process or thing is connected to a literal translation each time a new Latin term is introduced.  In this way the unfamiliar term is associated with a language the students may already know or are already learning.  If it is followed by a mental image as suggested by T. Andre in class this connection could be further strengthened and cognitive load diminished. In this way lower level, or what should be entry level skills, could be learned in a manner which reinforces their developing schemas about science and its shared latin vocabulary.  Of course, we might do what has not been done in recent memory and require that students learn Latin and English early in their careers and receive the benfits it would proceed from that in whatever discipline they chose, science included.In either case, the closer the Latin term comes in being related to the actual charateristic or process the better the student will do with subsequent relations of a similar type.For example, our prior knowledge of spelling relating to the word "possess." "Possess" consistently has the letter "s" appearing four times.  When this frequency does not occur, such as in the first paragraph of Hp533's problem description, those with prior knowledge add the missing "s" into the decoding process often unconsciously. Perhaps a list of the  most common Latin roots and their translations would be of some help in Hp533's (pre)(dic)a(ment).Hp533 seems to have a good understanding of the difficulties involved in teaching those who do not possess entry level skills.  The techniques and processes we study about in class I believe will go a long way in dealing with that issue.    
=========yorg=========
===from:Ap533
===date:Wed Sep 17 17:00:40 1997
===subject:Critic 1 Assign 2
===message:Prior knowledge of science can be useful in the understanding of Latin terminology if the Latin name for a process or thing is connected to a literal translation each time a new Latin term is introduced.  In this way the unfamiliar term is associated with a language the students may already know or are already learning.  If it is followed by a mental image as suggested by T. Andre in class this connection could be further strengthened and cognitive load diminished. <br>In this way lower level, or what should be entry level skills, could be learned in a manner which reinforces their developing schemas about science and its shared latin vocabulary.  Of course, we might do what has not been done in recent memory and require that students learn Latin and English early in their careers and receive the benfits it would proceed from that in whatever discipline they chose, science included.<br>In either case, the closer the Latin term comes in being related to the actual charateristic or process the better the student will do with subsequent relations of a similar type.<br>For example, our prior knowledge of spelling relating to the word "possess." "Possess" consistently has the letter "s" appearing four times.  When this frequency does not occur, such as in the first paragraph of Hp533's problem description, those with prior knowledge add the missing "s" into the decoding process often unconsciously. Perhaps a list of the  most common Latin roots and their translations would be of some help in Hp533's (pre)(dic)a(ment).<br>Hp533 seems to have a good understanding of the difficulties involved in teaching those who do not possess entry level skills.  The techniques and processes we study about in class I believe will go a long way in dealing with that issue.    
=========yorg=========
