===from:Up 533
===date:Wed Oct 29 13:10:05 1997
===subject:Assignment 9 Posting 
===message:5a. Conceptual Conflict, Source: Chapter 12, Pressley.
Conceptual conflict can occur when students have previous misconceptions about a given topic. If students are encouraged to become aware of their beliefs and misconceptions, they can then examine why they had the misconceptions and how to build a mental bridge between the them and the accurate information or awareness. This gap between the pre-existing conceptions and new learning produce what is called conflict. Conlict can motivate conflict resolution. In other words, students who are aware of and acknowledge pre-existing knowledge become motivated to find out more about the topic.
<p>
5b. Teaching with Analogies, Source: Chapter 12, Pressley.
Teaching with analogies involves comparing new, complex learnings to something that students already understand and are very familiar with. Analogies help students to gain a better understanding of the topic. They also promote comparison and contrasting between the two topics. When teaching with analogies, teachers should be careful to highlight or help students recognize the differences between the two topics.
<p>
5c. Multiple and Alternative Representations, Source: Chapter 12, Pressley. 
Experts of any given field can usually examine topics of their field in multiple ways. They also draw on information from as many sources as possible. Novice learners often need some coaching from teachers to learn to draw on the multiple perspectives. Three ways to encourage such perspectives involve encouraging students to 1) read for main ideas and construct summaries capturing the important points in a piece of science text, 2) create verbal and pictorial representations of the same concept, and 3) write about science in order to learn science.
<p>
5d. Conceptual Maps, Source: Chapter 12, Pressley.
One way to facilitate multiple perspectives is through the use of conceptual maps. These maps help learners to see connections and links between aspects of the topic. They also help learners to focus on key concepts.
<p>
6.    For my sample lesson, I will discuss how I would teach pre-service teachers about constructivist and behaviorist theory through the use of hypermedia. Students would be asked to create hypermedia stacks on any topic of their choice that relates to their future career goals. The hypermedia projects would not necessarily directly include information about behaviorism or constructivism, but the students would need to examine which theories they draw upon to create the project. 
<p>
     I would begin the lesson by having students in small groups critique and discuss professional as well as student created hypermedia products. This would encourage multiple perspectives - not only from the hypermedia authors' creations, but also from other group members. Their critique and discussion would include the theory that supports the hypermedia that they are looking at. 
<p>
     After students have had a chance to examine and discuss the hypermedia, we would meet as a class and discuss previous experiences they have had with behaviorism and constructivism. We would compare and contrast the two. Then students would be asked to share write in their journals about their experiences and conceptions and how they differed from the class discussion. Once we've had a rich class discussion, I would provide simple scenarios for the students and ask them to classify whether they think the scenarios are behaviorist or constructivist and why. This activity would be a part of teaching with analogies. The scenarios would be a bit more clear cut than some of the hypermedia projects that we examined. In order to address this issue of the analogies being slightly different from the actual learning situation, I would ask students to discuss what kinds of variables might make the scenarios more complex and harder to categorize. 
<p>
     They would then take their journal writings back to the small groups and discuss whether they would like to change their minds about whether or not they think the hypermedia projects are constructivist or behaviorist or both. This would fall under the conceptual conflict idea.
<p>
     Lastly, I would ask students to draw a concept map about the hypermedia projects. They need to include main concepts and their interrelation. Along with the concept maps, students would need to describe the target audience of the hypermedia project, the intended goals and the theory that supports the project (constructivist or behaviorist). Lastly, they would need to explain how/why they think the design of their project promotes constructivism or behaviorism. This activity would once again promote multiple perspectives of the topic.

=========yorg=========
===from: Op533
===date:Wed Oct 29 16:53:30 1997
===subject: assignment 9
===message:     The main points from Pressley and the readings are as follows:  1.  Students come to Science class with firmly in place misconceptions of scientific information.  2.  In many cases they just add what they read in the text to their previously held misconceptions and compound their misinformation.  3. To circumvent this there needs to be conceptual change learning taking place. There are four conditions that must be fulfilled before conceptual change takes place:  1.  There must be dissatisfaction with existing conceptions.  2.  A new conception must be intelligible.  3.  A new conception has to be intially plausible.  4.  A new conception has to be fruitful.  4.  To intiate conceptual change learning, teachers must be aware of students misconceptions as well as having a strong foundation of their own scientific information.  They also need to be comfortable with the teaching strategies conducive to conceptual change learning.  5.  Students need to socially verbalize what they are learning in science.  and 6.  They need to become comfortable with scientific terminology.  
     If I were to teach Science, it would be at the Middle School level.  Science in Middle School seems to mainly Earth Science.  A misconception held by many middle schoolers is that spiders are insects.
     To cause dissatisfaction (step 1) with prior concepts, I would display charts showing characteristics of insects:  3 body parts - head, thorax, and adomen; and six legs.  I would have the students disect spiders to see if they fit with these characteristics.  When the students realized that spiders didn't match the characteristics of insects, I would show a chart of spider characteristics:  2 body parts - ephalothorax and adomen; and four pairs of legs (making eight).  This would be intelligible and plausible conceptions (steps 2 and 3).
     I would then put the students in groups with charts showing the phylum Arthopoda and all its branches, worksheets of insect and spider body parts to lable and several different arthopods to place in correct classes.  (this would be step 4. making it fruitful)  I would have the students discuss with each other how to arrive at the answers and why. (social verbalizing)  To help the students become more comfortable with the terminology, I would have them do crossword puzzles, filling in the correct scientific terms derived from definations using lay language.  I would also have the students do word search puzzles in which they find the scientific terms.  Becoming familiar with the scientific terms in this way will help them read the text without picking out unfamiliar words to string together as answers to test questions without really understanding them.
 
=========yorg=========
