===from:  Op533
===date:Thu Nov 20 17:58:41 1997
===subject:  assignment 12
===message:     Rohman's early model of writing had three stages:  1. prewriting- planning  2. writing- composing a draft 3.  rewriting- editing and revising.  The trouble with this model is that it is too linear.  People really don't write like this.  Their writing is more recursive- they plan a little, write a little, plan some more, write some more; back and forth, then edit the final draft.  Good writing is really expert problem solving.  Good writers have these characteristics:  They use prior knowledge.  They are opportunistic.  They are flexible.  They monitor their progress.  They process the information deeply.  And all this takes a long time to develop.  Poor writers fail to:  establish a writing goal, generate enough content, organize what they write, do mechanics efficiently, and revise.  Englert, Raphael, Anderson, Anthony, and Stevens suggest these steps for teaching better writing:  Direct explanation and modeling by the teacher.  Daily writing by the students.  Prompt the students with procedural facilitators.  Conduct teacher-student conferences.  Publication of student papers.  Barry Zimmerman and Raphael Risemberg see writing as a sociocognitive process involving self regulation.  They identify three main areas:  environmental processes, behaviorial processes, and personal process.  They further divide this into 10 common self regulations.  Under environmental processes they list 1. Environmental structuring.  2. Self-selected models.  Under Behavioral processes they list:  3. Self-monitoring.  4.  Self-consequenses.  5.  Self-verbalization.  Under Personal processes they list: 6.  Time planning and management.  7.  Goal setting.  8. Self-evaluative standards.  9.  Cognitive strategies.  10.  Mental imagery.  As I read through this information, I was struck by how similar writing a paper is to producing a piece of artwork.  The artist has a goal and decides on the best medium to relay his/her message.  He then makes sketches and reworks sketches.  When she finally starts the final piece, and is adding texture and color, she might decide that something doesn't work and it is changed.  So there is a back and forth play of planning and revising until the final piece of art conveys theartist's message most efficiently and to the best of the artist's ability.  I would like to do a unit on painting and writing combined.  I would lead the students through this problem solving process in a painting.  Then I would have them write a paper about the meaning of the painting and why they used the techniques they did.  I would lead them through the same problem solving process with their papers, pointing out the similarities between the painting and the paper.  By combining the two artforms- painting and writing, it would have more impact on their understanding of the process of each.
  
=========yorg=========
===from:Up 533
===date:Wed Dec  3 17:39:34 1997
===subject:Posting - Assignment 12
===message:
<p>
<br>
5a. Model Interest in Learning.  Source:  Pressley.
Explanation: Teachers should show students that they have a strong interest in learning. They can do this by being curious and showing amazement about differenct learning situations. They should also share their statisfaction in academic avenues. This will help to heighten students interest and help them to development internal motivation and curiosity.
<br>
5b. Personalize Learning Material.  Source: Pressley. 
Explanation: Teachers should always try to make learning relevant to learners. This will help  students to avoid "so what" questions and encourage them to build on existing schemata. Teachers can do this by giving examples that apply to real life situations, tell stories about people who have experienced the learning or ask students to compare or apply learning to their own experiences.
<br>
5c. Make Learning Worthwhile.  Source: Pressley.
Explanation: For maximum retention and curiosity building, teachers should try to make learning worthwhile for learners. They can do this by making learning relevant to learners, by helping students to realize the importance or contribution of the learning in significant worldly events and by making learning in context rather than isolated. This helps students to make more connections accross disciplines and real life situations.
<br>
5d. Promote Self-Efficacy.  Source: Schunk.
Explanation: Students who believe they will succeed often perform better than students who believe they will "never get it". This can be attributed to various reasons. Students who believe they will succeed tend to ask more questions, gauge their own learning and recognizes successes versus failures. Teachers can help students develop a better sense of self-efficacy by encouraging students to become more aware of their feelings about achievement. If students are able to overcome negative feelings and enhance positive feelings, they can heighten motivation and put more effort into their work. Teachers can also help students to develop a sense of self-efficacy by modeling what it's like to have a strong sense of self-efficacy.
<br>
6. Learning Situation:
I see all of the previously mentionned ideas as motivational factors in the learning environment. Parents play a strong role in motivating their students to succeed or even not to succeed. I see the application of these principles as being ongoing parent practices, so I cannot isolate them to one specific learning situation. 
		 	I think parents and children could benefit from using these ideas in various settings multiple times during all developmental stages. First, parents can regularly talk to children about what courses they like the most and which ones they like the least. They should also discuss why they like the course the least. This shows the young person that the parents are interested in their learning. Secondly, parents can utilize the rich daily activities that they encounter to make learning of some of their children's more difficult subjects personal. If their child has difficulties in chemistry, for example, they should look at how chemistry appears in everyday life. They might talk about what role chemistry plays in cooking or in cleaning or in other household endeavors.
	 They can also use chemistry to look at larger issues. Parents might try to get kids interested in how pollutants affect the local lake. This not only helps make chemistry relevant to the child, but it also makes it meaningful and worthwhile. Lastly, parents should tie all of this real life learning to difficult subjects in school. They should revisit the issue of why certain classes are harder than others and whether their children feel successful in those classes or not. This helps children to develop a sense of self-efficacy. 

=========yorg=========
