===from:Michelle
===date:Tue Oct  8 20:21:52 2002
===subject:Armoring beaches
===message:Armoring beaches is a common practice. I don't think we should stop armoring beaches, because development of most, if not all coastal areas has made it necessary for beaches to have some help in resupplying themselves with sand. In the past, such as at West Hampton Dunes, armoring was not done in the proper direction, creating even further problems. I think that the development of better ways of armoring than groins, such as breakwaters that are built in such a way as to not collect so much sand that they are taking away from other areas is crucial to the future of beaches. If a breakwater can be designed in such a way as to slow down erosion in existing problem areas, without jeopardizing neighboring areas, they can be very useful. However this is going to take further research, innovation, and experimentation. As far as the future goes, restricting development will be key in not creating more areas where the existing development is not jeopardized. Armoring can be useful and can create safer conditions for existing beachfront homes. Ideally, the need for armoring would never have surfaced because the beaches would have been able to replenish their own sand supplies without being cut off from doing so by the high rate of development. The problem really remains in the poor planning and lack of thought in the previous development of coastal areas, but because this problem already exists, I think armoring can help the current situation that many of our beaches face. 

=========yorg=========
===from:Brock McCracken
===date:Tue Oct  8 22:25:10 2002
===subject:Disarm
===message:I think it is time to accept some of the real estate losses from armouring beaches. Coastal communities need to seriously develop plans to take a step back whenever possible. The lessons to be learned from armouring beaches are plentiful. They are not good. 
I live near Pismo Beach, CA. The business owners in the area built a pier in the 1920's to attract tourists from San Francisco. "Sleep on the Beach" was the marketing pitch or something. In the 30's a sea wall was built at the base of the pier to preserve the beach after a series of storms. Building a sea wall must have been the thing to do in those days. The wall eventually led to the dissappearance of a nearby city's beach, Shell Beach and prevented sand from nourishing the Guadalupe Dunes which lay south. Guadalupe Dunes is now home to the endangered species the red legged frog and the snowy plover seabird because the ecology of the dunes were slightly altered. A storm destroyed the pier and the sea wall in the 60's. The pier was rebuilt, not the sea wall. The coastal ecology is making a slight recovery after 40 years. 
Sebastian inlet is an example where armourming has provided some benefit. Armouring should be the last option. Starvation of sand can only be prolonged, short-term for that matter, not prevented.
=========yorg=========
===from:Kara
===email:ckara@nova.edu
===date:Wed Oct  9 20:03:13 2002
===subject:Armouring or Disarming
===message:Armouring beaches is a very common practice in coastal areas around the world. Should we stop this practice? Why or why not? Talk about consequences. <br>


<p>An argument comes to mind, as I read the pages of Against the Tide.  Engineers love money. People who live on the coast have money. Therefore, forget mother nature, lets make money.<br>

<p>The answer to the question is yes, we should stop armouring beaches. The scientists and even mother nature herself have proven the structures and techniques do not work.  It is too expensive and dangerous to keep trying. Plus, we have made some places much worse by using some of the techniques.

Private owners trap sand for themselves and "starve" their neighbors beaches.  In Long Island, the arificial opening of inlets has created dire circumstances for the rest of the island.  All of these and more have cost the taxpayers too much money $$$.  People who can not afford to live in these areas have to pay for people who do. Why? The zoning should have kept them from building in the first place.<br> 
=========yorg=========
===from:Jaime H
===email:hjaime@nova.edu
===date:Thu Oct 10 19:34:17 2002
===subject:To armor or disarmor...?
===message:One fact remains...the world (countries and communities) have way to much invested in their beaches to not continue to armor against the loss of "their" precious sand.  Do I think that makes it right? NO.  I lived in Myrtle Beach, SC for 5 years during which I witnessed a "beach renurishment" project.  This consisted of pumping sand from offshore to replenish the severely eroded beach. Hmmm, too bad they decided to do it right before hurricane season! But, luckily, not too much was washed away and the hotel and condo owners and bigger and more attractive beaches for their tourists.  The thing that really burned me was that there was a public forum before the approval of the renurishment project...I attended and commented on all the negatives of the project...wouldn't the sand just erode again since the beach can not move with stationary hotels and condos on it? Wouldn't we have to spend the same money over and over? What about the affects on marine life that you are sucking the sand from? They did not care.  There were more property owners there than environmentally minded people, and our comments were listened to, but not important.  Needless to say, the today beach is not what it was right after the project and sadly, many dead fish and sea creatures could be seen lining the beach right after the incident.  My point is that property owners and tax payers, especially in big touristy towns, have too much at stake and will always be looking to armor their investments, no matter what the costs.  
=========yorg=========
===from:Achim Kretschmer
===date:Fri Oct 11  8:35:01 2002
===subject:Property value governs policies
===message:The discussion of armoring vs. disarming coastlines is increasingly being governed by powerful communities that own coastal properties. The perfect example is what happened in Westhapton Dunes after part of the community had been cut off after a powerful storm when the barrier island split in two. So it is not so much of what should be done but what is being done and how. On Long Island (where I live), the majority of the people opposed government funding for the beach restoration project not only because it served only a handful of very wealthy property owners but also because of the environmental impact it would have. This majority was overruled because of the financial power of these landowners. Property taxes paid by property owners in the Hamptons average $ 10,000 annually!! <p> I fear that it is too late to disarmor parts of the coast line, simply because too many people would be affected. Just as armoring a small part of a beach shifted the burden to the property down the beach, disarming would mean that an entire region would have to perticipate, all at once. The cost would be too prohibitive. It would take a dictatorial decree (like resettling hundreds of thousands of people for the Three Gorges Dam in China) to accomplish any large scale undoing of the damage already done. Nature will take its course, and at one point the cost to armor and re-armor will outweigh the cost of giving up a community and disarmor.
=========yorg=========
===from:Yvonne Haberer
===date:Sat Oct 12 22:21:59 2002
===subject:To armor or not?
===message:We're probably not going to completely stop armoring our beaches because it just doesn't make good economic sense to let highly valuable properties just wash away, even at the expense of losing a beach.  It certainly makes sense to protect what is already there.  However, we should work our way of thinking towards abandoning the technique of armoring our beaches.  As Dean writes, some states have already taken steps to do just that.  The logical way of thinking would be to stop any future coastal development.  Continue protecting what is already there, but restrict new development.  Do we really want to let homes and businesses just fall into the ocean?  How could we just sit and watch coastal communities around the world just shut down?  The economic impact would be devastating to all whether it be directly or indirectly.  It's obvious that armoring is not the solution to protecting our beaches, it is just a method to protect the development behind the beach.  I guess it's just too simple to say...stop future coastal development. 
=========yorg=========
===from:Brock McCracken
===date:Wed Oct 16 21:44:14 2002
===subject:Monkey See Monkey Do
===message:Good comments Allan. 

I also noticed how Ms Dean mentioned in her book that sometimes it only takes one property owner in a loosely tied coastal community to armour their property and others will soon follow. Homeowner associations can be a beneficial thing.

=========yorg=========
===from:Jeremy
===date:Thu Oct 17 15:58:28 2002
===subject:Armor
===message:I have had little experience with armoring beaches, being from Kentucky I was not aware of the problem and the methods used to aleviate the shifting beaches until I sat in on a presentation from a visiting Professor from Duke Univ (whose name I cannot remember nor find) during my undergraduate career. So I must base my response on articles, videos, and presentations concerning the problem, instead of experiences. 
I do not agree with beach barriers because of the impact that it has on the beach, beaches naturally shift and reform in different configurations. A beach absorbs some of the impact of storms by shifting its sands out seaward with large waves, this causes the angle of the seafloor to be flatter and causes the waves to break farther out. In periods of less activity the sand is redistributed landward and deposited in sand dunes and new beach area. This process is a constant one that reworks the beach sands and can shift beach area from one location to another. 
Barriers interrupt this natural process and cause the beach to detererioate because it can't rebuild itself as easliy. Barriers cause the sand that is intended for adjacent or down-coast beaches to be slowed or even halted, this causes a need to place a barrier where there was none required before. This implacement of barriers can soon escalate into a large need for more and more barriers in an effort to couteract one another, and eventually defeats the purpose they were intended for. 
Another solution to shifting beaches and depleted sands, is to haul sand in and dump it on the beach, this seems like an even more futile effort since after a few storms this sand will have washed away. I undestand that this is a very expensive process, and one that once started must be ongoing. 
I also realize that this is a problem which can't be ignored nor is it going to go away. I believe there is a solution, one that is yet to be found, it may be different types of barriers or it may be something totally new and original. In either case the problem will have to be resolved and the temporary methods being used now are only a quick fix and will have to be redone in the future. 
=========yorg=========
===from:prof schmidt
===subject:Radical New Design Needed? - Ocean Habitation Anyone?
===date:Sat Oct 19  9:04:42 2002
===message:<br> Allan's comment (down at the end of this thread)prompted me to do some more <b>novel thinking</b> in an area I am not expert in but which may hold great promise for coastal construction and preservation - <b>architecture and engineering!</b><p>
Perhaps we need to have boat and floating vessel designers get together with dry land architects and contractors. They might come up with new structural ideas that will yield (without being destroyed) to the tides, wind, storm surge, surf when we build close to the shore. By the way, I have become very interested in Ocean colonization or <b>Habitatization</b> in the past year. Most of the world is covered by water and I am certain that we could develop some sustainable ways of living on and under the sea, respect the integrity of this environment, and improve how we relate to the shore and ocean. Building ON the seashore and draining wetlands or otherwise messing with the interstacial area between the sea and firm land is probably the <b>WORST</b> place for us to be as humans because these areas are the nurseries of much sea life and we are killing off all these "babies!"

=========yorg=========
===from:Ian Gibson
===date:Mon Oct 21 13:18:49 2002
===subject:Anti-armoring
===message:Armoring our shore is by far one of the most underrated threats to the marine and coastal environments of the planet.  It totally disrupts one of the most important natural processes - longshore drift.  The sandy beach is one of, if not the most crucial natural storm buffers.  They are the best defense against waves and storm surge.  Unfortunately, the armoring of sandy beaches with groins, jetties, and seawalls in an effort to elminate localized erosional problems and effects from jettied inlets has deepened a problem that man cannot viably fix.  These structure disrupt the longshore sediment flow and lead to heightened erosion, sand starvation, and severe decrease in the protective effectiveness of the beach system in regards to storms.  The transport of sediment along the shore is most likely a natural process that cannot be modified into a mold that is 100% beneficial to mankind.  It only works when left alone, and even then it varies with the nuances of the natural world.  Arrogantly expecting a well-placed line of rocks or on-shore wall to bend nature to your own whim is just stupid.  Well, it is either stupid or selfish, depending if your are up-stream or down-stream of the flow.  <p> The practice of armor our shore has really gone far enough - we have done enough damage.  There has to be a shift in the public perception away from castling ones beach front property and towards allowing the natural process from taking place.  the coast is a dynamic process, andnin living there one has to accept the fact the mother nature can take it away from you on any meteorological whim.
=========yorg=========
===from:Ted Kendziora
===date:Fri Oct 25 14:34:58 2002
===subject:armor
===message:Do I think that we should armor the shoreline against the ocean?  I have two opinions about this question.  First of all I drive up and down US 1 everyday and I can’t stand the traffic, but I could never imagine what this place would be like if we let the ocean take away our shoreline.  We would lose millions of dollars a year in buildings, roads, and landscaping and not protecting our shoreline would be ridiculous.
Secondly, I read about the first people that settled on the coast, and about the miles of natural beaches and giant sand dunes.  In this case I would say let the shoreline take its natural course.  Of course, I would love to see this and it would be wonderful to get the coast back to this condition but that would be impossible in today’s society.
I can understand why people don’t want construction along our shorelines because any coast is a unique and beautiful place.  It is a place of constant change and that draws people to the coasts.  The problem is that society has already made its mark on our coasts.  There is very little that can be done because of the fact that people own land and as long as that is allowed people will protect their land by any means possible in order to turn a profit.  I wouldn’t want the ocean to take my ocean front property after I spent over a million dollars for the land.
The only thing we can do in protecting our coast is to build walls and try to stabilize the shoreline.  Of course the ocean will always win but society will never give up trying to stop the waves from taking their properties.  I think that is it too late to order people to stop building on our current shoreline, but what about the land that is already under water?  I know that the oceans are rising, but I also believe that they will eventually begin to subside.  The lowering of the ocean is our only hope to gain back our coastline.  Maybe a law should be created that construction can not go beyond a specific line that we predetermine.  The problem here is that if we start gaining land along our coastline people will want to own that new ocean front property and if you have money in today’s society you can pretty much accomplish anything.  That is the American way of life.

=========yorg=========
