#!/usr/bin/perl

$cls = "/local/classnet/mt206s97";
$oldname = "Quiz%204";
$newname = "Quiz%202-12";

$dir = "$cls/students";
rename("$cls/assignments/$oldname","$cls/assignments/$newname");
opendir(SDIR,$dir);
my @students = grep(!/^\.\.?/,readdir(SDIR));
close SDIR;
foreach $sname (sort @students) {
    $gdir = "$dir/$sname/ungraded";
    if (-e "$gdir/$oldname") {
        print "$sname\n";
        rename("$gdir/$oldname","$gdir/$newname");
    } else {
        $gdir = "$dir/$sname/graded";
        if (-e "$gdir/$oldname") {
            print "$sname\n";
            rename("$gdir/$oldname","$gdir/$newname");
        }
    }
}

