#!/usr/bin/perl
package main;

#
# Membership
#

BEGIN {
   unshift(@INC,'/local1/www/apache-isu/cgi-bin/lib');
}
    
require "optimize.pl";
require CLASS;
require MultipartBuffer;
require TempFile;

# Turn off file mask
umask 000;

# Parse incoming query into query object
$query = new CGI;


# Instructor and course setup
$cls = CLASS->new('Furlough Study');
($cls->exists()) || die "$cls->{'Name'} does not exist\n";
$cls->{'Verify Enrollment'} = 0;
open(LIST,"</local1/www/apache-isu/cgi-bin/admin/list.dat") or die "list.dat 
doesn't exist\n"; while (<LIST>) {
  print $_;
  if (/^#/) { next;};
  if (s/^\+//) {
    my @info = split(/[,|\t]/);
    if ($#info == 3) {
      # Modify query object
      $query->{'First Name'}->[0] = $info[1];
      $query->{'Last Name'}->[0] = $info[0];
      $query->{'Email Address'}->[0] = CN_UTILS::remove_spaces($info[3]);
      $query->{'Password'}->[0] = $info[2];
      $query->{'Verify Password'}->[0] = $info[2];
      my $stud = STUDENT->new($query,$cls);
      if (!$cls->mem_exists($stud->{'Disk Username'})) {
         $stud->add($cls);
      }
    }
  }
}
close LIST;
