#!/usr/bin/perl
package main;

chdir '/';
system 'umount /local1';
system '/usr/sbin/newfs -i 4096 -m 3 /dev/rz0c';
chdir '/';
# mount /dev/rz0c /local1
# tar xpf /local2/local_backup/cn11Feb1999.tar
# /local/etc/rc.apache
