#!/usr/bin/perl

$GZIP     = '/usr/bin/gzip';

my @classes = `ls -1 /local/classnet/data/forums`;
chop @classes;
foreach $cname (@classes) {
    my $file = "/local/classnet/data/forums/$cname";
    if (-d $file) {
        print "$file\n";
        system("tar cf '$file.tar' '$file'");
        system("$GZIP '$file.tar'");
        system("rm -r '$file'");
    }
}
